use std::env;
use std::path::PathBuf;

/// The entry points a `macro_rules!` defines, as (source file, macro, heading, signature).
///
/// cbindgen parses source and does not expand macros, so it emits nothing for these and
/// their declarations have to be added to the header here. Only the signature shape is
/// written down: the names come from the invocation list in the source, which is the one
/// place they exist, so an invocation added or removed there reaches the header — and
/// through it the bindings and their parity test — without this file being touched.
const MACRO_EXPORTS: &[(&str, &str, &str, &str)] = &[
    (
        "src/dynamic.rs",
        "define_flat_sample_getter",
        "Dynamic primitive sample getters",
        "Int2DdsRet {name}(const uint8_t *bytes, uintptr_t len, const struct Int2DdsTypeObject *type_obj, const char *field_name, {ty} *out);",
    ),
    (
        "src/dynamic.rs",
        "define_handle_getter",
        "Handle-based DynamicData getters",
        "Int2DdsRet {name}(const struct Int2DdsDynamicData *data, const char *field_path, {ty} *out);",
    ),
    (
        "src/dynamic.rs",
        "define_handle_setter",
        "Handle-based DynamicData primitive setters",
        "Int2DdsRet {name}(struct Int2DdsDynamicData *data, const char *field, {ty} value);",
    ),
    (
        "src/dynamic_value.rs",
        "value_ctor",
        "DynamicValue scalar constructors",
        "Int2DdsRet {name}({ty} value, struct Int2DdsDynamicValue **out);",
    ),
    (
        "src/dynamic_value.rs",
        "value_as",
        "DynamicValue scalar extractors",
        "Int2DdsRet {name}(const struct Int2DdsDynamicValue *value, {ty} *out);",
    ),
];

/// The Rust type each macro is invoked with, spelled as the header spells it.
const C_TYPES: &[(&str, &str)] = &[
    ("bool", "bool"),
    ("i8", "int8_t"),
    ("u8", "uint8_t"),
    ("i16", "int16_t"),
    ("u16", "uint16_t"),
    ("i32", "int32_t"),
    ("u32", "uint32_t"),
    ("i64", "int64_t"),
    ("u64", "uint64_t"),
    ("f32", "float"),
    ("f64", "double"),
];

/// The `(entry point, C type)` pairs `macro_name!` is invoked with in `source`.
///
/// A line that opens an invocation but does not match is an error rather than a skip:
/// the failure mode of skipping is a declaration missing from the header, which is
/// exactly what this exists to prevent, and it would be silent.
fn invocations(source: &str, path: &str, macro_name: &str) -> Vec<(String, String)> {
    let opening = format!("{}!(", macro_name);
    let mut found = Vec::new();
    for line in source.lines().map(str::trim) {
        if !line.starts_with(&opening) {
            continue;
        }
        let args = line
            .strip_prefix(&opening)
            .and_then(|rest| rest.strip_suffix(");"))
            .unwrap_or_else(|| panic!("{}: `{}` is not a single line ending in `);`", path, line));
        let mut args = args.split(',').map(str::trim);
        let (Some(name), Some(rust_ty)) = (args.next(), args.next()) else {
            panic!("{}: `{}` has no (name, type) arguments", path, line)
        };
        let c_ty =
            C_TYPES.iter().find(|(rust, _)| *rust == rust_ty).map(|(_, c)| *c).unwrap_or_else(
                || panic!("{}: `{}` has no C spelling; add it to C_TYPES", path, rust_ty),
            );
        found.push((name.to_string(), c_ty.to_string()));
    }
    assert!(
        !found.is_empty(),
        "no {}! invocations in {}; was it renamed or moved?",
        macro_name,
        path
    );
    found
}

/// The declaration block for everything in [`MACRO_EXPORTS`].
fn macro_declarations(crate_dir: &str) -> String {
    let mut out = String::new();
    for (path, macro_name, heading, signature) in MACRO_EXPORTS {
        let source = std::fs::read_to_string(PathBuf::from(crate_dir).join(path))
            .unwrap_or_else(|e| panic!("read {}: {}", path, e));
        let entries = invocations(&source, path, macro_name);
        let name_width = entries.iter().map(|(n, _)| n.len()).max().unwrap() + 1;
        let ty_width = entries.iter().map(|(_, t)| t.len()).max().unwrap();
        out.push_str(&format!("\n/* {} (generated by {}! in {}). */\n", heading, macro_name, path));
        for (name, c_ty) in entries {
            out.push_str(
                &signature
                    .replace("{name}", &format!("{:name_width$}", name))
                    .replace("{ty}", &format!("{:ty_width$}", c_ty)),
            );
            out.push('\n');
        }
    }
    out
}

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let package_name = env::var("CARGO_PKG_NAME").unwrap();
    let output_file = PathBuf::from(&crate_dir).join("include").join(format!("{}.h", package_name));

    // Emit a portable deprecation attribute so C consumers get a compiler
    // warning when they call a deprecated entry point. cbindgen does not emit
    // anything for #[deprecated] unless `deprecated_with_note` is set.
    let mut config = cbindgen::Config::default();
    config.after_includes = Some(
        "\n#if defined(__GNUC__) || defined(__clang__)\n\
         #define INT2DDS_DEPRECATED(msg) __attribute__((deprecated(msg)))\n\
         #elif defined(_MSC_VER)\n\
         #define INT2DDS_DEPRECATED(msg) __declspec(deprecated(msg))\n\
         #else\n\
         #define INT2DDS_DEPRECATED(msg)\n\
         #endif"
            .to_string(),
    );
    config.function.deprecated_with_note = Some("INT2DDS_DEPRECATED({})".to_string());

    // Generate C header file using cbindgen
    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .with_language(cbindgen::Language::C)
        .with_include_guard("INT2DDS_FFI_H")
        .with_documentation(true)
        .with_cpp_compat(true)
        .with_pragma_once(true)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(&output_file);

    // Add the macro-generated entry points cbindgen cannot see, inside the `extern "C"`
    // block: a declaration after it gets C++ linkage, so a C++ caller would look for a
    // mangled name the library does not export.
    let contents = std::fs::read_to_string(&output_file).expect("read header");
    let epilogue = "#ifdef __cplusplus\n}  // extern \"C\"\n#endif  // __cplusplus";
    let idx = contents
        .find(epilogue)
        .expect("cbindgen's `extern \"C\"` epilogue is missing from the generated header");
    let (head, tail) = contents.split_at(idx);
    let new_contents = format!("{}{}\n{}", head, macro_declarations(&crate_dir), tail);
    std::fs::write(&output_file, new_contents).expect("write header");

    // Embed an ELF SONAME on the Linux cdylib. rustc does NOT set DT_SONAME for
    // cdylibs, so consumers would otherwise record an unversioned dependency on
    // "libint2dds_ffi.so". We inject the soname via the linker.
    //
    // Version source: Cargo sets CARGO_PKG_VERSION_MAJOR in the build environment
    // from this crate's `version` field in Cargo.toml. We track the MAJOR only
    // (libint2dds_ffi.so.<major>), the standard ELF convention where the soname
    // encodes the ABI-compatibility boundary and changes only on a major bump (a
    // deliberate ABI break).
    //
    // TRADE-OFF: pre-1.0 (0.x) a minor bump can also break ABI, but the soname
    // will NOT change, so linked consumers built against an older 0.x must be
    // rebuilt across such a break. Post-1.0 this matches normal expectations.
    //
    // Gated to Linux/ELF: the MSVC (COFF) linker rejects -Wl,-soname, and the
    // concept does not exist on Windows/macOS.
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os == "linux" {
        let major = env::var("CARGO_PKG_VERSION_MAJOR").unwrap();
        // cdylib output name = package name with '-' -> '_': libint2dds_ffi.so
        let lib_name = package_name.replace('-', "_");
        println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,lib{}.so.{}", lib_name, major);
    }

    // macOS: the SONAME analog is the dylib install name plus compat/current
    // versions. rustc sets none of these for a cdylib, so inject them via the
    // linker. @rpath keeps the install name relocatable for consumers.
    if target_os == "macos" {
        let major = env::var("CARGO_PKG_VERSION_MAJOR").unwrap();
        let minor = env::var("CARGO_PKG_VERSION_MINOR").unwrap();
        let patch = env::var("CARGO_PKG_VERSION_PATCH").unwrap();
        let lib_name = package_name.replace('-', "_");
        println!("cargo:rustc-cdylib-link-arg=-Wl,-install_name,@rpath/lib{}.dylib", lib_name);
        println!("cargo:rustc-cdylib-link-arg=-Wl,-compatibility_version,{}.{}", major, minor);
        println!("cargo:rustc-cdylib-link-arg=-Wl,-current_version,{}.{}.{}", major, minor, patch);
    }

    // Windows: embed a PE VERSIONINFO resource so the DLL reports a FileVersion
    // and ProductVersion (the SONAME analog). winresource reads CARGO_PKG_VERSION
    // for the numeric version fields. cfg(windows) guards it to the Windows host
    // (matching the cfg-gated build-dependency); the resource compiler (rc.exe or
    // windres) only exists there. The DLL filename itself stays unversioned.
    #[cfg(windows)]
    {
        if target_os == "windows" {
            let mut res = winresource::WindowsResource::new();
            res.set("ProductName", "int2dds-ffi");
            res.set("FileDescription", "C FFI bindings for int2DDS");
            res.compile().expect("embed Windows VERSIONINFO resource");
        }
    }

    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=Cargo.toml");
}
