// 코어가 디코딩할 수 있는 스칼라와 문자열만 모은 적합성 검증용 타입.
// ddsFields() 는 마지막 @key 까지의 모든 필드를 서술해야 하므로,
// 서술 가능한 종류를 앞에, octet/char/float/double/wstring 을 뒤에 둔다.
@extensibility(APPENDABLE)
struct CdrGolden {
    @key long id;
    boolean bool_val;
    int8 i8_val;
    uint8 u8_val;
    int16 i16_val;
    uint16 u16_val;
    int32 i32_val;
    uint32 u32_val;
    int64 i64_val;
    uint64 u64_val;
    string unbounded_str;
    @key string<64> bounded_str;
    octet byte_val;
    char char_val;
    float f32_val;
    double f64_val;
    sequence<wstring> wstr_seq;
    wstring wstr_arr[2];
    wstring unbounded_wstr;
    wstring<32> bounded_wstr;
};
