struct Point2D {
    float field0;
    float field1;
};

struct ArrayElement {
    long value;
    string label;
};

@extensibility(APPENDABLE)
struct ComplexArraysType {
    @key long id;
    ArrayElement struct_array[4];
    Point2D point_array[3];
    sequence<ArrayElement> struct_seq;
    long matrix[9];
};