enum Color {
    RED,
    GREEN,
    BLUE,
    YELLOW,
    PURPLE
};

enum StatusKind {
    UNKNOWN,
    ACTIVE,
    INACTIVE,
    PENDING
};

@extensibility(APPENDABLE)
struct EnumType {
    @key long id;
    Color color;
    StatusKind status;
};