@extensibility(APPENDABLE)
struct SequencesType {
    @key long id;
    sequence<boolean> bool_seq;
    sequence<octet> byte_seq;
    sequence<long> i32_seq;
    sequence<float> f32_seq;
    sequence<double> f64_seq;
    sequence<string> string_seq;
    sequence<long, 10> bounded_seq;
};