struct Point2D {
    float field0;
    float field1;
};

struct Point3D {
    double field0;
    double field1;
    double field2;
};

@extensibility(APPENDABLE)
struct TupleStructType {
    @key long id;
    Point2D point2d;
    Point3D point3d;
    sequence<Point2D> points;
};