/**
 * Auto-generated by int2dds-idl from HelloWorld.idl
 * DO NOT EDIT - changes will be overwritten
 */
#ifndef HELLO_WORLD_IDL_H
#define HELLO_WORLD_IDL_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "int2dds_cdr.h"

/* ========================================================================
 * Type: HelloWorld
 * Extensibility: FINAL
 * ======================================================================== */

typedef struct HelloWorld {
    uint32_t index;
    char message[257];
} HelloWorld;

static inline size_t HelloWorld_serialize_cdr(
    const HelloWorld *val,
    uint8_t *buf,
    size_t capacity)
{
    Int2DdsCdrWriter w;
    int2dds_cdr_writer_init(&w, buf, capacity, true, true);
    int2dds_cdr_write_encapsulation(&w, INT2DDS_CDR_FINAL);
    int2dds_cdr_write_u32(&w, val->index);
    int2dds_cdr_write_string(&w, val->message);
    return w.error == INT2DDS_CDR_OK ? int2dds_cdr_writer_size(&w) : 0;
}

static inline bool HelloWorld_deserialize_cdr(
    const uint8_t *buf,
    size_t len,
    HelloWorld *val_out)
{
    Int2DdsCdrReader r;
    if (int2dds_cdr_reader_init(&r, buf, len) != INT2DDS_CDR_OK)
        return false;
    int2dds_cdr_read_u32(&r, &val_out->index);
    int2dds_cdr_read_string_copy(&r, val_out->message, 257, NULL);
    return int2dds_cdr_reader_error(&r) == INT2DDS_CDR_OK;
}

static inline size_t HelloWorld_serialize_key(
    const HelloWorld *val,
    uint8_t *buf,
    size_t capacity)
{
    (void)val; (void)buf; (void)capacity;
    return 0;
}

#endif /* HELLO_WORLD_IDL_H */
