/**
 * Auto-generated by int2dds-idl from Arrays.idl
 * DO NOT EDIT - changes will be overwritten
 */
#ifndef ARRAYS_IDL_H
#define ARRAYS_IDL_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "int2dds_cdr.h"

/* ========================================================================
 * Type: ArraysType
 * Extensibility: APPENDABLE
 * ======================================================================== */

typedef struct ArraysType {
    int32_t id;
    bool bool_array[4];
    uint8_t byte_array[8];
    int32_t i32_array[4];
    float f32_array[4];
    double f64_array[4];
} ArraysType;

static inline void ArraysType_serialize_fields(
    Int2DdsCdrWriter *_w,
    const ArraysType *val)
{
    Int2DdsCdrWriter w = *_w;
    size_t dh = 0;
    if (w.xcdr2) {
        int2dds_cdr_write_dheader_begin(&w, &dh);
    }
    int2dds_cdr_write_i32(&w, val->id);
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_write_bool(&w, val->bool_array[_i]);
    }
    for (uint32_t _i = 0; _i < 8; _i++) {
        int2dds_cdr_write_u8(&w, val->byte_array[_i]);
    }
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_write_i32(&w, val->i32_array[_i]);
    }
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_write_f32(&w, val->f32_array[_i]);
    }
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_write_f64(&w, val->f64_array[_i]);
    }
    if (w.xcdr2) {
        int2dds_cdr_write_dheader_finalize(&w, dh);
    }
    *_w = w;
}

static inline void ArraysType_deserialize_fields(
    Int2DdsCdrReader *_r,
    ArraysType *val_out)
{
    Int2DdsCdrReader r = *_r;
    uint32_t obj_size = 0;
    size_t start_pos = 0;
    if (r.xcdr2) {
        int2dds_cdr_read_dheader(&r, &obj_size, &start_pos);
    }
    int2dds_cdr_read_i32(&r, &val_out->id);
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_read_bool(&r, &val_out->bool_array[_i]);
    }
    for (uint32_t _i = 0; _i < 8; _i++) {
        int2dds_cdr_read_u8(&r, &val_out->byte_array[_i]);
    }
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_read_i32(&r, &val_out->i32_array[_i]);
    }
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_read_f32(&r, &val_out->f32_array[_i]);
    }
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_read_f64(&r, &val_out->f64_array[_i]);
    }
    if (r.xcdr2) {
        int2dds_cdr_read_dheader_end(&r, obj_size, start_pos);
    }
    *_r = r;
}

static inline size_t ArraysType_serialize_cdr(
    const ArraysType *val,
    uint8_t *buf,
    size_t capacity,
    bool xcdr2)
{
    Int2DdsCdrWriter w;
    int2dds_cdr_writer_init(&w, buf, capacity, true, xcdr2);
    int2dds_cdr_write_encapsulation(&w, INT2DDS_CDR_APPENDABLE);
    size_t dh = 0;
    if (xcdr2) {
        int2dds_cdr_write_dheader_begin(&w, &dh);
    }
    int2dds_cdr_write_i32(&w, val->id);
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_write_bool(&w, val->bool_array[_i]);
    }
    for (uint32_t _i = 0; _i < 8; _i++) {
        int2dds_cdr_write_u8(&w, val->byte_array[_i]);
    }
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_write_i32(&w, val->i32_array[_i]);
    }
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_write_f32(&w, val->f32_array[_i]);
    }
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_write_f64(&w, val->f64_array[_i]);
    }
    if (xcdr2) {
        int2dds_cdr_write_dheader_finalize(&w, dh);
    }
    return w.error == INT2DDS_CDR_OK ? int2dds_cdr_writer_size(&w) : 0;
}

static inline bool ArraysType_deserialize_cdr(
    const uint8_t *buf,
    size_t len,
    ArraysType *val_out)
{
    Int2DdsCdrReader r;
    if (int2dds_cdr_reader_init(&r, buf, len) != INT2DDS_CDR_OK)
        return false;
    uint32_t obj_size = 0;
    size_t start_pos = 0;
    if (r.xcdr2) {
        int2dds_cdr_read_dheader(&r, &obj_size, &start_pos);
    }
    int2dds_cdr_read_i32(&r, &val_out->id);
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_read_bool(&r, &val_out->bool_array[_i]);
    }
    for (uint32_t _i = 0; _i < 8; _i++) {
        int2dds_cdr_read_u8(&r, &val_out->byte_array[_i]);
    }
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_read_i32(&r, &val_out->i32_array[_i]);
    }
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_read_f32(&r, &val_out->f32_array[_i]);
    }
    for (uint32_t _i = 0; _i < 4; _i++) {
        int2dds_cdr_read_f64(&r, &val_out->f64_array[_i]);
    }
    if (r.xcdr2) {
        int2dds_cdr_read_dheader_end(&r, obj_size, start_pos);
    }
    return int2dds_cdr_reader_error(&r) == INT2DDS_CDR_OK;
}

static inline size_t ArraysType_serialize_key(
    const ArraysType *val,
    uint8_t *buf,
    size_t capacity)
{
    Int2DdsCdrWriter w;
    int2dds_cdr_writer_init(&w, buf, capacity, false, true); /* BE, XCDR2, no header */
    int2dds_cdr_write_i32(&w, val->id);
    return w.error == INT2DDS_CDR_OK ? int2dds_cdr_writer_size(&w) : 0;
}

static inline Int2DdsTypeInfo* ArraysType_type_info(void) {
    Int2DdsTypeInfo *ti;
    int2dds_type_info_create("ArraysType", 1, &ti);
    int2dds_type_info_add_field(ti, "id", INT2DDS_FIELD_INT32, 1);
    int2dds_type_info_add_array_field(ti, "bool_array", INT2DDS_FIELD_BOOL, 4, 0);
    int2dds_type_info_add_array_field(ti, "byte_array", INT2DDS_FIELD_BYTE, 8, 0);
    int2dds_type_info_add_array_field(ti, "i32_array", INT2DDS_FIELD_INT32, 4, 0);
    int2dds_type_info_add_array_field(ti, "f32_array", INT2DDS_FIELD_FLOAT32, 4, 0);
    int2dds_type_info_add_array_field(ti, "f64_array", INT2DDS_FIELD_FLOAT64, 4, 0);
    return ti;
}

#endif /* ARRAYS_IDL_H */
