#![allow(non_camel_case_types, dead_code, unused_imports, unreachable_patterns, unused_variables)]
#![allow(clippy::useless_conversion, clippy::clone_on_copy, clippy::redundant_field_names)]

//! Auto-generated by int2dds-idl from robot_control.idl
//! DO NOT EDIT - changes will be overwritten

use int2dds_derive::DdsType;

#[derive(DdsType)]
#[repr(i32)]
pub enum Command {
    StartCommand = 0,
    StopCommand = 1,
}

#[derive(DdsType)]
pub struct Status {
    pub msg: String,
    pub code: i32,
}

use int2dds::serialize::cdr::serializer::primitive::PrimitiveSerialize;
use int2dds_rpc::client::ClientEndpoint;
use int2dds_rpc::client::{Client, ClientParams};
use int2dds_rpc::entity::{RpcEntity, ServiceProxy};
use int2dds_rpc::error::{DdsRpcError, DdsRpcResult};
use int2dds_rpc::requester::Future;
use int2dds_rpc::server::Dispatchable;
use int2dds_rpc::service::{RequestHandler, Service, ServiceParams};
use int2dds_rpc::types::InstanceName;
use int2dds_rpc::types::SampleIdentity;
use int2dds_rpc::types::{
    RemoteExceptionCode, ReplyHeader, RequestHeader, UnknownException, UnknownOperation,
    UnusedMember,
};
use std::time::Duration;

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct TooFast {
    pub max_speed: f32,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct InvalidCommand {
    pub reason: String,
}

pub const TOO_FAST_EX_HASH: i32 = -1861167746;
pub const INVALID_COMMAND_EX_HASH: i32 = 1669798880;

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RobotControl_command_In {
    pub com: Command,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RobotControl_command_Out {
    pub dummy: UnusedMember,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
#[repr(i32)]
pub enum RobotControl_command_Result {
    Result(RobotControl_command_Out) = 0,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RobotControl_setSpeed_In {
    pub speed: f32,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RobotControl_setSpeed_Out {
    pub return_: f32,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
#[repr(i32)]
pub enum RobotControl_setSpeed_Result {
    Result(RobotControl_setSpeed_Out) = 0,
    TooFast_ex(TooFast) = TOO_FAST_EX_HASH,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RobotControl_getSpeed_In {
    pub dummy: UnusedMember,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RobotControl_getSpeed_Out {
    pub return_: f32,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
#[repr(i32)]
pub enum RobotControl_getSpeed_Result {
    Result(RobotControl_getSpeed_Out) = 0,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RobotControl_getStatus_In {
    pub dummy: UnusedMember,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RobotControl_getStatus_Out {
    pub status: Status,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
#[repr(i32)]
pub enum RobotControl_getStatus_Result {
    Result(RobotControl_getStatus_Out) = 0,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RobotControl_navigate_In {
    pub x: f32,
    pub y: f32,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RobotControl_navigate_Out {
    pub dummy: UnusedMember,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
#[repr(i32)]
pub enum RobotControl_navigate_Result {
    Result(RobotControl_navigate_Out) = 0,
    TooFast_ex(TooFast) = TOO_FAST_EX_HASH,
    InvalidCommand_ex(InvalidCommand) = INVALID_COMMAND_EX_HASH,
}

#[derive(Debug, Clone)]
pub enum RobotControl_navigate_Error {
    TooFast(TooFast),
    InvalidCommand(InvalidCommand),
}

pub const ROBOT_CONTROL_COMMAND_HASH: i32 = -22164451;
pub const ROBOT_CONTROL_SET_SPEED_HASH: i32 = 1289593851;
pub const ROBOT_CONTROL_GET_SPEED_HASH: i32 = -1829179668;
pub const ROBOT_CONTROL_GET_STATUS_HASH: i32 = -2104359938;
pub const ROBOT_CONTROL_NAVIGATE_HASH: i32 = 813449939;

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
#[repr(i32)]
pub enum RobotControl_Call {
    UnknownOp(UnknownOperation) = -1,
    Command(RobotControl_command_In) = ROBOT_CONTROL_COMMAND_HASH,
    SetSpeed(RobotControl_setSpeed_In) = ROBOT_CONTROL_SET_SPEED_HASH,
    GetSpeed(RobotControl_getSpeed_In) = ROBOT_CONTROL_GET_SPEED_HASH,
    GetStatus(RobotControl_getStatus_In) = ROBOT_CONTROL_GET_STATUS_HASH,
    Navigate(RobotControl_navigate_In) = ROBOT_CONTROL_NAVIGATE_HASH,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
#[repr(i32)]
pub enum RobotControl_Return {
    UnknownOp(UnknownOperation) = -1,
    Command(RobotControl_command_Result) = ROBOT_CONTROL_COMMAND_HASH,
    SetSpeed(RobotControl_setSpeed_Result) = ROBOT_CONTROL_SET_SPEED_HASH,
    GetSpeed(RobotControl_getSpeed_Result) = ROBOT_CONTROL_GET_SPEED_HASH,
    GetStatus(RobotControl_getStatus_Result) = ROBOT_CONTROL_GET_STATUS_HASH,
    Navigate(RobotControl_navigate_Result) = ROBOT_CONTROL_NAVIGATE_HASH,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RobotControl_Request {
    pub header: RequestHeader,
    pub data: RobotControl_Call,
}

#[derive(DdsType, Debug, Clone)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RobotControl_Reply {
    pub header: ReplyHeader,
    pub data: RobotControl_Return,
}

pub struct RobotControl_command_Future {
    inner: Future<RobotControl_Return>,
}

impl RobotControl_command_Future {
    pub fn get(self) -> DdsRpcResult<()> {
        let sample = self.inner.get().map_err(DdsRpcError::from_untyped)?;
        let data = sample.data().map_err(|e| DdsRpcError::Dds(e.into()))?;
        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }
        match &data.data {
            RobotControl_Return::Command(result) => match result {
                RobotControl_command_Result::Result(out) => Ok(()),
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }

    pub fn get_timeout(self, timeout: Duration) -> DdsRpcResult<()> {
        let sample = self.inner.get_timeout(timeout).map_err(DdsRpcError::from_untyped)?;
        let data = sample.data().map_err(|e| DdsRpcError::Dds(e.into()))?;
        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }
        match &data.data {
            RobotControl_Return::Command(result) => match result {
                RobotControl_command_Result::Result(out) => Ok(()),
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }
}

pub struct RobotControl_setSpeed_Future {
    inner: Future<RobotControl_Return>,
}

impl RobotControl_setSpeed_Future {
    pub fn get(self) -> DdsRpcResult<f32, TooFast> {
        let sample = self.inner.get().map_err(DdsRpcError::from_untyped)?;
        let data = sample.data().map_err(|e| DdsRpcError::Dds(e.into()))?;
        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }
        match &data.data {
            RobotControl_Return::SetSpeed(result) => match result {
                RobotControl_setSpeed_Result::Result(out) => Ok(out.return_.clone()),
                RobotControl_setSpeed_Result::TooFast_ex(ex) => {
                    Err(DdsRpcError::UserException(ex.clone()))
                }
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }

    pub fn get_timeout(self, timeout: Duration) -> DdsRpcResult<f32, TooFast> {
        let sample = self.inner.get_timeout(timeout).map_err(DdsRpcError::from_untyped)?;
        let data = sample.data().map_err(|e| DdsRpcError::Dds(e.into()))?;
        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }
        match &data.data {
            RobotControl_Return::SetSpeed(result) => match result {
                RobotControl_setSpeed_Result::Result(out) => Ok(out.return_.clone()),
                RobotControl_setSpeed_Result::TooFast_ex(ex) => {
                    Err(DdsRpcError::UserException(ex.clone()))
                }
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }
}

pub struct RobotControl_getSpeed_Future {
    inner: Future<RobotControl_Return>,
}

impl RobotControl_getSpeed_Future {
    pub fn get(self) -> DdsRpcResult<f32> {
        let sample = self.inner.get().map_err(DdsRpcError::from_untyped)?;
        let data = sample.data().map_err(|e| DdsRpcError::Dds(e.into()))?;
        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }
        match &data.data {
            RobotControl_Return::GetSpeed(result) => match result {
                RobotControl_getSpeed_Result::Result(out) => Ok(out.return_.clone()),
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }

    pub fn get_timeout(self, timeout: Duration) -> DdsRpcResult<f32> {
        let sample = self.inner.get_timeout(timeout).map_err(DdsRpcError::from_untyped)?;
        let data = sample.data().map_err(|e| DdsRpcError::Dds(e.into()))?;
        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }
        match &data.data {
            RobotControl_Return::GetSpeed(result) => match result {
                RobotControl_getSpeed_Result::Result(out) => Ok(out.return_.clone()),
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }
}

pub struct RobotControl_getStatus_Future {
    inner: Future<RobotControl_Return>,
}

impl RobotControl_getStatus_Future {
    pub fn get(self) -> DdsRpcResult<Status> {
        let sample = self.inner.get().map_err(DdsRpcError::from_untyped)?;
        let data = sample.data().map_err(|e| DdsRpcError::Dds(e.into()))?;
        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }
        match &data.data {
            RobotControl_Return::GetStatus(result) => match result {
                RobotControl_getStatus_Result::Result(out) => Ok(out.status.clone()),
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }

    pub fn get_timeout(self, timeout: Duration) -> DdsRpcResult<Status> {
        let sample = self.inner.get_timeout(timeout).map_err(DdsRpcError::from_untyped)?;
        let data = sample.data().map_err(|e| DdsRpcError::Dds(e.into()))?;
        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }
        match &data.data {
            RobotControl_Return::GetStatus(result) => match result {
                RobotControl_getStatus_Result::Result(out) => Ok(out.status.clone()),
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }
}

pub struct RobotControl_navigate_Future {
    inner: Future<RobotControl_Return>,
}

impl RobotControl_navigate_Future {
    pub fn get(self) -> DdsRpcResult<(), RobotControl_navigate_Error> {
        let sample = self.inner.get().map_err(DdsRpcError::from_untyped)?;
        let data = sample.data().map_err(|e| DdsRpcError::Dds(e.into()))?;
        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }
        match &data.data {
            RobotControl_Return::Navigate(result) => match result {
                RobotControl_navigate_Result::Result(out) => Ok(()),
                RobotControl_navigate_Result::TooFast_ex(ex) => Err(DdsRpcError::UserException(
                    RobotControl_navigate_Error::TooFast(ex.clone()),
                )),
                RobotControl_navigate_Result::InvalidCommand_ex(ex) => {
                    Err(DdsRpcError::UserException(RobotControl_navigate_Error::InvalidCommand(
                        ex.clone(),
                    )))
                }
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }

    pub fn get_timeout(self, timeout: Duration) -> DdsRpcResult<(), RobotControl_navigate_Error> {
        let sample = self.inner.get_timeout(timeout).map_err(DdsRpcError::from_untyped)?;
        let data = sample.data().map_err(|e| DdsRpcError::Dds(e.into()))?;
        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }
        match &data.data {
            RobotControl_Return::Navigate(result) => match result {
                RobotControl_navigate_Result::Result(out) => Ok(()),
                RobotControl_navigate_Result::TooFast_ex(ex) => Err(DdsRpcError::UserException(
                    RobotControl_navigate_Error::TooFast(ex.clone()),
                )),
                RobotControl_navigate_Result::InvalidCommand_ex(ex) => {
                    Err(DdsRpcError::UserException(RobotControl_navigate_Error::InvalidCommand(
                        ex.clone(),
                    )))
                }
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }
}

pub trait RobotControl {
    fn command(&self, com: Command);
    fn set_speed(&self, speed: f32) -> Result<f32, TooFast>;
    fn get_speed(&self) -> f32;
    fn get_status(&self, status: &mut Status);
    fn navigate(&self, x: f32, y: f32) -> Result<(), RobotControl_navigate_Error>;
}

pub trait RobotControlAsync {
    fn command_async(&self, com: &Command) -> DdsRpcResult<RobotControl_command_Future>;
    fn set_speed_async(&self, speed: f32) -> DdsRpcResult<RobotControl_setSpeed_Future>;
    fn get_speed_async(&self) -> DdsRpcResult<RobotControl_getSpeed_Future>;
    fn get_status_async(&self) -> DdsRpcResult<RobotControl_getStatus_Future>;
    fn navigate_async(&self, x: f32, y: f32) -> DdsRpcResult<RobotControl_navigate_Future>;
}

pub struct RobotControlDispatcher<T: RobotControl> {
    inner: T,
}

impl<T: RobotControl> RobotControlDispatcher<T> {
    pub fn new(inner: T) -> Self {
        Self { inner }
    }
}

impl<T: RobotControl + Send + 'static> RequestHandler<RobotControl_Call, RobotControl_Return>
    for RobotControlDispatcher<T>
{
    fn handle_request(
        &self,
        request: &RobotControl_Call,
    ) -> (RobotControl_Return, RemoteExceptionCode) {
        match request {
            RobotControl_Call::Command(RobotControl_command_In { com }) => {
                self.inner.command(com.clone());
                (
                    RobotControl_Return::Command(RobotControl_command_Result::Result(
                        RobotControl_command_Out { dummy: UnusedMember {} },
                    )),
                    RemoteExceptionCode::Ok,
                )
            }
            RobotControl_Call::SetSpeed(RobotControl_setSpeed_In { speed }) => {
                match self.inner.set_speed(*speed) {
                    Ok(return_) => (
                        RobotControl_Return::SetSpeed(RobotControl_setSpeed_Result::Result(
                            RobotControl_setSpeed_Out { return_: return_ },
                        )),
                        RemoteExceptionCode::Ok,
                    ),
                    Err(ex) => (
                        RobotControl_Return::SetSpeed(RobotControl_setSpeed_Result::TooFast_ex(ex)),
                        RemoteExceptionCode::Ok,
                    ),
                }
            }
            RobotControl_Call::GetSpeed(_) => {
                let return_ = self.inner.get_speed();
                (
                    RobotControl_Return::GetSpeed(RobotControl_getSpeed_Result::Result(
                        RobotControl_getSpeed_Out { return_: return_ },
                    )),
                    RemoteExceptionCode::Ok,
                )
            }
            RobotControl_Call::GetStatus(_) => {
                let mut status = Default::default();
                self.inner.get_status(&mut status);
                (
                    RobotControl_Return::GetStatus(RobotControl_getStatus_Result::Result(
                        RobotControl_getStatus_Out { status: status },
                    )),
                    RemoteExceptionCode::Ok,
                )
            }
            RobotControl_Call::Navigate(RobotControl_navigate_In { x, y }) => {
                match self.inner.navigate(*x, *y) {
                    Ok(()) => (
                        RobotControl_Return::Navigate(RobotControl_navigate_Result::Result(
                            RobotControl_navigate_Out { dummy: UnusedMember {} },
                        )),
                        RemoteExceptionCode::Ok,
                    ),
                    Err(err) => match err {
                        RobotControl_navigate_Error::TooFast(ex) => (
                            RobotControl_Return::Navigate(
                                RobotControl_navigate_Result::TooFast_ex(ex),
                            ),
                            RemoteExceptionCode::Ok,
                        ),
                        RobotControl_navigate_Error::InvalidCommand(ex) => (
                            RobotControl_Return::Navigate(
                                RobotControl_navigate_Result::InvalidCommand_ex(ex),
                            ),
                            RemoteExceptionCode::Ok,
                        ),
                    },
                }
            }
            RobotControl_Call::UnknownOp(_) => (
                RobotControl_Return::UnknownOp(UnknownOperation {}),
                RemoteExceptionCode::Unsupported,
            ),
        }
    }
}

pub struct RobotControlService<T: RobotControl + Send + 'static> {
    inner: Service<RobotControl_Call, RobotControl_Return, RobotControlDispatcher<T>>,
}

impl<T: RobotControl + Send + 'static> RobotControlService<T> {
    pub fn new(params: ServiceParams, handler: T) -> DdsRpcResult<Self> {
        let params = params.interface_name("robot::RobotControl");
        let inner = Service::new(params, RobotControlDispatcher::new(handler))?;
        Ok(Self { inner })
    }
}

impl<T: RobotControl + Send + Sync + 'static> Dispatchable for RobotControlService<T> {
    fn try_dispatch_one(&self) -> DdsRpcResult<bool> {
        self.inner.try_dispatch_one()
    }
}

impl<T: RobotControl + Send + 'static> RpcEntity for RobotControlService<T> {
    fn close(&mut self) -> DdsRpcResult<()> {
        self.inner.close()
    }
    fn is_closed(&self) -> bool {
        self.inner.is_closed()
    }
}

pub struct RobotControlClient {
    client: Client<RobotControl_Call, RobotControl_Return>,
    default_timeout: Duration,
}

impl RobotControlClient {
    pub fn new(params: ClientParams) -> DdsRpcResult<Self> {
        let client = Client::new(params.interface_name("robot::RobotControl"))?;
        Ok(Self { client, default_timeout: Duration::from_secs(10) })
    }

    pub fn with_timeout(params: ClientParams, timeout: Duration) -> DdsRpcResult<Self> {
        let client = Client::new(params.interface_name("robot::RobotControl"))?;
        Ok(Self { client, default_timeout: timeout })
    }

    pub fn command(&self, com: Command, timeout: Duration) -> DdsRpcResult<()> {
        let call = RobotControl_Call::Command(RobotControl_command_In { com });
        let _id = self.client.send_request(&call).map_err(DdsRpcError::from_untyped)?;
        let reply = self.client.receive_reply(timeout).map_err(DdsRpcError::from_untyped)?;
        let data = reply.data().map_err(|e| DdsRpcError::Dds(e.into()))?;

        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }

        match &data.data {
            RobotControl_Return::Command(result) => match result {
                RobotControl_command_Result::Result(out) => Ok(()),
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }

    pub fn set_speed(&self, speed: f32, timeout: Duration) -> DdsRpcResult<f32, TooFast> {
        let call = RobotControl_Call::SetSpeed(RobotControl_setSpeed_In { speed });
        let _id = self.client.send_request(&call).map_err(DdsRpcError::from_untyped)?;
        let reply = self.client.receive_reply(timeout).map_err(DdsRpcError::from_untyped)?;
        let data = reply.data().map_err(|e| DdsRpcError::Dds(e.into()))?;

        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }

        match &data.data {
            RobotControl_Return::SetSpeed(result) => match result {
                RobotControl_setSpeed_Result::Result(out) => Ok(out.return_.clone()),
                RobotControl_setSpeed_Result::TooFast_ex(ex) => {
                    Err(DdsRpcError::UserException(ex.clone()))
                }
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }

    pub fn get_speed(&self, timeout: Duration) -> DdsRpcResult<f32> {
        let call = RobotControl_Call::GetSpeed(RobotControl_getSpeed_In { dummy: UnusedMember {} });
        let _id = self.client.send_request(&call).map_err(DdsRpcError::from_untyped)?;
        let reply = self.client.receive_reply(timeout).map_err(DdsRpcError::from_untyped)?;
        let data = reply.data().map_err(|e| DdsRpcError::Dds(e.into()))?;

        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }

        match &data.data {
            RobotControl_Return::GetSpeed(result) => match result {
                RobotControl_getSpeed_Result::Result(out) => Ok(out.return_.clone()),
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }

    pub fn get_status(&self, timeout: Duration) -> DdsRpcResult<Status> {
        let call =
            RobotControl_Call::GetStatus(RobotControl_getStatus_In { dummy: UnusedMember {} });
        let _id = self.client.send_request(&call).map_err(DdsRpcError::from_untyped)?;
        let reply = self.client.receive_reply(timeout).map_err(DdsRpcError::from_untyped)?;
        let data = reply.data().map_err(|e| DdsRpcError::Dds(e.into()))?;

        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }

        match &data.data {
            RobotControl_Return::GetStatus(result) => match result {
                RobotControl_getStatus_Result::Result(out) => Ok(out.status.clone()),
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }

    pub fn navigate(
        &self,
        x: f32,
        y: f32,
        timeout: Duration,
    ) -> DdsRpcResult<(), RobotControl_navigate_Error> {
        let call = RobotControl_Call::Navigate(RobotControl_navigate_In { x, y });
        let _id = self.client.send_request(&call).map_err(DdsRpcError::from_untyped)?;
        let reply = self.client.receive_reply(timeout).map_err(DdsRpcError::from_untyped)?;
        let data = reply.data().map_err(|e| DdsRpcError::Dds(e.into()))?;

        if data.header.remote_ex != RemoteExceptionCode::Ok {
            return Err(DdsRpcError::Remote(data.header.remote_ex));
        }

        match &data.data {
            RobotControl_Return::Navigate(result) => match result {
                RobotControl_navigate_Result::Result(out) => Ok(()),
                RobotControl_navigate_Result::TooFast_ex(ex) => Err(DdsRpcError::UserException(
                    RobotControl_navigate_Error::TooFast(ex.clone()),
                )),
                RobotControl_navigate_Result::InvalidCommand_ex(ex) => {
                    Err(DdsRpcError::UserException(RobotControl_navigate_Error::InvalidCommand(
                        ex.clone(),
                    )))
                }
                _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownException)),
            },
            _ => Err(DdsRpcError::Remote(RemoteExceptionCode::UnknownOperation)),
        }
    }
}

impl RobotControlAsync for RobotControlClient {
    fn command_async(&self, com: &Command) -> DdsRpcResult<RobotControl_command_Future> {
        let call = RobotControl_Call::Command(RobotControl_command_In { com: com.clone() });
        let future = self.client.send_request_async(&call).map_err(DdsRpcError::from_untyped)?;
        Ok(RobotControl_command_Future { inner: future })
    }
    fn set_speed_async(&self, speed: f32) -> DdsRpcResult<RobotControl_setSpeed_Future> {
        let call = RobotControl_Call::SetSpeed(RobotControl_setSpeed_In { speed });
        let future = self.client.send_request_async(&call).map_err(DdsRpcError::from_untyped)?;
        Ok(RobotControl_setSpeed_Future { inner: future })
    }
    fn get_speed_async(&self) -> DdsRpcResult<RobotControl_getSpeed_Future> {
        let call = RobotControl_Call::GetSpeed(RobotControl_getSpeed_In { dummy: UnusedMember {} });
        let future = self.client.send_request_async(&call).map_err(DdsRpcError::from_untyped)?;
        Ok(RobotControl_getSpeed_Future { inner: future })
    }
    fn get_status_async(&self) -> DdsRpcResult<RobotControl_getStatus_Future> {
        let call =
            RobotControl_Call::GetStatus(RobotControl_getStatus_In { dummy: UnusedMember {} });
        let future = self.client.send_request_async(&call).map_err(DdsRpcError::from_untyped)?;
        Ok(RobotControl_getStatus_Future { inner: future })
    }
    fn navigate_async(&self, x: f32, y: f32) -> DdsRpcResult<RobotControl_navigate_Future> {
        let call = RobotControl_Call::Navigate(RobotControl_navigate_In { x, y });
        let future = self.client.send_request_async(&call).map_err(DdsRpcError::from_untyped)?;
        Ok(RobotControl_navigate_Future { inner: future })
    }
}

impl RpcEntity for RobotControlClient {
    fn close(&mut self) -> DdsRpcResult<()> {
        self.client.close()
    }
    fn is_closed(&self) -> bool {
        self.client.is_closed()
    }
}

impl ServiceProxy for RobotControlClient {
    fn bind_instance(&mut self, name: InstanceName) -> DdsRpcResult<()> {
        self.client.bind_instance(name)
    }
    fn unbind(&mut self) -> DdsRpcResult<()> {
        self.client.unbind()
    }
    fn get_bound_instance_name(&self) -> Option<&str> {
        self.client.get_bound_instance_name()
    }
    fn wait_for_service(&self) -> DdsRpcResult<()> {
        self.client.wait_for_service()
    }
    fn wait_for_service_timeout(&self, timeout: Duration) -> DdsRpcResult<()> {
        self.client.wait_for_service_timeout(timeout)
    }
}

impl ClientEndpoint for RobotControlClient {
    type TReq = RobotControl_Call;
    type TRep = RobotControl_Return;
    fn get_request_datawriter(
        &self,
    ) -> DdsRpcResult<
        &int2dds::dcps::publication::data_writer::DataWriter<
            int2dds_rpc::types::Request<Self::TReq>,
        >,
    > {
        self.client.get_request_datawriter()
    }
    fn get_reply_datareader(
        &self,
    ) -> DdsRpcResult<
        &int2dds::dcps::subscription::data_reader::DataReader<
            int2dds_rpc::types::Reply<Self::TRep>,
        >,
    > {
        self.client.get_reply_datareader()
    }
}
