// Auto-generated by int2dds-idl from CdrGolden.idl
// DO NOT EDIT

package com.intellectus.int2dds.types;

import com.intellectus.int2dds.cdr.CdrReader;
import com.intellectus.int2dds.cdr.CdrWriter;
import com.intellectus.int2dds.cdr.Extensibility;
import com.intellectus.int2dds.core.TopicFieldDescriptor;
import com.intellectus.int2dds.types.IDdsType;
import com.intellectus.int2dds.xtypes.FieldType;
import java.util.Arrays;
import java.util.List;

public final class CdrGolden implements IDdsType {

    public int id;
    public boolean boolVal;
    public byte i8Val;
    public byte u8Val;
    public short i16Val;
    public short u16Val;
    public int i32Val;
    public int u32Val;
    public long i64Val;
    public long u64Val;
    public String unboundedStr = "";
    public String boundedStr = "";
    public byte byteVal;
    public byte charVal;
    public float f32Val;
    public double f64Val;

    @Override
    public String typeName() {
        return "CdrGolden";
    }

    @Override
    public Extensibility extensibility() {
        return Extensibility.APPENDABLE;
    }

    @Override
    public void serializeCdr(CdrWriter writer) {
        int token = writer.dheaderBegin();
        writer.writeI32(this.id);
        writer.writeBool(this.boolVal);
        writer.writeI8(this.i8Val);
        writer.writeU8(this.u8Val & 0xFF);
        writer.writeI16(this.i16Val);
        writer.writeU16(this.u16Val & 0xFFFF);
        writer.writeI32(this.i32Val);
        writer.writeU32(this.u32Val);
        writer.writeI64(this.i64Val);
        writer.writeU64(this.u64Val);
        writer.writeString(this.unboundedStr);
        if (this.boundedStr.length() > 64) {
            throw new IllegalStateException("boundedStr exceeds its IDL bound of 64");
        }
        writer.writeString(this.boundedStr);
        writer.writeU8(this.byteVal & 0xFF);
        writer.writeU8(this.charVal & 0xFF);
        writer.writeF32(this.f32Val);
        writer.writeF64(this.f64Val);
        writer.dheaderFinalize(token);
    }

    @Override
    public void deserializeCdr(CdrReader reader) {
        CdrReader.Dheader d = reader.readDheader();
        this.id = reader.readI32();
        this.boolVal = reader.readBool();
        this.i8Val = reader.readI8();
        this.u8Val = (byte) reader.readU8();
        this.i16Val = reader.readI16();
        this.u16Val = (short) reader.readU16();
        this.i32Val = reader.readI32();
        this.u32Val = reader.readU32();
        this.i64Val = reader.readI64();
        this.u64Val = reader.readU64();
        this.unboundedStr = reader.readString();
        this.boundedStr = reader.readString();
        this.byteVal = (byte) reader.readU8();
        this.charVal = (byte) reader.readU8();
        this.f32Val = reader.readF32();
        this.f64Val = reader.readF64();
        reader.readDheaderEnd(d);
    }

    /**
     * Field descriptors for {@link com.intellectus.int2dds.core.DomainParticipant
     * #createTopic(String, com.intellectus.int2dds.types.IDdsType, List)}.
     * Covers every field up to and including the last {@code @key} one:
     * the core's flat parser walks them in order and a gap misaligns
     * everything after it.
     */
    public static List<TopicFieldDescriptor> ddsFields() {
        return Arrays.asList(
                new TopicFieldDescriptor("id", FieldType.INT32, true),
                new TopicFieldDescriptor("bool_val", FieldType.BOOL, false),
                new TopicFieldDescriptor("i8_val", FieldType.INT8, false),
                new TopicFieldDescriptor("u8_val", FieldType.UINT8, false),
                new TopicFieldDescriptor("i16_val", FieldType.INT16, false),
                new TopicFieldDescriptor("u16_val", FieldType.UINT16, false),
                new TopicFieldDescriptor("i32_val", FieldType.INT32, false),
                new TopicFieldDescriptor("u32_val", FieldType.UINT32, false),
                new TopicFieldDescriptor("i64_val", FieldType.INT64, false),
                new TopicFieldDescriptor("u64_val", FieldType.UINT64, false),
                new TopicFieldDescriptor("unbounded_str", FieldType.STRING, false),
                new TopicFieldDescriptor("bounded_str", FieldType.STRING, true));
    }
}
