/**
 * Auto-generated by int2dds-idl from Nested_Structs.idl
 * DO NOT EDIT - changes will be overwritten
 */
#ifndef NESTED__STRUCTS_IDL_H
#define NESTED__STRUCTS_IDL_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "int2dds_cdr.h"

/* ========================================================================
 * Type: DeepInnerStruct
 * Extensibility: FINAL
 * ======================================================================== */

typedef struct DeepInnerStruct {
    int32_t value;
    char description[257];
} DeepInnerStruct;

static inline void DeepInnerStruct_serialize_fields(
    Int2DdsCdrWriter *_w,
    const DeepInnerStruct *val)
{
    Int2DdsCdrWriter w = *_w;
    int2dds_cdr_write_i32(&w, val->value);
    int2dds_cdr_write_string(&w, val->description);
    *_w = w;
}

static inline void DeepInnerStruct_deserialize_fields(
    Int2DdsCdrReader *_r,
    DeepInnerStruct *val_out)
{
    Int2DdsCdrReader r = *_r;
    int2dds_cdr_read_i32(&r, &val_out->value);
    int2dds_cdr_read_string_copy(&r, val_out->description, 257, NULL);
    *_r = r;
}

static inline size_t DeepInnerStruct_serialize_cdr(
    const DeepInnerStruct *val,
    uint8_t *buf,
    size_t capacity,
    bool xcdr2)
{
    Int2DdsCdrWriter w;
    int2dds_cdr_writer_init(&w, buf, capacity, true, xcdr2);
    int2dds_cdr_write_encapsulation(&w, INT2DDS_CDR_FINAL);
    int2dds_cdr_write_i32(&w, val->value);
    int2dds_cdr_write_string(&w, val->description);
    return w.error == INT2DDS_CDR_OK ? int2dds_cdr_writer_size(&w) : 0;
}

static inline bool DeepInnerStruct_deserialize_cdr(
    const uint8_t *buf,
    size_t len,
    DeepInnerStruct *val_out)
{
    Int2DdsCdrReader r;
    if (int2dds_cdr_reader_init(&r, buf, len) != INT2DDS_CDR_OK)
        return false;
    int2dds_cdr_read_i32(&r, &val_out->value);
    int2dds_cdr_read_string_copy(&r, val_out->description, 257, NULL);
    return int2dds_cdr_reader_error(&r) == INT2DDS_CDR_OK;
}

static inline size_t DeepInnerStruct_serialize_key(
    const DeepInnerStruct *val,
    uint8_t *buf,
    size_t capacity)
{
    (void)val; (void)buf; (void)capacity;
    return 0;
}

static inline Int2DdsTypeInfo* DeepInnerStruct_type_info(void) {
    Int2DdsTypeInfo *ti;
    int2dds_type_info_create("DeepInnerStruct", 0, &ti);
    int2dds_type_info_add_field(ti, "value", INT2DDS_FIELD_INT32, 0);
    int2dds_type_info_add_field(ti, "description", INT2DDS_FIELD_STRING, 0);
    return ti;
}

/* ========================================================================
 * Type: MiddleStruct
 * Extensibility: FINAL
 * ======================================================================== */

typedef struct MiddleStruct {
    int32_t level;
    DeepInnerStruct deep;
} MiddleStruct;

static inline void MiddleStruct_serialize_fields(
    Int2DdsCdrWriter *_w,
    const MiddleStruct *val)
{
    Int2DdsCdrWriter w = *_w;
    int2dds_cdr_write_i32(&w, val->level);
    { size_t _mbr_dh = 0;
    if (w.xcdr2) { int2dds_cdr_write_dheader_begin(&w, &_mbr_dh); }
    DeepInnerStruct_serialize_fields(&w, &val->deep);
    if (w.xcdr2) { int2dds_cdr_write_dheader_finalize(&w, _mbr_dh); }
    }
    *_w = w;
}

static inline void MiddleStruct_deserialize_fields(
    Int2DdsCdrReader *_r,
    MiddleStruct *val_out)
{
    Int2DdsCdrReader r = *_r;
    int2dds_cdr_read_i32(&r, &val_out->level);
    { uint32_t _mbr_sz = 0; size_t _mbr_sp = 0;
    if (r.xcdr2) { int2dds_cdr_read_dheader(&r, &_mbr_sz, &_mbr_sp); }
    DeepInnerStruct_deserialize_fields(&r, &val_out->deep);
    if (r.xcdr2) { int2dds_cdr_read_dheader_end(&r, _mbr_sz, _mbr_sp); }
    }
    *_r = r;
}

static inline size_t MiddleStruct_serialize_cdr(
    const MiddleStruct *val,
    uint8_t *buf,
    size_t capacity,
    bool xcdr2)
{
    Int2DdsCdrWriter w;
    int2dds_cdr_writer_init(&w, buf, capacity, true, xcdr2);
    int2dds_cdr_write_encapsulation(&w, INT2DDS_CDR_FINAL);
    int2dds_cdr_write_i32(&w, val->level);
    { size_t _mbr_dh = 0;
    if (w.xcdr2) { int2dds_cdr_write_dheader_begin(&w, &_mbr_dh); }
    DeepInnerStruct_serialize_fields(&w, &val->deep);
    if (w.xcdr2) { int2dds_cdr_write_dheader_finalize(&w, _mbr_dh); }
    }
    return w.error == INT2DDS_CDR_OK ? int2dds_cdr_writer_size(&w) : 0;
}

static inline bool MiddleStruct_deserialize_cdr(
    const uint8_t *buf,
    size_t len,
    MiddleStruct *val_out)
{
    Int2DdsCdrReader r;
    if (int2dds_cdr_reader_init(&r, buf, len) != INT2DDS_CDR_OK)
        return false;
    int2dds_cdr_read_i32(&r, &val_out->level);
    { uint32_t _mbr_sz = 0; size_t _mbr_sp = 0;
    if (r.xcdr2) { int2dds_cdr_read_dheader(&r, &_mbr_sz, &_mbr_sp); }
    DeepInnerStruct_deserialize_fields(&r, &val_out->deep);
    if (r.xcdr2) { int2dds_cdr_read_dheader_end(&r, _mbr_sz, _mbr_sp); }
    }
    return int2dds_cdr_reader_error(&r) == INT2DDS_CDR_OK;
}

static inline size_t MiddleStruct_serialize_key(
    const MiddleStruct *val,
    uint8_t *buf,
    size_t capacity)
{
    (void)val; (void)buf; (void)capacity;
    return 0;
}

static inline Int2DdsTypeInfo* MiddleStruct_type_info(void) {
    Int2DdsTypeInfo *ti;
    int2dds_type_info_create("MiddleStruct", 0, &ti);
    int2dds_type_info_add_field(ti, "level", INT2DDS_FIELD_INT32, 0);
    int2dds_type_info_add_named_type_field(ti, "deep", "DeepInnerStruct", 0);
    return ti;
}

/* ========================================================================
 * Type: InnerStruct
 * Extensibility: FINAL
 * ======================================================================== */

typedef struct InnerStruct {
    int32_t x;
    int32_t y;
    char name[257];
} InnerStruct;

static inline void InnerStruct_serialize_fields(
    Int2DdsCdrWriter *_w,
    const InnerStruct *val)
{
    Int2DdsCdrWriter w = *_w;
    int2dds_cdr_write_i32(&w, val->x);
    int2dds_cdr_write_i32(&w, val->y);
    int2dds_cdr_write_string(&w, val->name);
    *_w = w;
}

static inline void InnerStruct_deserialize_fields(
    Int2DdsCdrReader *_r,
    InnerStruct *val_out)
{
    Int2DdsCdrReader r = *_r;
    int2dds_cdr_read_i32(&r, &val_out->x);
    int2dds_cdr_read_i32(&r, &val_out->y);
    int2dds_cdr_read_string_copy(&r, val_out->name, 257, NULL);
    *_r = r;
}

static inline size_t InnerStruct_serialize_cdr(
    const InnerStruct *val,
    uint8_t *buf,
    size_t capacity,
    bool xcdr2)
{
    Int2DdsCdrWriter w;
    int2dds_cdr_writer_init(&w, buf, capacity, true, xcdr2);
    int2dds_cdr_write_encapsulation(&w, INT2DDS_CDR_FINAL);
    int2dds_cdr_write_i32(&w, val->x);
    int2dds_cdr_write_i32(&w, val->y);
    int2dds_cdr_write_string(&w, val->name);
    return w.error == INT2DDS_CDR_OK ? int2dds_cdr_writer_size(&w) : 0;
}

static inline bool InnerStruct_deserialize_cdr(
    const uint8_t *buf,
    size_t len,
    InnerStruct *val_out)
{
    Int2DdsCdrReader r;
    if (int2dds_cdr_reader_init(&r, buf, len) != INT2DDS_CDR_OK)
        return false;
    int2dds_cdr_read_i32(&r, &val_out->x);
    int2dds_cdr_read_i32(&r, &val_out->y);
    int2dds_cdr_read_string_copy(&r, val_out->name, 257, NULL);
    return int2dds_cdr_reader_error(&r) == INT2DDS_CDR_OK;
}

static inline size_t InnerStruct_serialize_key(
    const InnerStruct *val,
    uint8_t *buf,
    size_t capacity)
{
    (void)val; (void)buf; (void)capacity;
    return 0;
}

static inline Int2DdsTypeInfo* InnerStruct_type_info(void) {
    Int2DdsTypeInfo *ti;
    int2dds_type_info_create("InnerStruct", 0, &ti);
    int2dds_type_info_add_field(ti, "x", INT2DDS_FIELD_INT32, 0);
    int2dds_type_info_add_field(ti, "y", INT2DDS_FIELD_INT32, 0);
    int2dds_type_info_add_field(ti, "name", INT2DDS_FIELD_STRING, 0);
    return ti;
}

/* ========================================================================
 * Type: NestedStructType
 * Extensibility: APPENDABLE
 * ======================================================================== */

typedef struct NestedStructType {
    int32_t id;
    InnerStruct simple_nested;
    MiddleStruct deep_nested;
    struct { InnerStruct* data; uint32_t length; } struct_seq;
} NestedStructType;

static inline void NestedStructType_serialize_fields(
    Int2DdsCdrWriter *_w,
    const NestedStructType *val)
{
    Int2DdsCdrWriter w = *_w;
    size_t dh = 0;
    if (w.xcdr2) {
        int2dds_cdr_write_dheader_begin(&w, &dh);
    }
    int2dds_cdr_write_i32(&w, val->id);
    { size_t _mbr_dh = 0;
    if (w.xcdr2) { int2dds_cdr_write_dheader_begin(&w, &_mbr_dh); }
    InnerStruct_serialize_fields(&w, &val->simple_nested);
    if (w.xcdr2) { int2dds_cdr_write_dheader_finalize(&w, _mbr_dh); }
    }
    { size_t _mbr_dh = 0;
    if (w.xcdr2) { int2dds_cdr_write_dheader_begin(&w, &_mbr_dh); }
    MiddleStruct_serialize_fields(&w, &val->deep_nested);
    if (w.xcdr2) { int2dds_cdr_write_dheader_finalize(&w, _mbr_dh); }
    }
    int2dds_cdr_write_seq_header(&w, val->struct_seq.length);
    for (uint32_t _i = 0; _i < val->struct_seq.length; _i++) {
        { size_t _mbr_dh = 0;
        if (w.xcdr2) { int2dds_cdr_write_dheader_begin(&w, &_mbr_dh); }
        InnerStruct_serialize_fields(&w, &val->struct_seq.data[_i]);
        if (w.xcdr2) { int2dds_cdr_write_dheader_finalize(&w, _mbr_dh); }
        }
    }
    if (w.xcdr2) {
        int2dds_cdr_write_dheader_finalize(&w, dh);
    }
    *_w = w;
}

static inline void NestedStructType_deserialize_fields(
    Int2DdsCdrReader *_r,
    NestedStructType *val_out)
{
    Int2DdsCdrReader r = *_r;
    uint32_t obj_size = 0;
    size_t start_pos = 0;
    if (r.xcdr2) {
        int2dds_cdr_read_dheader(&r, &obj_size, &start_pos);
    }
    int2dds_cdr_read_i32(&r, &val_out->id);
    { uint32_t _mbr_sz = 0; size_t _mbr_sp = 0;
    if (r.xcdr2) { int2dds_cdr_read_dheader(&r, &_mbr_sz, &_mbr_sp); }
    InnerStruct_deserialize_fields(&r, &val_out->simple_nested);
    if (r.xcdr2) { int2dds_cdr_read_dheader_end(&r, _mbr_sz, _mbr_sp); }
    }
    { uint32_t _mbr_sz = 0; size_t _mbr_sp = 0;
    if (r.xcdr2) { int2dds_cdr_read_dheader(&r, &_mbr_sz, &_mbr_sp); }
    MiddleStruct_deserialize_fields(&r, &val_out->deep_nested);
    if (r.xcdr2) { int2dds_cdr_read_dheader_end(&r, _mbr_sz, _mbr_sp); }
    }
    int2dds_cdr_read_seq_header(&r, &val_out->struct_seq.length);
    for (uint32_t _i = 0; _i < val_out->struct_seq.length; _i++) {
        { uint32_t _mbr_sz = 0; size_t _mbr_sp = 0;
        if (r.xcdr2) { int2dds_cdr_read_dheader(&r, &_mbr_sz, &_mbr_sp); }
        InnerStruct_deserialize_fields(&r, &val_out->struct_seq.data[_i]);
        if (r.xcdr2) { int2dds_cdr_read_dheader_end(&r, _mbr_sz, _mbr_sp); }
        }
    }
    if (r.xcdr2) {
        int2dds_cdr_read_dheader_end(&r, obj_size, start_pos);
    }
    *_r = r;
}

static inline size_t NestedStructType_serialize_cdr(
    const NestedStructType *val,
    uint8_t *buf,
    size_t capacity,
    bool xcdr2)
{
    Int2DdsCdrWriter w;
    int2dds_cdr_writer_init(&w, buf, capacity, true, xcdr2);
    int2dds_cdr_write_encapsulation(&w, INT2DDS_CDR_APPENDABLE);
    size_t dh = 0;
    if (xcdr2) {
        int2dds_cdr_write_dheader_begin(&w, &dh);
    }
    int2dds_cdr_write_i32(&w, val->id);
    { size_t _mbr_dh = 0;
    if (w.xcdr2) { int2dds_cdr_write_dheader_begin(&w, &_mbr_dh); }
    InnerStruct_serialize_fields(&w, &val->simple_nested);
    if (w.xcdr2) { int2dds_cdr_write_dheader_finalize(&w, _mbr_dh); }
    }
    { size_t _mbr_dh = 0;
    if (w.xcdr2) { int2dds_cdr_write_dheader_begin(&w, &_mbr_dh); }
    MiddleStruct_serialize_fields(&w, &val->deep_nested);
    if (w.xcdr2) { int2dds_cdr_write_dheader_finalize(&w, _mbr_dh); }
    }
    int2dds_cdr_write_seq_header(&w, val->struct_seq.length);
    for (uint32_t _i = 0; _i < val->struct_seq.length; _i++) {
        { size_t _mbr_dh = 0;
        if (w.xcdr2) { int2dds_cdr_write_dheader_begin(&w, &_mbr_dh); }
        InnerStruct_serialize_fields(&w, &val->struct_seq.data[_i]);
        if (w.xcdr2) { int2dds_cdr_write_dheader_finalize(&w, _mbr_dh); }
        }
    }
    if (xcdr2) {
        int2dds_cdr_write_dheader_finalize(&w, dh);
    }
    return w.error == INT2DDS_CDR_OK ? int2dds_cdr_writer_size(&w) : 0;
}

static inline bool NestedStructType_deserialize_cdr(
    const uint8_t *buf,
    size_t len,
    NestedStructType *val_out)
{
    Int2DdsCdrReader r;
    if (int2dds_cdr_reader_init(&r, buf, len) != INT2DDS_CDR_OK)
        return false;
    uint32_t obj_size = 0;
    size_t start_pos = 0;
    if (r.xcdr2) {
        int2dds_cdr_read_dheader(&r, &obj_size, &start_pos);
    }
    int2dds_cdr_read_i32(&r, &val_out->id);
    { uint32_t _mbr_sz = 0; size_t _mbr_sp = 0;
    if (r.xcdr2) { int2dds_cdr_read_dheader(&r, &_mbr_sz, &_mbr_sp); }
    InnerStruct_deserialize_fields(&r, &val_out->simple_nested);
    if (r.xcdr2) { int2dds_cdr_read_dheader_end(&r, _mbr_sz, _mbr_sp); }
    }
    { uint32_t _mbr_sz = 0; size_t _mbr_sp = 0;
    if (r.xcdr2) { int2dds_cdr_read_dheader(&r, &_mbr_sz, &_mbr_sp); }
    MiddleStruct_deserialize_fields(&r, &val_out->deep_nested);
    if (r.xcdr2) { int2dds_cdr_read_dheader_end(&r, _mbr_sz, _mbr_sp); }
    }
    int2dds_cdr_read_seq_header(&r, &val_out->struct_seq.length);
    for (uint32_t _i = 0; _i < val_out->struct_seq.length; _i++) {
        { uint32_t _mbr_sz = 0; size_t _mbr_sp = 0;
        if (r.xcdr2) { int2dds_cdr_read_dheader(&r, &_mbr_sz, &_mbr_sp); }
        InnerStruct_deserialize_fields(&r, &val_out->struct_seq.data[_i]);
        if (r.xcdr2) { int2dds_cdr_read_dheader_end(&r, _mbr_sz, _mbr_sp); }
        }
    }
    if (r.xcdr2) {
        int2dds_cdr_read_dheader_end(&r, obj_size, start_pos);
    }
    return int2dds_cdr_reader_error(&r) == INT2DDS_CDR_OK;
}

static inline size_t NestedStructType_serialize_key(
    const NestedStructType *val,
    uint8_t *buf,
    size_t capacity)
{
    Int2DdsCdrWriter w;
    int2dds_cdr_writer_init(&w, buf, capacity, false, true); /* BE, XCDR2, no header */
    int2dds_cdr_write_i32(&w, val->id);
    return w.error == INT2DDS_CDR_OK ? int2dds_cdr_writer_size(&w) : 0;
}

static inline Int2DdsTypeInfo* NestedStructType_type_info(void) {
    Int2DdsTypeInfo *ti;
    int2dds_type_info_create("NestedStructType", 1, &ti);
    int2dds_type_info_add_field(ti, "id", INT2DDS_FIELD_INT32, 1);
    int2dds_type_info_add_named_type_field(ti, "simple_nested", "InnerStruct", 0);
    int2dds_type_info_add_named_type_field(ti, "deep_nested", "MiddleStruct", 0);
    int2dds_type_info_add_named_type_field(ti, "struct_seq", "Vec < InnerStruct >", 0);
    return ti;
}

#endif /* NESTED__STRUCTS_IDL_H */
