/// C# code generation backend.
///
/// Generates C# classes with CDR serialization methods
/// that use the Int2Dds C# CDR library.
use crate::codegen::flatten_array;
use crate::naming;
use crate::types::*;

/// Options for C# code generation.
#[derive(Debug, Clone)]
pub struct CSharpOptions {
    /// Namespace for the generated types (default: "GeneratedTypes")
    pub namespace: String,
}

impl Default for CSharpOptions {
    fn default() -> Self {
        Self::new()
    }
}

impl CSharpOptions {
    pub fn new() -> Self {
        Self { namespace: "GeneratedTypes".to_string() }
    }
}

/// Generate C# code from the IDL model.
pub fn generate(model: &IdlModel, idl_filename: &str, opts: &CSharpOptions) -> String {
    let mut gen = CsGen { out: String::new(), opts, model, indent: 0 };
    gen.emit_file(idl_filename);
    gen.out
}

/// Convert a name to PascalCase and escape if it's a C# keyword.
fn cs_ident(name: &str) -> String {
    naming::escape_keyword(&naming::to_pascal_case(name), naming::TargetLang::CSharp)
}

/// PascalCase a struct/enum/bitmask type reference by its leaf name. A cross-file
/// reference may be written qualified (`dep::msg::Header`); every generated type
/// shares one namespace, so C# resolves the leaf directly and the scope is dropped.
fn cs_type_ref(name: &str) -> String {
    naming::to_pascal_case(name.rsplit("::").next().unwrap_or(name))
}

/// Render a constant value as a C# literal (float constants need an `f` suffix).
fn cs_const_value(value: &ConstValue, ty: &ResolvedType) -> String {
    match value {
        ConstValue::Int(v) => v.to_string(),
        ConstValue::Float(v) => match ty {
            ResolvedType::F32 => format!("{:?}f", v),
            _ => format!("{:?}", v),
        },
        ConstValue::Bool(v) => v.to_string(),
        ConstValue::Str(v) => format!("{:?}", v),
        ConstValue::Ident(v) => v.rsplit("::").next().unwrap_or(v).to_string(),
    }
}

struct CsGen<'a> {
    out: String,
    opts: &'a CSharpOptions,
    model: &'a IdlModel,
    indent: usize,
}

impl<'a> CsGen<'a> {
    fn emit_file(&mut self, idl_filename: &str) {
        // File header
        self.line(&format!("// Auto-generated by int2dds-idl from {}", idl_filename));
        self.line("// DO NOT EDIT");
        self.line("");
        self.line("using System;");
        self.line("using System.Collections.Generic;");
        self.line("using Int2Dds.Cdr;");
        self.line("using Int2Dds.Types;");
        self.line("");
        self.line(&format!("namespace {}", self.opts.namespace));
        self.line("{");
        self.indent += 1;

        self.emit_constants();

        // Enums first (may be referenced by structs)
        for e in &self.model.enums.clone() {
            self.emit_enum(e);
            self.line("");
        }

        // Bitmasks
        for b in &self.model.bitmasks.clone() {
            self.emit_bitmask(b);
            self.line("");
        }

        // Bitsets
        for b in &self.model.bitsets.clone() {
            self.emit_bitset(b);
            self.line("");
        }

        // Unions
        for u in &self.model.unions.clone() {
            self.emit_union(u);
            self.line("");
        }

        // Structs
        for s in &self.model.structs.clone() {
            self.emit_struct(s);
            self.line("");
        }

        self.indent -= 1;
        self.line("}");
    }

    // ---- Enum ----

    fn emit_enum(&mut self, e: &ResolvedEnum) {
        let name = naming::to_pascal_case(&e.name);
        self.line(&format!("public enum {}", name));
        self.line("{");
        self.indent += 1;
        for v in &e.variants {
            let variant_name = cs_ident(&v.name);
            self.line(&format!("{} = {},", variant_name, v.value));
        }
        self.indent -= 1;
        self.line("}");
    }

    // ---- Bitmask ----

    fn bitmask_backing_info(
        bit_bound: u32,
    ) -> (&'static str, &'static str, &'static str, &'static str) {
        // Returns (cs_type, write_method, read_method, suffix)
        if bit_bound <= 8 {
            ("byte", "WriteU8", "ReadU8", "")
        } else if bit_bound <= 16 {
            ("ushort", "WriteU16", "ReadU16", "")
        } else if bit_bound <= 32 {
            ("uint", "WriteU32", "ReadU32", "u")
        } else {
            ("ulong", "WriteU64", "ReadU64", "ul")
        }
    }

    fn emit_bitmask(&mut self, b: &ResolvedBitmask) {
        let name = naming::to_pascal_case(&b.name);
        let (cs_type, _, _, suffix) = Self::bitmask_backing_info(b.bit_bound);
        self.line("[Flags]");
        self.line(&format!("public enum {} : {}", name, cs_type));
        self.line("{");
        self.indent += 1;
        for flag in &b.flags {
            let flag_name = cs_ident(&flag.name);
            self.line(&format!("{} = 1{} << {},", flag_name, suffix, flag.position));
        }
        self.indent -= 1;
        self.line("}");
    }

    // ---- Bitset ----

    fn emit_bitset(&mut self, b: &ResolvedBitset) {
        let class_name = naming::to_pascal_case(&b.name);

        // Determine the backing storage type based on total_bits
        let (storage_type, read_method, write_method) = if b.total_bits <= 8 {
            ("byte", "ReadU8", "WriteU8")
        } else if b.total_bits <= 16 {
            ("ushort", "ReadU16", "WriteU16")
        } else if b.total_bits <= 32 {
            ("uint", "ReadU32", "WriteU32")
        } else {
            ("ulong", "ReadU64", "WriteU64")
        };

        self.line(&format!("public class {}", class_name));
        self.line("{");
        self.indent += 1;

        // Properties for each bitfield
        for f in &b.fields {
            let prop_name = cs_ident(&f.name);
            let field_type = if f.bit_width <= 8 {
                "byte"
            } else if f.bit_width <= 16 {
                "ushort"
            } else {
                "uint"
            };
            self.line(&format!("public {} {} {{ get; set; }}", field_type, prop_name));
        }
        self.line("");

        self.line(&format!("public {}() {{ }}", class_name));
        self.line("");

        // SerializeCdr
        self.line("public byte[] SerializeCdr() => SerializeCdr(false);");
        self.line("");
        self.line("public byte[] SerializeCdr(bool xcdr2)");
        self.line("{");
        self.indent += 1;
        self.line("var w = new CdrWriter(Extensibility.Final, xcdr2: xcdr2);");
        self.line(&format!("{} packed = 0;", storage_type));
        let mut bit_offset = 0u32;
        for f in &b.fields {
            let prop_name = cs_ident(&f.name);
            let mask = (1u64 << f.bit_width) - 1;
            self.line(&format!(
                "packed |= ({})(((ulong){} & 0x{:X}) << {});",
                storage_type, prop_name, mask, bit_offset
            ));
            bit_offset += f.bit_width;
        }
        self.line(&format!("w.{}(packed);", write_method));
        self.line("return w.ToBytes();");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // DeserializeCdr
        self.line(&format!("public static {} DeserializeCdr(ReadOnlySpan<byte> data)", class_name));
        self.line("{");
        self.indent += 1;
        self.line("var r = new CdrReader(data);");
        self.line(&format!("var packed = r.{}();", read_method));
        self.line(&format!("var obj = new {}();", class_name));
        bit_offset = 0;
        for f in &b.fields {
            let prop_name = cs_ident(&f.name);
            let mask = (1u64 << f.bit_width) - 1;
            let field_type = if f.bit_width <= 8 {
                "byte"
            } else if f.bit_width <= 16 {
                "ushort"
            } else {
                "uint"
            };
            self.line(&format!(
                "obj.{} = ({})(((ulong)packed >> {}) & 0x{:X});",
                prop_name, field_type, bit_offset, mask
            ));
            bit_offset += f.bit_width;
        }
        self.line("return obj;");
        self.indent -= 1;
        self.line("}");
        self.line("");

        self.line(&format!(
            "public static {} DeserializeCdr(byte[] data) => DeserializeCdr(data.AsSpan());",
            class_name
        ));
        self.line("");

        // DeserializeCdrInline
        self.line(&format!("internal static {} DeserializeCdrInline(CdrReader r)", class_name));
        self.line("{");
        self.indent += 1;
        self.line(&format!("var packed = r.{}();", read_method));
        self.line(&format!("var obj = new {}();", class_name));
        bit_offset = 0;
        for f in &b.fields {
            let prop_name = cs_ident(&f.name);
            let mask = (1u64 << f.bit_width) - 1;
            let field_type = if f.bit_width <= 8 {
                "byte"
            } else if f.bit_width <= 16 {
                "ushort"
            } else {
                "uint"
            };
            self.line(&format!(
                "obj.{} = ({})(((ulong)packed >> {}) & 0x{:X});",
                prop_name, field_type, bit_offset, mask
            ));
            bit_offset += f.bit_width;
        }
        self.line("return obj;");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // SerializeCdrInline - writes packed value directly using parent writer
        self.line("internal void SerializeCdrInline(CdrWriter w)");
        self.line("{");
        self.indent += 1;
        self.line(&format!("{} packed = 0;", storage_type));
        bit_offset = 0;
        for f in &b.fields {
            let prop_name = cs_ident(&f.name);
            let mask = (1u64 << f.bit_width) - 1;
            self.line(&format!(
                "packed |= ({})(((ulong){} & 0x{:X}) << {});",
                storage_type, prop_name, mask, bit_offset
            ));
            bit_offset += f.bit_width;
        }
        self.line(&format!("w.{}(packed);", write_method));
        self.indent -= 1;
        self.line("}");

        self.indent -= 1;
        self.line("}");
    }

    // ---- Union ----

    fn discriminant_type_to_csharp(&self, ty: &ResolvedType) -> &str {
        match ty {
            ResolvedType::Bool => "bool",
            ResolvedType::I16 => "short",
            ResolvedType::U16 => "ushort",
            ResolvedType::I32 => "int",
            ResolvedType::U32 => "uint",
            ResolvedType::I64 => "long",
            ResolvedType::U64 => "ulong",
            _ => "int",
        }
    }

    fn discriminant_read_method(&self, ty: &ResolvedType) -> &str {
        match ty {
            ResolvedType::Bool => "ReadBool",
            ResolvedType::I16 => "ReadI16",
            ResolvedType::U16 => "ReadU16",
            ResolvedType::I32 => "ReadI32",
            ResolvedType::U32 => "ReadU32",
            ResolvedType::I64 => "ReadI64",
            ResolvedType::U64 => "ReadU64",
            _ => "ReadI32",
        }
    }

    fn discriminant_write_method(&self, ty: &ResolvedType) -> &str {
        match ty {
            ResolvedType::Bool => "WriteBool",
            ResolvedType::I16 => "WriteI16",
            ResolvedType::U16 => "WriteU16",
            ResolvedType::I32 => "WriteI32",
            ResolvedType::U32 => "WriteU32",
            ResolvedType::I64 => "WriteI64",
            ResolvedType::U64 => "WriteU64",
            _ => "WriteI32",
        }
    }

    fn label_to_csharp(&self, label: &ResolvedUnionLabel, _disc_type: &ResolvedType) -> String {
        match label {
            ResolvedUnionLabel::Int(v) => format!("{}", v),
            ResolvedUnionLabel::Bool(v) => {
                if *v {
                    "true".to_string()
                } else {
                    "false".to_string()
                }
            }
            ResolvedUnionLabel::Ident(s) => {
                // Could be an enum variant
                naming::to_pascal_case(s)
            }
        }
    }

    fn emit_union(&mut self, u: &ResolvedUnion) {
        let class_name = naming::to_pascal_case(&u.name);
        let disc_cs_type = self.discriminant_type_to_csharp(&u.discriminant_type).to_string();
        let disc_read = self.discriminant_read_method(&u.discriminant_type).to_string();
        let disc_write = self.discriminant_write_method(&u.discriminant_type).to_string();

        self.line(&format!("public class {}", class_name));
        self.line("{");
        self.indent += 1;

        // Discriminator property
        self.line(&format!("public {} Discriminator {{ get; set; }}", disc_cs_type));

        // Properties for each case member
        for case in &u.cases {
            let prop_name = cs_ident(&case.member.name);
            let cs_type = Self::type_to_csharp(&case.member.resolved_type);
            if self.needs_initializer(&case.member.resolved_type) {
                let default = self.default_value(&case.member.resolved_type);
                self.line(&format!(
                    "public {} {} {{ get; set; }} = {};",
                    cs_type, prop_name, default
                ));
            } else {
                self.line(&format!("public {} {} {{ get; set; }}", cs_type, prop_name));
            }
        }
        if let Some(ref def) = u.default_case {
            let prop_name = cs_ident(&def.name);
            let cs_type = Self::type_to_csharp(&def.resolved_type);
            if self.needs_initializer(&def.resolved_type) {
                let default = self.default_value(&def.resolved_type);
                self.line(&format!(
                    "public {} {} {{ get; set; }} = {};",
                    cs_type, prop_name, default
                ));
            } else {
                self.line(&format!("public {} {} {{ get; set; }}", cs_type, prop_name));
            }
        }
        self.line("");

        self.line(&format!("public {}() {{ }}", class_name));
        self.line("");

        // SerializeCdr
        self.line("public byte[] SerializeCdr() => SerializeCdr(false);");
        self.line("");
        self.line("public byte[] SerializeCdr(bool xcdr2)");
        self.line("{");
        self.indent += 1;
        let union_ext = match u.extensibility {
            ExtensibilityKind::Final => "Final",
            ExtensibilityKind::Appendable => "Appendable",
            ExtensibilityKind::Mutable => "Mutable",
        };
        let needs_union_dh = !matches!(u.extensibility, ExtensibilityKind::Final);
        self.line(&format!("var w = new CdrWriter(Extensibility.{}, xcdr2: xcdr2);", union_ext));
        if needs_union_dh {
            self.line("var _udt = w.DheaderBegin();");
        }
        self.line(&format!("w.{}(Discriminator);", disc_write));
        self.line("switch (Discriminator)");
        self.line("{");
        self.indent += 1;
        for case in &u.cases {
            for label in &case.labels {
                let label_str = self.label_to_csharp(label, &u.discriminant_type);
                self.line(&format!("case {}:", label_str));
            }
            self.indent += 1;
            let accessor = cs_ident(&case.member.name);
            self.emit_write_field(&case.member.resolved_type, &accessor);
            self.line("break;");
            self.indent -= 1;
        }
        if let Some(ref def) = u.default_case {
            self.line("default:");
            self.indent += 1;
            let accessor = cs_ident(&def.name);
            self.emit_write_field(&def.resolved_type, &accessor);
            self.line("break;");
            self.indent -= 1;
        }
        self.indent -= 1;
        self.line("}");
        if needs_union_dh {
            self.line("w.DheaderFinalize(_udt);");
        }
        self.line("return w.ToBytes();");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // DeserializeCdrInline
        self.line(&format!("internal static {} DeserializeCdrInline(CdrReader r)", class_name));
        self.line("{");
        self.indent += 1;
        self.line(&format!("var obj = new {}();", class_name));
        if needs_union_dh {
            self.line("var (_uSz, _uSp) = r.ReadDheader();");
        }
        self.line(&format!("obj.Discriminator = r.{}();", disc_read));
        self.line("switch (obj.Discriminator)");
        self.line("{");
        self.indent += 1;
        for case in &u.cases {
            for label in &case.labels {
                let label_str = self.label_to_csharp(label, &u.discriminant_type);
                self.line(&format!("case {}:", label_str));
            }
            self.indent += 1;
            let prop_name = cs_ident(&case.member.name);
            self.emit_read_field(&case.member.resolved_type, &prop_name, "obj");
            self.line("break;");
            self.indent -= 1;
        }
        if let Some(ref def) = u.default_case {
            self.line("default:");
            self.indent += 1;
            let prop_name = cs_ident(&def.name);
            self.emit_read_field(&def.resolved_type, &prop_name, "obj");
            self.line("break;");
            self.indent -= 1;
        }
        self.indent -= 1;
        self.line("}");
        if needs_union_dh {
            self.line("r.ReadDheaderEnd(_uSz, _uSp);");
        }
        self.line("return obj;");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // SerializeCdrInline
        self.line("internal void SerializeCdrInline(CdrWriter w)");
        self.line("{");
        self.indent += 1;
        if needs_union_dh {
            self.line("var _udt = w.DheaderBegin();");
        }
        self.line(&format!("w.{}(Discriminator);", disc_write));
        self.line("switch (Discriminator)");
        self.line("{");
        self.indent += 1;
        for case in &u.cases {
            for label in &case.labels {
                let label_str = self.label_to_csharp(label, &u.discriminant_type);
                self.line(&format!("case {}:", label_str));
            }
            self.indent += 1;
            let accessor = cs_ident(&case.member.name);
            self.emit_write_field(&case.member.resolved_type, &accessor);
            self.line("break;");
            self.indent -= 1;
        }
        if let Some(ref def) = u.default_case {
            self.line("default:");
            self.indent += 1;
            let accessor = cs_ident(&def.name);
            self.emit_write_field(&def.resolved_type, &accessor);
            self.line("break;");
            self.indent -= 1;
        }
        self.indent -= 1;
        self.line("}");
        if needs_union_dh {
            self.line("w.DheaderFinalize(_udt);");
        }
        self.indent -= 1;
        self.line("}");

        self.indent -= 1;
        self.line("}");
    }

    // ---- Struct ----

    /// Collect all members including inherited ones (ancestors first).
    fn collect_all_members(&self, s: &ResolvedStruct) -> Vec<ResolvedMember> {
        let mut all = Vec::new();
        if let Some(ref base_name) = s.base_type {
            if let Some(base) = self.find_struct(base_name) {
                all.extend(self.collect_all_members(base));
            }
        }
        all.extend(s.members.clone());
        all
    }

    /// Emit `DdsTypeInfoFields` for advertisable structs (all members are primitives, strings,
    /// sequences/arrays of primitives, or nested structs that are themselves recursively
    /// advertisable). The runtime reads it to advertise a TypeObject.
    fn emit_type_info_metadata(&mut self, members: &[ResolvedMember]) {
        let mut visited = std::collections::HashSet::new();
        if !members.iter().all(|m| self.member_advertisable(m, &mut visited)) {
            return;
        }
        self.line(
            "public static readonly DdsTypeInfoField[] DdsTypeInfoFields = new DdsTypeInfoField[]",
        );
        self.line("{");
        self.indent += 1;
        for (i, m) in members.iter().enumerate() {
            self.line(&Self::type_info_field_spec(m, i as u32));
        }
        self.indent -= 1;
        self.line("};");
        self.line("");
    }

    /// FFI INT2DDS_FIELD_* constant for a scalar/string/char type; None for composite types.
    fn field_constant(ty: &ResolvedType) -> Option<i32> {
        Some(match ty {
            ResolvedType::Bool => 0,
            ResolvedType::U8 => 1,   // BYTE (octet)
            ResolvedType::Char => 2, // CHAR8
            ResolvedType::I8 => 3,
            ResolvedType::I16 => 4,
            ResolvedType::I32 => 5,
            ResolvedType::I64 => 6,
            ResolvedType::UInt8 => 7, // UINT8
            ResolvedType::U16 => 8,
            ResolvedType::U32 => 9,
            ResolvedType::U64 => 10,
            ResolvedType::F32 => 11,
            ResolvedType::F64 => 12,
            ResolvedType::String { .. } => 13,
            ResolvedType::WChar => 14, // CHAR16
            ResolvedType::WString { .. } => 15,
            _ => return None,
        })
    }

    /// A member is advertisable byte-correctly when its type is a primitive/string, an enum, a
    /// (non-@external) nested struct that is itself recursively advertisable, or a sequence/array
    /// whose element is one of those (single-level). Bitmask, map, union, and nested collections
    /// are excluded (they fall back to the name-based keyed path).
    fn member_advertisable(
        &self,
        m: &ResolvedMember,
        visited: &mut std::collections::HashSet<String>,
    ) -> bool {
        if m.is_external && matches!(m.resolved_type, ResolvedType::Struct(_)) {
            return false;
        }
        self.type_advertisable(&m.resolved_type, visited)
    }

    /// Recursively decide advertisability of a member/element type.
    fn type_advertisable(
        &self,
        ty: &ResolvedType,
        visited: &mut std::collections::HashSet<String>,
    ) -> bool {
        match ty {
            ResolvedType::Struct(name) => self.struct_advertisable(name, visited),
            ResolvedType::Enum(_) => true,
            ResolvedType::Sequence { element, .. } => match element.as_ref() {
                ResolvedType::Struct(name) => self.struct_advertisable(name, visited),
                ResolvedType::Enum(_) => true,
                other => Self::field_constant(other).is_some(),
            },
            ResolvedType::Array { .. } => {
                // Dimensions flatten into one plain-array id, so only the base element
                // decides; a sequence/map base still has no builder spelling.
                let (_, base) = flatten_array(ty);
                match base {
                    ResolvedType::Struct(name) => self.struct_advertisable(name, visited),
                    ResolvedType::Enum(_) => true,
                    other => Self::field_constant(other).is_some(),
                }
            }
            other => Self::field_constant(other).is_some(),
        }
    }

    /// The generated CLR class name (PascalCase) for an advertisable named element
    /// (Struct/Enum), else None. Used to gate collection elements and emit nested refs.
    fn element_class_name(ty: &ResolvedType) -> Option<String> {
        match ty {
            ResolvedType::Struct(name) | ResolvedType::Enum(name) => {
                let simple = name.rsplit("::").next().unwrap_or(name);
                Some(naming::to_pascal_case(simple))
            }
            _ => None,
        }
    }

    /// A named struct is advertisable when it exists in the model and all of its members are
    /// recursively advertisable. `visited` guards against @external-induced type cycles.
    fn struct_advertisable(
        &self,
        name: &str,
        visited: &mut std::collections::HashSet<String>,
    ) -> bool {
        let simple = name.rsplit("::").next().unwrap_or(name);
        if !visited.insert(simple.to_string()) {
            return false;
        }
        let ok = match self.find_struct(simple).cloned() {
            Some(s) => {
                self.collect_all_members(&s).iter().all(|m| self.member_advertisable(m, visited))
            }
            None => false,
        };
        visited.remove(simple);
        ok
    }

    /// Member flag bitmask (KEY=1, OPTIONAL=2, MUST_UNDERSTAND=4, EXTERNAL=8). The FFI adds
    /// must-understand for @key automatically, so KEY alone is sufficient for keys.
    fn member_flags(m: &ResolvedMember) -> i32 {
        let mut f = 0;
        if m.is_key {
            f |= 1;
        }
        if m.is_optional {
            f |= 2;
        }
        if m.must_understand {
            f |= 4;
        }
        if m.is_external {
            f |= 8;
        }
        f
    }

    /// One `new DdsTypeInfoField(op, name, type_const, size, flags)` initializer for a member.
    /// Explicit `@id`/`@hashid` ids ride as a named trailing `memberId:` argument.
    fn type_info_field_spec(m: &ResolvedMember, index: u32) -> String {
        let flags = Self::member_flags(m);
        let id_arg = match m.member_id {
            Some(id) if id != index => format!(", memberId: {}", id),
            _ => String::new(),
        };
        match &m.resolved_type {
            ResolvedType::String { bound } => format!(
                "new DdsTypeInfoField(\"string\", \"{}\", 0, {}u, {}{}),",
                m.name,
                bound.unwrap_or(0),
                flags,
                id_arg
            ),
            ResolvedType::WString { bound } => format!(
                "new DdsTypeInfoField(\"wstring\", \"{}\", 0, {}u, {}{}),",
                m.name,
                bound.unwrap_or(0),
                flags,
                id_arg
            ),
            ResolvedType::Sequence { element, bound } => {
                if let Some(cls) = Self::element_class_name(element) {
                    format!(
                        "new DdsTypeInfoField(\"seq_nested\", \"{}\", typeof({}), {}u, {}{}),",
                        m.name,
                        cls,
                        bound.unwrap_or(0),
                        flags,
                        id_arg
                    )
                } else {
                    let ec = Self::field_constant(element).unwrap_or(0);
                    format!(
                        "new DdsTypeInfoField(\"seq\", \"{}\", {}, {}u, {}{}),",
                        m.name,
                        ec,
                        bound.unwrap_or(0),
                        flags,
                        id_arg
                    )
                }
            }
            ResolvedType::Array { .. } => {
                let (dims, base) = flatten_array(&m.resolved_type);
                if dims.len() > 1 {
                    let dims_lit =
                        dims.iter().map(|d| format!("{}u", d)).collect::<Vec<_>>().join(", ");
                    if let Some(cls) = Self::element_class_name(base) {
                        format!(
                            "new DdsTypeInfoField(\"arr_nested_nd\", \"{}\", typeof({}), new uint[] {{ {} }}, {}{}),",
                            m.name, cls, dims_lit, flags, id_arg
                        )
                    } else {
                        let ec = Self::field_constant(base).unwrap_or(0);
                        format!(
                            "new DdsTypeInfoField(\"arr_nd\", \"{}\", {}, new uint[] {{ {} }}, {}{}),",
                            m.name, ec, dims_lit, flags, id_arg
                        )
                    }
                } else if let Some(cls) = Self::element_class_name(base) {
                    format!(
                        "new DdsTypeInfoField(\"arr_nested\", \"{}\", typeof({}), {}u, {}{}),",
                        m.name, cls, dims[0], flags, id_arg
                    )
                } else {
                    let ec = Self::field_constant(base).unwrap_or(0);
                    format!(
                        "new DdsTypeInfoField(\"arr\", \"{}\", {}, {}u, {}{}),",
                        m.name, ec, dims[0], flags, id_arg
                    )
                }
            }
            ResolvedType::Struct(name) | ResolvedType::Enum(name) => {
                // Mirror the field-type rendering (type_to_csharp) so typeof(...) names the
                // exact generated class (struct or enum) that declares this member.
                let cls = cs_type_ref(name);
                format!(
                    "new DdsTypeInfoField(\"nested\", \"{}\", typeof({}), {}{}),",
                    m.name, cls, flags, id_arg
                )
            }
            other => {
                let c = Self::field_constant(other).unwrap_or(0);
                format!(
                    "new DdsTypeInfoField(\"field\", \"{}\", {}, 0u, {}{}),",
                    m.name, c, flags, id_arg
                )
            }
        }
    }

    fn emit_struct(&mut self, s: &ResolvedStruct) {
        let class_name = naming::to_pascal_case(&s.name);
        let ext_name = match s.extensibility {
            ExtensibilityKind::Final => "Final",
            ExtensibilityKind::Appendable => "Appendable",
            ExtensibilityKind::Mutable => "Mutable",
        };

        let all_members = self.collect_all_members(s);
        let has_key = all_members.iter().any(|m| m.is_key);

        let ext_int = match s.extensibility {
            ExtensibilityKind::Final => 0,
            ExtensibilityKind::Appendable => 1,
            ExtensibilityKind::Mutable => 2,
        };

        // DdsType attribute for runtime reflection (Topic creation uses this)
        self.line(&format!(
            "[DdsType(\"{}\", {}, {})]",
            s.qualified_name,
            ext_int,
            if has_key { "true" } else { "false" }
        ));

        // Class declaration
        self.line(&format!("public class {} : IDdsType", class_name));
        self.line("{");
        self.indent += 1;

        // Static metadata
        self.line(&format!("public static string DdsTypeName => \"{}\";", s.qualified_name));
        self.line(&format!(
            "public static Extensibility TypeExtensibility => Extensibility.{};",
            ext_name
        ));
        self.line(&format!(
            "public static bool HasKey => {};",
            if has_key { "true" } else { "false" }
        ));
        self.line("");

        // XTypes TypeObject advertisement metadata (flat types only). The runtime reflects
        // this and advertises a conformant TypeObject during discovery (matching the Rust
        // derive). Nested/named types are omitted and fall back to name-based matching.
        self.emit_type_info_metadata(&all_members);

        // Properties (all members including inherited)
        for m in &all_members {
            let prop_name = cs_ident(&m.name);
            let cs_type = Self::type_to_csharp(&m.resolved_type);
            if m.is_optional {
                // Optional members are nullable; null means absent on the wire.
                self.line(&format!("public {}? {} {{ get; set; }}", cs_type, prop_name));
            } else if self.needs_initializer(&m.resolved_type) {
                let default = self.default_value(&m.resolved_type);
                self.line(&format!(
                    "public {} {} {{ get; set; }} = {};",
                    cs_type, prop_name, default
                ));
            } else {
                self.line(&format!("public {} {} {{ get; set; }}", cs_type, prop_name));
            }
        }
        self.line("");

        // Default constructor
        self.line(&format!("public {}() {{ }}", class_name));
        self.line("");

        // Build a temporary struct with all_members for serialization
        let full_struct = ResolvedStruct {
            name: s.name.clone(),
            qualified_name: s.qualified_name.clone(),
            extensibility: s.extensibility,
            autoid: s.autoid,
            base_type: None,
            members: all_members.clone(),
        };

        // SerializeCdr method
        self.emit_serialize_cdr(&full_struct);
        self.line("");

        // DeserializeCdr static method
        self.emit_deserialize_cdr(&full_struct);
        self.line("");

        // DeserializeCdrInline internal static method
        self.emit_deserialize_cdr_inline(&full_struct);
        self.line("");

        // SerializeCdrInline internal method
        self.emit_serialize_cdr_inline(&full_struct);
        self.line("");

        self.indent -= 1;
        self.line("}");
    }

    /// IDL constants are grouped into a `static class Constants` (C# consts need a type).
    fn emit_constants(&mut self) {
        if self.model.constants.is_empty() {
            return;
        }
        self.line("public static class Constants");
        self.line("{");
        self.indent += 1;
        for c in &self.model.constants.clone() {
            let name = naming::escape_keyword(&c.name, naming::TargetLang::CSharp);
            let ty = Self::type_to_csharp(&c.resolved_type);
            let val = cs_const_value(&c.value, &c.resolved_type);
            self.line(&format!("public const {} {} = {};", ty, name, val));
        }
        self.indent -= 1;
        self.line("}");
        self.line("");
    }

    fn type_to_csharp(ty: &ResolvedType) -> String {
        match ty {
            ResolvedType::Bool => "bool".to_string(),
            ResolvedType::U8 | ResolvedType::UInt8 => "byte".to_string(),
            ResolvedType::I8 => "sbyte".to_string(),
            ResolvedType::I16 => "short".to_string(),
            ResolvedType::U16 => "ushort".to_string(),
            ResolvedType::I32 => "int".to_string(),
            ResolvedType::U32 => "uint".to_string(),
            ResolvedType::I64 => "long".to_string(),
            ResolvedType::U64 => "ulong".to_string(),
            ResolvedType::F32 => "float".to_string(),
            ResolvedType::F64 => "double".to_string(),
            ResolvedType::Char => "char".to_string(),
            ResolvedType::WChar => "char".to_string(),
            ResolvedType::String { .. } => "string".to_string(),
            ResolvedType::WString { .. } => "string".to_string(),
            ResolvedType::Sequence { element, .. } => {
                format!("List<{}>", Self::type_to_csharp(element))
            }
            ResolvedType::Array { element, .. } => {
                format!("{}[]", Self::type_to_csharp(element))
            }
            ResolvedType::Map { key, value, .. } => {
                format!(
                    "Dictionary<{}, {}>",
                    Self::type_to_csharp(key),
                    Self::type_to_csharp(value)
                )
            }
            ResolvedType::Struct(name) => cs_type_ref(name),
            ResolvedType::Enum(name) => cs_type_ref(name),
            ResolvedType::Bitmask(name) => cs_type_ref(name),
        }
    }

    /// Types whose C# mapping is a value type, so an optional member is `T?`
    /// and serialization must go through `.Value`.
    fn cs_is_value_type(ty: &ResolvedType) -> bool {
        matches!(
            ty,
            ResolvedType::Bool
                | ResolvedType::U8
                | ResolvedType::UInt8
                | ResolvedType::I8
                | ResolvedType::I16
                | ResolvedType::U16
                | ResolvedType::I32
                | ResolvedType::U32
                | ResolvedType::I64
                | ResolvedType::U64
                | ResolvedType::F32
                | ResolvedType::F64
                | ResolvedType::Char
                | ResolvedType::WChar
                | ResolvedType::Enum(_)
                | ResolvedType::Bitmask(_)
        )
    }

    fn needs_initializer(&self, ty: &ResolvedType) -> bool {
        matches!(
            ty,
            ResolvedType::String { .. }
                | ResolvedType::WString { .. }
                | ResolvedType::Sequence { .. }
                | ResolvedType::Array { .. }
                | ResolvedType::Map { .. }
                | ResolvedType::Struct(_)
        )
    }

    /// Per DDS-XTypes 7.4.3.5.4, sequences/arrays of non-primitive elements are
    /// preceded by a DHEADER carrying the byte size of the payload. Matches
    /// Rust `XcdrSerialize for Vec<T>` where T::IS_PRIMITIVE == false. Enum and
    /// bitmask are constructed types, so they are non-primitive here; OMG issue
    /// DDSXTY14-56 proposes exempting them but is unresolved.
    fn is_non_primitive_element(element: &ResolvedType) -> bool {
        match element {
            ResolvedType::String { .. }
            | ResolvedType::WString { .. }
            | ResolvedType::Struct(_)
            | ResolvedType::Enum(_)
            | ResolvedType::Bitmask(_)
            | ResolvedType::Sequence { .. }
            | ResolvedType::Array { .. }
            | ResolvedType::Map { .. } => true,
            _ => false,
        }
    }

    /// Whether an array frames itself. A multidimensional IDL array parses to nested
    /// `Array` but XTypes treats it as one array of the base type (7.4.3.4), so look
    /// through the dimensions.
    fn array_needs_dheader(element: &ResolvedType) -> bool {
        match element {
            ResolvedType::Array { element, .. } => Self::array_needs_dheader(element),
            other => Self::is_non_primitive_element(other),
        }
    }

    /// Allocate one rank of a jagged array: `long a[2][3]` maps to `int[][]`, whose
    /// outer rank is `new int[2][]` and whose rows are `new int[3]`. Only the rank
    /// being allocated carries a length; the ranks below it are empty brackets.
    fn jagged_alloc(base: &ResolvedType, dims: &[u32], depth: usize) -> String {
        format!(
            "new {}[{}]{}",
            Self::type_to_csharp(base),
            dims[depth],
            "[]".repeat(dims.len() - depth - 1)
        )
    }

    fn default_value(&self, ty: &ResolvedType) -> String {
        match ty {
            ResolvedType::Bool => "false".to_string(),
            ResolvedType::U8 | ResolvedType::UInt8 | ResolvedType::I8 => "0".to_string(),
            ResolvedType::I16 | ResolvedType::U16 => "0".to_string(),
            ResolvedType::I32 | ResolvedType::U32 => "0".to_string(),
            ResolvedType::I64 | ResolvedType::U64 => "0".to_string(),
            ResolvedType::F32 => "0.0f".to_string(),
            ResolvedType::F64 => "0.0".to_string(),
            ResolvedType::Char => "'\\0'".to_string(),
            ResolvedType::WChar => "'\\0'".to_string(),
            ResolvedType::String { .. } => "\"\"".to_string(),
            ResolvedType::WString { .. } => "\"\"".to_string(),
            ResolvedType::Sequence { element, .. } => {
                format!("new List<{}>()", Self::type_to_csharp(element))
            }
            ResolvedType::Array { .. } => {
                let (dims, base) = flatten_array(ty);
                Self::jagged_alloc(base, &dims, 0)
            }
            ResolvedType::Map { key, value, .. } => {
                format!(
                    "new Dictionary<{}, {}>()",
                    Self::type_to_csharp(key),
                    Self::type_to_csharp(value)
                )
            }
            ResolvedType::Struct(name) => {
                format!("new {}()", cs_type_ref(name))
            }
            ResolvedType::Enum(name) => {
                // Use 0 cast to enum type
                let cs_name = cs_type_ref(name);
                if let Some(e) = self.find_enum(name) {
                    if let Some(v) = e.variants.first() {
                        return format!("{}.{}", cs_name, cs_ident(&v.name));
                    }
                }
                format!("({})0", cs_name)
            }
            ResolvedType::Bitmask(name) => {
                format!("({})0", cs_type_ref(name))
            }
        }
    }

    // ---- Serialization ----

    fn emit_serialize_cdr(&mut self, s: &ResolvedStruct) {
        // SerializeCdr() - default uses XCDR1 (spec effective write default)
        self.line("public byte[] SerializeCdr() => SerializeCdr(false);");
        self.line("");

        // SerializeCdr(bool xcdr2) - actual implementation
        self.line("public byte[] SerializeCdr(bool xcdr2)");
        self.line("{");
        self.indent += 1;
        self.line("var w = new CdrWriter(TypeExtensibility, xcdr2: xcdr2);");

        match s.extensibility {
            ExtensibilityKind::Final => {
                self.emit_write_members_cs(&s.members);
            }
            ExtensibilityKind::Appendable => {
                self.line("var _dt = w.DheaderBegin();");
                self.emit_write_members_cs(&s.members);
                self.line("w.DheaderFinalize(_dt);");
            }
            ExtensibilityKind::Mutable => {
                // XCDR2: DHEADER + EMHEADER per field. XCDR1: PL_CDR headers + sentinel.
                self.line("if (w.IsXcdr2)");
                self.line("{");
                self.indent += 1;
                self.emit_mutable_ser_xcdr2_cs(&s.members);
                self.indent -= 1;
                self.line("}");
                self.line("else");
                self.line("{");
                self.indent += 1;
                self.emit_mutable_ser_xcdr1_cs(&s.members);
                self.indent -= 1;
                self.line("}");
            }
        }

        self.line("return w.ToBytes();");
        self.indent -= 1;
        self.line("}");
    }

    /// Final/Appendable member list; optional members get presence handling.
    fn emit_write_members_cs(&mut self, members: &[ResolvedMember]) {
        for (i, m) in members.iter().enumerate() {
            let prop = cs_ident(&m.name);
            if m.is_optional {
                self.emit_write_optional_cs(m, i as u32, &prop);
            } else {
                self.emit_write_field(&m.resolved_type, &prop);
            }
        }
    }

    /// Optional member in a Final/Appendable struct: XCDR2 writes a presence
    /// boolean, XCDR1 always writes a PL_CDR parameter header (length 0 = absent),
    /// matching the Rust derive writer.
    fn emit_write_optional_cs(&mut self, m: &ResolvedMember, index: u32, prop: &str) {
        let id = m.member_id.unwrap_or(index);
        let mu = if m.must_understand { "true" } else { "false" };
        let accessor = if Self::cs_is_value_type(&m.resolved_type) {
            format!("{}.Value", prop)
        } else {
            prop.to_string()
        };
        self.line("{");
        self.indent += 1;
        self.line("int _ot = -1;");
        self.line(&format!("if (w.IsXcdr2) {{ w.WriteBool({} != null); }}", prop));
        self.line(&format!("else {{ _ot = w.MemberV1Begin({}); }}", id));
        self.line(&format!("if ({} != null)", prop));
        self.line("{");
        self.indent += 1;
        self.emit_write_field(&m.resolved_type, &accessor);
        self.indent -= 1;
        self.line("}");
        self.line(&format!("if (!w.IsXcdr2) {{ w.MemberV1Finalize(_ot, {}, {}); }}", id, mu));
        self.indent -= 1;
        self.line("}");
    }

    fn emit_read_members_cs(&mut self, members: &[ResolvedMember]) {
        for m in members {
            let prop_name = cs_ident(&m.name);
            if m.is_optional {
                self.emit_read_optional_cs(m, &prop_name);
            } else {
                self.emit_read_field(&m.resolved_type, &prop_name, "obj");
            }
        }
    }

    /// Read counterpart: XCDR2 presence boolean, XCDR1 parameter header whose
    /// length decides presence (the pid itself is ignored, like the Rust readers).
    fn emit_read_optional_cs(&mut self, m: &ResolvedMember, prop: &str) {
        self.line("{");
        self.indent += 1;
        self.line("bool _has;");
        self.line("if (r.IsXcdr2) { _has = r.ReadBool(); }");
        self.line(
            "else { var (_, _olen, _, _osen) = r.ReadParameterHeader(); _has = !_osen && _olen != 0; }",
        );
        self.line("if (_has)");
        self.line("{");
        self.indent += 1;
        self.emit_read_field(&m.resolved_type, prop, "obj");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
    }

    fn emit_write_field(&mut self, ty: &ResolvedType, accessor: &str) {
        match ty {
            ResolvedType::Bool => self.line(&format!("w.WriteBool({});", accessor)),
            ResolvedType::U8 | ResolvedType::UInt8 => {
                self.line(&format!("w.WriteU8({});", accessor))
            }
            ResolvedType::I8 => self.line(&format!("w.WriteI8({});", accessor)),
            ResolvedType::I16 => self.line(&format!("w.WriteI16({});", accessor)),
            ResolvedType::U16 => self.line(&format!("w.WriteU16({});", accessor)),
            ResolvedType::I32 => self.line(&format!("w.WriteI32({});", accessor)),
            ResolvedType::U32 => self.line(&format!("w.WriteU32({});", accessor)),
            ResolvedType::I64 => self.line(&format!("w.WriteI64({});", accessor)),
            ResolvedType::U64 => self.line(&format!("w.WriteU64({});", accessor)),
            ResolvedType::F32 => self.line(&format!("w.WriteF32({});", accessor)),
            ResolvedType::F64 => self.line(&format!("w.WriteF64({});", accessor)),
            ResolvedType::Char => {
                self.line(&format!("w.WriteU8((byte){});", accessor));
            }
            ResolvedType::WChar => {
                self.line(&format!("w.WriteU16((ushort){});", accessor));
            }
            ResolvedType::String { .. } => {
                self.line(&format!("w.WriteString({});", accessor));
            }
            ResolvedType::WString { .. } => {
                self.line(&format!("w.WriteWString({});", accessor));
            }
            ResolvedType::Enum(_) => {
                self.line(&format!("w.WriteEnum((int){});", accessor));
            }
            ResolvedType::Bitmask(bitmask_name) => {
                let bit_bound = self.find_bitmask(bitmask_name).map(|b| b.bit_bound).unwrap_or(32);
                let (cs_type, write_method, _, _) = Self::bitmask_backing_info(bit_bound);
                self.line(&format!("w.{}(({}){}); ", write_method, cs_type, accessor));
            }
            ResolvedType::Struct(_) => {
                self.line(&format!("{}.SerializeCdrInline(w);", accessor));
            }
            ResolvedType::Sequence { element, .. } => {
                let non_prim = Self::is_non_primitive_element(element);
                if non_prim {
                    self.line("{");
                    self.indent += 1;
                    self.line("var _seqDt = w.DheaderBegin();");
                }
                self.line(&format!("w.WriteSeqHeader((uint){}.Count);", accessor));
                self.line(&format!("foreach (var _item in {})", accessor));
                self.line("{");
                self.indent += 1;
                self.emit_write_field(element, "_item");
                self.indent -= 1;
                self.line("}");
                if non_prim {
                    self.line("w.DheaderFinalize(_seqDt);");
                    self.indent -= 1;
                    self.line("}");
                }
            }
            ResolvedType::Array { .. } => {
                // One array of the base type (7.4.3.4): frame once above every dimension.
                // Recursing per dimension would nest DHEADERs and redeclare `_item`, which
                // C# rejects outright (CS0136).
                let (dims, base) = flatten_array(ty);
                let non_prim = Self::array_needs_dheader(base);
                if non_prim {
                    self.line("{");
                    self.indent += 1;
                    self.line("var _arrDt = w.DheaderBegin();");
                }
                let mut acc = accessor.to_string();
                for d in 0..dims.len() {
                    self.line(&format!("foreach (var _item{} in {})", d, acc));
                    self.line("{");
                    self.indent += 1;
                    acc = format!("_item{}", d);
                }
                self.emit_write_field(base, &acc);
                for _ in 0..dims.len() {
                    self.indent -= 1;
                    self.line("}");
                }
                if non_prim {
                    self.line("w.DheaderFinalize(_arrDt);");
                    self.indent -= 1;
                    self.line("}");
                }
            }
            ResolvedType::Map { key, value, .. } => {
                let non_prim =
                    Self::is_non_primitive_element(key) || Self::is_non_primitive_element(value);
                if non_prim {
                    self.line("{");
                    self.indent += 1;
                    self.line("var _mapDt = w.DheaderBegin();");
                }
                self.line(&format!("w.WriteSeqHeader((uint){}.Count);", accessor));
                self.line(&format!("foreach (var _entry in {})", accessor));
                self.line("{");
                self.indent += 1;
                self.emit_write_field(key, "_entry.Key");
                self.emit_write_field(value, "_entry.Value");
                self.indent -= 1;
                self.line("}");
                if non_prim {
                    self.line("w.DheaderFinalize(_mapDt);");
                    self.indent -= 1;
                    self.line("}");
                }
            }
        }
    }

    /// XCDR2 mutable serialize body: DHEADER + EMHEADER per field (no sentinel).
    fn emit_mutable_ser_xcdr2_cs(&mut self, members: &[ResolvedMember]) {
        self.line("var _dt = w.DheaderBegin();");
        for (i, m) in members.iter().enumerate() {
            let member_id = m.member_id.unwrap_or(i as u32);
            let must_understand = if m.must_understand { "true" } else { "false" };
            let prop = cs_ident(&m.name);
            let accessor = if m.is_optional && Self::cs_is_value_type(&m.resolved_type) {
                format!("{}.Value", prop)
            } else {
                prop.clone()
            };
            // Absent optional members are omitted entirely (no EMHEADER).
            if m.is_optional {
                self.line(&format!("if ({} != null)", prop));
                self.line("{");
                self.indent += 1;
            }
            self.line(&format!(
                "var _et{} = w.EmheaderBegin({}, {});",
                i, member_id, must_understand
            ));
            self.emit_write_field(&m.resolved_type, &accessor);
            self.line(&format!("w.EmheaderFinalize(_et{});", i));
            if m.is_optional {
                self.indent -= 1;
                self.line("}");
            }
        }
        self.line("w.DheaderFinalize(_dt);");
    }

    /// XCDR1 mutable serialize body: PL_CDR member headers terminated by a sentinel.
    fn emit_mutable_ser_xcdr1_cs(&mut self, members: &[ResolvedMember]) {
        for (i, m) in members.iter().enumerate() {
            let member_id = m.member_id.unwrap_or(i as u32);
            let must_understand = if m.must_understand { "true" } else { "false" };
            let prop = cs_ident(&m.name);
            let accessor = if m.is_optional && Self::cs_is_value_type(&m.resolved_type) {
                format!("{}.Value", prop)
            } else {
                prop.clone()
            };
            // Absent optional members are omitted entirely (no member header).
            if m.is_optional {
                self.line(&format!("if ({} != null)", prop));
                self.line("{");
                self.indent += 1;
            }
            self.line(&format!("var _mt{} = w.MemberV1Begin({});", i, member_id));
            self.emit_write_field(&m.resolved_type, &accessor);
            self.line(&format!(
                "w.MemberV1Finalize(_mt{}, {}, {});",
                i, member_id, must_understand
            ));
            if m.is_optional {
                self.indent -= 1;
                self.line("}");
            }
        }
        self.line("w.EndMutableStruct();");
    }

    /// The `if (_mid == N) { <read> } ... else { r.Skip((int)_mlen); }` dispatch shared by
    /// the XCDR2 (EMHEADER) and XCDR1 (PL_CDR) mutable deserialize loops.
    fn emit_mutable_deser_dispatch_cs(&mut self, members: &[ResolvedMember]) {
        let mut first = true;
        for (i, m) in members.iter().enumerate() {
            let member_id = m.member_id.unwrap_or(i as u32);
            let prop_name = cs_ident(&m.name);
            if first {
                self.line(&format!("if (_mid == {})", member_id));
                first = false;
            } else {
                self.line(&format!("else if (_mid == {})", member_id));
            }
            self.line("{");
            self.indent += 1;
            self.emit_read_field(&m.resolved_type, &prop_name, "obj");
            self.indent -= 1;
            self.line("}");
        }
        self.line("else");
        self.line("{");
        self.indent += 1;
        self.line("r.Skip((int)_mlen);");
        self.indent -= 1;
        self.line("}");
    }

    fn emit_deserialize_cdr(&mut self, s: &ResolvedStruct) {
        let class_name = naming::to_pascal_case(&s.name);

        self.line(&format!("public static {} DeserializeCdr(ReadOnlySpan<byte> data)", class_name));
        self.line("{");
        self.indent += 1;
        self.line("var r = new CdrReader(data);");
        self.line(&format!("var obj = new {}();", class_name));

        match s.extensibility {
            ExtensibilityKind::Final => {
                self.emit_read_members_cs(&s.members);
            }
            ExtensibilityKind::Appendable => {
                self.line("var (_dSize, _dStart) = r.ReadDheader();");
                self.emit_read_members_cs(&s.members);
                self.line("r.ReadDheaderEnd(_dSize, _dStart);");
            }
            ExtensibilityKind::Mutable => {
                // XCDR2: DHEADER-bounded EMHEADER loop. XCDR1: PL_CDR headers until sentinel.
                self.line("if (r.IsXcdr2)");
                self.line("{");
                self.indent += 1;
                self.line("var (_dSize, _dStart) = r.ReadDheader();");
                self.line("int _dEnd = _dStart + (int)_dSize;");
                self.line("while (r.Position < _dEnd)");
                self.line("{");
                self.indent += 1;
                self.line("var (_mid, _mlen, _mu) = r.ReadEmheader();");
                self.emit_mutable_deser_dispatch_cs(&s.members);
                self.indent -= 1;
                self.line("}");
                self.line("r.ReadDheaderEnd(_dSize, _dStart);");
                self.indent -= 1;
                self.line("}");
                self.line("else");
                self.line("{");
                self.indent += 1;
                self.line("while (true)");
                self.line("{");
                self.indent += 1;
                self.line("var (_mid, _mlen, _mu, _sentinel) = r.ReadParameterHeader();");
                self.line("if (_sentinel) break;");
                self.emit_mutable_deser_dispatch_cs(&s.members);
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
        }

        self.line("return obj;");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // byte[] overload for P/Invoke compatibility (DataReader uses reflection to find this signature)
        self.line(&format!(
            "public static {} DeserializeCdr(byte[] data) => DeserializeCdr(data.AsSpan());",
            class_name
        ));
    }

    fn emit_deserialize_cdr_inline(&mut self, s: &ResolvedStruct) {
        let class_name = naming::to_pascal_case(&s.name);

        self.line(&format!("internal static {} DeserializeCdrInline(CdrReader r)", class_name));
        self.line("{");
        self.indent += 1;
        self.line(&format!("var obj = new {}();", class_name));

        match s.extensibility {
            ExtensibilityKind::Final => {
                self.emit_read_members_cs(&s.members);
            }
            ExtensibilityKind::Appendable => {
                self.line("var (_dSize, _dStart) = r.ReadDheader();");
                self.emit_read_members_cs(&s.members);
                self.line("r.ReadDheaderEnd(_dSize, _dStart);");
            }
            ExtensibilityKind::Mutable => {
                // XCDR2: DHEADER-bounded EMHEADER loop. XCDR1: PL_CDR headers until sentinel.
                self.line("if (r.IsXcdr2)");
                self.line("{");
                self.indent += 1;
                self.line("var (_dSize, _dStart) = r.ReadDheader();");
                self.line("int _dEnd = _dStart + (int)_dSize;");
                self.line("while (r.Position < _dEnd)");
                self.line("{");
                self.indent += 1;
                self.line("var (_mid, _mlen, _mu) = r.ReadEmheader();");
                self.emit_mutable_deser_dispatch_cs(&s.members);
                self.indent -= 1;
                self.line("}");
                self.line("r.ReadDheaderEnd(_dSize, _dStart);");
                self.indent -= 1;
                self.line("}");
                self.line("else");
                self.line("{");
                self.indent += 1;
                self.line("while (true)");
                self.line("{");
                self.indent += 1;
                self.line("var (_mid, _mlen, _mu, _sentinel) = r.ReadParameterHeader();");
                self.line("if (_sentinel) break;");
                self.emit_mutable_deser_dispatch_cs(&s.members);
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
        }

        self.line("return obj;");
        self.indent -= 1;
        self.line("}");
    }

    fn emit_serialize_cdr_inline(&mut self, s: &ResolvedStruct) {
        self.line("internal void SerializeCdrInline(CdrWriter w)");
        self.line("{");
        self.indent += 1;

        match s.extensibility {
            ExtensibilityKind::Final => {
                self.emit_write_members_cs(&s.members);
            }
            ExtensibilityKind::Appendable => {
                self.line("var _dt = w.DheaderBegin();");
                self.emit_write_members_cs(&s.members);
                self.line("w.DheaderFinalize(_dt);");
            }
            ExtensibilityKind::Mutable => {
                self.line("if (w.IsXcdr2)");
                self.line("{");
                self.indent += 1;
                self.emit_mutable_ser_xcdr2_cs(&s.members);
                self.indent -= 1;
                self.line("}");
                self.line("else");
                self.line("{");
                self.indent += 1;
                self.emit_mutable_ser_xcdr1_cs(&s.members);
                self.indent -= 1;
                self.line("}");
            }
        }

        self.indent -= 1;
        self.line("}");
    }

    fn emit_read_field(&mut self, ty: &ResolvedType, name: &str, obj: &str) {
        match ty {
            ResolvedType::Bool => {
                self.line(&format!("{}.{} = r.ReadBool();", obj, name));
            }
            ResolvedType::U8 | ResolvedType::UInt8 => {
                self.line(&format!("{}.{} = r.ReadU8();", obj, name));
            }
            ResolvedType::I8 => {
                self.line(&format!("{}.{} = r.ReadI8();", obj, name));
            }
            ResolvedType::I16 => {
                self.line(&format!("{}.{} = r.ReadI16();", obj, name));
            }
            ResolvedType::U16 => {
                self.line(&format!("{}.{} = r.ReadU16();", obj, name));
            }
            ResolvedType::I32 => {
                self.line(&format!("{}.{} = r.ReadI32();", obj, name));
            }
            ResolvedType::U32 => {
                self.line(&format!("{}.{} = r.ReadU32();", obj, name));
            }
            ResolvedType::I64 => {
                self.line(&format!("{}.{} = r.ReadI64();", obj, name));
            }
            ResolvedType::U64 => {
                self.line(&format!("{}.{} = r.ReadU64();", obj, name));
            }
            ResolvedType::F32 => {
                self.line(&format!("{}.{} = r.ReadF32();", obj, name));
            }
            ResolvedType::F64 => {
                self.line(&format!("{}.{} = r.ReadF64();", obj, name));
            }
            ResolvedType::Char => {
                self.line(&format!("{}.{} = (char)r.ReadU8();", obj, name));
            }
            ResolvedType::WChar => {
                self.line(&format!("{}.{} = (char)r.ReadU16();", obj, name));
            }
            ResolvedType::String { .. } => {
                self.line(&format!("{}.{} = r.ReadString();", obj, name));
            }
            ResolvedType::WString { .. } => {
                self.line(&format!("{}.{} = r.ReadWString();", obj, name));
            }
            ResolvedType::Enum(enum_name) => {
                let cs_name = cs_type_ref(enum_name);
                self.line(&format!("{}.{} = ({})r.ReadEnum();", obj, name, cs_name));
            }
            ResolvedType::Bitmask(bitmask_name) => {
                let cs_name = cs_type_ref(bitmask_name);
                let bit_bound = self.find_bitmask(bitmask_name).map(|b| b.bit_bound).unwrap_or(32);
                let (_, _, read_method, _) = Self::bitmask_backing_info(bit_bound);
                self.line(&format!("{}.{} = ({})r.{}();", obj, name, cs_name, read_method));
            }
            ResolvedType::Struct(struct_name) => {
                let cs_name = cs_type_ref(struct_name);
                self.line(&format!("{}.{} = {}.DeserializeCdrInline(r);", obj, name, cs_name));
            }
            ResolvedType::Sequence { element, .. } => {
                let count_var = format!("_{name}Count");
                let cs_elem = Self::type_to_csharp(element);
                let non_prim = Self::is_non_primitive_element(element);
                let size_var = format!("_{name}SeqSize");
                let start_var = format!("_{name}SeqStart");
                if non_prim {
                    self.line(&format!("var ({}, {}) = r.ReadDheader();", size_var, start_var));
                }
                self.line(&format!("var {} = r.ReadSeqHeader();", count_var));
                self.line(&format!(
                    "{}.{} = new List<{}>((int){});",
                    obj, name, cs_elem, count_var
                ));
                self.line(&format!("for (var _i = 0; _i < {}; _i++)", count_var));
                self.line("{");
                self.indent += 1;
                self.emit_read_field_into_var(element, "_item");
                self.line(&format!("{}.{}.Add(_item);", obj, name));
                self.indent -= 1;
                self.line("}");
                if non_prim {
                    self.line(&format!("r.ReadDheaderEnd({}, {});", size_var, start_var));
                }
            }
            ResolvedType::Array { .. } => {
                self.emit_array_read_into(ty, &format!("{}.{}", obj, name), &format!("_{}", name));
            }
            ResolvedType::Map { key, value, .. } => {
                let count_var = format!("_{name}Count");
                let cs_key = Self::type_to_csharp(key);
                let cs_val = Self::type_to_csharp(value);
                let non_prim =
                    Self::is_non_primitive_element(key) || Self::is_non_primitive_element(value);
                let size_var = format!("_{name}MapSize");
                let start_var = format!("_{name}MapStart");
                if non_prim {
                    self.line(&format!("var ({}, {}) = r.ReadDheader();", size_var, start_var));
                }
                self.line(&format!("var {} = r.ReadSeqHeader();", count_var));
                self.line(&format!(
                    "{}.{} = new Dictionary<{}, {}>((int){});",
                    obj, name, cs_key, cs_val, count_var
                ));
                self.line(&format!("for (var _i = 0; _i < {}; _i++)", count_var));
                self.line("{");
                self.indent += 1;
                self.emit_read_field_into_var(key, "_k");
                self.emit_read_field_into_var(value, "_v");
                self.line(&format!("{}.{}[_k] = _v;", obj, name));
                self.indent -= 1;
                self.line("}");
                if non_prim {
                    self.line(&format!("r.ReadDheaderEnd({}, {});", size_var, start_var));
                }
            }
        }
    }

    /// Emit a read expression that assigns to a local variable.
    /// Read a possibly multidimensional array into `target`, which must already be
    /// assignable. `prefix` keeps the locals unique per field: recursing a dimension at
    /// a time reused `_j`/`_inner`, which collides from three dimensions on.
    fn emit_array_read_into(&mut self, ty: &ResolvedType, target: &str, prefix: &str) {
        let (dims, base) = flatten_array(ty);
        let non_prim = Self::array_needs_dheader(base);
        let size_var = format!("{prefix}ArrSize");
        let start_var = format!("{prefix}ArrStart");
        if non_prim {
            self.line(&format!("var ({}, {}) = r.ReadDheader();", size_var, start_var));
        }
        let mut acc = target.to_string();
        for d in 0..dims.len() {
            self.line(&format!("{} = {};", acc, Self::jagged_alloc(base, &dims, d)));
            let idx = format!("{}I{}", prefix, d);
            self.line(&format!("for (var {} = 0; {} < {}; {}++)", idx, idx, dims[d], idx));
            self.line("{");
            self.indent += 1;
            acc = format!("{}[{}]", acc, idx);
        }
        let elem = format!("{prefix}Elem");
        self.emit_read_field_into_var(base, &elem);
        self.line(&format!("{} = {};", acc, elem));
        for _ in 0..dims.len() {
            self.indent -= 1;
            self.line("}");
        }
        if non_prim {
            self.line(&format!("r.ReadDheaderEnd({}, {});", size_var, start_var));
        }
    }

    fn emit_read_field_into_var(&mut self, ty: &ResolvedType, var_name: &str) {
        match ty {
            ResolvedType::Bool => {
                self.line(&format!("var {} = r.ReadBool();", var_name));
            }
            ResolvedType::U8 | ResolvedType::UInt8 => {
                self.line(&format!("var {} = r.ReadU8();", var_name));
            }
            ResolvedType::I8 => {
                self.line(&format!("var {} = r.ReadI8();", var_name));
            }
            ResolvedType::I16 => {
                self.line(&format!("var {} = r.ReadI16();", var_name));
            }
            ResolvedType::U16 => {
                self.line(&format!("var {} = r.ReadU16();", var_name));
            }
            ResolvedType::I32 => {
                self.line(&format!("var {} = r.ReadI32();", var_name));
            }
            ResolvedType::U32 => {
                self.line(&format!("var {} = r.ReadU32();", var_name));
            }
            ResolvedType::I64 => {
                self.line(&format!("var {} = r.ReadI64();", var_name));
            }
            ResolvedType::U64 => {
                self.line(&format!("var {} = r.ReadU64();", var_name));
            }
            ResolvedType::F32 => {
                self.line(&format!("var {} = r.ReadF32();", var_name));
            }
            ResolvedType::F64 => {
                self.line(&format!("var {} = r.ReadF64();", var_name));
            }
            ResolvedType::Char => {
                self.line(&format!("var {} = (char)r.ReadU8();", var_name));
            }
            ResolvedType::WChar => {
                self.line(&format!("var {} = (char)r.ReadU16();", var_name));
            }
            ResolvedType::String { .. } => {
                self.line(&format!("var {} = r.ReadString();", var_name));
            }
            ResolvedType::WString { .. } => {
                self.line(&format!("var {} = r.ReadWString();", var_name));
            }
            ResolvedType::Enum(enum_name) => {
                let cs_name = cs_type_ref(enum_name);
                self.line(&format!("var {} = ({})r.ReadEnum();", var_name, cs_name));
            }
            ResolvedType::Bitmask(bitmask_name) => {
                let cs_name = cs_type_ref(bitmask_name);
                let bit_bound = self.find_bitmask(bitmask_name).map(|b| b.bit_bound).unwrap_or(32);
                let (_, _, read_method, _) = Self::bitmask_backing_info(bit_bound);
                self.line(&format!("var {} = ({})r.{}();", var_name, cs_name, read_method));
            }
            ResolvedType::Struct(struct_name) => {
                let cs_name = cs_type_ref(struct_name);
                self.line(&format!("var {} = {}.DeserializeCdrInline(r);", var_name, cs_name));
            }
            ResolvedType::Sequence { element, .. } => {
                let count_var = format!("{var_name}Count");
                let cs_elem = Self::type_to_csharp(element);
                let non_prim = Self::is_non_primitive_element(element);
                let size_var = format!("{var_name}SeqSize");
                let start_var = format!("{var_name}SeqStart");
                if non_prim {
                    self.line(&format!("var ({}, {}) = r.ReadDheader();", size_var, start_var));
                }
                self.line(&format!("var {} = r.ReadSeqHeader();", count_var));
                self.line(&format!(
                    "var {} = new List<{}>((int){});",
                    var_name, cs_elem, count_var
                ));
                self.line(&format!("for (var _j = 0; _j < {}; _j++)", count_var));
                self.line("{");
                self.indent += 1;
                self.emit_read_field_into_var(element, "_inner");
                self.line(&format!("{}.Add(_inner);", var_name));
                self.indent -= 1;
                self.line("}");
                if non_prim {
                    self.line(&format!("r.ReadDheaderEnd({}, {});", size_var, start_var));
                }
            }
            ResolvedType::Array { .. } => {
                self.line(&format!("{} {};", Self::type_to_csharp(ty), var_name));
                self.emit_array_read_into(ty, var_name, var_name);
            }
            ResolvedType::Map { key, value, .. } => {
                let count_var = format!("{var_name}Count");
                let cs_key = Self::type_to_csharp(key);
                let cs_val = Self::type_to_csharp(value);
                let non_prim =
                    Self::is_non_primitive_element(key) || Self::is_non_primitive_element(value);
                let size_var = format!("{var_name}MapSize");
                let start_var = format!("{var_name}MapStart");
                if non_prim {
                    self.line(&format!("var ({}, {}) = r.ReadDheader();", size_var, start_var));
                }
                self.line(&format!("var {} = r.ReadSeqHeader();", count_var));
                self.line(&format!(
                    "var {} = new Dictionary<{}, {}>((int){});",
                    var_name, cs_key, cs_val, count_var
                ));
                self.line(&format!("for (var _j = 0; _j < {}; _j++)", count_var));
                self.line("{");
                self.indent += 1;
                self.emit_read_field_into_var(key, "_mk");
                self.emit_read_field_into_var(value, "_mv");
                self.line(&format!("{}[_mk] = _mv;", var_name));
                self.indent -= 1;
                self.line("}");
                if non_prim {
                    self.line(&format!("r.ReadDheaderEnd({}, {});", size_var, start_var));
                }
            }
        }
    }

    fn find_bitmask(&self, name: &str) -> Option<&ResolvedBitmask> {
        let simple = name.rsplit("::").next().unwrap_or(name);
        self.model
            .bitmasks
            .iter()
            .chain(self.model.imported.bitmasks.iter())
            .find(|b| b.name == simple)
    }

    /// Locate a struct by leaf name in this file or in an `#include`d file.
    fn find_struct(&self, name: &str) -> Option<&ResolvedStruct> {
        let simple = name.rsplit("::").next().unwrap_or(name);
        self.model
            .structs
            .iter()
            .chain(self.model.imported.structs.iter())
            .find(|s| s.name == simple)
    }

    /// Locate an enum by leaf name in this file or in an `#include`d file.
    fn find_enum(&self, name: &str) -> Option<&ResolvedEnum> {
        let simple = name.rsplit("::").next().unwrap_or(name);
        self.model.enums.iter().chain(self.model.imported.enums.iter()).find(|e| e.name == simple)
    }

    // ---- Helpers ----

    fn line(&mut self, s: &str) {
        if s.is_empty() {
            self.out.push('\n');
        } else {
            for _ in 0..self.indent {
                self.out.push_str("    ");
            }
            self.out.push_str(s);
            self.out.push('\n');
        }
    }

    #[allow(dead_code)]
    fn raw(&mut self, s: &str) {
        self.out.push_str(s);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_idl;
    use crate::resolver::resolve;

    #[test]
    fn test_type_info_metadata_for_flat_struct() {
        let defs = parse_idl(
            r#"
            @appendable
            struct ShapeType {
                @key string<128> color;
                long x;
                sequence<uint8> payload;
                octet raw;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "ShapeType.idl", &CSharpOptions::default());

        assert!(
            code.contains("public static readonly DdsTypeInfoField[] DdsTypeInfoFields"),
            "{}",
            code
        );
        // @key string<128> -> ("string", name, 0, bound=128, KEY=1)
        assert!(
            code.contains(r#"new DdsTypeInfoField("string", "color", 0, 128u, 1),"#),
            "{}",
            code
        );
        // long -> INT2DDS_FIELD_INT32 = 5
        assert!(code.contains(r#"new DdsTypeInfoField("field", "x", 5, 0u, 0),"#), "{}", code);
        // sequence<uint8> -> ("seq", name, INT2DDS_FIELD_UINT8 = 7, bound=0, 0)
        assert!(code.contains(r#"new DdsTypeInfoField("seq", "payload", 7, 0u, 0),"#), "{}", code);
        // octet -> INT2DDS_FIELD_BYTE = 1 (distinct from uint8's 7)
        assert!(code.contains(r#"new DdsTypeInfoField("field", "raw", 1, 0u, 0),"#), "{}", code);
    }

    #[test]
    fn test_type_info_metadata_for_nested_struct_key() {
        let defs = parse_idl(
            r#"
            @final
            struct NestedKey {
                long a;
                long b;
            };
            @final
            struct Composite {
                @key NestedKey loc;
                long value;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Composite.idl", &CSharpOptions::default());

        // Composite advertises: the nested @key member references the nested CLR type.
        assert!(
            code.contains(r#"new DdsTypeInfoField("nested", "loc", typeof(NestedKey), 1),"#),
            "{}",
            code
        );
        assert!(code.contains(r#"new DdsTypeInfoField("field", "value", 5, 0u, 0),"#), "{}", code);
        // The nested struct still emits its own flat metadata (recursion source of truth).
        assert!(code.contains(r#"new DdsTypeInfoField("field", "a", 5, 0u, 0),"#), "{}", code);
        assert!(code.contains(r#"new DdsTypeInfoField("field", "b", 5, 0u, 0),"#), "{}", code);
    }

    /// The no-arg convenience `SerializeCdr()` must default to XCDR1 (spec effective
    /// write default), mirroring the core `int2dds_default_data_representation()`. The
    /// explicit `SerializeCdr(bool xcdr2)` overload stays for the QoS-driven write path.
    #[test]
    fn test_type_info_metadata_stamps_explicit_member_ids() {
        let defs = parse_idl(
            r#"
            @mutable
            struct SparseIds {
                @id(5) long a;
                long b;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Sparse.idl", &CSharpOptions::default());

        let a_line = code.lines().find(|l| l.contains("\"field\", \"a\"")).unwrap();
        assert!(a_line.contains("memberId: 5"), "{}", a_line);
        let b_line = code.lines().find(|l| l.contains("\"field\", \"b\"")).unwrap();
        assert!(!b_line.contains("memberId"), "{}", b_line);
    }

    #[test]
    fn test_optional_members_emit_presence_csharp() {
        let defs = parse_idl(
            r#"
            @extensibility(FINAL)
            struct OptF {
                long id;
                @optional long opt_num;
                @optional string opt_text;
            };
            @mutable
            struct OptM {
                long id;
                @optional string opt_label;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Opt.idl", &CSharpOptions::default());

        // Nullable representation, no initializer.
        assert!(code.contains("public int? OptNum { get; set; }"), "{}", code);
        assert!(code.contains("public string? OptText { get; set; }"), "{}", code);
        // Final/Appendable: XCDR2 presence bool, XCDR1 parameter header.
        assert!(code.contains("if (w.IsXcdr2) { w.WriteBool(OptNum != null); }"), "{}", code);
        assert!(code.contains("else { _ot = w.MemberV1Begin(1); }"), "{}", code);
        assert!(code.contains("w.WriteI32(OptNum.Value);"), "{}", code);
        assert!(
            code.contains("if (!w.IsXcdr2) { w.MemberV1Finalize(_ot, 1, false); }"),
            "{}",
            code
        );
        assert!(
            code.contains(
                "else { var (_, _olen, _, _osen) = r.ReadParameterHeader(); _has = !_osen && _olen != 0; }"
            ),
            "{}",
            code
        );
        // Mutable: absent members are omitted entirely.
        assert!(code.contains("if (OptLabel != null)"), "{}", code);
    }

    #[test]
    fn test_serialize_cdr_convenience_defaults_to_xcdr1() {
        let defs = parse_idl(
            r#"
            @appendable
            struct ShapeType {
                @key long id;
                long value;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "ShapeType.idl", &CSharpOptions::default());
        assert!(
            code.contains("public byte[] SerializeCdr() => SerializeCdr(false);"),
            "no-arg SerializeCdr() must default to XCDR1 (false): {}",
            code
        );
        assert!(!code.contains("SerializeCdr(true)"), "no XCDR2-default convenience: {}", code);
        assert!(
            code.contains("public byte[] SerializeCdr(bool xcdr2)"),
            "explicit xcdr2 overload must stay for QoS-driven writes: {}",
            code
        );
    }

    #[test]
    fn test_type_info_metadata_omitted_for_unsupported_members() {
        let defs = parse_idl(
            r#"
            struct Widget { map<long, long> m; long x; };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Widget.idl", &CSharpOptions::default());
        // Widget has a map member -> not advertisable -> advertisement metadata omitted.
        assert!(!code.contains("DdsTypeInfoFields"), "{}", code);
    }

    #[test]
    fn test_type_info_metadata_for_enum_and_collection_members() {
        let defs = parse_idl(
            r#"
            enum Color { RED, GREEN, BLUE };
            @final struct Point { long x; long y; };
            struct Widget {
                @key Color c;
                sequence<Point> path;
                Point grid[3];
                long x;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Widget.idl", &CSharpOptions::default());
        // Enum member -> nested typeof reference (built by reflection at runtime).
        assert!(
            code.contains(r#"new DdsTypeInfoField("nested", "c", typeof(Color), 1),"#),
            "{}",
            code
        );
        // sequence<Point> / Point[3] -> collection-of-nested with element typeof + size.
        assert!(
            code.contains(r#"new DdsTypeInfoField("seq_nested", "path", typeof(Point), 0u, 0),"#),
            "{}",
            code
        );
        assert!(
            code.contains(r#"new DdsTypeInfoField("arr_nested", "grid", typeof(Point), 3u, 0),"#),
            "{}",
            code
        );
    }

    #[test]
    fn test_keyword_escaping_struct_properties() {
        // C# keywords are lowercase (class, event, async, etc.)
        // After to_pascal_case, "class" → "Class" which is NOT a C# keyword → no escaping
        // This is correct because C# is case-sensitive and "Class" is a valid identifier.
        let defs = parse_idl(
            r#"
            struct KeywordTest {
                long class;
                long event;
                boolean async;
                string record;
                long value;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "KeywordTest.idl", &CSharpOptions::default());

        // PascalCase converts lowercase keywords to capitalized form → no longer a keyword
        assert!(code.contains("Class"), "class → Class: {}", code);
        assert!(code.contains("Event"), "event → Event: {}", code);
        assert!(code.contains("Async"), "async → Async: {}", code);
        assert!(code.contains("Record"), "record → Record: {}", code);
        assert!(code.contains("Value"), "value → Value: {}", code);
    }

    #[test]
    fn test_keyword_escaping_enum_variants() {
        let defs = parse_idl(
            r#"
            enum TestEnum {
                CLASS,
                EVENT,
                ASYNC
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "TestEnum.idl", &CSharpOptions::default());

        // PascalCase: CLASS -> Class, EVENT -> Event, ASYNC -> Async
        // These are NOT C# keywords (keywords are lowercase) → no @ prefix
        assert!(code.contains("Class ="), "Class variant: {}", code);
        assert!(code.contains("Event ="), "Event variant: {}", code);
        assert!(code.contains("Async ="), "Async variant: {}", code);
    }

    #[test]
    fn test_non_keyword_not_escaped_csharp() {
        let defs = parse_idl(
            r#"
            struct Normal {
                long data;
                string sensor_id;
                long temperature;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Normal.idl", &CSharpOptions::default());

        assert!(code.contains("Data"));
        assert!(code.contains("SensorId"));
        assert!(code.contains("Temperature"));
        assert!(!code.contains("@Data"));
        assert!(!code.contains("@Temperature"));
    }

    /// DDS-XTypes 7.4.3.5.3: an array of non-primitive elements carries a DHEADER over
    /// the element payload; an array of primitives does not.
    #[test]
    fn test_array_of_struct_dheader_csharp() {
        let defs = parse_idl(
            r#"
            struct Pt { long x; long y; };
            struct Holder {
                long nums[3];
                Pt row[2];
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Holder.idl", &CSharpOptions::default());

        assert!(code.contains("var _arrDt = w.DheaderBegin();"), "{}", code);
        assert!(code.contains("w.DheaderFinalize(_arrDt);"), "{}", code);
        assert!(code.contains("var (_RowArrSize, _RowArrStart) = r.ReadDheader();"), "{}", code);
        assert!(code.contains("r.ReadDheaderEnd(_RowArrSize, _RowArrStart);"), "{}", code);
        assert!(!code.contains("_NumsArrSize"), "primitive array stays unframed: {}", code);
    }

    #[test]
    fn test_multidim_array_csharp() {
        let defs = parse_idl(
            r#"
            enum Color { RED, GREEN };
            struct Holder {
                long nums[2][3];
                string words[2][3];
                Color e[2][3];
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Holder.idl", &CSharpOptions::default());

        // A jagged rank takes its length in its own brackets; `new int[][2]` does not parse.
        assert!(code.contains("public int[][] Nums { get; set; } = new int[2][];"), "{}", code);
        assert!(code.contains("obj.Nums[_NumsI0] = new int[3];"), "{}", code);

        // One frame over both dimensions: `string words[2][3]` frames exactly as often as
        // the flat `string words[6]`, rather than once per row.
        let flat = parse_idl("struct Flat { string words[6]; };").unwrap();
        let flat = generate(&resolve(flat).unwrap(), "Flat.idl", &CSharpOptions::default());
        let words_only = parse_idl("struct Holder { string words[2][3]; };").unwrap();
        let words_only =
            generate(&resolve(words_only).unwrap(), "Holder.idl", &CSharpOptions::default());
        assert_eq!(
            words_only.matches("w.DheaderBegin();").count(),
            flat.matches("w.DheaderBegin();").count(),
            "multidimensional array frames once: {}",
            words_only
        );

        // Distinct names per dimension: C# rejects the redeclaration outright (CS0136).
        assert!(code.contains("foreach (var _item1 in _item0)"), "{}", code);

        // type_info advertises the flattened dims (declaration order, outer first) via the
        // "arr_nd"/"arr_nested_nd" ops; before the `_nd` builders these members made the
        // whole type non-advertisable.
        assert!(
            code.contains(
                r#"new DdsTypeInfoField("arr_nd", "nums", 5, new uint[] { 2u, 3u }, 0),"#
            ),
            "{}",
            code
        );
        assert!(
            code.contains(
                r#"new DdsTypeInfoField("arr_nd", "words", 13, new uint[] { 2u, 3u }, 0),"#
            ),
            "{}",
            code
        );
        assert!(
            code.contains(
                r#"new DdsTypeInfoField("arr_nested_nd", "e", typeof(Color), new uint[] { 2u, 3u }, 0),"#
            ),
            "{}",
            code
        );
    }
}
