/// Python code generation backend.
///
/// Generates Python dataclasses with CDR serialization methods
/// that use the int2dds Python CDR library.
use crate::naming;
use crate::types::*;

/// Options for Python code generation.
#[derive(Debug, Clone, Default)]
pub struct PythonOptions {
    /// Module path for the int2dds package (default: "int2dds")
    pub int2dds_module: String,
}

impl PythonOptions {
    pub fn new() -> Self {
        Self { int2dds_module: "int2dds".to_string() }
    }
}

/// Generate Python code from the IDL model.
pub fn generate(model: &IdlModel, idl_filename: &str, opts: &PythonOptions) -> String {
    let mut gen = PyGen { out: String::new(), opts, model, indent: 0 };
    gen.emit_file(idl_filename);
    gen.out
}

/// Render a constant value as a Python literal.
fn py_const_value(value: &ConstValue) -> String {
    match value {
        ConstValue::Int(v) => v.to_string(),
        ConstValue::Float(v) => format!("{:?}", v),
        ConstValue::Bool(v) => if *v { "True" } else { "False" }.to_string(),
        ConstValue::Str(v) => format!("{:?}", v),
        ConstValue::Ident(v) => v.rsplit("::").next().unwrap_or(v).to_string(),
    }
}

struct PyGen<'a> {
    out: String,
    opts: &'a PythonOptions,
    model: &'a IdlModel,
    indent: usize,
}

impl<'a> PyGen<'a> {
    fn emit_file(&mut self, idl_filename: &str) {
        let module_name = &self.opts.int2dds_module;

        // File header
        self.line(&format!(
            "\"\"\"Auto-generated by int2dds-idl from {}\n\nDO NOT EDIT - changes will be overwritten\n\"\"\"",
            idl_filename
        ));
        self.line("");
        self.line("from __future__ import annotations");
        self.line("");
        self.line("from dataclasses import dataclass, field");
        self.line("from enum import IntEnum, IntFlag");
        self.line("from typing import ClassVar");
        self.line("");
        self.line(&format!("from {}.cdr import CdrReader, CdrWriter, Extensibility", module_name));
        self.line("");
        self.emit_cross_file_imports();
        self.line("");

        self.emit_constants();

        // Enums first (may be referenced by structs)
        for e in &self.model.enums {
            self.emit_enum(e);
            self.line("");
            self.line("");
        }

        // Bitmasks
        for b in &self.model.bitmasks {
            self.emit_bitmask(b);
            self.line("");
            self.line("");
        }

        // Bitsets (may be referenced by structs)
        for b in &self.model.bitsets {
            self.emit_bitset(b);
            self.line("");
            self.line("");
        }

        // Unions (may be referenced by structs)
        for u in &self.model.unions {
            self.emit_union(u);
            self.line("");
            self.line("");
        }

        // Structs
        for s in &self.model.structs {
            self.emit_struct(s);
            self.line("");
            self.line("");
        }
    }

    // ---- Enum ----

    fn emit_enum(&mut self, e: &ResolvedEnum) {
        self.line(&format!("class {}(IntEnum):", e.name));
        self.indent += 1;
        self.line(&format!("\"\"\"IDL enum: {}\"\"\"", e.qualified_name));
        self.line("");
        for v in &e.variants {
            let variant_name = naming::to_screaming_snake(&v.name);
            self.line(&format!("{} = {}", variant_name, v.value));
        }
        self.indent -= 1;
        // XTypes TypeObject descriptor for enum-typed members: (bit_bound, literals) where each
        // literal is (canonical_name, value, is_default). Attached AFTER the class body because
        // any assignment inside an IntEnum body becomes an enum member. The canonical name is
        // PascalCase to match the derive macro's variant name (the TypeObject literal name), NOT
        // the Python SCREAMING_SNAKE member name. IDL enums are i32 -> bit_bound 32, no @default.
        let literals: Vec<String> = e
            .variants
            .iter()
            .map(|v| format!("(\"{}\", {}, False)", naming::to_pascal_case(&v.name), v.value))
            .collect();
        self.line("");
        self.line(&format!("{}._dds_type_name = \"{}\"", e.name, e.qualified_name));
        self.line(&format!("{}._dds_enum_info = (32, ({},))", e.name, literals.join(", ")));
    }

    // ---- Bitmask ----

    fn emit_bitmask(&mut self, b: &ResolvedBitmask) {
        self.line(&format!("class {}(IntFlag):", b.name));
        self.indent += 1;
        self.line(&format!(
            "\"\"\"IDL bitmask: {} (bit_bound={})\"\"\"",
            b.qualified_name, b.bit_bound
        ));
        self.line("");
        for flag in &b.flags {
            let flag_name = naming::to_screaming_snake(&flag.name);
            self.line(&format!("{} = 1 << {}", flag_name, flag.position));
        }
        if b.flags.is_empty() {
            self.line("pass");
        }
        self.indent -= 1;
    }

    // ---- Bitset ----

    /// Returns (write_method, read_method, python_int_size_for_mask) for a bitset based on total_bits.
    fn bitset_methods(total_bits: u32) -> (&'static str, &'static str) {
        match total_bits {
            0..=8 => ("write_u8", "read_u8"),
            9..=16 => ("write_u16", "read_u16"),
            17..=32 => ("write_u32", "read_u32"),
            _ => ("write_u64", "read_u64"),
        }
    }

    fn emit_bitset(&mut self, b: &ResolvedBitset) {
        let class_name = b.name.clone();
        let (write_fn, read_fn) = Self::bitset_methods(b.total_bits);

        self.line("@dataclass");
        self.line(&format!("class {}:", class_name));
        self.indent += 1;
        self.line(&format!(
            "\"\"\"IDL bitset: {} (total_bits={})\"\"\"",
            b.qualified_name, b.total_bits
        ));
        self.line("");

        self.line(&format!("_dds_type_name: ClassVar[str] = \"{}\"", b.qualified_name));
        self.line("_extensibility: ClassVar[Extensibility] = Extensibility.FINAL");
        self.line("_has_key: ClassVar[bool] = False");
        self.line("");

        // Fields (each as int with default 0)
        for f in &b.fields {
            let field_name = naming::escape_keyword(&f.name, naming::TargetLang::Python);
            self.line(&format!("{}: int = 0", field_name));
        }
        self.line("");

        // _serialize_cdr (with encap header)
        self.line("def _serialize_cdr(self, xcdr2: bool = False) -> memoryview:");
        self.indent += 1;
        self.line("\"\"\"Serialize to CDR bytes with encapsulation header (zero-copy view).\"\"\"");
        self.line("w = CdrWriter(extensibility=self._extensibility, xcdr2=xcdr2)");
        self.line("self._serialize_cdr_inline(w)");
        self.line("return w.view()");
        self.indent -= 1;
        self.line("");

        // _serialize_cdr_inline (bit-packing)
        self.line("def _serialize_cdr_inline(self, w: CdrWriter) -> None:");
        self.indent += 1;
        self.line(
            "\"\"\"Serialize fields directly into an existing writer (no encap header).\"\"\"",
        );
        self.line("_packed = 0");
        let mut bit_offset: u32 = 0;
        for f in &b.fields {
            let field_name = naming::escape_keyword(&f.name, naming::TargetLang::Python);
            let mask: u64 = (1u64 << f.bit_width) - 1;
            self.line(&format!(
                "_packed |= (int(self.{}) & 0x{:x}) << {}",
                field_name, mask, bit_offset
            ));
            bit_offset += f.bit_width;
        }
        self.line(&format!("w.{}(_packed)", write_fn));
        self.indent -= 1;
        self.line("");

        // _deserialize_cdr (with encap header)
        self.line("@classmethod");
        self.line(&format!("def _deserialize_cdr(cls, data: bytes) -> \"{}\":", class_name));
        self.indent += 1;
        self.line("\"\"\"Deserialize from CDR bytes.\"\"\"");
        self.line("r = CdrReader(data)");
        self.line("return cls._deserialize_cdr_inline(r)");
        self.indent -= 1;
        self.line("");

        // _deserialize_cdr_inline (bit-unpacking)
        self.line("@classmethod");
        self.line(&format!(
            "def _deserialize_cdr_inline(cls, r: CdrReader) -> \"{}\":",
            class_name
        ));
        self.indent += 1;
        self.line("\"\"\"Deserialize from an existing CdrReader (no encapsulation header).\"\"\"");
        self.line(&format!("_packed = r.{}()", read_fn));
        self.line("obj = cls()");
        let mut bit_offset: u32 = 0;
        for f in &b.fields {
            let field_name = naming::escape_keyword(&f.name, naming::TargetLang::Python);
            let mask: u64 = (1u64 << f.bit_width) - 1;
            self.line(&format!("obj.{} = (_packed >> {}) & 0x{:x}", field_name, bit_offset, mask));
            bit_offset += f.bit_width;
        }
        self.line("return obj");
        self.indent -= 1;
        self.line("");

        self.indent -= 1;
    }

    // ---- Union ----

    fn discriminant_python_type(&self, ty: &ResolvedType) -> &str {
        match ty {
            ResolvedType::Bool => "bool",
            ResolvedType::F32 | ResolvedType::F64 => "float",
            _ => "int",
        }
    }

    fn discriminant_default(&self, ty: &ResolvedType) -> &str {
        match ty {
            ResolvedType::Bool => "False",
            ResolvedType::F32 | ResolvedType::F64 => "0.0",
            _ => "0",
        }
    }

    fn discriminant_read_method(&self, ty: &ResolvedType) -> &str {
        match ty {
            ResolvedType::Bool => "read_bool",
            ResolvedType::I8 => "read_i8",
            ResolvedType::U8 | ResolvedType::UInt8 => "read_u8",
            ResolvedType::I16 => "read_i16",
            ResolvedType::U16 => "read_u16",
            ResolvedType::I32 => "read_i32",
            ResolvedType::U32 => "read_u32",
            ResolvedType::I64 => "read_i64",
            ResolvedType::U64 => "read_u64",
            _ => "read_i32",
        }
    }

    fn discriminant_write_method(&self, ty: &ResolvedType) -> &str {
        match ty {
            ResolvedType::Bool => "write_bool",
            ResolvedType::I8 => "write_i8",
            ResolvedType::U8 | ResolvedType::UInt8 => "write_u8",
            ResolvedType::I16 => "write_i16",
            ResolvedType::U16 => "write_u16",
            ResolvedType::I32 => "write_i32",
            ResolvedType::U32 => "write_u32",
            ResolvedType::I64 => "write_i64",
            ResolvedType::U64 => "write_u64",
            _ => "write_i32",
        }
    }

    fn label_to_python(&self, label: &ResolvedUnionLabel) -> String {
        match label {
            ResolvedUnionLabel::Int(v) => format!("{}", v),
            ResolvedUnionLabel::Bool(v) => {
                if *v {
                    "True".to_string()
                } else {
                    "False".to_string()
                }
            }
            ResolvedUnionLabel::Ident(s) => s.clone(),
        }
    }

    fn emit_union(&mut self, u: &ResolvedUnion) {
        let class_name = u.name.clone();
        let disc_py_type = self.discriminant_python_type(&u.discriminant_type).to_string();
        let disc_default = self.discriminant_default(&u.discriminant_type).to_string();
        let disc_read = self.discriminant_read_method(&u.discriminant_type).to_string();
        let disc_write = self.discriminant_write_method(&u.discriminant_type).to_string();
        let ext_name = match u.extensibility {
            ExtensibilityKind::Final => "FINAL",
            ExtensibilityKind::Appendable => "APPENDABLE",
            ExtensibilityKind::Mutable => "MUTABLE",
        };

        // @dataclass class declaration
        self.line("@dataclass");
        self.line(&format!("class {}:", class_name));
        self.indent += 1;
        self.line(&format!("\"\"\"IDL union: {}\"\"\"", u.qualified_name));
        self.line("");

        // Type metadata
        self.line(&format!("_dds_type_name: ClassVar[str] = \"{}\"", u.qualified_name));
        self.line(&format!("_extensibility: ClassVar[Extensibility] = Extensibility.{}", ext_name));
        self.line("_has_key: ClassVar[bool] = False");
        self.line("");

        // Discriminator field
        self.line(&format!("discriminator: {} = {}", disc_py_type, disc_default));

        // Fields for each case member
        for case in &u.cases {
            let field_name = naming::escape_keyword(&case.member.name, naming::TargetLang::Python);
            let py_type = Self::type_to_python(&case.member.resolved_type);
            let default = self.default_value(&case.member.resolved_type);
            self.line(&format!("{}: {} = {}", field_name, py_type, default));
        }
        if let Some(ref def) = u.default_case {
            let field_name = naming::escape_keyword(&def.name, naming::TargetLang::Python);
            let py_type = Self::type_to_python(&def.resolved_type);
            let default = self.default_value(&def.resolved_type);
            self.line(&format!("{}: {} = {}", field_name, py_type, default));
        }
        self.line("");

        // _serialize_cdr (with encap header)
        self.line("def _serialize_cdr(self, xcdr2: bool = False) -> memoryview:");
        self.indent += 1;
        self.line("\"\"\"Serialize to CDR bytes with encapsulation header (zero-copy view).\"\"\"");
        self.line("w = CdrWriter(extensibility=self._extensibility, xcdr2=xcdr2)");
        self.line("self._serialize_cdr_inline(w)");
        self.line("return w.view()");
        self.indent -= 1;
        self.line("");

        let needs_union_dh = !matches!(u.extensibility, ExtensibilityKind::Final);

        // _serialize_cdr_inline
        self.line("def _serialize_cdr_inline(self, w: CdrWriter) -> None:");
        self.indent += 1;
        self.line(
            "\"\"\"Serialize fields directly into an existing writer (no encap header).\"\"\"",
        );
        if needs_union_dh {
            self.line("if w._xcdr2:");
            self.indent += 1;
            self.line("_u_token = w.write_dheader_begin()");
            self.indent -= 1;
        }
        self.line(&format!("w.{}(self.discriminator)", disc_write));
        self.emit_union_switch_write(u);
        if needs_union_dh {
            self.line("if w._xcdr2:");
            self.indent += 1;
            self.line("w.write_dheader_finalize(_u_token)");
            self.indent -= 1;
        }
        self.indent -= 1;
        self.line("");

        // _deserialize_cdr (with encap header)
        self.line("@classmethod");
        self.line(&format!("def _deserialize_cdr(cls, data: bytes) -> \"{}\":", class_name));
        self.indent += 1;
        self.line("\"\"\"Deserialize from CDR bytes.\"\"\"");
        self.line("r = CdrReader(data)");
        self.line("return cls._deserialize_cdr_inline(r)");
        self.indent -= 1;
        self.line("");

        // _deserialize_cdr_inline
        self.line("@classmethod");
        self.line(&format!(
            "def _deserialize_cdr_inline(cls, r: CdrReader) -> \"{}\":",
            class_name
        ));
        self.indent += 1;
        self.line("\"\"\"Deserialize from an existing CdrReader (no encapsulation header).\"\"\"");
        self.line("obj = cls()");
        if needs_union_dh {
            self.line("if r._xcdr2:");
            self.indent += 1;
            self.line("_u_dsize, _u_dstart = r.read_dheader()");
            self.indent -= 1;
        }
        self.line(&format!("obj.discriminator = r.{}()", disc_read));
        self.emit_union_switch_read(u);
        if needs_union_dh {
            self.line("if r._xcdr2:");
            self.indent += 1;
            self.line("r.read_dheader_end(_u_dsize, _u_dstart)");
            self.indent -= 1;
        }
        self.line("return obj");
        self.indent -= 1;
        self.line("");

        self.indent -= 1;
    }

    /// Emit the if/elif chain for union case write inside _serialize_cdr_inline.
    fn emit_union_switch_write(&mut self, u: &ResolvedUnion) {
        let mut first = true;
        for case in &u.cases {
            // Combine multiple labels with `or`
            let conditions: Vec<String> = case
                .labels
                .iter()
                .map(|l| format!("self.discriminator == {}", self.label_to_python(l)))
                .collect();
            let cond = conditions.join(" or ");
            if first {
                self.line(&format!("if {}:", cond));
                first = false;
            } else {
                self.line(&format!("elif {}:", cond));
            }
            self.indent += 1;
            let accessor = format!(
                "self.{}",
                naming::escape_keyword(&case.member.name, naming::TargetLang::Python)
            );
            self.emit_write_field(&case.member.resolved_type, &accessor);
            self.indent -= 1;
        }
        if let Some(ref def) = u.default_case {
            if first {
                // No cases, only default
                self.line("if True:");
            } else {
                self.line("else:");
            }
            self.indent += 1;
            let accessor =
                format!("self.{}", naming::escape_keyword(&def.name, naming::TargetLang::Python));
            self.emit_write_field(&def.resolved_type, &accessor);
            self.indent -= 1;
        }
    }

    /// Emit the if/elif chain for union case read inside _deserialize_cdr_inline.
    fn emit_union_switch_read(&mut self, u: &ResolvedUnion) {
        let mut first = true;
        for case in &u.cases {
            let conditions: Vec<String> = case
                .labels
                .iter()
                .map(|l| format!("obj.discriminator == {}", self.label_to_python(l)))
                .collect();
            let cond = conditions.join(" or ");
            if first {
                self.line(&format!("if {}:", cond));
                first = false;
            } else {
                self.line(&format!("elif {}:", cond));
            }
            self.indent += 1;
            let field_name = naming::escape_keyword(&case.member.name, naming::TargetLang::Python);
            // emit_read_field assigns to a local variable; we need to assign to obj.field
            // So generate: tmp = read; obj.field = tmp
            let tmp_name = "_v".to_string();
            self.emit_read_field(&case.member.resolved_type, &tmp_name);
            self.line(&format!("obj.{} = _v", field_name));
            self.indent -= 1;
        }
        if let Some(ref def) = u.default_case {
            if first {
                self.line("if True:");
            } else {
                self.line("else:");
            }
            self.indent += 1;
            let field_name = naming::escape_keyword(&def.name, naming::TargetLang::Python);
            let tmp_name = "_v".to_string();
            self.emit_read_field(&def.resolved_type, &tmp_name);
            self.line(&format!("obj.{} = _v", field_name));
            self.indent -= 1;
        }
    }

    // ---- Struct ----

    fn emit_struct(&mut self, s: &ResolvedStruct) {
        let ext_name = match s.extensibility {
            ExtensibilityKind::Final => "FINAL",
            ExtensibilityKind::Appendable => "APPENDABLE",
            ExtensibilityKind::Mutable => "MUTABLE",
        };

        // Collect all members including inherited fields
        let all_members = self.collect_all_members(s);
        let has_key = all_members.iter().any(|m| m.is_key);

        // @dataclass decorator
        self.line("@dataclass");
        self.line(&format!("class {}:", s.name));
        self.indent += 1;

        // Docstring
        self.line(&format!(
            "\"\"\"IDL struct: {} (Extensibility: {})\"\"\"",
            s.qualified_name, ext_name
        ));
        self.line("");

        // Type metadata as class variables
        self.line(&format!("_dds_type_name: ClassVar[str] = \"{}\"", s.qualified_name));
        self.line(&format!("_extensibility: ClassVar[Extensibility] = Extensibility.{}", ext_name));
        self.line(&format!(
            "_has_key: ClassVar[bool] = {}",
            if has_key { "True" } else { "False" }
        ));
        self.line("");

        // XTypes TypeObject advertisement metadata: the runtime builds an Int2DdsTypeInfo from
        // this and advertises a conformant TypeObject during discovery, matching the Rust derive.
        // Nested structs are referenced by content-hash (via int2dds_type_info_add_nested_field)
        // so composite keys resolve. Enums/maps/unions still fall back to name-based matching.
        self.emit_type_info_metadata(&all_members);

        // Fields (including inherited from base structs)
        for m in &all_members {
            let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
            let py_type = Self::type_to_python(&m.resolved_type);
            let default = self.default_value(&m.resolved_type);
            self.line(&format!("{}: {} = {}", field_name, py_type, default));
        }
        self.line("");

        // _serialize_cdr method
        self.emit_serialize_cdr(s);
        self.line("");

        // _serialize_cdr_inline method (for nested struct serialization)
        self.emit_serialize_cdr_inline(s);
        self.line("");

        // _deserialize_cdr class method
        self.emit_deserialize_cdr(s);
        self.line("");

        // _deserialize_cdr_inline class method (for nested struct deserialization)
        self.emit_deserialize_cdr_inline(s);
        self.line("");

        self.indent -= 1;
    }

    /// Emit `_dds_type_info_fields` for advertisable structs (all members are primitives,
    /// strings, sequences/arrays of primitives, or nested structs that are themselves
    /// recursively advertisable). The runtime reads this to advertise a TypeObject.
    fn emit_type_info_metadata(&mut self, members: &[ResolvedMember]) {
        let mut visited = std::collections::HashSet::new();
        if !members.iter().all(|m| self.member_advertisable(m, &mut visited)) {
            return;
        }
        self.line("_dds_type_info_fields: ClassVar[list] = [");
        self.indent += 1;
        for m in members {
            self.line(&Self::type_info_field_spec(m));
        }
        self.indent -= 1;
        self.line("]");
        self.line("");
    }

    /// FFI INT2DDS_FIELD_* constant for a scalar/string/char type; None for composite types.
    fn field_constant(ty: &ResolvedType) -> Option<i32> {
        Some(match ty {
            ResolvedType::Bool => 0,
            ResolvedType::U8 => 1,   // BYTE (octet)
            ResolvedType::Char => 2, // CHAR8
            ResolvedType::I8 => 3,
            ResolvedType::I16 => 4,
            ResolvedType::I32 => 5,
            ResolvedType::I64 => 6,
            ResolvedType::UInt8 => 7, // UINT8
            ResolvedType::U16 => 8,
            ResolvedType::U32 => 9,
            ResolvedType::U64 => 10,
            ResolvedType::F32 => 11,
            ResolvedType::F64 => 12,
            ResolvedType::String { .. } => 13,
            ResolvedType::WChar => 14, // CHAR16
            ResolvedType::WString { .. } => 15,
            _ => return None,
        })
    }

    /// A member is advertisable byte-correctly when its type is a primitive/string, an enum or
    /// bitmask, a (non-@external) nested struct that is itself recursively advertisable, or a
    /// sequence/array whose element is one of those (single-level). Maps, unions, and nested
    /// collections are excluded (they fall back to the name-based keyed path).
    fn member_advertisable(
        &self,
        m: &ResolvedMember,
        visited: &mut std::collections::HashSet<String>,
    ) -> bool {
        // @external only guards direct struct members (Box) against type cycles.
        if m.is_external && matches!(m.resolved_type, ResolvedType::Struct(_)) {
            return false;
        }
        self.type_advertisable(&m.resolved_type, visited)
    }

    /// Recursively decide advertisability of a member/element type.
    fn type_advertisable(
        &self,
        ty: &ResolvedType,
        visited: &mut std::collections::HashSet<String>,
    ) -> bool {
        match ty {
            ResolvedType::Struct(name) => self.struct_advertisable(name, visited),
            ResolvedType::Enum(_) => true,
            ResolvedType::Sequence { element, .. } | ResolvedType::Array { element, .. } => {
                // Single-level only: element is a leaf named type or primitive/string, not
                // another collection (nested-collection ids aren't emitted yet).
                match element.as_ref() {
                    ResolvedType::Struct(name) => self.struct_advertisable(name, visited),
                    ResolvedType::Enum(_) => true,
                    other => Self::field_constant(other).is_some(),
                }
            }
            // Bitmask/Map/Union keys fall back to the name-based keyed path (deferred).
            other => Self::field_constant(other).is_some(),
        }
    }

    /// The simple generated class name for an advertisable named element (Struct/Enum), else
    /// None. Used both to gate collection elements and to emit the nested-reference spec.
    fn element_class_name(ty: &ResolvedType) -> Option<String> {
        match ty {
            ResolvedType::Struct(name) | ResolvedType::Enum(name) => {
                Some(name.rsplit("::").next().unwrap_or(name).to_string())
            }
            _ => None,
        }
    }

    /// A named struct is advertisable when it exists in the model and all of its members are
    /// recursively advertisable. `visited` guards against @external-induced type cycles.
    fn struct_advertisable(
        &self,
        name: &str,
        visited: &mut std::collections::HashSet<String>,
    ) -> bool {
        let simple = name.rsplit("::").next().unwrap_or(name);
        if !visited.insert(simple.to_string()) {
            return false;
        }
        let ok = match self.find_struct(simple).cloned() {
            Some(s) => {
                self.collect_all_members(&s).iter().all(|m| self.member_advertisable(m, visited))
            }
            None => false,
        };
        visited.remove(simple);
        ok
    }

    /// Member flag bitmask (KEY=1, OPTIONAL=2, MUST_UNDERSTAND=4, EXTERNAL=8). The FFI adds
    /// must-understand for @key automatically, so KEY alone is sufficient for keys.
    fn member_flags(m: &ResolvedMember) -> i32 {
        let mut f = 0;
        if m.is_key {
            f |= 1;
        }
        if m.is_optional {
            f |= 2;
        }
        if m.must_understand {
            f |= 4;
        }
        if m.is_external {
            f |= 8;
        }
        f
    }

    /// One `(op, name, type_const, size, flags)` tuple describing how the runtime should add
    /// this member to the type_info builder.
    fn type_info_field_spec(m: &ResolvedMember) -> String {
        let flags = Self::member_flags(m);
        match &m.resolved_type {
            ResolvedType::String { bound } => {
                format!("(\"string\", \"{}\", 0, {}, {}),", m.name, bound.unwrap_or(0), flags)
            }
            ResolvedType::WString { bound } => {
                format!("(\"wstring\", \"{}\", 0, {}, {}),", m.name, bound.unwrap_or(0), flags)
            }
            ResolvedType::Sequence { element, bound } => {
                if let Some(cls) = Self::element_class_name(element) {
                    format!(
                        "(\"seq_nested\", \"{}\", {}, {}, {}),",
                        m.name,
                        cls,
                        bound.unwrap_or(0),
                        flags
                    )
                } else {
                    let ec = Self::field_constant(element).unwrap_or(0);
                    format!("(\"seq\", \"{}\", {}, {}, {}),", m.name, ec, bound.unwrap_or(0), flags)
                }
            }
            ResolvedType::Array { element, size } => {
                if let Some(cls) = Self::element_class_name(element) {
                    format!("(\"arr_nested\", \"{}\", {}, {}, {}),", m.name, cls, size, flags)
                } else {
                    let ec = Self::field_constant(element).unwrap_or(0);
                    format!("(\"arr\", \"{}\", {}, {}, {}),", m.name, ec, size, flags)
                }
            }
            ResolvedType::Struct(name) | ResolvedType::Enum(name) => {
                // Reference the generated class object (struct/enum) so the runtime recursively
                // builds its nested type_info by content-hash.
                let cls = name.rsplit("::").next().unwrap_or(name);
                format!("(\"nested\", \"{}\", {}, 0, {}),", m.name, cls, flags)
            }
            other => {
                let c = Self::field_constant(other).unwrap_or(0);
                format!("(\"field\", \"{}\", {}, 0, {}),", m.name, c, flags)
            }
        }
    }

    fn emit_constants(&mut self) {
        if self.model.constants.is_empty() {
            return;
        }
        for c in &self.model.constants {
            let name = naming::escape_keyword(&c.name, naming::TargetLang::Python);
            let ty = Self::type_to_python(&c.resolved_type);
            self.line(&format!("{}: {} = {}", name, ty, py_const_value(&c.value)));
        }
        self.line("");
        self.line("");
    }

    fn type_to_python(ty: &ResolvedType) -> String {
        match ty {
            ResolvedType::Bool => "bool".to_string(),
            ResolvedType::U8 | ResolvedType::UInt8 | ResolvedType::I8 => "int".to_string(),
            ResolvedType::I16 | ResolvedType::U16 => "int".to_string(),
            ResolvedType::I32 | ResolvedType::U32 => "int".to_string(),
            ResolvedType::I64 | ResolvedType::U64 => "int".to_string(),
            ResolvedType::F32 | ResolvedType::F64 => "float".to_string(),
            ResolvedType::Char => "str".to_string(),
            ResolvedType::String { .. } => "str".to_string(),
            ResolvedType::Sequence { element, .. } => {
                format!("list[{}]", Self::type_to_python(element))
            }
            ResolvedType::Array { element, .. } => {
                format!("list[{}]", Self::type_to_python(element))
            }
            ResolvedType::Struct(name) => {
                format!("\"{}\"", name.rsplit("::").next().unwrap_or(name))
            }
            ResolvedType::Enum(name) => name.rsplit("::").next().unwrap_or(name).to_string(),
            ResolvedType::WChar => "str".to_string(),
            ResolvedType::WString { .. } => "str".to_string(),
            ResolvedType::Map { key, value, .. } => {
                format!("dict[{}, {}]", Self::type_to_python(key), Self::type_to_python(value))
            }
            ResolvedType::Bitmask(name) => name.rsplit("::").next().unwrap_or(name).to_string(),
        }
    }

    fn default_value(&self, ty: &ResolvedType) -> String {
        match ty {
            ResolvedType::Bool => "False".to_string(),
            ResolvedType::U8 | ResolvedType::UInt8 | ResolvedType::I8 => "0".to_string(),
            ResolvedType::I16 | ResolvedType::U16 => "0".to_string(),
            ResolvedType::I32 | ResolvedType::U32 => "0".to_string(),
            ResolvedType::I64 | ResolvedType::U64 => "0".to_string(),
            ResolvedType::F32 | ResolvedType::F64 => "0.0".to_string(),
            ResolvedType::Char => "\"\"".to_string(),
            ResolvedType::String { .. } => "\"\"".to_string(),
            ResolvedType::Sequence { .. } => "field(default_factory=list)".to_string(),
            ResolvedType::Array { element, size } => {
                let elem_default = self.default_value(element);
                format!("field(default_factory=lambda: [{}] * {})", elem_default, size)
            }
            ResolvedType::Struct(name) => {
                let cls = name.rsplit("::").next().unwrap_or(name);
                format!("field(default_factory=lambda: {}())", cls)
            }
            ResolvedType::Enum(name) => {
                let cls = name.rsplit("::").next().unwrap_or(name);
                // Use first variant as default
                if let Some(e) = self.find_enum(name) {
                    if let Some(v) = e.variants.first() {
                        return format!("{}.{}", cls, naming::to_screaming_snake(&v.name));
                    }
                }
                format!("{}(0)", cls)
            }
            ResolvedType::WChar => "\"\"".to_string(),
            ResolvedType::WString { .. } => "\"\"".to_string(),
            ResolvedType::Map { .. } => "field(default_factory=dict)".to_string(),
            ResolvedType::Bitmask(name) => {
                format!("{}(0)", name.rsplit("::").next().unwrap_or(name))
            }
        }
    }

    // ---- Serialization ----

    fn emit_serialize_cdr(&mut self, s: &ResolvedStruct) {
        let members = self.collect_all_members(s);
        self.line("def _serialize_cdr(self, xcdr2: bool = False) -> memoryview:");
        self.indent += 1;
        self.line("\"\"\"Serialize to CDR bytes with encapsulation header (zero-copy view).\"\"\"");
        self.line("w = CdrWriter(extensibility=self._extensibility, xcdr2=xcdr2)");

        match s.extensibility {
            ExtensibilityKind::Final => {
                // Final: just serialize fields
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                }
            }
            ExtensibilityKind::Appendable => {
                // Appendable: wrap with DHEADER only in XCDR2.
                // Inherited fields are flattened (single outer DHEADER bounds the
                // whole struct including parent fields) to match Rust/C# wire format.
                self.line("if w._xcdr2:");
                self.indent += 1;
                self.line("with w.dheader():");
                self.indent += 1;
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                }
                self.indent -= 1;
                self.indent -= 1;
                self.line("else:");
                self.indent += 1;
                // XCDR1: flat field order (no DHEADER)
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                }
                self.indent -= 1;
            }
            ExtensibilityKind::Mutable => {
                // XCDR2: DHEADER + EMHEADER per field (no sentinel; DHEADER bounds the struct).
                // XCDR1: PL_CDR (PID member headers) terminated by a sentinel, no DHEADER.
                self.line("if w._xcdr2:");
                self.indent += 1;
                self.line("with w.dheader():");
                self.indent += 1;
                for (i, m) in members.iter().enumerate() {
                    let member_id = m.member_id.unwrap_or(i as u32);
                    let must_understand = if m.must_understand { "True" } else { "False" };
                    self.line(&format!(
                        "with w.emheader(member_id={}, must_understand={}):",
                        member_id, must_understand
                    ));
                    self.indent += 1;
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                    self.indent -= 1;
                }
                self.indent -= 1;
                self.indent -= 1;
                self.line("else:");
                self.indent += 1;
                for (i, m) in members.iter().enumerate() {
                    let member_id = m.member_id.unwrap_or(i as u32);
                    let must_understand = if m.must_understand { "True" } else { "False" };
                    self.line(&format!(
                        "with w.member_v1(member_id={}, must_understand={}):",
                        member_id, must_understand
                    ));
                    self.indent += 1;
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                    self.indent -= 1;
                }
                self.line("w.end_mutable_struct()");
                self.indent -= 1;
            }
        }

        self.line("return w.view()");
        self.indent -= 1;
    }

    fn emit_serialize_cdr_inline(&mut self, s: &ResolvedStruct) {
        let members = self.collect_all_members(s);
        self.line("def _serialize_cdr_inline(self, w: CdrWriter) -> None:");
        self.indent += 1;
        self.line(
            "\"\"\"Serialize fields directly into an existing writer (no encap header).\"\"\"",
        );

        match s.extensibility {
            ExtensibilityKind::Final => {
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                }
            }
            ExtensibilityKind::Appendable => {
                self.line("if w._xcdr2:");
                self.indent += 1;
                self.line("with w.dheader():");
                self.indent += 1;
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                }
                self.indent -= 1;
                self.indent -= 1;
                self.line("else:");
                self.indent += 1;
                // XCDR1: flat field order (no DHEADER)
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                }
                self.indent -= 1;
            }
            ExtensibilityKind::Mutable => {
                self.line("if w._xcdr2:");
                self.indent += 1;
                self.line("with w.dheader():");
                self.indent += 1;
                for (i, m) in members.iter().enumerate() {
                    let member_id = m.member_id.unwrap_or(i as u32);
                    let must_understand = if m.must_understand { "True" } else { "False" };
                    self.line(&format!(
                        "with w.emheader(member_id={}, must_understand={}):",
                        member_id, must_understand
                    ));
                    self.indent += 1;
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                    self.indent -= 1;
                }
                self.indent -= 1;
                self.indent -= 1;
                self.line("else:");
                self.indent += 1;
                for (i, m) in members.iter().enumerate() {
                    let member_id = m.member_id.unwrap_or(i as u32);
                    let must_understand = if m.must_understand { "True" } else { "False" };
                    self.line(&format!(
                        "with w.member_v1(member_id={}, must_understand={}):",
                        member_id, must_understand
                    ));
                    self.indent += 1;
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                    self.indent -= 1;
                }
                self.line("w.end_mutable_struct()");
                self.indent -= 1;
            }
        }

        self.indent -= 1;
    }

    /// Recursively collect all members including inherited fields from base structs.
    /// Parent fields come first, then own fields (matches CDR wire order).
    fn collect_all_members(&self, s: &ResolvedStruct) -> Vec<ResolvedMember> {
        let mut all = Vec::new();
        if let Some(ref base_name) = s.base_type {
            if let Some(base) = self.find_struct(base_name) {
                all.extend(self.collect_all_members(base));
            }
        }
        all.extend(s.members.clone());
        all
    }

    /// Emit `from <module> import <Leaf>` for every `#include`d type this file
    /// references. Same-file types resolve by their in-module class; imported
    /// ones must be pulled in explicitly since each file is a flat module.
    fn emit_cross_file_imports(&mut self) {
        if self.model.imported.modules.is_empty() {
            return;
        }
        let mut refs: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
        for s in &self.model.structs {
            if let Some(base) = &s.base_type {
                refs.insert(base.clone());
            }
            for m in &s.members {
                Self::collect_referenced_types(&m.resolved_type, &mut refs);
            }
        }
        for u in &self.model.unions {
            for c in &u.cases {
                Self::collect_referenced_types(&c.member.resolved_type, &mut refs);
            }
            if let Some(dc) = &u.default_case {
                Self::collect_referenced_types(&dc.resolved_type, &mut refs);
            }
        }

        // (module, leaf) pairs, deduped and sorted for stable output.
        let mut imports: std::collections::BTreeSet<(String, String)> =
            std::collections::BTreeSet::new();
        for name in &refs {
            let leaf = name.rsplit("::").next().unwrap_or(name);
            // Skip types emitted in this same file.
            if self.is_locally_defined(leaf) {
                continue;
            }
            if let Some(module) = self
                .model
                .imported
                .modules
                .get(name)
                .or_else(|| self.model.imported.modules.get(leaf))
            {
                imports.insert((module.clone(), leaf.to_string()));
            }
        }
        for (module, leaf) in imports {
            self.line(&format!("from {} import {}", module, leaf));
        }
    }

    /// Collect struct/enum/bitmask type names referenced by `ty` (recursing
    /// through sequences, arrays, and maps) into `refs`.
    fn collect_referenced_types(ty: &ResolvedType, refs: &mut std::collections::BTreeSet<String>) {
        match ty {
            ResolvedType::Struct(name) | ResolvedType::Enum(name) | ResolvedType::Bitmask(name) => {
                refs.insert(name.clone());
            }
            ResolvedType::Sequence { element, .. } | ResolvedType::Array { element, .. } => {
                Self::collect_referenced_types(element, refs);
            }
            ResolvedType::Map { key, value, .. } => {
                Self::collect_referenced_types(key, refs);
                Self::collect_referenced_types(value, refs);
            }
            _ => {}
        }
    }

    /// True if a type with this leaf name is emitted in the current file.
    fn is_locally_defined(&self, leaf: &str) -> bool {
        self.model.structs.iter().any(|s| s.name == leaf)
            || self.model.enums.iter().any(|e| e.name == leaf)
            || self.model.bitmasks.iter().any(|b| b.name == leaf)
            || self.model.bitsets.iter().any(|b| b.name == leaf)
            || self.model.unions.iter().any(|u| u.name == leaf)
    }

    fn is_non_primitive_element(element: &ResolvedType) -> bool {
        // Per DDS-XTypes 7.4.3.5.4, sequences/arrays of non-primitive elements
        // are preceded by a DHEADER. Matches Rust `XcdrSerialize for Vec<T>`
        // where T::IS_PRIMITIVE == false.
        matches!(
            element,
            ResolvedType::String { .. }
                | ResolvedType::WString { .. }
                | ResolvedType::Struct(_)
                | ResolvedType::Sequence { .. }
                | ResolvedType::Array { .. }
                | ResolvedType::Map { .. }
        )
    }

    fn find_bitmask(&self, name: &str) -> Option<&ResolvedBitmask> {
        let simple = name.rsplit("::").next().unwrap_or(name);
        self.model
            .bitmasks
            .iter()
            .chain(self.model.imported.bitmasks.iter())
            .find(|b| b.name == simple)
    }

    /// Locate a struct by leaf name in this file or in an `#include`d file.
    fn find_struct(&self, name: &str) -> Option<&ResolvedStruct> {
        let simple = name.rsplit("::").next().unwrap_or(name);
        self.model
            .structs
            .iter()
            .chain(self.model.imported.structs.iter())
            .find(|s| s.name == simple)
    }

    /// Locate an enum by leaf name in this file or in an `#include`d file.
    fn find_enum(&self, name: &str) -> Option<&ResolvedEnum> {
        let simple = name.rsplit("::").next().unwrap_or(name);
        self.model.enums.iter().chain(self.model.imported.enums.iter()).find(|e| e.name == simple)
    }

    /// Returns (write_method, read_method) for a bitmask based on bit_bound.
    fn bitmask_methods(&self, bitmask_name: &str) -> (&'static str, &'static str) {
        let bit_bound = self.find_bitmask(bitmask_name).map(|b| b.bit_bound).unwrap_or(32);
        match bit_bound {
            0..=8 => ("write_u8", "read_u8"),
            9..=16 => ("write_u16", "read_u16"),
            17..=32 => ("write_u32", "read_u32"),
            _ => ("write_u64", "read_u64"),
        }
    }

    fn emit_write_field(&mut self, ty: &ResolvedType, accessor: &str) {
        match ty {
            ResolvedType::Bool => self.line(&format!("w.write_bool({})", accessor)),
            ResolvedType::U8 | ResolvedType::UInt8 => {
                self.line(&format!("w.write_u8({})", accessor))
            }
            ResolvedType::I8 => self.line(&format!("w.write_i8({})", accessor)),
            ResolvedType::I16 => self.line(&format!("w.write_i16({})", accessor)),
            ResolvedType::U16 => self.line(&format!("w.write_u16({})", accessor)),
            ResolvedType::I32 => self.line(&format!("w.write_i32({})", accessor)),
            ResolvedType::U32 => self.line(&format!("w.write_u32({})", accessor)),
            ResolvedType::I64 => self.line(&format!("w.write_i64({})", accessor)),
            ResolvedType::U64 => self.line(&format!("w.write_u64({})", accessor)),
            ResolvedType::F32 => self.line(&format!("w.write_f32({})", accessor)),
            ResolvedType::F64 => self.line(&format!("w.write_f64({})", accessor)),
            ResolvedType::Char => self.line(&format!("w.write_char({})", accessor)),
            ResolvedType::String { .. } => self.line(&format!("w.write_string({})", accessor)),
            ResolvedType::Enum(_) => self.line(&format!("w.write_enum(int({}))", accessor)),
            ResolvedType::Struct(_) => {
                // Nested struct: write directly to parent writer (preserves alignment)
                self.line(&format!("{}._serialize_cdr_inline(w)", accessor));
            }
            ResolvedType::Sequence { element, .. } => {
                self.line(&format!("w.write_seq_header(len({}))", accessor));
                self.line(&format!("for _item in {}:", accessor));
                self.indent += 1;
                self.emit_write_field(element, "_item");
                self.indent -= 1;
            }
            ResolvedType::Array { element, size } => {
                self.line(&format!(
                    "assert len({}) == {}, \"Array size mismatch\"",
                    accessor, size
                ));
                self.line(&format!("for _item in {}:", accessor));
                self.indent += 1;
                self.emit_write_field(element, "_item");
                self.indent -= 1;
            }
            ResolvedType::WChar => self.line(&format!("w.write_wchar({})", accessor)),
            ResolvedType::WString { .. } => self.line(&format!("w.write_wstring({})", accessor)),
            ResolvedType::Map { key, value, .. } => {
                if Self::is_non_primitive_element(key) || Self::is_non_primitive_element(value) {
                    self.line("if w._xcdr2:");
                    self.indent += 1;
                    self.line("_map_token = w.write_dheader_begin()");
                    self.line(&format!("w.write_seq_header(len({}))", accessor));
                    self.line(&format!("for _k, _v in {}.items():", accessor));
                    self.indent += 1;
                    self.emit_write_field(key, "_k");
                    self.emit_write_field(value, "_v");
                    self.indent -= 1;
                    self.line("w.write_dheader_finalize(_map_token)");
                    self.indent -= 1;
                    self.line("else:");
                    self.indent += 1;
                    self.line(&format!("w.write_seq_header(len({}))", accessor));
                    self.line(&format!("for _k, _v in {}.items():", accessor));
                    self.indent += 1;
                    self.emit_write_field(key, "_k");
                    self.emit_write_field(value, "_v");
                    self.indent -= 1;
                    self.indent -= 1;
                } else {
                    self.line(&format!("w.write_seq_header(len({}))", accessor));
                    self.line(&format!("for _k, _v in {}.items():", accessor));
                    self.indent += 1;
                    self.emit_write_field(key, "_k");
                    self.emit_write_field(value, "_v");
                    self.indent -= 1;
                }
            }
            ResolvedType::Bitmask(bitmask_name) => {
                let (write_fn, _) = self.bitmask_methods(bitmask_name);
                self.line(&format!("w.{}(int({}))", write_fn, accessor));
            }
        }
    }

    /// Emit the `if _mid == N: <read> ... else: r.skip(_mlen)` dispatch shared by the
    /// XCDR2 (EMHEADER) and XCDR1 (PL_CDR) mutable deserialize loops.
    fn emit_mutable_member_dispatch(&mut self, members: &[ResolvedMember]) {
        let mut first = true;
        for (i, m) in members.iter().enumerate() {
            let member_id = m.member_id.unwrap_or(i as u32);
            let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
            if first {
                self.line(&format!("if _mid == {}:", member_id));
                first = false;
            } else {
                self.line(&format!("elif _mid == {}:", member_id));
            }
            self.indent += 1;
            self.emit_read_field(&m.resolved_type, &field_name);
            self.indent -= 1;
        }
        self.line("else:");
        self.indent += 1;
        self.line("r.skip(_mlen)  # Unknown field");
        self.indent -= 1;
    }

    fn emit_deserialize_cdr(&mut self, s: &ResolvedStruct) {
        let members = self.collect_all_members(s);
        self.line("@classmethod");
        self.line(&format!("def _deserialize_cdr(cls, data: bytes) -> \"{}\":", s.name));
        self.indent += 1;
        self.line("\"\"\"Deserialize from CDR bytes.\"\"\"");
        self.line("r = CdrReader(data)");

        match s.extensibility {
            ExtensibilityKind::Final => {
                // Final: read fields directly
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_read_field(&m.resolved_type, &field_name);
                }
            }
            ExtensibilityKind::Appendable => {
                // Appendable: XCDR2 has a single outer DHEADER bounding all fields
                // (including inherited parent fields). Matches Rust/C# wire format.
                self.line("if r._xcdr2:");
                self.indent += 1;
                self.line("_dsize, _dstart = r.read_dheader()");
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_read_field(&m.resolved_type, &field_name);
                }
                self.line("r.read_dheader_end(_dsize, _dstart)");
                self.indent -= 1;
                self.line("else:");
                self.indent += 1;
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_read_field(&m.resolved_type, &field_name);
                }
                self.indent -= 1;
            }
            ExtensibilityKind::Mutable => {
                // Default-init every field (any member may be absent), then read member
                // headers — XCDR2 EMHEADERs bounded by a DHEADER, or XCDR1 PL_CDR headers
                // terminated by a sentinel.
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    let default = self.default_value(&m.resolved_type);
                    // Handle field(default_factory=...) case
                    if default.starts_with("field(") {
                        if default.contains("lambda:") {
                            // Extract the lambda body: strip "field(default_factory=lambda: " prefix
                            // and the single trailing ')'
                            let inner = default
                                .trim_start_matches("field(default_factory=lambda: ")
                                .strip_suffix(')')
                                .unwrap_or("");
                            self.line(&format!("{} = {}", field_name, inner));
                        } else {
                            // It's field(default_factory=TypeName)
                            let inner = default
                                .trim_start_matches("field(default_factory=")
                                .strip_suffix(')')
                                .unwrap_or("");
                            self.line(&format!("{} = {}()", field_name, inner));
                        }
                    } else {
                        self.line(&format!("{} = {}", field_name, default));
                    }
                }

                self.line("if r._xcdr2:");
                self.indent += 1;
                self.line("_dsize, _dstart = r.read_dheader()");
                self.line("_dend = _dstart + _dsize");
                self.line("while r.position < _dend:");
                self.indent += 1;
                self.line("_mid, _mlen, _mu = r.read_emheader()");
                self.emit_mutable_member_dispatch(&members);
                self.indent -= 1;
                self.line("r.read_dheader_end(_dsize, _dstart)");
                self.indent -= 1;
                self.line("else:");
                self.indent += 1;
                self.line("while True:");
                self.indent += 1;
                self.line("_kind, _mid, _mlen, _mu = r.read_parameter_header()");
                self.line("if _kind == \"sentinel\":");
                self.indent += 1;
                self.line("break");
                self.indent -= 1;
                self.emit_mutable_member_dispatch(&members);
                self.indent -= 1;
                self.indent -= 1;
            }
        }

        // Create and return instance
        let field_names: Vec<String> = members
            .iter()
            .map(|m| naming::escape_keyword(&m.name, naming::TargetLang::Python))
            .collect();
        self.line(&format!("return cls({})", field_names.join(", ")));
        self.indent -= 1;
    }

    fn emit_deserialize_cdr_inline(&mut self, s: &ResolvedStruct) {
        let members = self.collect_all_members(s);
        self.line("@classmethod");
        self.line(&format!("def _deserialize_cdr_inline(cls, r: CdrReader) -> \"{}\":", s.name));
        self.indent += 1;
        self.line("\"\"\"Deserialize from an existing CdrReader (no encapsulation header).\"\"\"");

        match s.extensibility {
            ExtensibilityKind::Final => {
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_read_field(&m.resolved_type, &field_name);
                }
            }
            ExtensibilityKind::Appendable => {
                self.line("if r._xcdr2:");
                self.indent += 1;
                self.line("_dsize, _dstart = r.read_dheader()");
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_read_field(&m.resolved_type, &field_name);
                }
                self.line("r.read_dheader_end(_dsize, _dstart)");
                self.indent -= 1;
                self.line("else:");
                self.indent += 1;
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_read_field(&m.resolved_type, &field_name);
                }
                self.indent -= 1;
            }
            ExtensibilityKind::Mutable => {
                for m in &members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    let default = self.default_value(&m.resolved_type);
                    if default.starts_with("field(") {
                        if default.contains("lambda:") {
                            let inner = default
                                .trim_start_matches("field(default_factory=lambda: ")
                                .trim_end_matches(')');
                            self.line(&format!("{} = {}", field_name, inner));
                        } else {
                            let inner = default
                                .trim_start_matches("field(default_factory=")
                                .trim_end_matches(')');
                            self.line(&format!("{} = {}()", field_name, inner));
                        }
                    } else {
                        self.line(&format!("{} = {}", field_name, default));
                    }
                }
                self.line("if r._xcdr2:");
                self.indent += 1;
                self.line("_dsize, _dstart = r.read_dheader()");
                self.line("_dend = _dstart + _dsize");
                self.line("while r.position < _dend:");
                self.indent += 1;
                self.line("_mid, _mlen, _mu = r.read_emheader()");
                self.emit_mutable_member_dispatch(&members);
                self.indent -= 1;
                self.line("r.read_dheader_end(_dsize, _dstart)");
                self.indent -= 1;
                self.line("else:");
                self.indent += 1;
                self.line("while True:");
                self.indent += 1;
                self.line("_kind, _mid, _mlen, _mu = r.read_parameter_header()");
                self.line("if _kind == \"sentinel\":");
                self.indent += 1;
                self.line("break");
                self.indent -= 1;
                self.emit_mutable_member_dispatch(&members);
                self.indent -= 1;
                self.indent -= 1;
            }
        }

        let field_names: Vec<String> = members
            .iter()
            .map(|m| naming::escape_keyword(&m.name, naming::TargetLang::Python))
            .collect();
        self.line(&format!("return cls({})", field_names.join(", ")));
        self.indent -= 1;
    }

    fn emit_read_field(&mut self, ty: &ResolvedType, name: &str) {
        match ty {
            ResolvedType::Bool => self.line(&format!("{} = r.read_bool()", name)),
            ResolvedType::U8 | ResolvedType::UInt8 => self.line(&format!("{} = r.read_u8()", name)),
            ResolvedType::I8 => self.line(&format!("{} = r.read_i8()", name)),
            ResolvedType::I16 => self.line(&format!("{} = r.read_i16()", name)),
            ResolvedType::U16 => self.line(&format!("{} = r.read_u16()", name)),
            ResolvedType::I32 => self.line(&format!("{} = r.read_i32()", name)),
            ResolvedType::U32 => self.line(&format!("{} = r.read_u32()", name)),
            ResolvedType::I64 => self.line(&format!("{} = r.read_i64()", name)),
            ResolvedType::U64 => self.line(&format!("{} = r.read_u64()", name)),
            ResolvedType::F32 => self.line(&format!("{} = r.read_f32()", name)),
            ResolvedType::F64 => self.line(&format!("{} = r.read_f64()", name)),
            ResolvedType::Char => self.line(&format!("{} = r.read_char()", name)),
            ResolvedType::String { .. } => self.line(&format!("{} = r.read_string()", name)),
            ResolvedType::Enum(enum_name) => {
                let cls = enum_name.rsplit("::").next().unwrap_or(enum_name);
                self.line(&format!("{} = {}(r.read_enum())", name, cls));
            }
            ResolvedType::Struct(struct_name) => {
                // Nested struct: read inline from the existing reader
                let cls = struct_name.rsplit("::").next().unwrap_or(struct_name);
                self.line(&format!("{} = {}._deserialize_cdr_inline(r)", name, cls));
            }
            ResolvedType::Sequence { element, .. } => {
                self.line(&format!("_{}_count = r.read_seq_header()", name));
                self.line(&format!("{} = []", name));
                self.line(&format!("for _ in range(_{}_count):", name));
                self.indent += 1;
                let item_name = format!("_{}_item", name);
                self.emit_read_field(element, &item_name);
                self.line(&format!("{}.append({})", name, item_name));
                self.indent -= 1;
            }
            ResolvedType::Array { element, size } => {
                self.line(&format!("{} = []", name));
                self.line(&format!("for _ in range({}):", size));
                self.indent += 1;
                let item_name = format!("_{}_item", name);
                self.emit_read_field(element, &item_name);
                self.line(&format!("{}.append({})", name, item_name));
                self.indent -= 1;
            }
            ResolvedType::WChar => self.line(&format!("{} = r.read_wchar()", name)),
            ResolvedType::WString { .. } => self.line(&format!("{} = r.read_wstring()", name)),
            ResolvedType::Map { key, value, .. } => {
                if Self::is_non_primitive_element(key) || Self::is_non_primitive_element(value) {
                    self.line("if r._xcdr2:");
                    self.indent += 1;
                    self.line("_map_dsize, _map_dstart = r.read_dheader()");
                    self.indent -= 1;
                }
                self.line(&format!("_{}_count = r.read_seq_header()", name));
                self.line(&format!("{} = {{}}", name));
                self.line(&format!("for _ in range(_{}_count):", name));
                self.indent += 1;
                self.emit_read_field(key, "_k");
                self.emit_read_field(value, "_v");
                self.line(&format!("{}[_k] = _v", name));
                self.indent -= 1;
                if Self::is_non_primitive_element(key) || Self::is_non_primitive_element(value) {
                    self.line("if r._xcdr2:");
                    self.indent += 1;
                    self.line("r.read_dheader_end(_map_dsize, _map_dstart)");
                    self.indent -= 1;
                }
            }
            ResolvedType::Bitmask(bitmask_name) => {
                let (_, read_fn) = self.bitmask_methods(bitmask_name);
                let cls = bitmask_name.rsplit("::").next().unwrap_or(bitmask_name);
                self.line(&format!("{} = {}(r.{}())", name, cls, read_fn));
            }
        }
    }

    // ---- Helpers ----

    fn line(&mut self, s: &str) {
        if s.is_empty() {
            self.out.push('\n');
        } else {
            for _ in 0..self.indent {
                self.out.push_str("    ");
            }
            self.out.push_str(s);
            self.out.push('\n');
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_idl;
    use crate::resolver::resolve;

    /// The no-arg convenience `_serialize_cdr()` must default to XCDR1 (spec effective
    /// write default), mirroring the core `int2dds_default_data_representation()`.
    #[test]
    fn test_serialize_cdr_convenience_defaults_to_xcdr1() {
        let defs = parse_idl(
            r#"
            @appendable
            struct ShapeType {
                @key long id;
                long value;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "ShapeType.idl", &PythonOptions::new());
        assert!(
            code.contains("def _serialize_cdr(self, xcdr2: bool = False) -> memoryview:"),
            "no-arg _serialize_cdr must default to XCDR1 (False): {}",
            code
        );
        assert!(!code.contains("xcdr2: bool = True"), "no XCDR2-default convenience: {}", code);
    }

    #[test]
    fn test_keyword_escaping_struct_fields() {
        let defs = parse_idl(
            r#"
            struct KeywordTest {
                long type;
                string class;
                string list;
                long match;
                long lambda;
                string tuple;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "KeywordTest.idl", &PythonOptions::new());

        // Field declarations
        assert!(code.contains("type_: int"), "type should be escaped: {}", code);
        assert!(code.contains("class_: str"), "class should be escaped: {}", code);
        assert!(code.contains("list_: str"), "list should be escaped: {}", code);
        assert!(code.contains("match_: int"), "match should be escaped: {}", code);
        assert!(code.contains("lambda_: int"), "lambda should be escaped: {}", code);
        assert!(code.contains("tuple_: str"), "tuple should be escaped: {}", code);
    }

    #[test]
    fn test_type_info_metadata_for_flat_struct() {
        let defs = parse_idl(
            r#"
            @appendable
            struct ShapeType {
                @key string<128> color;
                long x;
                sequence<uint8> payload;
                octet raw;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "ShapeType.idl", &PythonOptions::new());

        assert!(code.contains("_dds_type_info_fields: ClassVar[list] = ["), "{}", code);
        // @key string<128> -> ("string", name, 0, bound=128, KEY=1)
        assert!(code.contains(r#"("string", "color", 0, 128, 1),"#), "{}", code);
        // long -> INT2DDS_FIELD_INT32 = 5
        assert!(code.contains(r#"("field", "x", 5, 0, 0),"#), "{}", code);
        // sequence<uint8> -> ("seq", name, INT2DDS_FIELD_UINT8 = 7, bound=0, 0)
        assert!(code.contains(r#"("seq", "payload", 7, 0, 0),"#), "{}", code);
        // octet -> INT2DDS_FIELD_BYTE = 1 (distinct from uint8's 7)
        assert!(code.contains(r#"("field", "raw", 1, 0, 0),"#), "{}", code);
    }

    #[test]
    fn test_type_info_metadata_omitted_for_unsupported_members() {
        let defs = parse_idl(
            r#"
            struct Widget { map<long, long> m; long x; };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Widget.idl", &PythonOptions::new());
        // Widget has a map member -> not advertisable -> advertisement metadata is omitted
        // so it falls back to name-based matching.
        assert!(!code.contains("_dds_type_info_fields"), "{}", code);
    }

    #[test]
    fn test_type_info_metadata_for_enum_member() {
        let defs = parse_idl(
            r#"
            enum Color { RED, GREEN, BLUE };
            struct Widget { @key Color c; long x; };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Widget.idl", &PythonOptions::new());
        // Enum member is now advertisable: referenced as a nested class, with the enum's own
        // descriptor emitted (canonical PascalCase literal names, bit_bound 32).
        assert!(code.contains(r#"("nested", "c", Color, 0, 1),"#), "{}", code);
        assert!(
            code.contains(r#"Color._dds_enum_info = (32, (("Red", 0, False), ("Green", 1, False), ("Blue", 2, False),))"#),
            "{}",
            code
        );
    }

    #[test]
    fn test_type_info_metadata_for_collection_of_nested() {
        let defs = parse_idl(
            r#"
            @final struct Point { long x; long y; };
            struct Widget {
                sequence<Point> path;
                Point grid[3];
                long x;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Widget.idl", &PythonOptions::new());
        assert!(code.contains(r#"("seq_nested", "path", Point, 0, 0),"#), "{}", code);
        assert!(code.contains(r#"("arr_nested", "grid", Point, 3, 0),"#), "{}", code);
    }

    #[test]
    fn test_type_info_metadata_for_nested_struct_key() {
        let defs = parse_idl(
            r#"
            @final
            struct NestedKey {
                long a;
                long b;
            };
            @final
            struct Composite {
                @key NestedKey loc;
                long value;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Composite.idl", &PythonOptions::new());

        // The nested @key member references the nested generated class directly (KEY flag=1).
        assert!(code.contains(r#"("nested", "loc", NestedKey, 0, 1),"#), "{}", code);
        assert!(code.contains(r#"("field", "value", 5, 0, 0),"#), "{}", code);
        // The nested struct still emits its own flat metadata (recursion source of truth).
        assert!(code.contains(r#"("field", "a", 5, 0, 0),"#), "{}", code);
        assert!(code.contains(r#"("field", "b", 5, 0, 0),"#), "{}", code);
    }

    #[test]
    fn test_keyword_escaping_in_serialize() {
        let defs = parse_idl(
            r#"
            struct SerTest {
                long type;
                string class;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "SerTest.idl", &PythonOptions::new());

        // Serialization should use escaped accessor: self.type_, self.class_
        assert!(code.contains("self.type_"), "serialize should use escaped name: {}", code);
        assert!(code.contains("self.class_"), "serialize should use escaped name: {}", code);
        // Deserialization return should use escaped names
        assert!(
            code.contains("return cls(type_, class_)"),
            "return should use escaped names: {}",
            code
        );
    }

    #[test]
    fn test_keyword_escaping_in_key_serialize() {
        let defs = parse_idl(
            r#"
            struct KeyTest {
                @key long type;
                string class;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "KeyTest.idl", &PythonOptions::new());

        // Key serialization should also use escaped name
        assert!(code.contains("self.type_"), "key serialize should use escaped name: {}", code);
    }

    #[test]
    fn test_non_keyword_not_escaped_python() {
        let defs = parse_idl(
            r#"
            struct Normal {
                long data;
                string sensor_id;
                long type_name;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Normal.idl", &PythonOptions::new());

        assert!(code.contains("data: int"));
        assert!(code.contains("sensor_id: str"));
        assert!(code.contains("type_name: int"));
        // Should NOT have trailing underscore
        assert!(!code.contains("data_:"));
        assert!(!code.contains("sensor_id_:"));
    }
}
