/// Python code generation backend.
///
/// Generates Python dataclasses with CDR serialization methods
/// that use the int2dds Python CDR library.
use crate::naming;
use crate::types::*;

/// Options for Python code generation.
#[derive(Debug, Clone, Default)]
pub struct PythonOptions {
    /// Module path for the int2dds package (default: "int2dds")
    pub int2dds_module: String,
}

impl PythonOptions {
    pub fn new() -> Self {
        Self { int2dds_module: "int2dds".to_string() }
    }
}

/// Generate Python code from the IDL model.
pub fn generate(model: &IdlModel, idl_filename: &str, opts: &PythonOptions) -> String {
    let mut gen = PyGen { out: String::new(), opts, model, indent: 0 };
    gen.emit_file(idl_filename);
    gen.out
}

struct PyGen<'a> {
    out: String,
    opts: &'a PythonOptions,
    model: &'a IdlModel,
    indent: usize,
}

impl<'a> PyGen<'a> {
    fn emit_file(&mut self, idl_filename: &str) {
        let module_name = &self.opts.int2dds_module;

        // File header
        self.line(&format!(
            "\"\"\"Auto-generated by int2dds-idl from {}\n\nDO NOT EDIT - changes will be overwritten\n\"\"\"",
            idl_filename
        ));
        self.line("");
        self.line("from __future__ import annotations");
        self.line("");
        self.line("from dataclasses import dataclass, field");
        self.line("from enum import IntEnum, IntFlag");
        self.line("from typing import ClassVar");
        self.line("");
        self.line(&format!("from {}.cdr import CdrReader, CdrWriter, Extensibility", module_name));
        self.line(&format!("from {}.cdr.writer import CdrKeyWriter", module_name));
        self.line("");
        self.line("");

        // Enums first (may be referenced by structs)
        for e in &self.model.enums {
            self.emit_enum(e);
            self.line("");
            self.line("");
        }

        // Bitmasks
        for b in &self.model.bitmasks {
            self.emit_bitmask(b);
            self.line("");
            self.line("");
        }

        // Structs
        for s in &self.model.structs {
            self.emit_struct(s);
            self.line("");
            self.line("");
        }
    }

    // ---- Enum ----

    fn emit_enum(&mut self, e: &ResolvedEnum) {
        self.line(&format!("class {}(IntEnum):", e.name));
        self.indent += 1;
        self.line(&format!("\"\"\"IDL enum: {}\"\"\"", e.qualified_name));
        self.line("");
        for v in &e.variants {
            let variant_name = naming::to_screaming_snake(&v.name);
            self.line(&format!("{} = {}", variant_name, v.value));
        }
        self.indent -= 1;
    }

    // ---- Bitmask ----

    fn emit_bitmask(&mut self, b: &ResolvedBitmask) {
        self.line(&format!("class {}(IntFlag):", b.name));
        self.indent += 1;
        self.line(&format!(
            "\"\"\"IDL bitmask: {} (bit_bound={})\"\"\"",
            b.qualified_name, b.bit_bound
        ));
        self.line("");
        for flag in &b.flags {
            let flag_name = naming::to_screaming_snake(&flag.name);
            self.line(&format!("{} = 1 << {}", flag_name, flag.position));
        }
        if b.flags.is_empty() {
            self.line("pass");
        }
        self.indent -= 1;
    }

    // ---- Struct ----

    fn emit_struct(&mut self, s: &ResolvedStruct) {
        let ext_name = match s.extensibility {
            ExtensibilityKind::Final => "FINAL",
            ExtensibilityKind::Appendable => "APPENDABLE",
            ExtensibilityKind::Mutable => "MUTABLE",
        };

        let has_key = s.members.iter().any(|m| m.is_key);

        // @dataclass decorator
        self.line("@dataclass");
        self.line(&format!("class {}:", s.name));
        self.indent += 1;

        // Docstring
        self.line(&format!(
            "\"\"\"IDL struct: {} (Extensibility: {})\"\"\"",
            s.qualified_name, ext_name
        ));
        self.line("");

        // Type metadata as class variables
        self.line(&format!("_dds_type_name: ClassVar[str] = \"{}\"", s.qualified_name));
        self.line(&format!("_extensibility: ClassVar[Extensibility] = Extensibility.{}", ext_name));
        self.line(&format!(
            "_has_key: ClassVar[bool] = {}",
            if has_key { "True" } else { "False" }
        ));
        self.line("");

        // Fields
        for m in &s.members {
            let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
            let py_type = self.type_to_python(&m.resolved_type);
            let default = self.default_value(&m.resolved_type);
            self.line(&format!("{}: {} = {}", field_name, py_type, default));
        }
        self.line("");

        // _serialize_cdr method
        self.emit_serialize_cdr(s);
        self.line("");

        // _serialize_cdr_inline method (for nested struct serialization)
        self.emit_serialize_cdr_inline(s);
        self.line("");

        // _deserialize_cdr class method
        self.emit_deserialize_cdr(s);
        self.line("");

        // _deserialize_cdr_inline class method (for nested struct deserialization)
        self.emit_deserialize_cdr_inline(s);
        self.line("");

        // _serialize_key method
        self.emit_serialize_key(s);

        self.indent -= 1;
    }

    fn type_to_python(&self, ty: &ResolvedType) -> String {
        match ty {
            ResolvedType::Bool => "bool".to_string(),
            ResolvedType::U8 | ResolvedType::I8 => "int".to_string(),
            ResolvedType::I16 | ResolvedType::U16 => "int".to_string(),
            ResolvedType::I32 | ResolvedType::U32 => "int".to_string(),
            ResolvedType::I64 | ResolvedType::U64 => "int".to_string(),
            ResolvedType::F32 | ResolvedType::F64 => "float".to_string(),
            ResolvedType::Char => "str".to_string(),
            ResolvedType::String { .. } => "str".to_string(),
            ResolvedType::Sequence { element, .. } => {
                format!("list[{}]", self.type_to_python(element))
            }
            ResolvedType::Array { element, .. } => {
                format!("list[{}]", self.type_to_python(element))
            }
            ResolvedType::Struct(name) => format!("\"{}\"", name),
            ResolvedType::Enum(name) => name.clone(),
            ResolvedType::WChar => "str".to_string(),
            ResolvedType::WString { .. } => "str".to_string(),
            ResolvedType::Map { key, value, .. } => {
                format!("dict[{}, {}]", self.type_to_python(key), self.type_to_python(value))
            }
            ResolvedType::Bitmask(name) => name.clone(),
        }
    }

    fn default_value(&self, ty: &ResolvedType) -> String {
        match ty {
            ResolvedType::Bool => "False".to_string(),
            ResolvedType::U8 | ResolvedType::I8 => "0".to_string(),
            ResolvedType::I16 | ResolvedType::U16 => "0".to_string(),
            ResolvedType::I32 | ResolvedType::U32 => "0".to_string(),
            ResolvedType::I64 | ResolvedType::U64 => "0".to_string(),
            ResolvedType::F32 | ResolvedType::F64 => "0.0".to_string(),
            ResolvedType::Char => "\"\"".to_string(),
            ResolvedType::String { .. } => "\"\"".to_string(),
            ResolvedType::Sequence { .. } => "field(default_factory=list)".to_string(),
            ResolvedType::Array { element, size } => {
                let elem_default = self.default_value(element);
                format!("field(default_factory=lambda: [{}] * {})", elem_default, size)
            }
            ResolvedType::Struct(name) => format!("field(default_factory={})", name),
            ResolvedType::Enum(name) => {
                // Use first variant as default
                if let Some(e) = self.model.enums.iter().find(|e| &e.name == name) {
                    if let Some(v) = e.variants.first() {
                        return format!("{}.{}", name, naming::to_screaming_snake(&v.name));
                    }
                }
                format!("{}(0)", name)
            }
            ResolvedType::WChar => "\"\"".to_string(),
            ResolvedType::WString { .. } => "\"\"".to_string(),
            ResolvedType::Map { .. } => "field(default_factory=dict)".to_string(),
            ResolvedType::Bitmask(name) => format!("{}(0)", name),
        }
    }

    // ---- Serialization ----

    fn emit_serialize_cdr(&mut self, s: &ResolvedStruct) {
        self.line("def _serialize_cdr(self, xcdr2: bool = True) -> bytes:");
        self.indent += 1;
        self.line("\"\"\"Serialize to CDR bytes with encapsulation header.\"\"\"");
        self.line("w = CdrWriter(extensibility=self._extensibility, xcdr2=xcdr2)");

        match s.extensibility {
            ExtensibilityKind::Final => {
                // Final: just serialize fields
                for m in &s.members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                }
            }
            ExtensibilityKind::Appendable => {
                // Appendable: wrap with DHEADER only in XCDR2
                self.line("if w._xcdr2:");
                self.indent += 1;
                self.line("with w.dheader():");
                self.indent += 1;
                for m in &s.members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                }
                self.indent -= 1;
                self.indent -= 1;
                self.line("else:");
                self.indent += 1;
                for m in &s.members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                }
                self.indent -= 1;
            }
            ExtensibilityKind::Mutable => {
                // Mutable: DHEADER + EMHEADER per field + sentinel
                self.line("with w.dheader():");
                self.indent += 1;
                for (i, m) in s.members.iter().enumerate() {
                    let member_id = m.member_id.unwrap_or(i as u32);
                    let must_understand = if m.must_understand { "True" } else { "False" };
                    self.line(&format!(
                        "with w.emheader(member_id={}, must_understand={}):",
                        member_id, must_understand
                    ));
                    self.indent += 1;
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                    self.indent -= 1;
                }
                self.line("w.write_sentinel()");
                self.indent -= 1;
            }
        }

        self.line("return w.to_bytes()");
        self.indent -= 1;
    }

    fn emit_serialize_cdr_inline(&mut self, s: &ResolvedStruct) {
        self.line("def _serialize_cdr_inline(self, w: CdrWriter) -> None:");
        self.indent += 1;
        self.line("\"\"\"Serialize fields directly into an existing writer (no encap header).\"\"\"");

        match s.extensibility {
            ExtensibilityKind::Final => {
                for m in &s.members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                }
            }
            ExtensibilityKind::Appendable => {
                self.line("if w._xcdr2:");
                self.indent += 1;
                self.line("with w.dheader():");
                self.indent += 1;
                for m in &s.members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                }
                self.indent -= 1;
                self.indent -= 1;
                self.line("else:");
                self.indent += 1;
                for m in &s.members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                }
                self.indent -= 1;
            }
            ExtensibilityKind::Mutable => {
                self.line("with w.dheader():");
                self.indent += 1;
                for (i, m) in s.members.iter().enumerate() {
                    let member_id = m.member_id.unwrap_or(i as u32);
                    let must_understand = if m.must_understand { "True" } else { "False" };
                    self.line(&format!(
                        "with w.emheader(member_id={}, must_understand={}):",
                        member_id, must_understand
                    ));
                    self.indent += 1;
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_write_field(&m.resolved_type, &format!("self.{}", field_name));
                    self.indent -= 1;
                }
                self.line("w.write_sentinel()");
                self.indent -= 1;
            }
        }

        self.indent -= 1;
    }

    fn is_non_primitive_element(element: &ResolvedType) -> bool {
        // Only String needs per-sequence DHEADER in XCDR2.
        // Enum: fixed-size (i32), no DHEADER needed.
        // Struct: APPENDABLE structs already have per-element DHEADER.
        matches!(element, ResolvedType::String { .. })
    }

    fn emit_write_field(&mut self, ty: &ResolvedType, accessor: &str) {
        match ty {
            ResolvedType::Bool => self.line(&format!("w.write_bool({})", accessor)),
            ResolvedType::U8 => self.line(&format!("w.write_u8({})", accessor)),
            ResolvedType::I8 => self.line(&format!("w.write_i8({})", accessor)),
            ResolvedType::I16 => self.line(&format!("w.write_i16({})", accessor)),
            ResolvedType::U16 => self.line(&format!("w.write_u16({})", accessor)),
            ResolvedType::I32 => self.line(&format!("w.write_i32({})", accessor)),
            ResolvedType::U32 => self.line(&format!("w.write_u32({})", accessor)),
            ResolvedType::I64 => self.line(&format!("w.write_i64({})", accessor)),
            ResolvedType::U64 => self.line(&format!("w.write_u64({})", accessor)),
            ResolvedType::F32 => self.line(&format!("w.write_f32({})", accessor)),
            ResolvedType::F64 => self.line(&format!("w.write_f64({})", accessor)),
            ResolvedType::Char => self.line(&format!("w.write_char({})", accessor)),
            ResolvedType::String { .. } => self.line(&format!("w.write_string({})", accessor)),
            ResolvedType::Enum(_) => self.line(&format!("w.write_enum(int({}))", accessor)),
            ResolvedType::Struct(_) => {
                // Nested struct: write directly to parent writer (preserves alignment)
                self.line(&format!("{}._serialize_cdr_inline(w)", accessor));
            }
            ResolvedType::Sequence { element, .. } => {
                if Self::is_non_primitive_element(element) {
                    // XCDR2: non-primitive sequences need DHEADER
                    self.line("if w._xcdr2:");
                    self.indent += 1;
                    self.line("_seq_token = w.write_dheader_begin()");
                    self.line(&format!("w.write_seq_header(len({}))", accessor));
                    self.line(&format!("for _item in {}:", accessor));
                    self.indent += 1;
                    self.emit_write_field(element, "_item");
                    self.indent -= 1;
                    self.line("w.write_dheader_finalize(_seq_token)");
                    self.indent -= 1;
                    self.line("else:");
                    self.indent += 1;
                    self.line(&format!("w.write_seq_header(len({}))", accessor));
                    self.line(&format!("for _item in {}:", accessor));
                    self.indent += 1;
                    self.emit_write_field(element, "_item");
                    self.indent -= 1;
                    self.indent -= 1;
                } else {
                    self.line(&format!("w.write_seq_header(len({}))", accessor));
                    self.line(&format!("for _item in {}:", accessor));
                    self.indent += 1;
                    self.emit_write_field(element, "_item");
                    self.indent -= 1;
                }
            }
            ResolvedType::Array { element, size } => {
                self.line(&format!(
                    "assert len({}) == {}, \"Array size mismatch\"",
                    accessor, size
                ));
                self.line(&format!("for _item in {}:", accessor));
                self.indent += 1;
                self.emit_write_field(element, "_item");
                self.indent -= 1;
            }
            ResolvedType::WChar => self.line(&format!("w.write_wchar({})", accessor)),
            ResolvedType::WString { .. } => self.line(&format!("w.write_wstring({})", accessor)),
            ResolvedType::Map { key, value, .. } => {
                self.line(&format!("w.write_seq_header(len({}))", accessor));
                self.line(&format!("for _k, _v in {}.items():", accessor));
                self.indent += 1;
                self.emit_write_field(key, "_k");
                self.emit_write_field(value, "_v");
                self.indent -= 1;
            }
            ResolvedType::Bitmask(_) => self.line(&format!("w.write_u32(int({}))", accessor)),
        }
    }

    fn emit_deserialize_cdr(&mut self, s: &ResolvedStruct) {
        self.line("@classmethod");
        self.line(&format!("def _deserialize_cdr(cls, data: bytes) -> \"{}\":", s.name));
        self.indent += 1;
        self.line("\"\"\"Deserialize from CDR bytes.\"\"\"");
        self.line("r = CdrReader(data)");

        match s.extensibility {
            ExtensibilityKind::Final => {
                // Final: read fields directly
                for m in &s.members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_read_field(&m.resolved_type, &field_name);
                }
            }
            ExtensibilityKind::Appendable => {
                // Appendable: read DHEADER only in XCDR2
                self.line("if r._xcdr2:");
                self.indent += 1;
                self.line("_dsize, _dstart = r.read_dheader()");
                self.indent -= 1;
                for m in &s.members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_read_field(&m.resolved_type, &field_name);
                }
                self.line("if r._xcdr2:");
                self.indent += 1;
                self.line("r.read_dheader_end(_dsize, _dstart)");
                self.indent -= 1;
            }
            ExtensibilityKind::Mutable => {
                // Mutable: read DHEADER, then loop over EMHEADERs
                self.line("_dsize, _dstart = r.read_dheader()");

                // Initialize all fields with defaults
                for m in &s.members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    let default = self.default_value(&m.resolved_type);
                    // Handle field(default_factory=...) case
                    if default.starts_with("field(") {
                        if default.contains("lambda:") {
                            // Extract the lambda expression
                            let inner = default
                                .trim_start_matches("field(default_factory=lambda: ")
                                .trim_end_matches(')');
                            self.line(&format!("{} = {}", field_name, inner));
                        } else {
                            // It's field(default_factory=TypeName)
                            let inner = default
                                .trim_start_matches("field(default_factory=")
                                .trim_end_matches(')');
                            self.line(&format!("{} = {}()", field_name, inner));
                        }
                    } else {
                        self.line(&format!("{} = {}", field_name, default));
                    }
                }

                self.line("while not r.is_sentinel():");
                self.indent += 1;
                self.line("_mid, _mlen, _mu = r.read_emheader()");

                // Switch on member_id
                let mut first = true;
                for (i, m) in s.members.iter().enumerate() {
                    let member_id = m.member_id.unwrap_or(i as u32);
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    if first {
                        self.line(&format!("if _mid == {}:", member_id));
                        first = false;
                    } else {
                        self.line(&format!("elif _mid == {}:", member_id));
                    }
                    self.indent += 1;
                    self.emit_read_field(&m.resolved_type, &field_name);
                    self.indent -= 1;
                }
                self.line("else:");
                self.indent += 1;
                self.line("r.skip(_mlen)  # Unknown field");
                self.indent -= 1;

                self.indent -= 1;
                self.line("r.skip_sentinel()");
                self.line("r.read_dheader_end(_dsize, _dstart)");
            }
        }

        // Create and return instance
        let field_names: Vec<String> = s
            .members
            .iter()
            .map(|m| naming::escape_keyword(&m.name, naming::TargetLang::Python))
            .collect();
        self.line(&format!("return cls({})", field_names.join(", ")));
        self.indent -= 1;
    }

    fn emit_deserialize_cdr_inline(&mut self, s: &ResolvedStruct) {
        self.line("@classmethod");
        self.line(&format!("def _deserialize_cdr_inline(cls, r: CdrReader) -> \"{}\":", s.name));
        self.indent += 1;
        self.line("\"\"\"Deserialize from an existing CdrReader (no encapsulation header).\"\"\"");

        match s.extensibility {
            ExtensibilityKind::Final => {
                for m in &s.members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_read_field(&m.resolved_type, &field_name);
                }
            }
            ExtensibilityKind::Appendable => {
                self.line("if r._xcdr2:");
                self.indent += 1;
                self.line("_dsize, _dstart = r.read_dheader()");
                self.indent -= 1;
                for m in &s.members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    self.emit_read_field(&m.resolved_type, &field_name);
                }
                self.line("if r._xcdr2:");
                self.indent += 1;
                self.line("r.read_dheader_end(_dsize, _dstart)");
                self.indent -= 1;
            }
            ExtensibilityKind::Mutable => {
                self.line("_dsize, _dstart = r.read_dheader()");
                for m in &s.members {
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    let default = self.default_value(&m.resolved_type);
                    if default.starts_with("field(") {
                        if default.contains("lambda:") {
                            let inner = default
                                .trim_start_matches("field(default_factory=lambda: ")
                                .trim_end_matches(')');
                            self.line(&format!("{} = {}", field_name, inner));
                        } else {
                            let inner = default
                                .trim_start_matches("field(default_factory=")
                                .trim_end_matches(')');
                            self.line(&format!("{} = {}()", field_name, inner));
                        }
                    } else {
                        self.line(&format!("{} = {}", field_name, default));
                    }
                }
                self.line("while not r.is_sentinel():");
                self.indent += 1;
                self.line("_mid, _mlen, _mu = r.read_emheader()");
                let mut first = true;
                for (i, m) in s.members.iter().enumerate() {
                    let member_id = m.member_id.unwrap_or(i as u32);
                    let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                    if first {
                        self.line(&format!("if _mid == {}:", member_id));
                        first = false;
                    } else {
                        self.line(&format!("elif _mid == {}:", member_id));
                    }
                    self.indent += 1;
                    self.emit_read_field(&m.resolved_type, &field_name);
                    self.indent -= 1;
                }
                self.line("else:");
                self.indent += 1;
                self.line("r.skip(_mlen)  # Unknown field");
                self.indent -= 1;
                self.indent -= 1;
                self.line("r.skip_sentinel()");
                self.line("r.read_dheader_end(_dsize, _dstart)");
            }
        }

        let field_names: Vec<String> = s
            .members
            .iter()
            .map(|m| naming::escape_keyword(&m.name, naming::TargetLang::Python))
            .collect();
        self.line(&format!("return cls({})", field_names.join(", ")));
        self.indent -= 1;
    }

    fn emit_read_field(&mut self, ty: &ResolvedType, name: &str) {
        match ty {
            ResolvedType::Bool => self.line(&format!("{} = r.read_bool()", name)),
            ResolvedType::U8 => self.line(&format!("{} = r.read_u8()", name)),
            ResolvedType::I8 => self.line(&format!("{} = r.read_i8()", name)),
            ResolvedType::I16 => self.line(&format!("{} = r.read_i16()", name)),
            ResolvedType::U16 => self.line(&format!("{} = r.read_u16()", name)),
            ResolvedType::I32 => self.line(&format!("{} = r.read_i32()", name)),
            ResolvedType::U32 => self.line(&format!("{} = r.read_u32()", name)),
            ResolvedType::I64 => self.line(&format!("{} = r.read_i64()", name)),
            ResolvedType::U64 => self.line(&format!("{} = r.read_u64()", name)),
            ResolvedType::F32 => self.line(&format!("{} = r.read_f32()", name)),
            ResolvedType::F64 => self.line(&format!("{} = r.read_f64()", name)),
            ResolvedType::Char => self.line(&format!("{} = r.read_char()", name)),
            ResolvedType::String { .. } => self.line(&format!("{} = r.read_string()", name)),
            ResolvedType::Enum(enum_name) => {
                self.line(&format!("{} = {}(r.read_enum())", name, enum_name));
            }
            ResolvedType::Struct(struct_name) => {
                // Nested struct: read inline from the existing reader
                self.line(&format!("{} = {}._deserialize_cdr_inline(r)", name, struct_name));
            }
            ResolvedType::Sequence { element, .. } => {
                if Self::is_non_primitive_element(element) {
                    // XCDR2: non-primitive sequences have DHEADER
                    self.line("if r._xcdr2:");
                    self.indent += 1;
                    self.line("_seq_dsize, _seq_dstart = r.read_dheader()");
                    self.indent -= 1;
                }
                self.line(&format!("_{}_count = r.read_seq_header()", name));
                self.line(&format!("{} = []", name));
                self.line(&format!("for _ in range(_{}_count):", name));
                self.indent += 1;
                let item_name = format!("_{}_item", name);
                self.emit_read_field(element, &item_name);
                self.line(&format!("{}.append({})", name, item_name));
                self.indent -= 1;
                if Self::is_non_primitive_element(element) {
                    self.line("if r._xcdr2:");
                    self.indent += 1;
                    self.line("r.read_dheader_end(_seq_dsize, _seq_dstart)");
                    self.indent -= 1;
                }
            }
            ResolvedType::Array { element, size } => {
                self.line(&format!("{} = []", name));
                self.line(&format!("for _ in range({}):", size));
                self.indent += 1;
                let item_name = format!("_{}_item", name);
                self.emit_read_field(element, &item_name);
                self.line(&format!("{}.append({})", name, item_name));
                self.indent -= 1;
            }
            ResolvedType::WChar => self.line(&format!("{} = r.read_wchar()", name)),
            ResolvedType::WString { .. } => self.line(&format!("{} = r.read_wstring()", name)),
            ResolvedType::Map { key, value, .. } => {
                self.line(&format!("_{}_count = r.read_seq_header()", name));
                self.line(&format!("{} = {{}}", name));
                self.line(&format!("for _ in range(_{}_count):", name));
                self.indent += 1;
                self.emit_read_field(key, "_k");
                self.emit_read_field(value, "_v");
                self.line(&format!("{}[_k] = _v", name));
                self.indent -= 1;
            }
            ResolvedType::Bitmask(bitmask_name) => {
                self.line(&format!("{} = {}(r.read_u32())", name, bitmask_name));
            }
        }
    }

    fn emit_serialize_key(&mut self, s: &ResolvedStruct) {
        self.line("def _serialize_key(self) -> bytes:");
        self.indent += 1;
        self.line("\"\"\"Serialize key fields only (big-endian, no encapsulation).\"\"\"");

        let key_fields: Vec<&ResolvedMember> = s.members.iter().filter(|m| m.is_key).collect();

        if key_fields.is_empty() {
            self.line("return b\"\"");
        } else {
            self.line("w = CdrKeyWriter()");
            for m in key_fields {
                let field_name = naming::escape_keyword(&m.name, naming::TargetLang::Python);
                self.emit_write_key_field(&m.resolved_type, &format!("self.{}", field_name));
            }
            self.line("return w.to_bytes()");
        }

        self.indent -= 1;
    }

    fn emit_write_key_field(&mut self, ty: &ResolvedType, accessor: &str) {
        match ty {
            ResolvedType::Bool => self.line(&format!("w.write_bool({})", accessor)),
            ResolvedType::U8 => self.line(&format!("w.write_u8({})", accessor)),
            ResolvedType::I8 => self.line(&format!("w.write_i8({})", accessor)),
            ResolvedType::I16 => self.line(&format!("w.write_i16({})", accessor)),
            ResolvedType::U16 => self.line(&format!("w.write_u16({})", accessor)),
            ResolvedType::I32 => self.line(&format!("w.write_i32({})", accessor)),
            ResolvedType::U32 => self.line(&format!("w.write_u32({})", accessor)),
            ResolvedType::I64 => self.line(&format!("w.write_i64({})", accessor)),
            ResolvedType::U64 => self.line(&format!("w.write_u64({})", accessor)),
            ResolvedType::F32 => self.line(&format!("w.write_f32({})", accessor)),
            ResolvedType::F64 => self.line(&format!("w.write_f64({})", accessor)),
            ResolvedType::String { .. } => self.line(&format!("w.write_string({})", accessor)),
            ResolvedType::Enum(_) => self.line(&format!("w.write_enum(int({}))", accessor)),
            ResolvedType::Char => self.line(&format!("w.write_char({})", accessor)),
            ResolvedType::WChar => self.line(&format!("w.write_wchar({})", accessor)),
            ResolvedType::WString { .. } => self.line(&format!("w.write_wstring({})", accessor)),
            ResolvedType::Bitmask(_) => self.line(&format!("w.write_u32(int({}))", accessor)),
            _ => {
                // Complex types (Struct, Sequence, Array, Map) in keys are not common
                self.line(&format!("# TODO: Complex key field {}", accessor));
            }
        }
    }

    // ---- Helpers ----

    fn line(&mut self, s: &str) {
        if s.is_empty() {
            self.out.push('\n');
        } else {
            for _ in 0..self.indent {
                self.out.push_str("    ");
            }
            self.out.push_str(s);
            self.out.push('\n');
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_idl;
    use crate::resolver::resolve;

    #[test]
    fn test_keyword_escaping_struct_fields() {
        let defs = parse_idl(
            r#"
            struct KeywordTest {
                long type;
                string class;
                string list;
                long match;
                long lambda;
                string tuple;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "KeywordTest.idl", &PythonOptions::new());

        // Field declarations
        assert!(code.contains("type_: int"), "type should be escaped: {}", code);
        assert!(code.contains("class_: str"), "class should be escaped: {}", code);
        assert!(code.contains("list_: str"), "list should be escaped: {}", code);
        assert!(code.contains("match_: int"), "match should be escaped: {}", code);
        assert!(code.contains("lambda_: int"), "lambda should be escaped: {}", code);
        assert!(code.contains("tuple_: str"), "tuple should be escaped: {}", code);
    }

    #[test]
    fn test_keyword_escaping_in_serialize() {
        let defs = parse_idl(
            r#"
            struct SerTest {
                long type;
                string class;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "SerTest.idl", &PythonOptions::new());

        // Serialization should use escaped accessor: self.type_, self.class_
        assert!(code.contains("self.type_"), "serialize should use escaped name: {}", code);
        assert!(code.contains("self.class_"), "serialize should use escaped name: {}", code);
        // Deserialization return should use escaped names
        assert!(code.contains("return cls(type_, class_)"), "return should use escaped names: {}", code);
    }

    #[test]
    fn test_keyword_escaping_in_key_serialize() {
        let defs = parse_idl(
            r#"
            struct KeyTest {
                @key long type;
                string class;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "KeyTest.idl", &PythonOptions::new());

        // Key serialization should also use escaped name
        assert!(code.contains("self.type_"), "key serialize should use escaped name: {}", code);
    }

    #[test]
    fn test_non_keyword_not_escaped_python() {
        let defs = parse_idl(
            r#"
            struct Normal {
                long data;
                string sensor_id;
                long type_name;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Normal.idl", &PythonOptions::new());

        assert!(code.contains("data: int"));
        assert!(code.contains("sensor_id: str"));
        assert!(code.contains("type_name: int"));
        // Should NOT have trailing underscore
        assert!(!code.contains("data_:"));
        assert!(!code.contains("sensor_id_:"));
    }
}
