/// Rust code generation backend.
///
/// Generates .rs files with `#[derive(DdsType)]` structs from the resolved IDL model.
use crate::naming;
use crate::types::*;

pub struct RustOptions {
    pub crate_path: String,
}

impl Default for RustOptions {
    fn default() -> Self {
        Self { crate_path: "int2dds".to_string() }
    }
}

pub fn generate(model: &IdlModel, idl_filename: &str, opts: &RustOptions) -> String {
    let mut gen =
        RustGen { out: String::new(), indent: 0, opts, model, own_quals: own_type_quals(model) };
    gen.emit_file(idl_filename);
    gen.out
}

/// Unmangled qualified names of every type this file emits. A *qualified* reference
/// not in this set is external (resolved from an `#include`d file) and is referenced
/// by its full package path instead of a bare leaf. `qualified_name` is unmangled so
/// the comparison holds under `--ros2` (member references are never mangled).
fn own_type_quals(model: &IdlModel) -> std::collections::HashSet<String> {
    model
        .structs
        .iter()
        .map(|s| s.qualified_name.as_str())
        .chain(model.enums.iter().map(|e| e.qualified_name.as_str()))
        .chain(model.bitmasks.iter().map(|b| b.qualified_name.as_str()))
        .chain(model.bitsets.iter().map(|b| b.qualified_name.as_str()))
        .chain(model.unions.iter().map(|u| u.qualified_name.as_str()))
        .map(naming::ros2_unmangle)
        .collect()
}

struct RustGen<'a> {
    out: String,
    indent: usize,
    opts: &'a RustOptions,
    model: &'a IdlModel,
    own_quals: std::collections::HashSet<String>,
}

impl<'a> RustGen<'a> {
    fn emit_file(&mut self, idl_filename: &str) {
        self.line(&format!("// Auto-generated by int2dds-idl from {}", idl_filename));
        self.line("// DO NOT EDIT - changes will be overwritten");
        self.line("");
        self.line(&format!("use {}::DdsType;", self.opts.crate_path));

        // Conditionally add imports based on types used
        if self.needs_wchar_import() {
            self.line(&format!(
                "use {}::serialize::core::{{WChar, WString}};",
                self.opts.crate_path
            ));
        }
        if self.needs_hashmap_import() {
            self.line("use std::collections::HashMap;");
        }
        self.line("");

        self.emit_constants();

        for e in &self.model.enums {
            self.emit_enum(e);
            self.line("");
        }

        for b in &self.model.bitmasks {
            self.emit_bitmask(b);
            self.line("");
        }

        for b in &self.model.bitsets {
            self.emit_bitset(b);
            self.line("");
        }

        for u in &self.model.unions {
            self.emit_union(u);
            self.line("");
        }

        for s in &self.model.structs {
            self.emit_struct(s);
            self.line("");
        }
    }

    fn needs_wchar_import(&self) -> bool {
        self.model
            .structs
            .iter()
            .any(|s| s.members.iter().any(|m| Self::type_uses_wchar(&m.resolved_type)))
    }

    fn needs_hashmap_import(&self) -> bool {
        self.model
            .structs
            .iter()
            .any(|s| s.members.iter().any(|m| Self::type_uses_map(&m.resolved_type)))
            || self.model.unions.iter().any(|u| {
                u.cases.iter().any(|c| Self::type_uses_map(&c.member.resolved_type))
                    || u.default_case
                        .as_ref()
                        .is_some_and(|dc| Self::type_uses_map(&dc.resolved_type))
            })
    }

    fn type_uses_wchar(ty: &ResolvedType) -> bool {
        match ty {
            ResolvedType::WChar | ResolvedType::WString { .. } => true,
            ResolvedType::Sequence { element, .. } | ResolvedType::Array { element, .. } => {
                Self::type_uses_wchar(element)
            }
            ResolvedType::Map { key, value, .. } => {
                Self::type_uses_wchar(key) || Self::type_uses_wchar(value)
            }
            _ => false,
        }
    }

    /// Whether a type contains a map that is emitted as `HashMap` (i.e. a non-float key).
    /// Float-key maps are emitted as `Vec<(K, V)>` and need no `HashMap` import.
    fn type_uses_map(ty: &ResolvedType) -> bool {
        match ty {
            ResolvedType::Map { key, value, .. } => {
                !matches!(**key, ResolvedType::F32 | ResolvedType::F64)
                    || Self::type_uses_map(value)
            }
            ResolvedType::Sequence { element, .. } | ResolvedType::Array { element, .. } => {
                Self::type_uses_map(element)
            }
            _ => false,
        }
    }

    fn emit_constants(&mut self) {
        if self.model.constants.is_empty() {
            return;
        }
        for c in &self.model.constants {
            let name = naming::escape_keyword(
                &naming::to_screaming_snake(&c.name),
                naming::TargetLang::Rust,
            );
            let ty = self.const_rust_type(&c.resolved_type);
            let val = self.const_rust_value(&c.value);
            self.line(&format!("pub const {}: {} = {};", name, ty, val));
        }
        self.line("");
    }

    /// Rust type for a `const`: strings become `&str`, everything else mirrors fields.
    fn const_rust_type(&self, ty: &ResolvedType) -> String {
        match ty {
            ResolvedType::String { .. } | ResolvedType::WString { .. } => "&str".to_string(),
            _ => self.type_to_rust(ty),
        }
    }

    fn const_rust_value(&self, value: &ConstValue) -> String {
        match value {
            ConstValue::Int(v) => v.to_string(),
            ConstValue::Float(v) => format!("{:?}", v),
            ConstValue::Bool(v) => v.to_string(),
            ConstValue::Str(v) => format!("{:?}", v),
            ConstValue::Ident(v) => {
                let simple = v.rsplit("::").next().unwrap_or(v);
                naming::escape_keyword(simple, naming::TargetLang::Rust)
            }
        }
    }

    fn emit_enum(&mut self, e: &ResolvedEnum) {
        let rust_name = naming::to_pascal_case(&e.name);
        self.line("#[derive(DdsType)]");
        // Preserve the registered DDS type name when it differs from the Rust name
        if e.qualified_name != rust_name {
            self.line(&format!("#[dds_type(type_name = \"{}\")]", e.qualified_name));
        }
        self.line("#[repr(i32)]");
        self.line(&format!("pub enum {} {{", rust_name));
        self.indent += 1;
        for v in &e.variants {
            let variant_name =
                naming::escape_keyword(&naming::to_pascal_case(&v.name), naming::TargetLang::Rust);
            self.line(&format!("{} = {},", variant_name, v.value));
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_bitmask(&mut self, b: &ResolvedBitmask) {
        let rust_name = naming::to_pascal_case(&b.name);
        self.line("#[derive(DdsType)]");
        let mut attrs = format!("bitmask, bit_bound = {}", b.bit_bound);
        if b.qualified_name != rust_name {
            attrs.push_str(&format!(", type_name = \"{}\"", b.qualified_name));
        }
        self.line(&format!("#[dds_type({})]", attrs));
        self.line(&format!("pub enum {} {{", rust_name));
        self.indent += 1;
        for flag in &b.flags {
            let flag_name = naming::escape_keyword(
                &naming::to_pascal_case(&flag.name),
                naming::TargetLang::Rust,
            );
            self.line(&format!("#[dds(position = {})]", flag.position));
            self.line(&format!("{},", flag_name));
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_bitset(&mut self, b: &ResolvedBitset) {
        let rust_name = naming::to_pascal_case(&b.name);
        self.line("#[derive(DdsType)]");
        if b.qualified_name != rust_name {
            self.line(&format!("#[dds_type(bitset, type_name = \"{}\")]", b.qualified_name));
        } else {
            self.line("#[dds_type(bitset)]");
        }
        self.line(&format!("pub struct {} {{", rust_name));
        self.indent += 1;
        for f in &b.fields {
            self.line(&format!("#[dds(bitfield = {})]", f.bit_width));
            let rust_type = bitfield_rust_type(f.bit_width);
            let field_name = naming::escape_keyword(&f.name, naming::TargetLang::Rust);
            self.line(&format!("pub {}: {},", field_name, rust_type));
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_union(&mut self, u: &ResolvedUnion) {
        let rust_name = naming::to_pascal_case(&u.name);

        self.line("#[derive(DdsType)]");
        if u.qualified_name != rust_name {
            self.line(&format!("#[dds_type(type_name = \"{}\")]", u.qualified_name));
        }

        // Determine repr type from discriminant
        let repr = self.discriminant_repr(&u.discriminant_type);
        self.line(&format!("#[repr({})]", repr));

        self.line(&format!("pub enum {} {{", rust_name));
        self.indent += 1;

        for case in &u.cases {
            // Use first label as discriminant value
            if let Some(label) = case.labels.first() {
                let disc_val = self.label_to_string(label);
                let variant_name = naming::escape_keyword(
                    &naming::to_pascal_case(&case.member.name),
                    naming::TargetLang::Rust,
                );
                let type_str = self.type_to_rust(&case.member.resolved_type);
                self.line(&format!("{}({}) = {},", variant_name, type_str, disc_val));
            }
        }

        if let Some(dc) = &u.default_case {
            let variant_name =
                naming::escape_keyword(&naming::to_pascal_case(&dc.name), naming::TargetLang::Rust);
            let type_str = self.type_to_rust(&dc.resolved_type);
            let disc_val = self.default_discriminant(u, repr);

            self.line("#[dds(default)]");
            self.line(&format!("{}({}) = {},", variant_name, type_str, disc_val));
        }

        self.indent -= 1;
        self.line("}");
    }

    fn default_discriminant(&self, u: &ResolvedUnion, repr: &str) -> String {
        let used: std::collections::HashSet<i64> = u
            .cases
            .iter()
            .flat_map(|c| &c.labels)
            .filter_map(|l| match l {
                ResolvedUnionLabel::Int(v) => Some(*v),
                ResolvedUnionLabel::Bool(b) => Some(*b as i64),
                ResolvedUnionLabel::Ident(_) => None,
            })
            .collect();

        // Signed discriminators default to -1, or, when -1 is already a declared label,
        // the negative value closest to zero that no label uses (spec §7.14.2).
        // Unsigned discriminators use the value closest to zero that no label uses.
        if matches!(repr, "i8" | "i16" | "i32" | "i64") {
            let mut candidate = -1i64;
            while used.contains(&candidate) {
                candidate -= 1;
            }
            candidate.to_string()
        } else {
            let mut candidate = 0i64;
            while used.contains(&candidate) {
                candidate += 1;
            }
            candidate.to_string()
        }
    }

    fn discriminant_repr(&self, ty: &ResolvedType) -> &'static str {
        match ty {
            ResolvedType::Bool => "u8",
            // char, octet and uint8 are byte-width unsigned discriminators (spec Table 7.9).
            ResolvedType::Char | ResolvedType::U8 | ResolvedType::UInt8 => "u8",
            ResolvedType::I8 => "i8",
            ResolvedType::I16 => "i16",
            ResolvedType::U16 => "u16",
            ResolvedType::I32 | ResolvedType::Enum(_) => "i32",
            ResolvedType::U32 => "u32",
            ResolvedType::I64 => "i64",
            ResolvedType::U64 => "u64",
            _ => "i32",
        }
    }

    fn label_to_string(&self, label: &ResolvedUnionLabel) -> String {
        match label {
            ResolvedUnionLabel::Int(v) => v.to_string(),
            ResolvedUnionLabel::Bool(v) => if *v { "1" } else { "0" }.to_string(),
            ResolvedUnionLabel::Ident(name) => name.clone(),
        }
    }

    fn emit_struct(&mut self, s: &ResolvedStruct) {
        let rust_name = naming::to_pascal_case(&s.name);

        // Derives
        self.line("#[derive(DdsType)]");

        // Type-level attributes
        let mut type_attrs = Vec::new();
        if self.opts.crate_path != "int2dds" {
            type_attrs.push(format!("crate_path = \"{}\"", self.opts.crate_path));
        }
        // Preserve the registered DDS type name when it differs from the Rust name
        // (case conversion, module scope, or ROS2 mangling)
        if s.qualified_name != rust_name {
            type_attrs.push(format!("type_name = \"{}\"", s.qualified_name));
        }
        match s.extensibility {
            ExtensibilityKind::Appendable => {} // default, no annotation needed
            ExtensibilityKind::Final => type_attrs.push("extensibility = \"Final\"".to_string()),
            ExtensibilityKind::Mutable => {
                type_attrs.push("extensibility = \"Mutable\"".to_string())
            }
        }
        if let Some(autoid) = &s.autoid {
            match autoid {
                AutoIdKind::Hash => type_attrs.push("autoid = \"Hash\"".to_string()),
                AutoIdKind::Sequential => type_attrs.push("autoid = \"Sequential\"".to_string()),
            }
        }
        if !type_attrs.is_empty() {
            self.line(&format!("#[dds_type({})]", type_attrs.join(", ")));
        }

        self.line(&format!("pub struct {} {{", rust_name));
        self.indent += 1;

        // If there's a base type, emit the inherited base field first. It is named `base`,
        // or `base_` when a member also maps to `base` (spec §7.2.4.3.2).
        if let Some(base) = &s.base_type {
            let base_rust = naming::to_pascal_case(base.rsplit("::").next().unwrap_or(base));
            let collides = s.members.iter().any(|m| naming::to_snake_case(&m.name) == "base");
            let field_name = if collides { "base_" } else { "base" };
            self.line("#[dds(parent)]");
            self.line(&format!("pub {}: {},", field_name, base_rust));
        }

        for m in &s.members {
            self.emit_field(m, s.autoid);
        }

        self.indent -= 1;
        self.line("}");
    }

    fn emit_field(&mut self, m: &ResolvedMember, struct_autoid: Option<AutoIdKind>) {
        // Build field-level #[dds(...)] attributes
        let mut dds_attrs = Vec::new();
        if m.is_key {
            dds_attrs.push("key".to_string());
        }
        let id_is_auto_computed =
            m.hashid.is_some() || matches!(struct_autoid, Some(AutoIdKind::Hash));
        if let Some(id) = m.member_id {
            if !id_is_auto_computed {
                dds_attrs.push(format!("id = {}", id));
            }
        }
        if m.is_optional {
            dds_attrs.push("optional".to_string());
        }
        if m.must_understand {
            dds_attrs.push("must_understand".to_string());
        }
        if m.is_external {
            dds_attrs.push("external".to_string());
        }

        // @hashid
        if let Some(hashid) = &m.hashid {
            match hashid {
                Some(name) => dds_attrs.push(format!("hashid = \"{}\"", name)),
                None => dds_attrs.push("hashid".to_string()),
            }
        }

        // @default
        if let Some(default) = &m.default_value {
            match default {
                ConstValue::Int(v) => dds_attrs.push(format!("default = {}", v)),
                ConstValue::Float(v) => dds_attrs.push(format!("default = {}", v)),
                ConstValue::Str(v) => dds_attrs.push(format!("default = \"{}\"", v)),
                ConstValue::Bool(v) => dds_attrs.push(format!("default = {}", v)),
                ConstValue::Ident(v) => dds_attrs.push(format!("default = {}", v)),
            }
        }

        // Check for bound on string/wstring/sequence/map
        match &m.resolved_type {
            ResolvedType::String { bound: Some(n) } => {
                dds_attrs.push(format!("bound = {}", n));
            }
            ResolvedType::WString { bound: Some(n) } => {
                dds_attrs.push(format!("bound = {}", n));
            }
            ResolvedType::Sequence { bound: Some(n), .. } => {
                dds_attrs.push(format!("bound = {}", n));
            }
            ResolvedType::Map { bound: Some(n), .. } => {
                dds_attrs.push(format!("bound = {}", n));
            }
            _ => {}
        }

        // IDL `char` is mapped to Rust u8 (Rust char is 4 bytes), but the
        // XTypes TypeObject must still register it as CHAR8 to interoperate
        // with codegen from other languages. The derive macro reads the
        // #[dds(char)] hint to override the metadata kind.
        let is_char_field = matches!(&m.resolved_type, ResolvedType::Char)
            || matches!(
                &m.resolved_type,
                ResolvedType::Array { element, .. } if matches!(**element, ResolvedType::Char)
            );
        if is_char_field {
            dds_attrs.push("char".to_string());
        }

        // IDL `uint8` maps to Rust u8 (same storage as `octet`), but the derive macro must
        // register it as UINT8 (not BYTE) via the #[dds(uint8)] hint so the TypeObject kind
        // matches strict XTypes peers — octet and uint8 are NOT assignable.
        let is_uint8_field = matches!(&m.resolved_type, ResolvedType::UInt8)
            || matches!(
                &m.resolved_type,
                ResolvedType::Array { element, .. } | ResolvedType::Sequence { element, .. }
                    if matches!(**element, ResolvedType::UInt8)
            );
        if is_uint8_field {
            dds_attrs.push("uint8".to_string());
        }

        if !dds_attrs.is_empty() {
            self.line(&format!("#[dds({})]", dds_attrs.join(", ")));
        }

        // `@external` introduces `Box<T>`; `@optional` wraps the result in `Option<...>`.
        // Both may apply, giving `Option<Box<T>>` (spec §7.2.4.4).
        let mut final_type = self.type_to_rust(&m.resolved_type);
        if m.is_external {
            final_type = format!("Box<{}>", final_type);
        }
        if m.is_optional {
            final_type = format!("Option<{}>", final_type);
        }

        let field_name =
            naming::escape_keyword(&naming::to_snake_case(&m.name), naming::TargetLang::Rust);
        self.line(&format!("pub {}: {},", field_name, final_type));
    }

    fn type_to_rust(&self, ty: &ResolvedType) -> String {
        match ty {
            ResolvedType::Bool => "bool".to_string(),
            ResolvedType::U8 | ResolvedType::UInt8 => "u8".to_string(),
            ResolvedType::I8 => "i8".to_string(),
            ResolvedType::I16 => "i16".to_string(),
            ResolvedType::U16 => "u16".to_string(),
            ResolvedType::I32 => "i32".to_string(),
            ResolvedType::U32 => "u32".to_string(),
            ResolvedType::I64 => "i64".to_string(),
            ResolvedType::U64 => "u64".to_string(),
            ResolvedType::F32 => "f32".to_string(),
            ResolvedType::F64 => "f64".to_string(),
            ResolvedType::Char => "u8".to_string(),
            ResolvedType::WChar => "WChar".to_string(),
            ResolvedType::String { .. } => "String".to_string(),
            ResolvedType::WString { .. } => "WString".to_string(),
            ResolvedType::Sequence { element, .. } => {
                format!("Vec<{}>", self.type_to_rust(element))
            }
            ResolvedType::Array { element, size } => {
                format!("[{}; {}]", self.type_to_rust(element), size)
            }
            ResolvedType::Map { key, value, .. } => {
                // A floating-point key does not implement Eq + Hash, so HashMap would not
                // compile. Fall back to an insertion-ordered Vec of pairs (spec §7.2.4.2.5).
                if matches!(**key, ResolvedType::F32 | ResolvedType::F64) {
                    format!("Vec<({}, {})>", self.type_to_rust(key), self.type_to_rust(value))
                } else {
                    format!("HashMap<{}, {}>", self.type_to_rust(key), self.type_to_rust(value))
                }
            }
            ResolvedType::Struct(name) | ResolvedType::Enum(name) => {
                if self.is_external(name) {
                    naming::rust_external_path(name)
                } else {
                    let simple = name.rsplit("::").next().unwrap_or(name);
                    naming::to_pascal_case(simple)
                }
            }
            ResolvedType::Bitmask(name) => {
                if self.is_external(name) {
                    format!("{}Value", naming::rust_external_path(name))
                } else {
                    let simple = name.rsplit("::").next().unwrap_or(name);
                    format!("{}Value", naming::to_pascal_case(simple))
                }
            }
        }
    }

    /// A type reference is external when it is qualified (names another package's
    /// scope) and is not one of the types this file emits. Bare leaf references are
    /// always local — a foreign type cannot be named without qualifying it.
    fn is_external(&self, name: &str) -> bool {
        name.contains("::") && !self.own_quals.contains(name)
    }

    fn line(&mut self, text: &str) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(text);
        self.out.push('\n');
    }
}

/// Map bitfield width to smallest Rust integer type.
fn bitfield_rust_type(bit_width: u32) -> &'static str {
    match bit_width {
        0..=8 => "u8",
        9..=16 => "u16",
        17..=32 => "u32",
        _ => "u64",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_idl;
    use crate::resolver::resolve;

    #[test]
    fn test_hello_world_codegen() {
        let defs = parse_idl(
            r#"
            @extensibility(APPENDABLE)
            struct HelloWorld {
                unsigned long index;
                string message;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "HelloWorld.idl", &RustOptions::default());

        assert!(code.contains("#[derive(DdsType)]"));
        assert!(!code.contains("extensibility")); // Appendable is default, no annotation needed
        assert!(code.contains("pub struct HelloWorld {"));
        assert!(code.contains("pub index: u32,"));
        assert!(code.contains("pub message: String,"));
    }

    #[test]
    fn test_keyed_struct_codegen() {
        let defs = parse_idl(
            r#"
            struct SensorData {
                @key long sensor_id;
                double temperature;
                string<128> location;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "SensorData.idl", &RustOptions::default());

        assert!(code.contains("#[dds(key)]"));
        assert!(code.contains("pub sensor_id: i32,"));
        assert!(code.contains("#[dds(bound = 128)]"));
        assert!(code.contains("pub location: String,"));
    }

    #[test]
    fn test_enum_codegen() {
        let defs = parse_idl("enum Color { RED, GREEN = 5, BLUE };").unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Color.idl", &RustOptions::default());

        assert!(code.contains("#[repr(i32)]"));
        assert!(code.contains("pub enum Color {"));
        assert!(code.contains("Red = 0,"));
        assert!(code.contains("Green = 5,"));
        assert!(code.contains("Blue = 6,"));
    }

    #[test]
    fn test_wstring_codegen() {
        let defs = parse_idl(
            r#"
            struct WideData {
                wchar wc;
                wstring ws;
                wstring<128> bounded_ws;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "WideData.idl", &RustOptions::default());

        assert!(code.contains("use int2dds::serialize::core::{WChar, WString};"));
        assert!(code.contains("pub wc: WChar,"));
        assert!(code.contains("pub ws: WString,"));
        assert!(code.contains("#[dds(bound = 128)]"));
        assert!(code.contains("pub bounded_ws: WString,"));
    }

    #[test]
    fn test_external_codegen() {
        let defs = parse_idl(
            r#"
            struct Data {
                @external long large_data;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Data.idl", &RustOptions::default());

        assert!(code.contains("#[dds(external)]"));
        assert!(code.contains("pub large_data: Box<i32>,"));
    }

    #[test]
    fn test_default_codegen() {
        let defs = parse_idl(
            r#"
            struct Data {
                @default(42) long count;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Data.idl", &RustOptions::default());

        assert!(code.contains("#[dds(default = 42)]"));
    }

    #[test]
    fn test_constants_codegen() {
        let defs = parse_idl(
            r#"
            module T_Constants {
                const int8 STATUS_NO_FIX = -1;
                const double GAIN = 1.5;
                const string MODE = "auto";
                const boolean ENABLED = TRUE;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "T.idl", &RustOptions::default());

        assert!(code.contains("pub const STATUS_NO_FIX: i8 = -1;"), "{}", code);
        assert!(code.contains("pub const GAIN: f64 = 1.5;"), "{}", code);
        assert!(code.contains("pub const MODE: &str = \"auto\";"), "{}", code);
        assert!(code.contains("pub const ENABLED: bool = true;"), "{}", code);
    }

    #[test]
    fn test_scoped_dependency_reference_codegen() {
        // resolve-only include: the dependency type (Header) is resolved but not
        // emitted. The root type references it by leaf name; the consuming build
        // must provide that type in scope. This pins that contract for the Rust
        // backend so a regression in the reference form is caught.
        use crate::resolver::resolve_scoped;
        let dep =
            parse_idl("module std_msgs { module msg { struct Header { uint32 stamp; }; }; };")
                .unwrap();
        let root = parse_idl(
            "module sensor_msgs { module msg { struct Imu { std_msgs::msg::Header header; double v[3]; }; }; };",
        )
        .unwrap();
        let mut all = dep.clone();
        all.extend(root.clone());
        let model = resolve_scoped(&root, all).unwrap();
        let code = generate(&model, "Imu.idl", &RustOptions::default());

        assert!(code.contains("pub struct Imu {"), "{}", code);
        // External (included) type is referenced by its full package path so the
        // output compiles against the dependency's own generated module.
        assert!(code.contains("pub header: std_msgs::msg::Header,"), "{}", code);
        // The included type is not re-emitted in this file.
        assert!(!code.contains("pub struct Header"), "{}", code);
    }

    #[test]
    fn test_local_nested_reference_unchanged() {
        // A type defined in the same file is still referenced by bare leaf name.
        let defs = parse_idl(
            "module p { module msg {
                struct Inner { long a; };
                struct Outer { Inner inner; long b; };
            }; };",
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "P.idl", &RustOptions::default());
        assert!(code.contains("pub inner: Inner,"), "{}", code);
        // The field type is the bare leaf, not a package path.
        assert!(!code.contains(": p::msg::Inner"), "{}", code);
    }

    #[test]
    fn test_external_same_leaf_collision() {
        // The root defines `Status` and also references a different package's
        // `Status`. Qualified-name detection keeps the local one bare and the
        // external one fully pathed, so they don't collapse onto each other.
        use crate::resolver::resolve_scoped;
        let dep =
            parse_idl("module other_pkg { module msg { struct Status { long x; }; }; };").unwrap();
        let root = parse_idl(
            "module my_pkg { module msg {
                struct Status { long a; };
                struct Holder { Status local_status; other_pkg::msg::Status ext_status; };
            }; };",
        )
        .unwrap();
        let mut all = dep.clone();
        all.extend(root.clone());
        let model = resolve_scoped(&root, all).unwrap();
        let code = generate(&model, "Holder.idl", &RustOptions::default());

        assert!(code.contains("pub local_status: Status,"), "{}", code);
        assert!(code.contains("pub ext_status: other_pkg::msg::Status,"), "{}", code);
        // The local Status is emitted; the external one is not re-defined.
        assert!(code.contains("pub struct Status {"), "{}", code);
    }

    #[test]
    fn test_hashid_codegen() {
        let defs = parse_idl(
            r#"
            struct Data {
                @hashid long field_a;
                @hashid("custom") long field_b;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Data.idl", &RustOptions::default());

        assert!(code.contains("#[dds(hashid)]"));
        assert!(code.contains("#[dds(hashid = \"custom\")]"));
    }

    #[test]
    fn test_autoid_codegen() {
        let defs = parse_idl(
            r#"
            @autoid(HASH)
            @extensibility(MUTABLE)
            struct Data {
                long x;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Data.idl", &RustOptions::default());

        assert!(code.contains("autoid = \"Hash\""));
        assert!(code.contains("extensibility = \"Mutable\""));
    }

    #[test]
    fn test_inheritance_codegen() {
        let defs = parse_idl(
            r#"
            struct Base {
                long x;
            };
            struct Derived : Base {
                long y;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Derived.idl", &RustOptions::default());

        assert!(code.contains("#[dds(parent)]"));
        assert!(code.contains("pub base: Base,"), "got:\n{}", code);
        assert!(code.contains("pub y: i32,"));
    }

    #[test]
    fn test_inheritance_base_field_collision() {
        // Spec §7.2.4.3.2: the base field is named `base`, or `base_` when a member also
        // maps to `base`.
        let defs = parse_idl(
            r#"
            struct Root {
                long x;
            };
            struct Leaf : Root {
                long base;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Leaf.idl", &RustOptions::default());

        assert!(code.contains("pub base_: Root,"), "got:\n{}", code);
        assert!(code.contains("pub base: i32,"), "got:\n{}", code);
    }

    #[test]
    fn test_member_name_snake_case() {
        // Spec §7.1.1: structure members map to snake_case.
        let defs = parse_idl(
            r#"
            struct Data {
                long fooBar;
                long HTTPStatus;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Data.idl", &RustOptions::default());

        assert!(code.contains("pub foo_bar: i32,"), "got:\n{}", code);
        assert!(code.contains("pub http_status: i32,"), "got:\n{}", code);
    }

    #[test]
    fn test_constant_name_screaming_snake() {
        // Spec §7.1.1: constants map to SCREAMING_SNAKE_CASE.
        let defs = parse_idl("const long maxSize = 5;").unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "C.idl", &RustOptions::default());

        assert!(code.contains("pub const MAX_SIZE: i32 = 5;"), "got:\n{}", code);
    }

    #[test]
    fn test_optional_external_codegen() {
        // Spec §7.2.4.4: an optional member that closes a recursion maps to Option<Box<T>>.
        let defs = parse_idl(
            r#"
            struct Config {
                @optional @external Config fallback;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Config.idl", &RustOptions::default());

        assert!(code.contains("pub fallback: Option<Box<Config>>,"), "got:\n{}", code);
    }

    #[test]
    fn test_map_float_key_uses_vec() {
        // Spec §7.2.4.2.5: a floating-point key type does not implement Eq + Hash,
        // so the map maps to Vec<(K, V)> rather than HashMap (which would not compile).
        let defs = parse_idl(
            r#"
            struct M {
                map<double, long> by_val;
                map<float, string> by_f;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "M.idl", &RustOptions::default());

        assert!(code.contains("pub by_val: Vec<(f64, i32)>,"), "got:\n{}", code);
        assert!(code.contains("pub by_f: Vec<(f32, String)>,"), "got:\n{}", code);
        assert!(!code.contains("HashMap<f64"), "float key must not use HashMap:\n{}", code);
        // Only float-key maps present -> no HashMap emitted -> no HashMap import.
        assert!(!code.contains("use std::collections::HashMap;"), "unused import:\n{}", code);
    }

    #[test]
    fn test_union_byte_width_discriminator_repr() {
        // Spec Table 7.9: octet/char/uint8 discriminators map to repr(u8), int8 to repr(i8),
        // not the i32 fallback (which would change the wire size).
        for (disc, repr) in [("octet", "u8"), ("char", "u8"), ("uint8", "u8"), ("int8", "i8")] {
            let src = format!("union U switch({}) {{ case 0: long a; case 1: long b; }};", disc);
            let model = resolve(parse_idl(&src).unwrap()).unwrap();
            let code = generate(&model, "U.idl", &RustOptions::default());
            assert!(
                code.contains(&format!("#[repr({})]", repr)),
                "discriminator {} should map to repr({}):\n{}",
                disc,
                repr,
                code
            );
        }
    }

    #[test]
    fn test_union_signed_default_avoids_used_minus_one() {
        // Spec §7.14.2: default discriminant is -1, unless -1 is a declared label, in which
        // case it is the negative value closest to zero that no label uses.
        let defs = parse_idl(
            r#"
            union U switch(long) {
                case -1: long a;
                case -2: long b;
                default: string d;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "U.idl", &RustOptions::default());

        // The default variant D must not reuse -1 (taken by label a); it takes -3.
        assert!(!code.contains("D(String) = -1,"), "default must not reuse -1:\n{}", code);
        assert!(
            code.contains("D(String) = -3,"),
            "default should be -3 (nearest unused negative):\n{}",
            code
        );
    }

    #[test]
    fn test_map_codegen() {
        let defs = parse_idl(
            r#"
            struct MapData {
                map<long, string> lookup;
                map<string, double, 100> bounded_map;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "MapData.idl", &RustOptions::default());

        assert!(code.contains("use std::collections::HashMap;"));
        assert!(code.contains("pub lookup: HashMap<i32, String>,"));
        assert!(code.contains("#[dds(bound = 100)]"));
        assert!(code.contains("pub bounded_map: HashMap<String, f64>,"));
    }

    #[test]
    fn test_bitmask_codegen() {
        let defs = parse_idl(
            r#"
            @bit_bound(8)
            bitmask MyFlags {
                FLAG_A,
                @position(3) FLAG_B,
                FLAG_C
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "MyFlags.idl", &RustOptions::default());

        assert!(code.contains("#[dds_type(bitmask, bit_bound = 8)]"));
        assert!(code.contains("pub enum MyFlags {"));
        assert!(code.contains("#[dds(position = 0)]"));
        assert!(code.contains("FlagA,"));
        assert!(code.contains("#[dds(position = 3)]"));
        assert!(code.contains("FlagB,"));
        assert!(code.contains("#[dds(position = 4)]"));
        assert!(code.contains("FlagC,"));
    }

    #[test]
    fn test_bitset_codegen() {
        let defs = parse_idl(
            r#"
            bitset MyBitset {
                bitfield<3> field_a;
                bitfield<5> field_b;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "MyBitset.idl", &RustOptions::default());

        assert!(code.contains("#[dds_type(bitset)]"));
        assert!(code.contains("pub struct MyBitset {"));
        assert!(code.contains("#[dds(bitfield = 3)]"));
        assert!(code.contains("pub field_a: u8,"));
        assert!(code.contains("#[dds(bitfield = 5)]"));
        assert!(code.contains("pub field_b: u8,"));
    }

    #[test]
    fn test_union_codegen() {
        let defs = parse_idl(
            r#"
            union MyUnion switch(long) {
                case 0: long int_val;
                case 1: string str_val;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "MyUnion.idl", &RustOptions::default());

        assert!(code.contains("#[derive(DdsType)]"));
        assert!(code.contains("#[repr(i32)]"));
        assert!(code.contains("pub enum MyUnion {"));
        assert!(code.contains("IntVal(i32) = 0,"));
        assert!(code.contains("StrVal(String) = 1,"));
    }

    #[test]
    fn test_union_bool_default_codegen() {
        let defs = parse_idl(
            r#"
            union BoolUnion switch(boolean) {
                case TRUE: long true_val;
                default: string other;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "BoolUnion.idl", &RustOptions::default());

        assert!(code.contains("#[repr(u8)]"), "{}", code);
        assert!(code.contains("#[dds(default)]"), "{}", code);
        assert!(!code.contains("= -1,"), "u8 repr default must not be -1: {}", code);
        assert!(code.contains("Other(String) = 0,"), "default takes unused label 0: {}", code);
    }

    #[test]
    fn test_union_unsigned_default_codegen() {
        let defs = parse_idl(
            r#"
            union UU switch(unsigned long) {
                case 0: long a;
                case 1: long b;
                default: string d;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "UU.idl", &RustOptions::default());

        assert!(code.contains("#[repr(u32)]"), "{}", code);
        assert!(!code.contains("= -1,"), "u32 repr default must not be -1: {}", code);
        assert!(code.contains("D(String) = 2,"), "default takes smallest unused label 2: {}", code);
    }

    #[test]
    fn test_keyword_escaping_in_struct_fields() {
        let defs = parse_idl(
            r#"
            struct KeywordTest {
                long type;
                long match;
                boolean async;
                string yield;
                long gen;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "KeywordTest.idl", &RustOptions::default());

        assert!(code.contains("pub r#type: i32,"), "type field should be escaped: {}", code);
        assert!(code.contains("pub r#match: i32,"), "match field should be escaped: {}", code);
        assert!(code.contains("pub r#async: bool,"), "async field should be escaped: {}", code);
        assert!(code.contains("pub r#yield: String,"), "yield field should be escaped: {}", code);
        assert!(code.contains("pub r#gen: i32,"), "gen field should be escaped: {}", code);
    }

    #[test]
    fn test_non_keyword_fields_not_escaped() {
        let defs = parse_idl(
            r#"
            struct Normal {
                long data;
                long sensor_id;
                string temperature;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Normal.idl", &RustOptions::default());

        assert!(code.contains("pub data: i32,"));
        assert!(code.contains("pub sensor_id: i32,"));
        assert!(code.contains("pub temperature: String,"));
        // Should NOT contain r#
        assert!(!code.contains("r#data"));
        assert!(!code.contains("r#sensor_id"));
    }

    #[test]
    fn test_keyword_prefix_not_escaped() {
        let defs = parse_idl(
            r#"
            struct PrefixTest {
                long type_name;
                long class_id;
                long return_value;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "PrefixTest.idl", &RustOptions::default());

        assert!(code.contains("pub type_name: i32,"));
        assert!(code.contains("pub class_id: i32,"));
        assert!(code.contains("pub return_value: i32,"));
    }

    #[test]
    fn test_keyword_escaping_in_union() {
        // Union case names go through to_pascal_case, so "type" → "Type"
        // "Type" is NOT a Rust keyword (keywords are lowercase) → no r# prefix
        let defs = parse_idl(
            r#"
            union KeywordUnion switch(long) {
                case 0: long type;
                case 1: string class;
                default: boolean match;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "KeywordUnion.idl", &RustOptions::default());

        assert!(code.contains("Type(i32) = 0,"), "union case 'type' → Type: {}", code);
        assert!(code.contains("Class(String) = 1,"), "union case 'class' → Class: {}", code);
        assert!(code.contains("Match(bool) = -1,"), "union default 'match' → Match: {}", code);
    }

    #[test]
    fn test_keyword_escaping_in_enum_variants() {
        // Enum variants go through to_pascal_case: TYPE → Type, MATCH → Match
        // PascalCase forms are NOT Rust keywords → no escaping needed
        let defs = parse_idl(
            r#"
            enum KeywordEnum {
                TYPE,
                MATCH,
                IMPL
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "KeywordEnum.idl", &RustOptions::default());

        assert!(code.contains("Type = 0,"), "Type variant: {}", code);
        assert!(code.contains("Match = 1,"), "Match variant: {}", code);
        assert!(code.contains("Impl = 2,"), "Impl variant: {}", code);
    }
}
