/// Rust code generation backend.
///
/// Generates .rs files with `#[derive(DdsType)]` structs from the resolved IDL model.
use crate::naming;
use crate::types::*;

pub struct RustOptions {
    pub crate_path: String,
}

impl Default for RustOptions {
    fn default() -> Self {
        Self { crate_path: "int2dds".to_string() }
    }
}

pub fn generate(model: &IdlModel, idl_filename: &str, opts: &RustOptions) -> String {
    let mut gen = RustGen { out: String::new(), indent: 0, opts, model };
    gen.emit_file(idl_filename);
    gen.out
}

struct RustGen<'a> {
    out: String,
    indent: usize,
    opts: &'a RustOptions,
    model: &'a IdlModel,
}

impl<'a> RustGen<'a> {
    fn emit_file(&mut self, idl_filename: &str) {
        self.line(&format!("//! Auto-generated by int2dds-idl from {}", idl_filename));
        self.line("//! DO NOT EDIT - changes will be overwritten");
        self.line("");
        self.line(&format!("use {}_derive::DdsType;", self.opts.crate_path));

        // Conditionally add imports based on types used
        if self.needs_wchar_import() {
            self.line(&format!(
                "use {}::serialize::core::bounded_types::{{WChar, WString}};",
                self.opts.crate_path
            ));
        }
        if self.needs_hashmap_import() {
            self.line("use std::collections::HashMap;");
        }
        self.line("");

        for e in &self.model.enums {
            self.emit_enum(e);
            self.line("");
        }

        for b in &self.model.bitmasks {
            self.emit_bitmask(b);
            self.line("");
        }

        for b in &self.model.bitsets {
            self.emit_bitset(b);
            self.line("");
        }

        for u in &self.model.unions {
            self.emit_union(u);
            self.line("");
        }

        for s in &self.model.structs {
            self.emit_struct(s);
            self.line("");
        }
    }

    fn needs_wchar_import(&self) -> bool {
        self.model
            .structs
            .iter()
            .any(|s| s.members.iter().any(|m| self.type_uses_wchar(&m.resolved_type)))
    }

    fn needs_hashmap_import(&self) -> bool {
        self.model
            .structs
            .iter()
            .any(|s| s.members.iter().any(|m| self.type_uses_map(&m.resolved_type)))
            || self.model.unions.iter().any(|u| {
                u.cases.iter().any(|c| self.type_uses_map(&c.member.resolved_type))
                    || u.default_case
                        .as_ref()
                        .is_some_and(|dc| self.type_uses_map(&dc.resolved_type))
            })
    }

    fn type_uses_wchar(&self, ty: &ResolvedType) -> bool {
        match ty {
            ResolvedType::WChar | ResolvedType::WString { .. } => true,
            ResolvedType::Sequence { element, .. } | ResolvedType::Array { element, .. } => {
                self.type_uses_wchar(element)
            }
            ResolvedType::Map { key, value, .. } => {
                self.type_uses_wchar(key) || self.type_uses_wchar(value)
            }
            _ => false,
        }
    }

    fn type_uses_map(&self, ty: &ResolvedType) -> bool {
        match ty {
            ResolvedType::Map { .. } => true,
            ResolvedType::Sequence { element, .. } | ResolvedType::Array { element, .. } => {
                self.type_uses_map(element)
            }
            _ => false,
        }
    }

    fn emit_enum(&mut self, e: &ResolvedEnum) {
        let rust_name = naming::to_pascal_case(&e.name);
        self.line("#[derive(DdsType)]");
        // Preserve original IDL type name when it differs from PascalCase Rust name
        if e.name != rust_name {
            self.line(&format!("#[dds_type(type_name = \"{}\")]", e.qualified_name));
        }
        self.line("#[repr(i32)]");
        self.line(&format!("pub enum {} {{", rust_name));
        self.indent += 1;
        for v in &e.variants {
            let variant_name = naming::to_pascal_case(&v.name);
            self.line(&format!("{} = {},", variant_name, v.value));
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_bitmask(&mut self, b: &ResolvedBitmask) {
        let rust_name = naming::to_pascal_case(&b.name);
        self.line("#[derive(DdsType)]");
        self.line(&format!("#[dds_type(bitmask, bit_bound = {})]", b.bit_bound));
        self.line(&format!("pub enum {} {{", rust_name));
        self.indent += 1;
        for flag in &b.flags {
            let flag_name = naming::to_pascal_case(&flag.name);
            self.line(&format!("#[dds(position = {})]", flag.position));
            self.line(&format!("{},", flag_name));
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_bitset(&mut self, b: &ResolvedBitset) {
        let rust_name = naming::to_pascal_case(&b.name);
        self.line("#[derive(DdsType)]");
        self.line("#[dds_type(bitset)]");
        self.line(&format!("pub struct {} {{", rust_name));
        self.indent += 1;
        for f in &b.fields {
            self.line(&format!("#[dds(bitfield = {})]", f.bit_width));
            let rust_type = bitfield_rust_type(f.bit_width);
            self.line(&format!("pub {}: {},", f.name, rust_type));
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_union(&mut self, u: &ResolvedUnion) {
        let rust_name = naming::to_pascal_case(&u.name);

        self.line("#[derive(DdsType)]");

        // Determine repr type from discriminant
        let repr = self.discriminant_repr(&u.discriminant_type);
        self.line(&format!("#[repr({})]", repr));

        self.line(&format!("pub enum {} {{", rust_name));
        self.indent += 1;

        for case in &u.cases {
            // Use first label as discriminant value
            if let Some(label) = case.labels.first() {
                let disc_val = self.label_to_string(label);
                let variant_name = naming::to_pascal_case(&case.member.name);
                let type_str = self.type_to_rust(&case.member.resolved_type);
                self.line(&format!("{}({}) = {},", variant_name, type_str, disc_val));
            }
        }

        if let Some(dc) = &u.default_case {
            let variant_name = naming::to_pascal_case(&dc.name);
            let type_str = self.type_to_rust(&dc.resolved_type);
            // Default case needs a discriminant value that doesn't conflict.
            // Use -1 as a convention for default.
            self.line(&format!("{}({}) = -1,", variant_name, type_str));
        }

        self.indent -= 1;
        self.line("}");
    }

    fn discriminant_repr(&self, ty: &ResolvedType) -> &'static str {
        match ty {
            ResolvedType::Bool => "i32",
            ResolvedType::I16 => "i16",
            ResolvedType::U16 => "u16",
            ResolvedType::I32 | ResolvedType::Enum(_) => "i32",
            ResolvedType::U32 => "u32",
            ResolvedType::I64 => "i64",
            ResolvedType::U64 => "u64",
            _ => "i32",
        }
    }

    fn label_to_string(&self, label: &ResolvedUnionLabel) -> String {
        match label {
            ResolvedUnionLabel::Int(v) => v.to_string(),
            ResolvedUnionLabel::Bool(v) => if *v { "1" } else { "0" }.to_string(),
            ResolvedUnionLabel::Ident(name) => name.clone(),
        }
    }

    fn emit_struct(&mut self, s: &ResolvedStruct) {
        let rust_name = naming::to_pascal_case(&s.name);

        // Derives
        self.line("#[derive(DdsType)]");

        // Type-level attributes
        let mut type_attrs = Vec::new();
        if self.opts.crate_path != "int2dds" {
            type_attrs.push(format!("crate_path = \"{}\"", self.opts.crate_path));
        }
        // Preserve original IDL type name when it differs from PascalCase Rust name
        if s.name != rust_name {
            type_attrs.push(format!("type_name = \"{}\"", s.qualified_name));
        }
        match s.extensibility {
            ExtensibilityKind::Final => {} // default, no annotation needed
            ExtensibilityKind::Appendable => {
                type_attrs.push("extensibility = \"Appendable\"".to_string())
            }
            ExtensibilityKind::Mutable => {
                type_attrs.push("extensibility = \"Mutable\"".to_string())
            }
        }
        if let Some(autoid) = &s.autoid {
            match autoid {
                AutoIdKind::Hash => type_attrs.push("autoid = \"Hash\"".to_string()),
                AutoIdKind::Sequential => type_attrs.push("autoid = \"Sequential\"".to_string()),
            }
        }
        if !type_attrs.is_empty() {
            self.line(&format!("#[dds_type({})]", type_attrs.join(", ")));
        }

        self.line(&format!("pub struct {} {{", rust_name));
        self.indent += 1;

        // If there's a base type, emit parent field first
        if let Some(base) = &s.base_type {
            let base_rust = naming::to_pascal_case(base.rsplit("::").next().unwrap_or(base));
            self.line("#[dds(parent)]");
            self.line(&format!("pub parent: {},", base_rust));
        }

        for m in &s.members {
            self.emit_field(m);
        }

        self.indent -= 1;
        self.line("}");
    }

    fn emit_field(&mut self, m: &ResolvedMember) {
        // Build field-level #[dds(...)] attributes
        let mut dds_attrs = Vec::new();
        if m.is_key {
            dds_attrs.push("key".to_string());
        }
        if let Some(id) = m.member_id {
            dds_attrs.push(format!("id = {}", id));
        }
        if m.is_optional {
            dds_attrs.push("optional".to_string());
        }
        if m.must_understand {
            dds_attrs.push("must_understand".to_string());
        }
        if m.is_external {
            dds_attrs.push("external".to_string());
        }

        // @hashid
        if let Some(hashid) = &m.hashid {
            match hashid {
                Some(name) => dds_attrs.push(format!("hashid = \"{}\"", name)),
                None => dds_attrs.push("hashid".to_string()),
            }
        }

        // @default
        if let Some(default) = &m.default_value {
            match default {
                ConstValue::Int(v) => dds_attrs.push(format!("default = {}", v)),
                ConstValue::Float(v) => dds_attrs.push(format!("default = {}", v)),
                ConstValue::Str(v) => dds_attrs.push(format!("default = \"{}\"", v)),
                ConstValue::Bool(v) => dds_attrs.push(format!("default = {}", v)),
                ConstValue::Ident(v) => dds_attrs.push(format!("default = {}", v)),
            }
        }

        // Check for bound on string/wstring/sequence/map
        match &m.resolved_type {
            ResolvedType::String { bound: Some(n) } => {
                dds_attrs.push(format!("bound = {}", n));
            }
            ResolvedType::WString { bound: Some(n) } => {
                dds_attrs.push(format!("bound = {}", n));
            }
            ResolvedType::Sequence { bound: Some(n), .. } => {
                dds_attrs.push(format!("bound = {}", n));
            }
            ResolvedType::Map { bound: Some(n), .. } => {
                dds_attrs.push(format!("bound = {}", n));
            }
            _ => {}
        }

        if !dds_attrs.is_empty() {
            self.line(&format!("#[dds({})]", dds_attrs.join(", ")));
        }

        let type_str = self.type_to_rust(&m.resolved_type);
        let final_type = if m.is_external {
            format!("Box<{}>", type_str)
        } else if m.is_optional {
            format!("Option<{}>", type_str)
        } else {
            type_str
        };

        self.line(&format!("pub {}: {},", m.name, final_type));
    }

    fn type_to_rust(&self, ty: &ResolvedType) -> String {
        match ty {
            ResolvedType::Bool => "bool".to_string(),
            ResolvedType::U8 => "u8".to_string(),
            ResolvedType::I8 => "i8".to_string(),
            ResolvedType::I16 => "i16".to_string(),
            ResolvedType::U16 => "u16".to_string(),
            ResolvedType::I32 => "i32".to_string(),
            ResolvedType::U32 => "u32".to_string(),
            ResolvedType::I64 => "i64".to_string(),
            ResolvedType::U64 => "u64".to_string(),
            ResolvedType::F32 => "f32".to_string(),
            ResolvedType::F64 => "f64".to_string(),
            ResolvedType::Char => "char".to_string(),
            ResolvedType::WChar => "WChar".to_string(),
            ResolvedType::String { .. } => "String".to_string(),
            ResolvedType::WString { .. } => "WString".to_string(),
            ResolvedType::Sequence { element, .. } => {
                format!("Vec<{}>", self.type_to_rust(element))
            }
            ResolvedType::Array { element, size } => {
                format!("[{}; {}]", self.type_to_rust(element), size)
            }
            ResolvedType::Map { key, value, .. } => {
                format!("HashMap<{}, {}>", self.type_to_rust(key), self.type_to_rust(value))
            }
            ResolvedType::Struct(name) | ResolvedType::Enum(name) | ResolvedType::Bitmask(name) => {
                let simple = name.rsplit("::").next().unwrap_or(name);
                naming::to_pascal_case(simple)
            }
        }
    }

    fn line(&mut self, text: &str) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(text);
        self.out.push('\n');
    }
}

/// Map bitfield width to smallest Rust integer type.
fn bitfield_rust_type(bit_width: u32) -> &'static str {
    match bit_width {
        0..=8 => "u8",
        9..=16 => "u16",
        17..=32 => "u32",
        _ => "u64",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_idl;
    use crate::resolver::resolve;

    #[test]
    fn test_hello_world_codegen() {
        let defs = parse_idl(
            r#"
            @extensibility(APPENDABLE)
            struct HelloWorld {
                unsigned long index;
                string message;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "HelloWorld.idl", &RustOptions::default());

        assert!(code.contains("#[derive(DdsType)]"));
        assert!(code.contains("#[dds_type(extensibility = \"Appendable\")]"));
        assert!(code.contains("pub struct HelloWorld {"));
        assert!(code.contains("pub index: u32,"));
        assert!(code.contains("pub message: String,"));
    }

    #[test]
    fn test_keyed_struct_codegen() {
        let defs = parse_idl(
            r#"
            struct SensorData {
                @key long sensor_id;
                double temperature;
                string<128> location;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "SensorData.idl", &RustOptions::default());

        assert!(code.contains("#[dds(key)]"));
        assert!(code.contains("pub sensor_id: i32,"));
        assert!(code.contains("#[dds(bound = 128)]"));
        assert!(code.contains("pub location: String,"));
    }

    #[test]
    fn test_enum_codegen() {
        let defs = parse_idl("enum Color { RED, GREEN = 5, BLUE };").unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Color.idl", &RustOptions::default());

        assert!(code.contains("#[repr(i32)]"));
        assert!(code.contains("pub enum Color {"));
        assert!(code.contains("Red = 0,"));
        assert!(code.contains("Green = 5,"));
        assert!(code.contains("Blue = 6,"));
    }

    #[test]
    fn test_wstring_codegen() {
        let defs = parse_idl(
            r#"
            struct WideData {
                wchar wc;
                wstring ws;
                wstring<128> bounded_ws;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "WideData.idl", &RustOptions::default());

        assert!(code.contains("use int2dds::serialize::core::bounded_types::{WChar, WString};"));
        assert!(code.contains("pub wc: WChar,"));
        assert!(code.contains("pub ws: WString,"));
        assert!(code.contains("#[dds(bound = 128)]"));
        assert!(code.contains("pub bounded_ws: WString,"));
    }

    #[test]
    fn test_external_codegen() {
        let defs = parse_idl(
            r#"
            struct Data {
                @external long large_data;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Data.idl", &RustOptions::default());

        assert!(code.contains("#[dds(external)]"));
        assert!(code.contains("pub large_data: Box<i32>,"));
    }

    #[test]
    fn test_default_codegen() {
        let defs = parse_idl(
            r#"
            struct Data {
                @default(42) long count;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Data.idl", &RustOptions::default());

        assert!(code.contains("#[dds(default = 42)]"));
    }

    #[test]
    fn test_hashid_codegen() {
        let defs = parse_idl(
            r#"
            struct Data {
                @hashid long field_a;
                @hashid("custom") long field_b;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Data.idl", &RustOptions::default());

        assert!(code.contains("#[dds(hashid)]"));
        assert!(code.contains("#[dds(hashid = \"custom\")]"));
    }

    #[test]
    fn test_autoid_codegen() {
        let defs = parse_idl(
            r#"
            @autoid(HASH)
            @extensibility(MUTABLE)
            struct Data {
                long x;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Data.idl", &RustOptions::default());

        assert!(code.contains("autoid = \"Hash\""));
        assert!(code.contains("extensibility = \"Mutable\""));
    }

    #[test]
    fn test_inheritance_codegen() {
        let defs = parse_idl(
            r#"
            struct Base {
                long x;
            };
            struct Derived : Base {
                long y;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "Derived.idl", &RustOptions::default());

        assert!(code.contains("#[dds(parent)]"));
        assert!(code.contains("pub parent: Base,"));
        assert!(code.contains("pub y: i32,"));
    }

    #[test]
    fn test_map_codegen() {
        let defs = parse_idl(
            r#"
            struct MapData {
                map<long, string> lookup;
                map<string, double, 100> bounded_map;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "MapData.idl", &RustOptions::default());

        assert!(code.contains("use std::collections::HashMap;"));
        assert!(code.contains("pub lookup: HashMap<i32, String>,"));
        assert!(code.contains("#[dds(bound = 100)]"));
        assert!(code.contains("pub bounded_map: HashMap<String, f64>,"));
    }

    #[test]
    fn test_bitmask_codegen() {
        let defs = parse_idl(
            r#"
            @bit_bound(8)
            bitmask MyFlags {
                FLAG_A,
                @position(3) FLAG_B,
                FLAG_C
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "MyFlags.idl", &RustOptions::default());

        assert!(code.contains("#[dds_type(bitmask, bit_bound = 8)]"));
        assert!(code.contains("pub enum MyFlags {"));
        assert!(code.contains("#[dds(position = 0)]"));
        assert!(code.contains("FlagA,"));
        assert!(code.contains("#[dds(position = 3)]"));
        assert!(code.contains("FlagB,"));
        assert!(code.contains("#[dds(position = 4)]"));
        assert!(code.contains("FlagC,"));
    }

    #[test]
    fn test_bitset_codegen() {
        let defs = parse_idl(
            r#"
            bitset MyBitset {
                bitfield<3> field_a;
                bitfield<5> field_b;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "MyBitset.idl", &RustOptions::default());

        assert!(code.contains("#[dds_type(bitset)]"));
        assert!(code.contains("pub struct MyBitset {"));
        assert!(code.contains("#[dds(bitfield = 3)]"));
        assert!(code.contains("pub field_a: u8,"));
        assert!(code.contains("#[dds(bitfield = 5)]"));
        assert!(code.contains("pub field_b: u8,"));
    }

    #[test]
    fn test_union_codegen() {
        let defs = parse_idl(
            r#"
            union MyUnion switch(long) {
                case 0: long int_val;
                case 1: string str_val;
            };
            "#,
        )
        .unwrap();
        let model = resolve(defs).unwrap();
        let code = generate(&model, "MyUnion.idl", &RustOptions::default());

        assert!(code.contains("#[derive(DdsType)]"));
        assert!(code.contains("#[repr(i32)]"));
        assert!(code.contains("pub enum MyUnion {"));
        assert!(code.contains("IntVal(i32) = 0,"));
        assert!(code.contains("StrVal(String) = 1,"));
    }
}
