/// XML type-representation backend (XTypes 7.3.2).
///
/// Emits the dialect consumed by `int2dds::config::xml::XmlTypeRegistry`, mirroring
/// the resolved model 1:1 so the XML -> TypeObject path stays byte-identical to the
/// IDL -> Rust -> derive path.
use std::collections::HashMap;

use crate::codegen::flatten_array;
use crate::naming;
use crate::types::*;

#[derive(Default)]
pub struct XmlOptions {}

pub fn generate(
    model: &IdlModel,
    idl_filename: &str,
    _opts: &XmlOptions,
) -> Result<String, String> {
    let mut gen = XmlGen { out: String::new(), indent: 0, model, refs: build_ref_map(model) };
    gen.emit_file(idl_filename)?;
    Ok(gen.out)
}

/// Any-form reference (leaf or qualified) -> fully-qualified name, so
/// `nonBasicTypeName`/`baseType` always carry a name the registry can resolve.
fn build_ref_map(model: &IdlModel) -> HashMap<String, String> {
    let mut refs = HashMap::new();
    let mut add = |name: &str, qname: &str| {
        refs.entry(qname.to_string()).or_insert_with(|| qname.to_string());
        refs.entry(name.to_string()).or_insert_with(|| qname.to_string());
    };
    for s in &model.structs {
        add(&s.name, &s.qualified_name);
    }
    for e in &model.enums {
        add(&e.name, &e.qualified_name);
    }
    for b in &model.bitmasks {
        add(&b.name, &b.qualified_name);
    }
    for b in &model.bitsets {
        add(&b.name, &b.qualified_name);
    }
    for u in &model.unions {
        add(&u.name, &u.qualified_name);
    }
    refs
}

struct XmlGen<'a> {
    out: String,
    indent: usize,
    model: &'a IdlModel,
    refs: HashMap<String, String>,
}

impl<'a> XmlGen<'a> {
    fn emit_file(&mut self, idl_filename: &str) -> Result<(), String> {
        self.line("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        self.line(&format!("<!-- Auto-generated by int2dds-idl from {} -->", idl_filename));
        self.line("<dds>");
        self.indent += 1;
        self.line("<types>");
        self.indent += 1;

        for e in &self.model.enums {
            self.emit_enum(e);
        }
        for b in &self.model.bitmasks {
            self.emit_bitmask(b);
        }
        for b in &self.model.bitsets {
            self.emit_bitset(b);
        }
        for u in &self.model.unions {
            self.emit_union(u)?;
        }
        for s in &self.model.structs {
            self.emit_struct(s)?;
        }

        self.indent -= 1;
        self.line("</types>");
        self.indent -= 1;
        self.line("</dds>");
        Ok(())
    }

    fn emit_enum(&mut self, e: &ResolvedEnum) {
        self.line(&format!("<enum name=\"{}\">", attr(&e.qualified_name)));
        self.indent += 1;
        for v in &e.variants {
            self.line(&format!(
                "<enumerator name=\"{}\" value=\"{}\"/>",
                attr(&naming::to_pascal_case(&v.name)),
                v.value
            ));
        }
        self.indent -= 1;
        self.line("</enum>");
    }

    fn emit_bitmask(&mut self, b: &ResolvedBitmask) {
        self.line(&format!(
            "<bitmask name=\"{}\" bit_bound=\"{}\">",
            attr(&b.qualified_name),
            b.bit_bound
        ));
        self.indent += 1;
        for f in &b.flags {
            self.line(&format!(
                "<bit_value name=\"{}\" position=\"{}\"/>",
                attr(&naming::to_pascal_case(&f.name)),
                f.position
            ));
        }
        self.indent -= 1;
        self.line("</bitmask>");
    }

    fn emit_bitset(&mut self, b: &ResolvedBitset) {
        self.line(&format!("<bitset name=\"{}\">", attr(&b.qualified_name)));
        self.indent += 1;
        for f in &b.fields {
            self.line(&format!(
                "<bitfield name=\"{}\" bit_bound=\"{}\" type=\"{}\"/>",
                attr(&f.name),
                f.bit_width,
                bitfield_holder_name(f.bit_width)
            ));
        }
        self.indent -= 1;
        self.line("</bitset>");
    }

    fn emit_union(&mut self, u: &ResolvedUnion) -> Result<(), String> {
        let mut open = format!("<union name=\"{}\"", attr(&u.qualified_name));
        if let Some(ext) = extensibility_attr(u.extensibility) {
            open.push_str(&format!(" extensibility=\"{}\"", ext));
        }
        open.push('>');
        self.line(&open);
        self.indent += 1;

        self.line(&format!("<discriminator {}/>", self.discriminator_attrs(&u.discriminant_type)?));

        for case in &u.cases {
            self.line("<case>");
            self.indent += 1;
            for label in &case.labels {
                self.line(&format!("<caseDiscriminator value=\"{}\"/>", attr(&label_value(label))));
            }
            let name = naming::to_pascal_case(&case.member.name);
            self.emit_member_named(&name, &case.member.resolved_type, "")?;
            self.indent -= 1;
            self.line("</case>");
        }
        if let Some(dc) = &u.default_case {
            self.line("<case>");
            self.indent += 1;
            self.line("<caseDiscriminator value=\"default\"/>");
            let name = naming::to_pascal_case(&dc.name);
            self.emit_member_named(&name, &dc.resolved_type, "")?;
            self.indent -= 1;
            self.line("</case>");
        }

        self.indent -= 1;
        self.line("</union>");
        Ok(())
    }

    fn emit_struct(&mut self, s: &ResolvedStruct) -> Result<(), String> {
        let mut open = format!("<struct name=\"{}\"", attr(&s.qualified_name));
        if let Some(base) = &s.base_type {
            open.push_str(&format!(" baseType=\"{}\"", attr(&self.resolve_ref(base))));
        }
        if let Some(ext) = extensibility_attr(s.extensibility) {
            open.push_str(&format!(" extensibility=\"{}\"", ext));
        }
        if matches!(s.autoid, Some(AutoIdKind::Hash)) {
            open.push_str(" autoid=\"hash\"");
        }
        open.push('>');
        self.line(&open);
        self.indent += 1;
        for m in &s.members {
            self.emit_member(m)?;
        }
        self.indent -= 1;
        self.line("</struct>");
        Ok(())
    }

    fn emit_member(&mut self, m: &ResolvedMember) -> Result<(), String> {
        let mut extra = String::new();
        if m.is_key {
            extra.push_str(" key=\"true\"");
        }
        // A @hashid member is written as hashid=; otherwise any resolved id (explicit
        // or autoid-hash) is emitted verbatim — the value is what the registry recomputes.
        if let Some(hashid) = &m.hashid {
            extra.push_str(&format!(" hashid=\"{}\"", attr(hashid.as_deref().unwrap_or(""))));
        } else if let Some(id) = m.member_id {
            extra.push_str(&format!(" id=\"{}\"", id));
        }
        if m.is_optional {
            extra.push_str(" optional=\"true\"");
        }
        if m.is_external {
            extra.push_str(" external=\"true\"");
        }
        if m.must_understand {
            extra.push_str(" mustUnderstand=\"true\"");
        }
        self.emit_member_named(&m.name, &m.resolved_type, &extra)
    }

    fn emit_member_named(
        &mut self,
        name: &str,
        ty: &ResolvedType,
        extra: &str,
    ) -> Result<(), String> {
        let type_attrs = self.type_spec_attrs(ty)?;
        self.line(&format!("<member name=\"{}\" {}{}/>", attr(name), type_attrs, extra));
        Ok(())
    }

    /// Flat type-spec attributes for a member. Errors on a collection nested directly
    /// in another collection (only array-of-sequence is expressible in attributes).
    fn type_spec_attrs(&self, ty: &ResolvedType) -> Result<String, String> {
        match ty {
            ResolvedType::Sequence { element, bound } => {
                self.ensure_base(element)?;
                Ok(format!(
                    "{} sequenceMaxLength=\"{}\"",
                    self.base_attrs(element)?,
                    seq_bound(bound)
                ))
            }
            ResolvedType::Array { .. } => {
                let (dims, inner) = flatten_array(ty);
                match inner {
                    ResolvedType::Sequence { element, bound } => {
                        self.ensure_base(element)?;
                        Ok(format!(
                            "{} sequenceMaxLength=\"{}\" arrayDimensions=\"{}\"",
                            self.base_attrs(element)?,
                            seq_bound(bound),
                            join_dims(&dims)
                        ))
                    }
                    ResolvedType::Map { .. } => {
                        Err("XML codegen: array of map is not expressible in XML".to_string())
                    }
                    base => Ok(format!(
                        "{} arrayDimensions=\"{}\"",
                        self.base_attrs(base)?,
                        join_dims(&dims)
                    )),
                }
            }
            ResolvedType::Map { key, value, bound } => {
                self.ensure_base(value)?;
                let mut attrs =
                    format!("{} key_type=\"{}\"", self.base_attrs(value)?, self.map_key_name(key)?);
                if let Some(n) = bound {
                    attrs.push_str(&format!(" mapMaxLength=\"{}\"", n));
                }
                Ok(attrs)
            }
            base => self.base_attrs(base),
        }
    }

    fn base_attrs(&self, ty: &ResolvedType) -> Result<String, String> {
        Ok(match ty {
            ResolvedType::Struct(name) | ResolvedType::Enum(name) | ResolvedType::Bitmask(name) => {
                format!("type=\"nonBasic\" nonBasicTypeName=\"{}\"", attr(&self.resolve_ref(name)))
            }
            ResolvedType::String { bound } => string_attrs("string", bound),
            ResolvedType::WString { bound } => string_attrs("wstring", bound),
            ResolvedType::Sequence { .. }
            | ResolvedType::Array { .. }
            | ResolvedType::Map { .. } => {
                return Err(format!("XML codegen: {:?} is not a scalar/base type", ty))
            }
            scalar => format!("type=\"{}\"", scalar_name(scalar)),
        })
    }

    fn discriminator_attrs(&self, ty: &ResolvedType) -> Result<String, String> {
        match ty {
            ResolvedType::Enum(_)
            | ResolvedType::Bool
            | ResolvedType::U8
            | ResolvedType::UInt8
            | ResolvedType::I8
            | ResolvedType::I16
            | ResolvedType::U16
            | ResolvedType::I32
            | ResolvedType::U32
            | ResolvedType::I64
            | ResolvedType::U64
            | ResolvedType::Char
            | ResolvedType::WChar => self.base_attrs(ty),
            _ => Err(format!("XML codegen: invalid union discriminator type {:?}", ty)),
        }
    }

    fn map_key_name(&self, key: &ResolvedType) -> Result<&'static str, String> {
        match key {
            ResolvedType::String { .. } => Ok("string"),
            ResolvedType::WString { .. } => Ok("wstring"),
            ResolvedType::F32 | ResolvedType::F64 => {
                Err(format!("XML codegen: map key {:?} must be integral or string", key))
            }
            ResolvedType::Bool
            | ResolvedType::U8
            | ResolvedType::UInt8
            | ResolvedType::I8
            | ResolvedType::I16
            | ResolvedType::U16
            | ResolvedType::I32
            | ResolvedType::U32
            | ResolvedType::I64
            | ResolvedType::U64
            | ResolvedType::Char
            | ResolvedType::WChar => Ok(scalar_name(key)),
            other => Err(format!("XML codegen: map key {:?} must be integral or string", other)),
        }
    }

    fn ensure_base(&self, ty: &ResolvedType) -> Result<(), String> {
        match ty {
            ResolvedType::Sequence { .. }
            | ResolvedType::Array { .. }
            | ResolvedType::Map { .. } => {
                Err("XML codegen: a collection nested in another collection is not expressible in \
                     XML; introduce a named typedef/struct for the inner type"
                    .to_string())
            }
            _ => Ok(()),
        }
    }

    fn resolve_ref(&self, name: &str) -> String {
        self.refs.get(name).cloned().unwrap_or_else(|| name.to_string())
    }

    fn line(&mut self, text: &str) {
        for _ in 0..self.indent {
            self.out.push_str("  ");
        }
        self.out.push_str(text);
        self.out.push('\n');
    }
}

fn join_dims(dims: &[u32]) -> String {
    dims.iter().map(u32::to_string).collect::<Vec<_>>().join(",")
}

fn seq_bound(bound: &Option<u32>) -> String {
    bound.map_or_else(|| "-1".to_string(), |n| n.to_string())
}

fn string_attrs(kind: &str, bound: &Option<u32>) -> String {
    match bound {
        Some(n) => format!("type=\"{}\" stringMaxLength=\"{}\"", kind, n),
        None => format!("type=\"{}\"", kind),
    }
}

/// Scalar primitive XML name. `u8`/`char` map to `byte`/`char8` to match the
/// TypeIdentifier the derive macro registers for the Rust storage type.
fn scalar_name(ty: &ResolvedType) -> &'static str {
    match ty {
        ResolvedType::Bool => "boolean",
        ResolvedType::U8 => "byte",
        ResolvedType::UInt8 => "uint8",
        ResolvedType::I8 => "int8",
        ResolvedType::I16 => "int16",
        ResolvedType::U16 => "uint16",
        ResolvedType::I32 => "int32",
        ResolvedType::U32 => "uint32",
        ResolvedType::I64 => "int64",
        ResolvedType::U64 => "uint64",
        ResolvedType::F32 => "float32",
        ResolvedType::F64 => "float64",
        ResolvedType::Char => "char8",
        ResolvedType::WChar => "char16",
        _ => "",
    }
}

/// Appendable is the parser default, so left implicit (matching the Rust backend).
fn extensibility_attr(ext: ExtensibilityKind) -> Option<&'static str> {
    match ext {
        ExtensibilityKind::Appendable => None,
        ExtensibilityKind::Final => Some("final"),
        ExtensibilityKind::Mutable => Some("mutable"),
    }
}

fn label_value(label: &ResolvedUnionLabel) -> String {
    match label {
        ResolvedUnionLabel::Int(v) => v.to_string(),
        ResolvedUnionLabel::Bool(v) => if *v { "1" } else { "0" }.to_string(),
        ResolvedUnionLabel::Ident(name) => name.clone(),
    }
}

/// Holder TypeIdentifier the derive macro registers for the Rust storage type:
/// u8 -> BYTE, u16 -> UINT16, u32 -> UINT32, u64 -> UINT64.
fn bitfield_holder_name(bit_width: u32) -> &'static str {
    match bit_width {
        0..=8 => "byte",
        9..=16 => "uint16",
        17..=32 => "uint32",
        _ => "uint64",
    }
}

fn attr(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;").replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_idl;
    use crate::resolver::resolve;

    fn gen(idl: &str) -> String {
        let model = resolve(parse_idl(idl).unwrap()).unwrap();
        generate(&model, "test.idl", &XmlOptions::default()).unwrap()
    }

    fn gen_err(idl: &str) -> String {
        let model = resolve(parse_idl(idl).unwrap()).unwrap();
        generate(&model, "test.idl", &XmlOptions::default()).unwrap_err()
    }

    #[test]
    fn struct_header_and_primitives() {
        let xml =
            gen("struct HelloWorld { unsigned long index; string message; octet raw; char c; };");
        assert!(xml.starts_with("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"));
        assert!(xml.contains("<dds>\n  <types>\n"));
        assert!(xml.contains("<struct name=\"HelloWorld\">"));
        assert!(xml.contains("<member name=\"index\" type=\"uint32\"/>"));
        assert!(xml.contains("<member name=\"message\" type=\"string\"/>"));
        assert!(xml.contains("<member name=\"raw\" type=\"byte\"/>"));
        assert!(xml.contains("<member name=\"c\" type=\"char8\"/>"));
    }

    #[test]
    fn keyed_bound_and_extensibility() {
        let xml = gen(
            "@extensibility(FINAL) struct S { @key long id; string<128> loc; sequence<long,10> xs; };",
        );
        assert!(xml.contains("<struct name=\"S\" extensibility=\"final\">"));
        assert!(xml.contains("<member name=\"id\" type=\"int32\" key=\"true\"/>"));
        assert!(xml.contains("<member name=\"loc\" type=\"string\" stringMaxLength=\"128\"/>"));
        assert!(xml.contains("<member name=\"xs\" type=\"int32\" sequenceMaxLength=\"10\"/>"));
    }

    #[test]
    fn annotations_id_hashid_autoid() {
        let xml = gen(
            "@autoid(HASH) @extensibility(MUTABLE) struct A { @id(10) @key long a; @hashid(\"crc\") long b; @must_understand short c; };",
        );
        assert!(xml.contains("extensibility=\"mutable\""));
        assert!(xml.contains("autoid=\"hash\""));
        assert!(xml.contains("<member name=\"a\" type=\"int32\" key=\"true\" id=\"10\"/>"));
        assert!(xml.contains("<member name=\"b\" type=\"int32\" hashid=\"crc\"/>"));
        // autoid=hash gives c a recomputed id; just check the type and flag survive
        assert!(xml.contains("name=\"c\" type=\"int16\""));
        assert!(xml.contains("mustUnderstand=\"true\"/>"));
    }

    #[test]
    fn enum_with_values() {
        let xml = gen("enum Color { RED, GREEN = 5, BLUE };");
        assert!(xml.contains("<enum name=\"Color\">"));
        // enum literal names are PascalCased to match the derive variant identifiers
        assert!(xml.contains("<enumerator name=\"Red\" value=\"0\"/>"));
        assert!(xml.contains("<enumerator name=\"Green\" value=\"5\"/>"));
        assert!(xml.contains("<enumerator name=\"Blue\" value=\"6\"/>"));
    }

    #[test]
    fn map_and_wstring() {
        let xml = gen("struct M { map<long,string> a; map<string,double,100> b; wstring w; };");
        assert!(xml.contains("<member name=\"a\" type=\"string\" key_type=\"int32\"/>"));
        assert!(xml.contains(
            "<member name=\"b\" type=\"float64\" key_type=\"string\" mapMaxLength=\"100\"/>"
        ));
        assert!(xml.contains("<member name=\"w\" type=\"wstring\"/>"));
    }

    #[test]
    fn nested_struct_and_inheritance() {
        let xml = gen(
            "struct Inner { long v; }; struct Outer : Inner { Inner inner; sequence<Inner> xs; Inner arr[3]; };",
        );
        assert!(xml.contains("<struct name=\"Outer\" baseType=\"Inner\">"));
        assert!(
            xml.contains("<member name=\"inner\" type=\"nonBasic\" nonBasicTypeName=\"Inner\"/>")
        );
        assert!(xml.contains(
            "<member name=\"xs\" type=\"nonBasic\" nonBasicTypeName=\"Inner\" sequenceMaxLength=\"-1\"/>"
        ));
        assert!(xml.contains(
            "<member name=\"arr\" type=\"nonBasic\" nonBasicTypeName=\"Inner\" arrayDimensions=\"3\"/>"
        ));
    }

    #[test]
    fn module_qualifies_names() {
        let xml = gen("module geo { struct Point { long x; }; struct Line { Point a; }; };");
        assert!(xml.contains("<struct name=\"geo::Point\">"));
        assert!(xml.contains("nonBasicTypeName=\"geo::Point\""));
    }

    #[test]
    fn bitmask_and_bitset() {
        let xml = gen(
            "@bit_bound(8) bitmask Flags { A, @position(3) B }; bitset Hdr { bitfield<4> ver; bitfield<12> len; };",
        );
        assert!(xml.contains("<bitmask name=\"Flags\" bit_bound=\"8\">"));
        assert!(xml.contains("<bit_value name=\"A\" position=\"0\"/>"));
        assert!(xml.contains("<bit_value name=\"B\" position=\"3\"/>"));
        assert!(xml.contains("<bitfield name=\"ver\" bit_bound=\"4\" type=\"byte\"/>"));
        assert!(xml.contains("<bitfield name=\"len\" bit_bound=\"12\" type=\"uint16\"/>"));
    }

    #[test]
    fn union_cases_and_default() {
        let xml = gen(
            "union U switch(long) { case 0: long a; case 1: case 2: string b; default: octet c; };",
        );
        assert!(xml.contains("<union name=\"U\">"));
        assert!(xml.contains("<discriminator type=\"int32\"/>"));
        assert!(xml.contains("<caseDiscriminator value=\"0\"/>"));
        assert!(xml.contains("<caseDiscriminator value=\"1\"/>"));
        assert!(xml.contains("<caseDiscriminator value=\"2\"/>"));
        // union case member names are PascalCased to match derive variant identifiers
        assert!(xml.contains("<member name=\"A\" type=\"int32\"/>"));
        assert!(xml.contains("<caseDiscriminator value=\"default\"/>"));
        assert!(xml.contains("<member name=\"C\" type=\"byte\"/>"));
    }

    #[test]
    fn array_of_sequence_is_supported() {
        // multi-dim array
        let xml = gen("struct G { long grid[2][3]; };");
        assert!(xml.contains("<member name=\"grid\" type=\"int32\" arrayDimensions=\"2,3\"/>"));
    }

    #[test]
    fn nested_collection_is_rejected() {
        let err = gen_err("struct N { sequence<sequence<long> > nested; };");
        assert!(err.contains("collection nested in another collection"), "{err}");
    }
}
