// Auto-generated by int2dds-idl from HelloWorld.idl
// DO NOT EDIT

package kr.co.intellectus.int2dds.examples;

import kr.co.intellectus.int2dds.cdr.CdrReader;
import kr.co.intellectus.int2dds.cdr.CdrWriter;
import kr.co.intellectus.int2dds.cdr.Extensibility;
import kr.co.intellectus.int2dds.types.IDdsType;
import kr.co.intellectus.int2dds.xtypes.FieldType;
import kr.co.intellectus.int2dds.xtypes.TypeInfo;

public final class HelloWorld implements IDdsType {

    public int index;
    public String message = "";

    @Override
    public String typeName() {
        return "HelloWorld";
    }

    @Override
    public Extensibility extensibility() {
        return Extensibility.APPENDABLE;
    }

    @Override
    public void serializeCdr(CdrWriter writer) {
        int token = writer.dheaderBegin();
        writer.writeU32(this.index);
        writer.writeString(this.message);
        writer.dheaderFinalize(token);
    }

    @Override
    public void deserializeCdr(CdrReader reader) {
        CdrReader.Dheader d = reader.readDheader();
        this.index = reader.readU32();
        this.message = reader.readString();
        reader.readDheaderEnd(d);
    }

    @Override
    public TypeInfo typeInfo() {
        TypeInfo ti = new TypeInfo("HelloWorld", Extensibility.APPENDABLE);
        try {
            ti.addField("index", FieldType.UINT32, 0);
            ti.addStringField("message", 0, 0);
            return ti;
        } catch (RuntimeException e) {
            ti.close();
            throw e;
        }
    }
}
