// Auto-generated by int2dds-idl from CdrGolden.idl
// DO NOT EDIT

package kr.co.intellectus.int2dds.types;

import kr.co.intellectus.int2dds.cdr.CdrReader;
import kr.co.intellectus.int2dds.cdr.CdrWriter;
import kr.co.intellectus.int2dds.cdr.Extensibility;
import kr.co.intellectus.int2dds.types.IDdsType;
import kr.co.intellectus.int2dds.xtypes.FieldType;
import kr.co.intellectus.int2dds.xtypes.TypeInfo;

public final class CdrGoldenPoint implements IDdsType {

    public int x;
    public double y;

    @Override
    public String typeName() {
        return "CdrGoldenPoint";
    }

    @Override
    public Extensibility extensibility() {
        return Extensibility.FINAL;
    }

    @Override
    public void serializeCdr(CdrWriter writer) {
        writer.writeI32(this.x);
        writer.writeF64(this.y);
    }

    @Override
    public void deserializeCdr(CdrReader reader) {
        this.x = reader.readI32();
        this.y = reader.readF64();
    }

    @Override
    public TypeInfo typeInfo() {
        TypeInfo ti = new TypeInfo("CdrGoldenPoint", Extensibility.FINAL);
        try {
            ti.addField("x", FieldType.INT32, 0);
            ti.addField("y", FieldType.FLOAT64, 0);
            return ti;
        } catch (RuntimeException e) {
            ti.close();
            throw e;
        }
    }
}
