//! DDS-RPC common types (7.5.1.1.1)

use std::any::Any;

use int2dds::dcps::core::error::{DdsError, DdsResult};
use int2dds::dcps::topic::type_support::{DdsType, FieldAccessor};
use int2dds::topic::sql::ast::Parameter;

// Re-export DDS layer types used for constructing SampleIdentity
pub use int2dds::rtps::common::guid::Guid;
pub use int2dds::rtps::common::sequence::SequenceNumber;

// Local SequenceNumber with DdsType derive for SampleIdentity field access.
// The original SequenceNumber in dds crate cannot have DdsType derived
// due to trait conflicts.
#[derive(int2dds_derive::DdsType, Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RpcSequenceNumber {
    pub high: i32,
    pub low: u32,
}

impl From<SequenceNumber> for RpcSequenceNumber {
    fn from(sn: SequenceNumber) -> Self {
        Self { high: sn.high, low: sn.low }
    }
}

impl From<RpcSequenceNumber> for SequenceNumber {
    fn from(sn: RpcSequenceNumber) -> Self {
        Self::new(sn.high, sn.low)
    }
}

// TypeSupport (serialize/deserialize) is auto-generated by DdsType derive.
// FieldAccessor is manually implemented for custom QueryCondition support.
#[derive(int2dds_derive::DdsType, Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[dds_type(crate_path = "int2dds", no_additional_derives, skip_field_accessor)]
pub struct SampleIdentity {
    pub writer_guid: Guid,
    pub sequence_number: RpcSequenceNumber,
}

// QueryCondition support for SampleIdentity (7.2.3)
//
// writer_guid is compared as a 32-char hex string.
// sequence_number is compared via nested .high (i32) and .low (u32) fields.
// This enables SQL filter expressions like:
//   "header.related_request_id.writer_guid = %0
//    AND header.related_request_id.sequence_number.high = %1
//    AND header.related_request_id.sequence_number.low = %2"

#[derive(Default)]
pub struct SampleIdentityFieldAccessor;

impl FieldAccessor for SampleIdentityFieldAccessor {
    fn get_field_value(&self, data: &dyn Any, field_path: &str) -> DdsResult<Parameter> {
        let typed = data.downcast_ref::<SampleIdentity>().ok_or(DdsError::BadParameter)?;

        if let Some((first, rest)) = field_path.split_once('.') {
            match first {
                "sequence_number" => match rest {
                    "high" => Ok(Parameter::IntegerValue(typed.sequence_number.high)),
                    "low" => Ok(Parameter::IntegerValue(typed.sequence_number.low as i32)),
                    _ => Err(DdsError::Error(format!("Field '{}' not found", field_path))),
                },
                _ => Err(DdsError::Error(format!("Field '{}' not found", first))),
            }
        } else {
            match field_path {
                "writer_guid" => Ok(Parameter::String(typed.writer_guid.to_hex_string())),
                _ => Err(DdsError::Error(format!("Field '{}' not found", field_path))),
            }
        }
    }

    fn has_field(&self, field_path: &str) -> bool {
        matches!(field_path, "writer_guid" | "sequence_number.high" | "sequence_number.low")
    }
}

impl DdsType for SampleIdentity {
    type TypeSupport = SampleIdentityTypeSupport;
    type FieldAccessor = SampleIdentityFieldAccessor;
}

pub type InstanceName = String; // max 255 chars

#[derive(int2dds_derive::DdsType, Debug, Clone, Default)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct RequestHeader {
    pub request_id: SampleIdentity,
    pub instance_name: InstanceName,
}

#[derive(int2dds_derive::DdsType, Debug, Clone, Default)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
pub struct ReplyHeader {
    pub related_request_id: SampleIdentity,
    pub remote_ex: RemoteExceptionCode,
}

#[derive(int2dds_derive::DdsType, Debug, Clone, Copy, PartialEq, Eq, Default)]
#[dds_type(crate_path = "int2dds", no_additional_derives)]
#[repr(i32)]
pub enum RemoteExceptionCode {
    #[default]
    Ok = 0,
    Unsupported = 1,
    InvalidArgument = 2,
    OutOfResources = 3,
    UnknownOperation = 4,
    UnknownException = 5,
}

/// Trait for types that carry a RequestHeader (Basic Service Mapping).
/// User-defined request types must implement this.
pub trait RpcRequest {
    fn header(&self) -> &RequestHeader;
    fn header_mut(&mut self) -> &mut RequestHeader;
}

/// Trait for types that carry a ReplyHeader (Basic Service Mapping).
/// User-defined reply types must implement this.
pub trait RpcReply {
    fn header(&self) -> &ReplyHeader;
    fn header_mut(&mut self) -> &mut ReplyHeader;
}

/// Default case in Call/Return unions for unrecognized operations (7.5.1.1.6, 7.5.1.1.7)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct UnknownOperation;

/// Default case in Result unions for unrecognized exceptions
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct UnknownException;

/// Dummy member for In/Out structs with no parameters (7.5.1.1.4)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct UnusedMember;

/// Re-export from DDS layer (7.5.1.1.5 Rule 3)
pub use int2dds::dcps::core::error::RETCODE_OK;

#[cfg(test)]
mod tests {
    use super::*;
    use int2dds::rtps::common::entity_id::EntityId;

    fn make_test_identity() -> SampleIdentity {
        let prefix = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c];
        let entity_id = EntityId {
            entity_key: [0x0d, 0x0e, 0x0f],
            entity_kind: int2dds::rtps::common::entity_kind::EntityKind(0x10),
        };
        SampleIdentity {
            writer_guid: Guid::new(prefix, entity_id),
            sequence_number: SequenceNumber::new(0, 42).into(),
        }
    }

    #[test]
    fn test_get_field_value_writer_guid() {
        let id = make_test_identity();
        let val = id.get_field_value("writer_guid").unwrap();
        assert_eq!(val, Parameter::String("0102030405060708090a0b0c0d0e0f10".to_string()));
    }

    #[test]
    fn test_get_field_value_sequence_number_high() {
        let id = make_test_identity();
        let val = id.get_field_value("sequence_number.high").unwrap();
        assert_eq!(val, Parameter::IntegerValue(0));
    }

    #[test]
    fn test_get_field_value_sequence_number_low() {
        let id = make_test_identity();
        let val = id.get_field_value("sequence_number.low").unwrap();
        assert_eq!(val, Parameter::IntegerValue(42));
    }

    #[test]
    fn test_has_field() {
        let id = make_test_identity();
        assert!(id.has_field("writer_guid").unwrap());
        assert!(id.has_field("sequence_number.high").unwrap());
        assert!(id.has_field("sequence_number.low").unwrap());
        assert!(!id.has_field("nonexistent").unwrap());
        assert!(!id.has_field("sequence_number").unwrap());
    }

    #[test]
    fn test_get_field_value_invalid_field() {
        let id = make_test_identity();
        assert!(id.get_field_value("nonexistent").is_err());
        assert!(id.get_field_value("sequence_number.invalid").is_err());
        assert!(id.get_field_value("writer_guid.prefix").is_err());
    }
}
