/**
 * Auto-generated by int2dds-idl from LatencyTestData.idl
 * DO NOT EDIT - changes will be overwritten
 */
#ifndef LATENCY_TEST_DATA_IDL_H
#define LATENCY_TEST_DATA_IDL_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "int2dds_cdr.h"

/* ========================================================================
 * Type: LatencyTestData
 * Extensibility: APPENDABLE
 * ======================================================================== */

typedef struct LatencyTestData {
    uint64_t seq_num;
    uint64_t send_timestamp;
    uint64_t echo_timestamp;
    struct { uint8_t* data; uint32_t length; } data;
} LatencyTestData;

static inline size_t LatencyTestData_serialize_cdr(
    const LatencyTestData *val,
    uint8_t *buf,
    size_t capacity)
{
    Int2DdsCdrWriter w;
    int2dds_cdr_writer_init(&w, buf, capacity, true, true);
    int2dds_cdr_write_encapsulation(&w, INT2DDS_CDR_APPENDABLE);
    size_t dh_token;
    int2dds_cdr_write_dheader_begin(&w, &dh_token);
    int2dds_cdr_write_u64(&w, val->seq_num);
    int2dds_cdr_write_u64(&w, val->send_timestamp);
    int2dds_cdr_write_u64(&w, val->echo_timestamp);
    int2dds_cdr_write_seq_header(&w, val->data.length);
    for (uint32_t _i = 0; _i < val->data.length; _i++) {
        int2dds_cdr_write_u8(&w, val->data.data[_i]);
    }
    int2dds_cdr_write_dheader_finalize(&w, dh_token);
    return w.error == INT2DDS_CDR_OK ? int2dds_cdr_writer_size(&w) : 0;
}

static inline bool LatencyTestData_deserialize_cdr(
    const uint8_t *buf,
    size_t len,
    LatencyTestData *val_out)
{
    Int2DdsCdrReader r;
    if (int2dds_cdr_reader_init(&r, buf, len) != INT2DDS_CDR_OK)
        return false;
    uint32_t dh_size; size_t dh_start;
    int2dds_cdr_read_dheader(&r, &dh_size, &dh_start);
    int2dds_cdr_read_u64(&r, &val_out->seq_num);
    int2dds_cdr_read_u64(&r, &val_out->send_timestamp);
    int2dds_cdr_read_u64(&r, &val_out->echo_timestamp);
    int2dds_cdr_read_seq_header(&r, &val_out->data.length);
    for (uint32_t _i = 0; _i < val_out->data.length; _i++) {
        int2dds_cdr_read_u8(&r, &val_out->data.data[_i]);
    }
    return int2dds_cdr_reader_error(&r) == INT2DDS_CDR_OK;
}

static inline size_t LatencyTestData_serialize_key(
    const LatencyTestData *val,
    uint8_t *buf,
    size_t capacity)
{
    (void)val; (void)buf; (void)capacity;
    return 0;
}

#endif /* LATENCY_TEST_DATA_IDL_H */
