/**
 * Auto-generated by int2dds-idl from Sequence_Enum.idl
 * DO NOT EDIT - changes will be overwritten
 */
#ifndef SEQUENCE__ENUM_IDL_H
#define SEQUENCE__ENUM_IDL_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "int2dds_cdr.h"

typedef enum Color {
    COLOR_RED = 0,
    COLOR_GREEN = 1,
    COLOR_BLUE = 2,
    COLOR_YELLOW = 3,
    COLOR_PURPLE = 4
} Color;

/* ========================================================================
 * Type: SequenceEnumType
 * Extensibility: APPENDABLE
 * ======================================================================== */

typedef struct SequenceEnumType {
    int32_t id;
    struct { Color* data; uint32_t length; } color_seq;
} SequenceEnumType;

static inline void SequenceEnumType_serialize_fields(
    Int2DdsCdrWriter *_w,
    const SequenceEnumType *val)
{
    Int2DdsCdrWriter w = *_w;
    size_t dh = 0;
    if (w.xcdr2) {
        int2dds_cdr_write_dheader_begin(&w, &dh);
    }
    int2dds_cdr_write_i32(&w, val->id);
    int2dds_cdr_write_seq_header(&w, val->color_seq.length);
    for (uint32_t _i = 0; _i < val->color_seq.length; _i++) {
        int2dds_cdr_write_enum(&w, (int32_t)val->color_seq.data[_i]);
    }
    if (w.xcdr2) {
        int2dds_cdr_write_dheader_finalize(&w, dh);
    }
    *_w = w;
}

static inline void SequenceEnumType_deserialize_fields(
    Int2DdsCdrReader *_r,
    SequenceEnumType *val_out)
{
    Int2DdsCdrReader r = *_r;
    uint32_t obj_size = 0;
    size_t start_pos = 0;
    if (r.xcdr2) {
        int2dds_cdr_read_dheader(&r, &obj_size, &start_pos);
    }
    int2dds_cdr_read_i32(&r, &val_out->id);
    int2dds_cdr_read_seq_header(&r, &val_out->color_seq.length);
    for (uint32_t _i = 0; _i < val_out->color_seq.length; _i++) {
        int2dds_cdr_read_enum(&r, (int32_t*)&val_out->color_seq.data[_i]);
    }
    if (r.xcdr2) {
        int2dds_cdr_read_dheader_end(&r, obj_size, start_pos);
    }
    *_r = r;
}

static inline size_t SequenceEnumType_serialize_cdr(
    const SequenceEnumType *val,
    uint8_t *buf,
    size_t capacity,
    bool xcdr2)
{
    Int2DdsCdrWriter w;
    int2dds_cdr_writer_init(&w, buf, capacity, true, xcdr2);
    int2dds_cdr_write_encapsulation(&w, INT2DDS_CDR_APPENDABLE);
    size_t dh = 0;
    if (xcdr2) {
        int2dds_cdr_write_dheader_begin(&w, &dh);
    }
    int2dds_cdr_write_i32(&w, val->id);
    int2dds_cdr_write_seq_header(&w, val->color_seq.length);
    for (uint32_t _i = 0; _i < val->color_seq.length; _i++) {
        int2dds_cdr_write_enum(&w, (int32_t)val->color_seq.data[_i]);
    }
    if (xcdr2) {
        int2dds_cdr_write_dheader_finalize(&w, dh);
    }
    return w.error == INT2DDS_CDR_OK ? int2dds_cdr_writer_size(&w) : 0;
}

static inline bool SequenceEnumType_deserialize_cdr(
    const uint8_t *buf,
    size_t len,
    SequenceEnumType *val_out)
{
    Int2DdsCdrReader r;
    if (int2dds_cdr_reader_init(&r, buf, len) != INT2DDS_CDR_OK)
        return false;
    uint32_t obj_size = 0;
    size_t start_pos = 0;
    if (r.xcdr2) {
        int2dds_cdr_read_dheader(&r, &obj_size, &start_pos);
    }
    int2dds_cdr_read_i32(&r, &val_out->id);
    int2dds_cdr_read_seq_header(&r, &val_out->color_seq.length);
    for (uint32_t _i = 0; _i < val_out->color_seq.length; _i++) {
        int2dds_cdr_read_enum(&r, (int32_t*)&val_out->color_seq.data[_i]);
    }
    if (r.xcdr2) {
        int2dds_cdr_read_dheader_end(&r, obj_size, start_pos);
    }
    return int2dds_cdr_reader_error(&r) == INT2DDS_CDR_OK;
}

static inline size_t SequenceEnumType_serialize_key(
    const SequenceEnumType *val,
    uint8_t *buf,
    size_t capacity)
{
    Int2DdsCdrWriter w;
    int2dds_cdr_writer_init(&w, buf, capacity, false, true); /* BE, XCDR2, no header */
    int2dds_cdr_write_i32(&w, val->id);
    return w.error == INT2DDS_CDR_OK ? int2dds_cdr_writer_size(&w) : 0;
}

static inline Int2DdsTypeInfo* SequenceEnumType_type_info(void) {
    Int2DdsTypeInfo *ti;
    int2dds_type_info_create("SequenceEnumType", 1, &ti);
    int2dds_type_info_add_field(ti, "id", INT2DDS_FIELD_INT32, 1);
    int2dds_type_info_add_sequence_field(ti, "color_seq", INT2DDS_FIELD_ENUM, 0, 0);
    return ti;
}

#endif /* SEQUENCE__ENUM_IDL_H */
