//! Auto-generated by int2dds-idl from HelloWorld.idl
//! DO NOT EDIT - changes will be overwritten

use int2dds::DdsType;

#[derive(Debug, Clone, PartialEq, DdsType)]
pub struct HelloWorld {
    pub index: u32,
    pub message: String,
}

