//! Auto-generated by int2dds-idl from PerformanceTestData.idl
//! DO NOT EDIT - changes will be overwritten

use int2dds::prelude::*;
use int2dds_derive::DdsType;

#[derive(Debug, Clone, PartialEq, DdsType)]
pub struct PerformanceTestData {
    pub seq_num: u64,
    pub timestamp: u64,
    pub data: Vec<u8>,
}

