//! # Type Info Builder
//!
//! Provides `Int2DdsTypeInfo` for building DDS-XTypes TypeIdentifier and TypeObject
//! from field descriptions. This enables the FFI layer to send type information
//! during discovery (sent as PID_TYPE_INFORMATION 0x0075 + legacy 0x0069). The
//! full TypeObject is served on demand via TypeLookup, not inlined into SEDP.
//!
//! ## Usage from C
//!
//! ```c
//! Int2DdsTypeInfo *ti = PrimitivesType_type_info(); // auto-generated by IDL
//! int2dds_create_topic_with_type_info(participant, "TopicName", ti, NULL, &topic);
//! int2dds_type_info_destroy(ti);
//! ```

use std::ffi::CStr;

use int2dds::{
    serialize::cdr::ExtensibilityKind,
    xtypes::{
        plain_collection_equiv_kind, plain_map_identifier, CollectionElementFlag,
        CommonStructMember, CompleteBitfield, CompleteBitflag, CompleteBitmaskType,
        CompleteBitsetType, CompleteEnumeratedLiteral, CompleteEnumeratedType,
        CompleteMemberDetail, CompleteStructMember, CompleteStructType, CompleteTypeObject,
        CompleteUnionMember, CompleteUnionType, EnumeratedLiteralFlag, EquivalenceHash, MemberFlag,
        PlainCollectionHeader, TryConstructKind, TypeFlag, TypeIdentifier, TypeObject,
    },
};

use super::error::*;

/// Decode a C string argument to `&str`, returning `INT2DDS_RET_INVALID_ARGUMENT`
/// when it is not valid UTF-8. Caller must have already null-checked the pointer.
macro_rules! cstr_arg {
    ($ptr:expr) => {
        match CStr::from_ptr($ptr).to_str() {
            Ok(s) => s,
            Err(_) => return INT2DDS_RET_INVALID_ARGUMENT,
        }
    };
}

/// Field type constants for C FFI.
pub const INT2DDS_FIELD_BOOL: i32 = 0;
pub const INT2DDS_FIELD_BYTE: i32 = 1;
pub const INT2DDS_FIELD_CHAR8: i32 = 2;
pub const INT2DDS_FIELD_INT8: i32 = 3;
pub const INT2DDS_FIELD_INT16: i32 = 4;
pub const INT2DDS_FIELD_INT32: i32 = 5;
pub const INT2DDS_FIELD_INT64: i32 = 6;
pub const INT2DDS_FIELD_UINT8: i32 = 7;
pub const INT2DDS_FIELD_UINT16: i32 = 8;
pub const INT2DDS_FIELD_UINT32: i32 = 9;
pub const INT2DDS_FIELD_UINT64: i32 = 10;
pub const INT2DDS_FIELD_FLOAT32: i32 = 11;
pub const INT2DDS_FIELD_FLOAT64: i32 = 12;
pub const INT2DDS_FIELD_STRING: i32 = 13;
pub const INT2DDS_FIELD_CHAR16: i32 = 14;
pub const INT2DDS_FIELD_WSTRING: i32 = 15;
pub const INT2DDS_FIELD_NESTED: i32 = 16;
pub const INT2DDS_FIELD_SEQUENCE: i32 = 17;
pub const INT2DDS_FIELD_ARRAY: i32 = 18;
pub const INT2DDS_FIELD_MAP: i32 = 19;
pub const INT2DDS_MEMBER_KEY: i32 = 1 << 0;
pub const INT2DDS_MEMBER_OPTIONAL: i32 = 1 << 1;
pub const INT2DDS_MEMBER_MUST_UNDERSTAND: i32 = 1 << 2;
pub const INT2DDS_MEMBER_EXTERNAL: i32 = 1 << 3;
/// Marks the `default:` case member of a union builder (`IS_DEFAULT`); ignored on structs.
pub const INT2DDS_MEMBER_DEFAULT: i32 = 1 << 4;

/// Internal field description. `labels` is only populated on union builders.
struct FieldInfo {
    name: String,
    type_id: TypeIdentifier,
    flags: i32,
    labels: Vec<i32>,
}

impl FieldInfo {
    fn is_key(&self) -> bool {
        self.flags & INT2DDS_MEMBER_KEY != 0
    }
    fn is_optional(&self) -> bool {
        self.flags & INT2DDS_MEMBER_OPTIONAL != 0
    }
    fn is_must_understand(&self) -> bool {
        self.flags & INT2DDS_MEMBER_MUST_UNDERSTAND != 0
    }
    fn is_external(&self) -> bool {
        self.flags & INT2DDS_MEMBER_EXTERNAL != 0
    }
    fn is_default(&self) -> bool {
        self.flags & INT2DDS_MEMBER_DEFAULT != 0
    }
}

/// One enum literal: discriminant `value`, `name`, and whether it is the `@default` literal.
struct EnumLiteral {
    value: i32,
    name: String,
    is_default: bool,
}

/// One bitmask flag: bit `position` and `name`.
struct BitFlag {
    position: u16,
    name: String,
}

/// One bitset field: cumulative bit `position`, `bitcount`, and the primitive holder
/// type the derive macro assigns from the Rust field type.
struct BitsetField {
    name: String,
    position: u16,
    bitcount: u8,
    holder_type: TypeIdentifier,
}

/// The kind-specific body of a type info builder. `Struct` and `Union` use the builder's
/// `fields` (union case members carry their labels); `Enum`/`Bitmask`/`Bitset` carry
/// their own literals/flags/bitfields. This lets a single builder represent any named
/// type a member can reference, so the content-hash nested machinery
/// (`push_nested_field`, seq/array/map-of-nested) works uniformly — matching the derive
/// macro's `<FieldType>::type_identifier()`.
enum TypeInfoBody {
    Struct,
    Enum { bit_bound: u16, literals: Vec<EnumLiteral> },
    Bitmask { bit_bound: u16, flags: Vec<BitFlag> },
    Bitset { fields: Vec<BitsetField> },
    Union { discriminator: TypeIdentifier },
}

/// Opaque type info builder for the FFI layer.
///
/// Collects field descriptions and builds TypeIdentifier/TypeObject
/// for DDS-XTypes discovery.
pub struct Int2DdsTypeInfo {
    pub(crate) type_name: String,
    pub(crate) extensibility: ExtensibilityKind,
    body: TypeInfoBody,
    fields: Vec<FieldInfo>,
    /// Transitive closure of nested `TypeObject`s referenced by struct-typed members,
    /// keyed by the content-hash `CompleteTypeId` the member points at. Empty for flat
    /// types. Fed into a `TypeRegistry` at topic creation so composite (nested-struct)
    /// key members resolve and compute the same InstanceHandle as native Rust.
    dependencies: Vec<(TypeIdentifier, TypeObject)>,
}

impl Int2DdsTypeInfo {
    /// Assemble an empty struct builder from Rust (e.g. `create_topic_with_field_descriptors`),
    /// without going through the C `int2dds_type_info_create` handle path.
    pub(crate) fn new(type_name: String, extensibility: ExtensibilityKind) -> Self {
        Self {
            type_name,
            extensibility,
            body: TypeInfoBody::Struct,
            fields: Vec::new(),
            dependencies: Vec::new(),
        }
    }

    /// Assemble an enum builder. Enums have no extensibility of their own (they are leaf
    /// types); `Final` is stored as a placeholder and never consulted for enums.
    pub(crate) fn new_enum(type_name: String, bit_bound: u16) -> Self {
        Self {
            type_name,
            extensibility: ExtensibilityKind::Final,
            body: TypeInfoBody::Enum { bit_bound, literals: Vec::new() },
            fields: Vec::new(),
            dependencies: Vec::new(),
        }
    }

    /// Assemble a bitmask builder.
    pub(crate) fn new_bitmask(type_name: String, bit_bound: u16) -> Self {
        Self {
            type_name,
            extensibility: ExtensibilityKind::Final,
            body: TypeInfoBody::Bitmask { bit_bound, flags: Vec::new() },
            fields: Vec::new(),
            dependencies: Vec::new(),
        }
    }

    /// Assemble a bitset builder. Bitfields are appended with `push_bitfield`, which
    /// assigns positions cumulatively in declaration order like the derive macro.
    pub(crate) fn new_bitset(type_name: String) -> Self {
        Self {
            type_name,
            extensibility: ExtensibilityKind::Final,
            body: TypeInfoBody::Bitset { fields: Vec::new() },
            fields: Vec::new(),
            dependencies: Vec::new(),
        }
    }

    /// Assemble a union builder whose discriminator is `discriminator`. Case members are
    /// appended with the same `push_*_field` calls a struct uses (member ids follow
    /// declaration order) and select on the labels added via `push_union_label`; the
    /// `default:` member carries `INT2DDS_MEMBER_DEFAULT` in its flags.
    pub(crate) fn new_union(
        type_name: String,
        extensibility: ExtensibilityKind,
        discriminator: TypeIdentifier,
    ) -> Self {
        Self {
            type_name,
            extensibility,
            body: TypeInfoBody::Union { discriminator },
            fields: Vec::new(),
            dependencies: Vec::new(),
        }
    }

    /// Append an enum literal. No-op if this builder is not an enum.
    pub(crate) fn push_enum_literal(&mut self, name: String, value: i32, is_default: bool) {
        if let TypeInfoBody::Enum { literals, .. } = &mut self.body {
            literals.push(EnumLiteral { value, name, is_default });
        }
    }

    /// Append a bitmask flag. No-op if this builder is not a bitmask.
    pub(crate) fn push_bitmask_flag(&mut self, name: String, position: u16) {
        if let TypeInfoBody::Bitmask { flags, .. } = &mut self.body {
            flags.push(BitFlag { position, name });
        }
    }

    /// Append a bitfield of `bitcount` bits held in `holder_type`, positioned right after
    /// the previous bitfield. No-op if this builder is not a bitset.
    pub(crate) fn push_bitfield(
        &mut self,
        name: String,
        bitcount: u8,
        holder_type: TypeIdentifier,
    ) {
        if let TypeInfoBody::Bitset { fields } = &mut self.body {
            let position = fields.iter().map(|f| u16::from(f.bitcount)).sum();
            fields.push(BitsetField { name, position, bitcount, holder_type });
        }
    }

    /// Append `label` to the case member named `member_name`. Returns false when this is
    /// not a union builder or no such member has been added yet.
    pub(crate) fn push_union_label(&mut self, member_name: &str, label: i32) -> bool {
        if !matches!(self.body, TypeInfoBody::Union { .. }) {
            return false;
        }
        match self.fields.iter_mut().find(|f| f.name == member_name) {
            Some(field) => {
                field.labels.push(label);
                true
            }
            None => false,
        }
    }

    /// Append a field whose `TypeIdentifier` is already resolved. `flags` uses the
    /// `INT2DDS_MEMBER_*` bitmask (KEY/OPTIONAL/MUST_UNDERSTAND/EXTERNAL/DEFAULT).
    pub(crate) fn push_field(&mut self, name: String, type_id: TypeIdentifier, flags: i32) {
        self.fields.push(FieldInfo { name, type_id, flags, labels: Vec::new() });
    }

    /// Append a nested struct-typed field, referencing `nested` by its content-hash
    /// `CompleteTypeId` (matching the derive macro's `<FieldType>::type_identifier()`)
    /// and recording `nested`'s `TypeObject` plus its own transitive dependencies so the
    /// full closure is available for registry-backed key resolution.
    pub(crate) fn push_nested_field(&mut self, name: String, nested: &Int2DdsTypeInfo, flags: i32) {
        let nested_id = self.intern_nested(nested);
        self.push_field(name, nested_id, flags);
    }

    /// Resolve `nested` to its content-hash `CompleteTypeId` and record its `TypeObject`
    /// plus transitive dependencies, returning the element id. Shared by the nested-field
    /// and collection-of-nested builders.
    fn intern_nested(&mut self, nested: &Int2DdsTypeInfo) -> TypeIdentifier {
        let nested_obj = nested.build_type_object();
        let nested_id = TypeIdentifier::CompleteTypeId(nested_obj.compute_hash());
        self.add_dependency(nested_id.clone(), nested_obj);
        for (id, obj) in &nested.dependencies {
            self.add_dependency(id.clone(), obj.clone());
        }
        nested_id
    }

    /// Append a `sequence<Nested>` field, referencing the element by content-hash
    /// `CompleteTypeId` wrapped in a plain-sequence id (whose header equiv_kind is derived
    /// as Complete). Records the element `TypeObject` and its transitive deps.
    pub(crate) fn push_sequence_of_nested_field(
        &mut self,
        name: String,
        element: &Int2DdsTypeInfo,
        bound: u32,
        flags: i32,
    ) {
        let element_id = self.intern_nested(element);
        self.push_field(name, plain_sequence_id(element_id, bound), flags);
    }

    /// Append a `Nested[N]` fixed-array field, referencing the element by content-hash
    /// `CompleteTypeId` wrapped in a plain-array id. Records element + transitive deps.
    pub(crate) fn push_array_of_nested_field(
        &mut self,
        name: String,
        element: &Int2DdsTypeInfo,
        array_size: u32,
        flags: i32,
    ) {
        let element_id = self.intern_nested(element);
        self.push_field(name, plain_array_id(element_id, array_size), flags);
    }

    /// Append a `map<K, V>` field whose key and value ids are already resolved
    /// (primitives/strings). `bound == 0` means unbounded.
    pub(crate) fn push_map_field(
        &mut self,
        name: String,
        key: TypeIdentifier,
        value: TypeIdentifier,
        bound: u32,
        flags: i32,
    ) {
        self.push_field(name, plain_map_identifier(key, value, bound), flags);
    }

    /// Append a `map<K, Nested>` field whose value is a nested struct/enum/bitmask/union
    /// builder, referenced by content-hash `CompleteTypeId` with its `TypeObject` and
    /// transitive dependencies recorded so the runtime can resolve the map entries.
    pub(crate) fn push_map_of_nested_field(
        &mut self,
        name: String,
        key: TypeIdentifier,
        value: &Int2DdsTypeInfo,
        bound: u32,
        flags: i32,
    ) {
        let value_id = self.intern_nested(value);
        self.push_field(name, plain_map_identifier(key, value_id, bound), flags);
    }

    /// Record a nested dependency, de-duplicating by `TypeIdentifier`.
    fn add_dependency(&mut self, id: TypeIdentifier, obj: TypeObject) {
        if !self.dependencies.iter().any(|(existing, _)| existing == &id) {
            self.dependencies.push((id, obj));
        }
    }

    /// The nested-type dependency closure for registry-backed key resolution.
    pub(crate) fn dependency_closure(&self) -> Vec<(TypeIdentifier, TypeObject)> {
        self.dependencies.clone()
    }

    /// The builder's extensibility as the XTypes `TypeFlag` extensibility kind.
    fn xtypes_extensibility(&self) -> int2dds::xtypes::ExtensibilityKind {
        match self.extensibility {
            ExtensibilityKind::Final => int2dds::xtypes::ExtensibilityKind::Final,
            ExtensibilityKind::Appendable => int2dds::xtypes::ExtensibilityKind::Appendable,
            ExtensibilityKind::Mutable => int2dds::xtypes::ExtensibilityKind::Mutable,
        }
    }

    /// Build a CompleteStructType from the collected fields.
    fn build_complete_struct_type(&self) -> CompleteStructType {
        let type_flags = TypeFlag::new(self.xtypes_extensibility(), false, false);
        let mut complete = CompleteStructType::new(type_flags, self.type_name.clone(), None);

        for (index, field) in self.fields.iter().enumerate() {
            let member_flags = MemberFlag::new(
                TryConstructKind::Discard,
                field.is_external(),
                field.is_optional(),
                // @key members are implicitly must-understand (XTypes 7.2.2.4.4.4.7),
                // matching the derive macro so FFI-built and derived TypeObjects hash alike.
                field.is_must_understand() || field.is_key(),
                field.is_key(),
                false, // is_default
            );
            let common = CommonStructMember {
                member_id: index as u32,
                member_flags,
                member_type_id: field.type_id.clone(),
            };
            let detail = CompleteMemberDetail {
                name: field.name.clone(),
                ann_builtin: None,
                ann_custom: Vec::new(),
            };
            complete.add_member(CompleteStructMember { common, detail });
        }

        complete
    }

    /// Build a CompleteEnumeratedType from the collected literals. Mirrors the derive macro:
    /// `TypeFlag::default()`, literals with `EnumeratedLiteralFlag::DEFAULT` on the `@default`
    /// literal (else `default()`), so FFI-built and derived enum TypeObjects hash alike.
    fn build_complete_enum_type(
        &self,
        bit_bound: u16,
        literals: &[EnumLiteral],
    ) -> CompleteEnumeratedType {
        let mut enum_type =
            CompleteEnumeratedType::new(TypeFlag::default(), self.type_name.clone(), bit_bound);
        for lit in literals {
            let flag = if lit.is_default {
                EnumeratedLiteralFlag::DEFAULT
            } else {
                EnumeratedLiteralFlag::default()
            };
            enum_type.add_literal(CompleteEnumeratedLiteral::new(
                lit.value,
                flag,
                lit.name.clone(),
            ));
        }
        enum_type
    }

    /// Build a CompleteBitmaskType from the collected flags. Mirrors the derive macro.
    fn build_complete_bitmask_type(
        &self,
        bit_bound: u16,
        flags: &[BitFlag],
    ) -> CompleteBitmaskType {
        let mut bitmask_type =
            CompleteBitmaskType::new(TypeFlag::default(), self.type_name.clone(), bit_bound);
        for f in flags {
            bitmask_type.add_flag(CompleteBitflag::new(
                f.position,
                MemberFlag::default(),
                f.name.clone(),
            ));
        }
        bitmask_type
    }

    /// Build a CompleteBitsetType from the collected bitfields. Mirrors the derive macro:
    /// `TypeFlag::default()`, cumulative positions, `MemberFlag::default()` per bitfield.
    fn build_complete_bitset_type(&self, fields: &[BitsetField]) -> CompleteBitsetType {
        let mut bitset_type = CompleteBitsetType::new(TypeFlag::default(), self.type_name.clone());
        for f in fields {
            bitset_type.add_field(CompleteBitfield::new(
                f.position,
                MemberFlag::default(),
                f.bitcount,
                f.holder_type.clone(),
                f.name.clone(),
            ));
        }
        bitset_type
    }

    /// Build a CompleteUnionType from the collected case members. Mirrors the derive
    /// macro (extensibility in the type flags, default discriminator flags, member ids in
    /// declaration order, `MemberFlag::default()` per case) except that the `default:`
    /// member also raises `IS_DEFAULT`, which the dynamic deserializer needs to accept a
    /// discriminator value that matches no explicit label.
    fn build_complete_union_type(&self, discriminator: &TypeIdentifier) -> CompleteUnionType {
        let mut union_type = CompleteUnionType::new(
            TypeFlag::new(self.xtypes_extensibility(), false, false),
            MemberFlag::default(),
            discriminator.clone(),
            self.type_name.clone(),
        );
        for (index, field) in self.fields.iter().enumerate() {
            let member_flags = MemberFlag::new(
                TryConstructKind::Discard,
                false,
                false,
                false,
                false,
                field.is_default(),
            );
            union_type.add_member(CompleteUnionMember::new(
                index as u32,
                member_flags,
                field.type_id.clone(),
                field.labels.clone(),
                field.name.clone(),
            ));
        }
        union_type
    }

    /// Build TypeObject from the collected fields/literals/flags, dispatching on body kind.
    pub(crate) fn build_type_object(&self) -> TypeObject {
        match &self.body {
            TypeInfoBody::Struct => {
                TypeObject::Complete(CompleteTypeObject::Struct(self.build_complete_struct_type()))
            }
            TypeInfoBody::Enum { bit_bound, literals } => TypeObject::Complete(
                CompleteTypeObject::Enum(self.build_complete_enum_type(*bit_bound, literals)),
            ),
            TypeInfoBody::Bitmask { bit_bound, flags } => TypeObject::Complete(
                CompleteTypeObject::Bitmask(self.build_complete_bitmask_type(*bit_bound, flags)),
            ),
            TypeInfoBody::Bitset { fields } => TypeObject::Complete(CompleteTypeObject::Bitset(
                self.build_complete_bitset_type(fields),
            )),
            TypeInfoBody::Union { discriminator } => TypeObject::Complete(
                CompleteTypeObject::Union(self.build_complete_union_type(discriminator)),
            ),
        }
    }

    /// Check if any field is marked as a key field.
    pub(crate) fn has_key_field(&self) -> bool {
        self.fields.iter().any(|f| f.is_key())
    }

    /// Flat CDR field descriptors for the raw ContentFilteredTopic / QueryCondition
    /// parser, so filters work on generated (type_info) topics — not just the explicit
    /// `create_topic_with_field_descriptors` path. Returns `None` if this is not a struct
    /// or any member is non-flat (nested/collection/enum/float/wide-string/char): the
    /// parser skips members sequentially, so a partial set would misalign every field after
    /// the gap. `None` preserves the prior no-filtering behavior for those types.
    pub(crate) fn cdr_field_descriptors(&self) -> Option<Vec<crate::data::CdrFieldDescriptor>> {
        if !matches!(self.body, TypeInfoBody::Struct) {
            return None;
        }
        // The flat sequential-skip parser handles Final (no header) and Appendable
        // (leading DHEADER) layouts, but not Mutable EMHEADER-per-member framing — so
        // leave Mutable topics without descriptors (filter unavailable) rather than
        // mis-parsing them.
        if matches!(self.extensibility, ExtensibilityKind::Mutable) {
            return None;
        }
        let mut descriptors = Vec::with_capacity(self.fields.len());
        for field in &self.fields {
            descriptors.push(crate::data::CdrFieldDescriptor {
                name: field.name.clone(),
                field_type: type_identifier_to_cdr_field_type(&field.type_id)?,
                is_key: field.is_key(),
            });
        }
        Some(descriptors)
    }

    /// Build TypeIdentifier (CompleteTypeId hash) from the collected fields.
    pub(crate) fn build_type_identifier(&self) -> TypeIdentifier {
        let type_obj = self.build_type_object();
        TypeIdentifier::CompleteTypeId(type_obj.compute_hash())
    }
}

/// Convert a field_type integer constant to a TypeIdentifier.
fn field_type_to_type_identifier(field_type: i32) -> Option<TypeIdentifier> {
    match field_type {
        INT2DDS_FIELD_BOOL => Some(TypeIdentifier::Boolean),
        INT2DDS_FIELD_BYTE => Some(TypeIdentifier::Byte),
        INT2DDS_FIELD_CHAR8 => Some(TypeIdentifier::Char8),
        INT2DDS_FIELD_CHAR16 => Some(TypeIdentifier::Char16),
        INT2DDS_FIELD_INT8 => Some(TypeIdentifier::Int8),
        INT2DDS_FIELD_INT16 => Some(TypeIdentifier::Int16),
        INT2DDS_FIELD_INT32 => Some(TypeIdentifier::Int32),
        INT2DDS_FIELD_INT64 => Some(TypeIdentifier::Int64),
        INT2DDS_FIELD_UINT8 => Some(TypeIdentifier::Uint8),
        INT2DDS_FIELD_UINT16 => Some(TypeIdentifier::Uint16),
        INT2DDS_FIELD_UINT32 => Some(TypeIdentifier::Uint32),
        INT2DDS_FIELD_UINT64 => Some(TypeIdentifier::Uint64),
        INT2DDS_FIELD_FLOAT32 => Some(TypeIdentifier::Float32),
        INT2DDS_FIELD_FLOAT64 => Some(TypeIdentifier::Float64),
        INT2DDS_FIELD_STRING => Some(TypeIdentifier::String8),
        INT2DDS_FIELD_WSTRING => Some(TypeIdentifier::String16),
        _ => None,
    }
}

/// Map a resolved member `TypeIdentifier` to the flat `CdrFieldType` the raw
/// ContentFilteredTopic / QueryCondition parser understands. Returns `None` for any
/// type the parser cannot skip or read (nested structs, collections, maps, enums,
/// bitmasks, wide strings, floats, chars) — a single non-flat member makes the whole
/// descriptor set unusable, since the parser walks members sequentially.
fn type_identifier_to_cdr_field_type(id: &TypeIdentifier) -> Option<crate::data::CdrFieldType> {
    use crate::data::CdrFieldType;
    Some(match id {
        TypeIdentifier::Boolean => CdrFieldType::Bool,
        TypeIdentifier::Byte | TypeIdentifier::Uint8 => CdrFieldType::UInt8,
        TypeIdentifier::Int8 => CdrFieldType::Int8,
        TypeIdentifier::Int16 => CdrFieldType::Int16,
        TypeIdentifier::Int32 => CdrFieldType::Int32,
        TypeIdentifier::Int64 => CdrFieldType::Int64,
        TypeIdentifier::Uint16 => CdrFieldType::UInt16,
        TypeIdentifier::Uint32 => CdrFieldType::UInt32,
        TypeIdentifier::Uint64 => CdrFieldType::UInt64,
        TypeIdentifier::String8
        | TypeIdentifier::String8Small { .. }
        | TypeIdentifier::String8Large { .. } => CdrFieldType::String,
        _ => return None,
    })
}

fn named_type_identifier(hash_name: &str) -> TypeIdentifier {
    TypeIdentifier::MinimalTypeId(EquivalenceHash::compute(hash_name.as_bytes()))
}

/// Build the plain-collection header, deriving `equiv_kind` from the element exactly as
/// the derive macro does (primitives -> Both, hashed composites -> Minimal/Complete).
fn plain_collection_header(element: &TypeIdentifier) -> PlainCollectionHeader {
    PlainCollectionHeader {
        equiv_kind: plain_collection_equiv_kind(element),
        element_flags: CollectionElementFlag::default(),
    }
}

/// Sequence id: SMALL when `bound <= 255` (unbounded == 0 -> SMALL), else LARGE.
fn plain_sequence_id(element: TypeIdentifier, bound: u32) -> TypeIdentifier {
    let header = plain_collection_header(&element);
    if bound <= 255 {
        TypeIdentifier::PlainSequenceSmall {
            header,
            bound: bound as u8,
            element_identifier: Box::new(element),
        }
    } else {
        TypeIdentifier::PlainSequenceLarge { header, bound, element_identifier: Box::new(element) }
    }
}

/// Array id: SMALL when `array_size <= 255`, else LARGE.
fn plain_array_id(element: TypeIdentifier, array_size: u32) -> TypeIdentifier {
    let header = plain_collection_header(&element);
    if array_size <= 255 {
        TypeIdentifier::PlainArraySmall {
            header,
            array_bound_seq: vec![array_size as u8],
            element_identifier: Box::new(element),
        }
    } else {
        TypeIdentifier::PlainArrayLarge {
            header,
            array_bound_seq: vec![array_size],
            element_identifier: Box::new(element),
        }
    }
}

/// Resolve a scalar `INT2DDS_FIELD_*` constant to its id, honoring `bound` for the string
/// kinds (`0` = unbounded) and ignoring it otherwise. `None` for non-scalar constants.
fn scalar_id(field_type: i32, bound: u32) -> Option<TypeIdentifier> {
    match field_type {
        INT2DDS_FIELD_STRING => Some(string_id(bound, false)),
        INT2DDS_FIELD_WSTRING => Some(string_id(bound, true)),
        other => field_type_to_type_identifier(other),
    }
}

/// String id honoring an optional bound: `0` -> unbounded `String8`/`String16`;
/// `<= 255` -> `*Small`; else `*Large`. Mirrors the derive macro's `string_identifier`.
fn string_id(bound: u32, wide: bool) -> TypeIdentifier {
    match bound {
        0 => {
            if wide {
                TypeIdentifier::String16
            } else {
                TypeIdentifier::String8
            }
        }
        b if b <= 255 => {
            if wide {
                TypeIdentifier::String16Small { bound: b as u8 }
            } else {
                TypeIdentifier::String8Small { bound: b as u8 }
            }
        }
        b => {
            if wide {
                TypeIdentifier::String16Large { bound: b }
            } else {
                TypeIdentifier::String8Large { bound: b }
            }
        }
    }
}

/// # Safety
/// - `type_name` must be a valid null-terminated C string
/// - `out` must be a valid pointer to a null pointer
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_create(
    type_name: *const std::os::raw::c_char,
    extensibility: i32,
    out: *mut *mut Int2DdsTypeInfo,
) -> Int2DdsRet {
    check_null!(type_name);
    check_null!(out);

    let name_str = cstr_arg!(type_name);

    let ext_kind = match crate::topic::resolve_extensibility(extensibility) {
        Some(k) => k,
        None => return INT2DDS_RET_INVALID_ARGUMENT,
    };

    let ti = Box::new(Int2DdsTypeInfo::new(name_str.to_string(), ext_kind));

    *out = Box::into_raw(ti);
    INT2DDS_RET_OK
}

/// Create an enum type info builder. `bit_bound` is the discriminant bit width (IDL enums
/// are i32 -> 32). Populate literals with `int2dds_type_info_add_enum_literal`, then pass
/// the builder to `int2dds_type_info_add_nested_field` (or a collection-of-nested variant)
/// on the parent so an enum-typed member resolves and computes native-Rust keys.
///
/// # Safety
/// - `type_name` must be a valid null-terminated C string
/// - `out` must be a valid pointer to a null pointer
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_create_enum(
    type_name: *const std::os::raw::c_char,
    bit_bound: u16,
    out: *mut *mut Int2DdsTypeInfo,
) -> Int2DdsRet {
    check_null!(type_name);
    check_null!(out);
    let name_str = cstr_arg!(type_name);
    let ti = Box::new(Int2DdsTypeInfo::new_enum(name_str.to_string(), bit_bound));
    *out = Box::into_raw(ti);
    INT2DDS_RET_OK
}

/// Append a literal to an enum builder. `is_default` marks the `@default` literal (0/1);
/// no-op on a non-enum builder.
///
/// # Safety
/// - `type_info` must be a valid type info builder
/// - `literal_name` must be a valid null-terminated C string
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_enum_literal(
    type_info: *mut Int2DdsTypeInfo,
    literal_name: *const std::os::raw::c_char,
    value: i32,
    is_default: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(literal_name);
    let ti = &mut *type_info;
    let name_str = cstr_arg!(literal_name);
    ti.push_enum_literal(name_str.to_string(), value, is_default != 0);
    INT2DDS_RET_OK
}

/// Create a bitmask type info builder. `bit_bound` is the flag storage bit width (default 32).
///
/// # Safety
/// - `type_name` must be a valid null-terminated C string
/// - `out` must be a valid pointer to a null pointer
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_create_bitmask(
    type_name: *const std::os::raw::c_char,
    bit_bound: u16,
    out: *mut *mut Int2DdsTypeInfo,
) -> Int2DdsRet {
    check_null!(type_name);
    check_null!(out);
    let name_str = cstr_arg!(type_name);
    let ti = Box::new(Int2DdsTypeInfo::new_bitmask(name_str.to_string(), bit_bound));
    *out = Box::into_raw(ti);
    INT2DDS_RET_OK
}

/// Append a flag to a bitmask builder. `position` is the bit index; no-op on a non-bitmask.
///
/// # Safety
/// - `type_info` must be a valid type info builder
/// - `flag_name` must be a valid null-terminated C string
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_bitmask_flag(
    type_info: *mut Int2DdsTypeInfo,
    flag_name: *const std::os::raw::c_char,
    position: u16,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(flag_name);
    let ti = &mut *type_info;
    let name_str = cstr_arg!(flag_name);
    ti.push_bitmask_flag(name_str.to_string(), position);
    INT2DDS_RET_OK
}

/// Create a bitset type info builder. Populate it with `int2dds_type_info_add_bitfield`
/// in declaration order, then pass it to `int2dds_type_info_add_nested_field` on the
/// parent so a bitset-typed member resolves like the derive's `#[dds_type(bitset)]`.
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_create_bitset(
    type_name: *const std::os::raw::c_char,
    out: *mut *mut Int2DdsTypeInfo,
) -> Int2DdsRet {
    check_null!(type_name);
    check_null!(out);
    let name_str = cstr_arg!(type_name);
    let ti = Box::new(Int2DdsTypeInfo::new_bitset(name_str.to_string()));
    *out = Box::into_raw(ti);
    INT2DDS_RET_OK
}

/// Append a `bitfield<bitcount>` to a bitset builder. `holder_type` is the
/// `INT2DDS_FIELD_*` integer kind that holds the field (`BYTE` up to 8 bits, then
/// `UINT16`/`UINT32`/`UINT64`); the bit position follows the previous bitfield.
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_bitfield(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    bitcount: u8,
    holder_type: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);
    let ti = &mut *type_info;
    let name_str = cstr_arg!(field_name);
    let holder = match field_type_to_type_identifier(holder_type) {
        Some(id) => id,
        None => return INT2DDS_RET_INVALID_ARGUMENT,
    };
    ti.push_bitfield(name_str.to_string(), bitcount, holder);
    INT2DDS_RET_OK
}

/// Create a union type info builder. `discriminator_type` is the `INT2DDS_FIELD_*`
/// scalar kind of the switch (string kinds are rejected). Add each case member with the
/// same `int2dds_type_info_add_*_field` calls a struct uses, giving the `default:`
/// member `INT2DDS_MEMBER_DEFAULT`, then attach its labels with
/// `int2dds_type_info_add_union_label`.
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_create_union(
    type_name: *const std::os::raw::c_char,
    extensibility: i32,
    discriminator_type: i32,
    out: *mut *mut Int2DdsTypeInfo,
) -> Int2DdsRet {
    check_null!(type_name);
    check_null!(out);
    let name_str = cstr_arg!(type_name);
    let ext_kind = match crate::topic::resolve_extensibility(extensibility) {
        Some(k) => k,
        None => return INT2DDS_RET_INVALID_ARGUMENT,
    };
    let discriminator = match field_type_to_type_identifier(discriminator_type) {
        Some(id @ (TypeIdentifier::String8 | TypeIdentifier::String16)) => {
            let _ = id;
            return INT2DDS_RET_INVALID_ARGUMENT;
        }
        Some(id) => id,
        None => return INT2DDS_RET_INVALID_ARGUMENT,
    };
    let ti = Box::new(Int2DdsTypeInfo::new_union(name_str.to_string(), ext_kind, discriminator));
    *out = Box::into_raw(ti);
    INT2DDS_RET_OK
}

/// Append a case label to the union member named `member_name`, which must already
/// have been added. Boolean labels are `1`/`0`; enum labels are their literal value.
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_union_label(
    type_info: *mut Int2DdsTypeInfo,
    member_name: *const std::os::raw::c_char,
    label: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(member_name);
    let ti = &mut *type_info;
    let name_str = cstr_arg!(member_name);
    if ti.push_union_label(name_str, label) {
        INT2DDS_RET_OK
    } else {
        INT2DDS_RET_INVALID_ARGUMENT
    }
}

/// Add a primitive-typed field to the type info builder.
///
/// # Safety
/// - `type_info` must be a valid type info builder
/// - `field_name` must be a valid null-terminated C string
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    field_type: i32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);

    let ti = &mut *type_info;

    let name_str = match CStr::from_ptr(field_name).to_str() {
        Ok(s) => s,
        Err(_) => return INT2DDS_RET_INVALID_ARGUMENT,
    };

    let type_id = match field_type_to_type_identifier(field_type) {
        Some(id) => id,
        None => return INT2DDS_RET_INVALID_ARGUMENT,
    };

    ti.push_field(name_str.to_string(), type_id, flags);

    INT2DDS_RET_OK
}

/// Add a (possibly bounded) narrow-string field. `bound == 0` means unbounded.
///
/// Prefer this over `int2dds_type_info_add_field(.., INT2DDS_FIELD_STRING, ..)` when the
/// IDL declares `string<N>`, so the emitted TypeIdentifier carries the bound and matches
/// strict XTypes peers byte-for-byte.
///
/// # Safety
/// - `type_info` must be a valid type info builder
/// - `field_name` must be a valid null-terminated C string
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_string_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    bound: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);

    let ti = &mut *type_info;
    let name_str = cstr_arg!(field_name);
    let type_id = string_id(bound, false);
    ti.push_field(name_str.to_string(), type_id, flags);

    INT2DDS_RET_OK
}

/// Add a (possibly bounded) wide-string (`wstring<N>`) field. `bound == 0` means unbounded.
///
/// # Safety
/// - `type_info` must be a valid type info builder
/// - `field_name` must be a valid null-terminated C string
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_wstring_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    bound: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);

    let ti = &mut *type_info;
    let name_str = cstr_arg!(field_name);
    let type_id = string_id(bound, true);
    ti.push_field(name_str.to_string(), type_id, flags);

    INT2DDS_RET_OK
}

/// Add a sequence field to the type info builder.
///
/// # Safety
/// - `type_info` must be a valid type info builder
/// - `field_name` must be a valid null-terminated C string
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_sequence_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    element_type: i32,
    bound: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);

    let ti = &mut *type_info;

    let name_str = cstr_arg!(field_name);

    let element_id = match field_type_to_type_identifier(element_type) {
        Some(id) => id,
        None => return INT2DDS_RET_INVALID_ARGUMENT,
    };

    let type_id = plain_sequence_id(element_id, bound);

    ti.push_field(name_str.to_string(), type_id, flags);

    INT2DDS_RET_OK
}

/// Add an array field to the type info builder.
///
/// # Safety
/// - `type_info` must be a valid type info builder
/// - `field_name` must be a valid null-terminated C string
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_array_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    element_type: i32,
    array_size: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);

    let ti = &mut *type_info;

    let name_str = cstr_arg!(field_name);

    let element_id = match field_type_to_type_identifier(element_type) {
        Some(id) => id,
        None => return INT2DDS_RET_INVALID_ARGUMENT,
    };

    let type_id = plain_array_id(element_id, array_size);

    ti.push_field(name_str.to_string(), type_id, flags);

    INT2DDS_RET_OK
}

/// Add a named (complex) type field to the type info builder.
///
/// # Safety
/// - `type_info` must be a valid type info builder
/// - `field_name` must be a valid null-terminated C string
/// - `type_hash_name` must be a valid null-terminated C string
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_named_type_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    type_hash_name: *const std::os::raw::c_char,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);
    check_null!(type_hash_name);

    let ti = &mut *type_info;

    let name_str = cstr_arg!(field_name);
    let hash_name = cstr_arg!(type_hash_name);

    let type_id = named_type_identifier(hash_name);

    ti.push_field(name_str.to_string(), type_id, flags);

    INT2DDS_RET_OK
}

/// Add a nested struct-typed field, supplying the nested type's own builder.
///
/// Unlike `int2dds_type_info_add_named_type_field` (which emits a name-hash
/// `MinimalTypeId` reference), this references the nested type by its content-hash
/// `CompleteTypeId` — matching the derive macro byte-for-byte — and captures the nested
/// `TypeObject` so composite (nested-struct) key members resolve and compute native-Rust
/// InstanceHandles. `nested_type_info` is borrowed, not consumed: the caller still owns
/// it and must destroy it.
///
/// # Safety
/// - `type_info` must be a valid type info builder
/// - `field_name` must be a valid null-terminated C string
/// - `nested_type_info` must be a valid type info builder; it is borrowed, not
///   consumed, and the caller still owns it
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_nested_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    nested_type_info: *const Int2DdsTypeInfo,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);
    check_null!(nested_type_info);

    let ti = &mut *type_info;
    let nested = &*nested_type_info;
    let name_str = cstr_arg!(field_name);

    ti.push_nested_field(name_str.to_string(), nested, flags);

    INT2DDS_RET_OK
}

/// Add a `sequence<Nested>` field whose element is a nested struct/enum/bitmask, supplying
/// the element's own builder. References the element by content-hash `CompleteTypeId`
/// (matching the derive macro) so sequence-of-nested key members resolve and compute
/// native-Rust InstanceHandles. `element_type_info` is borrowed, not consumed.
///
/// # Safety
/// - `type_info` must be a valid type info builder
/// - `field_name` must be a valid null-terminated C string
/// - `element_type_info` must be a valid type info builder; it is borrowed, not
///   consumed, and the caller still owns it
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_sequence_of_nested_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    element_type_info: *const Int2DdsTypeInfo,
    bound: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);
    check_null!(element_type_info);

    let ti = &mut *type_info;
    let element = &*element_type_info;
    let name_str = cstr_arg!(field_name);

    ti.push_sequence_of_nested_field(name_str.to_string(), element, bound, flags);

    INT2DDS_RET_OK
}

/// Add a `Nested[N]` fixed-array field whose element is a nested struct/enum/bitmask,
/// supplying the element's own builder. `element_type_info` is borrowed, not consumed.
///
/// # Safety
/// - `type_info` must be a valid type info builder
/// - `field_name` must be a valid null-terminated C string
/// - `element_type_info` must be a valid type info builder; it is borrowed, not
///   consumed, and the caller still owns it
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_array_of_nested_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    element_type_info: *const Int2DdsTypeInfo,
    array_size: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);
    check_null!(element_type_info);

    let ti = &mut *type_info;
    let element = &*element_type_info;
    let name_str = cstr_arg!(field_name);

    ti.push_array_of_nested_field(name_str.to_string(), element, array_size, flags);

    INT2DDS_RET_OK
}

/// # Safety
/// - `type_info` must be a valid type info builder
/// - `field_name` must be a valid null-terminated C string
/// - `element_hash_name` must be a valid null-terminated C string
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_sequence_of_named_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    element_hash_name: *const std::os::raw::c_char,
    bound: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);
    check_null!(element_hash_name);

    let ti = &mut *type_info;

    let name_str = cstr_arg!(field_name);
    let hash_name = cstr_arg!(element_hash_name);

    let type_id = plain_sequence_id(named_type_identifier(hash_name), bound);

    ti.push_field(name_str.to_string(), type_id, flags);

    INT2DDS_RET_OK
}

/// # Safety
/// - `type_info` must be a valid type info builder
/// - `field_name` must be a valid null-terminated C string
/// - `element_hash_name` must be a valid null-terminated C string
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_array_of_named_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    element_hash_name: *const std::os::raw::c_char,
    array_size: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);
    check_null!(element_hash_name);

    let ti = &mut *type_info;

    let name_str = cstr_arg!(field_name);
    let hash_name = cstr_arg!(element_hash_name);

    let type_id = plain_array_id(named_type_identifier(hash_name), array_size);

    ti.push_field(name_str.to_string(), type_id, flags);

    INT2DDS_RET_OK
}

/// Add a `map<K, V>` field whose key and value are scalar `INT2DDS_FIELD_*` kinds.
/// `key_bound`/`value_bound` apply to the string kinds (`0` = unbounded) and are ignored
/// otherwise; `bound` is the map's own bound (`0` = unbounded).
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_map_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    key_type: i32,
    key_bound: u32,
    value_type: i32,
    value_bound: u32,
    bound: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);

    let ti = &mut *type_info;
    let name_str = cstr_arg!(field_name);

    let (Some(key), Some(value)) =
        (scalar_id(key_type, key_bound), scalar_id(value_type, value_bound))
    else {
        return INT2DDS_RET_INVALID_ARGUMENT;
    };

    ti.push_map_field(name_str.to_string(), key, value, bound, flags);

    INT2DDS_RET_OK
}

/// Add a `map<K, Nested>` field whose key is a scalar `INT2DDS_FIELD_*` kind and whose
/// value is a nested struct/enum/bitmask/union builder, referenced by content-hash so
/// the runtime can resolve the entries. `value_type_info` is borrowed, not consumed.
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_map_of_nested_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    key_type: i32,
    key_bound: u32,
    value_type_info: *const Int2DdsTypeInfo,
    bound: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);
    check_null!(value_type_info);

    let ti = &mut *type_info;
    let value = &*value_type_info;
    let name_str = cstr_arg!(field_name);

    let Some(key) = scalar_id(key_type, key_bound) else {
        return INT2DDS_RET_INVALID_ARGUMENT;
    };

    ti.push_map_of_nested_field(name_str.to_string(), key, value, bound, flags);

    INT2DDS_RET_OK
}

/// # Safety
/// - `type_info` must be a valid type info builder
/// - `out` must be a valid pointer to a null pointer
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_to_type_object(
    type_info: *const Int2DdsTypeInfo,
    out: *mut *mut crate::dynamic::Int2DdsTypeObject,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(out);
    let to = (*type_info).build_type_object();
    let deps = (*type_info).dependency_closure();
    *out = Box::into_raw(Box::new(crate::dynamic::Int2DdsTypeObject::from_type_object_with_deps(
        to, deps,
    )));
    INT2DDS_RET_OK
}

/// Destroy a type info builder.
///
/// # Safety
/// - `type_info` must be a valid type info builder, or null (null is a no-op)
/// - `type_info` must not be used after this call
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_destroy(type_info: *mut Int2DdsTypeInfo) {
    if !type_info.is_null() {
        drop(Box::from_raw(type_info));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use int2dds::xtypes::{
        CompleteStructMember, CompleteStructType, CompleteTypeObject, MemberFlag, TryConstructKind,
        TypeFlag, TypeIdentifier, TypeObject,
    };

    #[test]
    fn test_primitives_type_hash_matches_derive_macro() {
        use int2dds::xtypes::HasTypeObject;
        use int2dds_derive::DdsType;

        // The real derive-macro output is the source of truth. Comparing against an actual
        // `#[derive(DdsType)]` struct (not a hand-rolled CompleteStructType) is what makes
        // this test able to catch FFI-vs-derive divergence.
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct PrimitivesType {
            #[dds(key)]
            id: i32,
            bool_val: bool,
            byte_val: u8,
            short_val: u16,
        }

        // FFI type_info builder path (mirrors what the generated C emits).
        let mut ti =
            Int2DdsTypeInfo::new("PrimitivesType".to_string(), ExtensibilityKind::Appendable);
        ti.push_field("id".to_string(), TypeIdentifier::Int32, INT2DDS_MEMBER_KEY);
        ti.push_field("bool_val".to_string(), TypeIdentifier::Boolean, 0);
        ti.push_field("byte_val".to_string(), TypeIdentifier::Byte, 0);
        ti.push_field("short_val".to_string(), TypeIdentifier::Uint16, 0);

        let ffi_serialized = match ti.build_type_object() {
            TypeObject::Complete(c) => c.serialize(),
            _ => panic!("Expected Complete"),
        };
        let derive_serialized = PrimitivesType::complete_type_object().serialize();

        assert_eq!(
            ffi_serialized, derive_serialized,
            "Serialized CompleteTypeObject bytes differ between FFI and derive paths"
        );
        assert_eq!(
            ti.build_type_identifier(),
            PrimitivesType::type_identifier(),
            "TypeIdentifier hashes differ between FFI and derive paths"
        );
    }

    /// An unbounded `String` field must hash identically between the FFI builder and the
    /// derive macro. Exercises the `new` / `push_field` pub(crate) builders used by
    /// `create_topic_with_field_descriptors`, and closes the String parity gap that the
    /// primitives test did not cover.
    #[test]
    fn test_string_field_hash_matches_derive_macro() {
        use int2dds::xtypes::HasTypeObject;
        use int2dds_derive::DdsType;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct StringFieldType {
            #[dds(key)]
            id: i32,
            name: String,
            count: u32,
        }

        let mut ti =
            Int2DdsTypeInfo::new("StringFieldType".to_string(), ExtensibilityKind::Appendable);
        ti.push_field("id".to_string(), TypeIdentifier::Int32, INT2DDS_MEMBER_KEY);
        ti.push_field("name".to_string(), TypeIdentifier::String8, 0);
        ti.push_field("count".to_string(), TypeIdentifier::Uint32, 0);

        let ffi_serialized = match ti.build_type_object() {
            TypeObject::Complete(c) => c.serialize(),
            _ => panic!("Expected Complete"),
        };
        assert_eq!(
            ffi_serialized,
            StringFieldType::complete_type_object().serialize(),
            "Serialized CompleteTypeObject bytes differ between FFI and derive paths"
        );
        assert_eq!(
            ti.build_type_identifier(),
            StringFieldType::type_identifier(),
            "TypeIdentifier hashes differ between FFI and derive paths"
        );
    }

    /// Sequence / array / bounded-sequence / uint8-element fields must produce the same
    /// TypeIdentifier as the real derive macro. Pinned to `T::type_identifier()` so it
    /// catches the SMALL/LARGE and equiv_kind divergences the old self-consistent test missed.
    #[test]
    fn test_sequence_type_hash_matches_derive_macro() {
        use int2dds::xtypes::HasTypeObject;
        use int2dds_derive::DdsType;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct TestSeqType {
            #[dds(key)]
            id: i32,
            bool_seq: Vec<bool>,
            #[dds(bound = 10)]
            bounded_seq: Vec<i32>,
            #[dds(uint8)]
            payload: Vec<u8>,
            bool_array: [bool; 4],
        }

        let mut ti = Int2DdsTypeInfo::new("TestSeqType".to_string(), ExtensibilityKind::Appendable);
        ti.push_field("id".to_string(), TypeIdentifier::Int32, INT2DDS_MEMBER_KEY);
        ti.push_field("bool_seq".to_string(), plain_sequence_id(TypeIdentifier::Boolean, 0), 0);
        ti.push_field("bounded_seq".to_string(), plain_sequence_id(TypeIdentifier::Int32, 10), 0);
        ti.push_field("payload".to_string(), plain_sequence_id(TypeIdentifier::Uint8, 0), 0);
        ti.push_field("bool_array".to_string(), plain_array_id(TypeIdentifier::Boolean, 4), 0);

        assert_eq!(
            ti.build_type_identifier(),
            TestSeqType::type_identifier(),
            "TypeIdentifier hashes differ for sequence/array/bounded/uint8 fields"
        );
    }

    #[test]
    fn test_named_collection_type_hash_matches_derive_macro() {
        use std::ffi::CString;

        let name = CString::new("NamedCollType").unwrap();
        let mut ffi_ptr: *mut Int2DdsTypeInfo = std::ptr::null_mut();
        unsafe {
            assert_eq!(int2dds_type_info_create(name.as_ptr(), 1, &mut ffi_ptr), INT2DDS_RET_OK);
            let id_field = CString::new("id").unwrap();
            assert_eq!(
                int2dds_type_info_add_field(
                    ffi_ptr,
                    id_field.as_ptr(),
                    INT2DDS_FIELD_INT32,
                    INT2DDS_MEMBER_KEY,
                ),
                INT2DDS_RET_OK
            );
            let seq_field = CString::new("leaves").unwrap();
            let leaf_name = CString::new("NestedLeaf").unwrap();
            assert_eq!(
                int2dds_type_info_add_sequence_of_named_field(
                    ffi_ptr,
                    seq_field.as_ptr(),
                    leaf_name.as_ptr(),
                    0,
                    0,
                ),
                INT2DDS_RET_OK
            );
            let arr_field = CString::new("fixed").unwrap();
            assert_eq!(
                int2dds_type_info_add_array_of_named_field(
                    ffi_ptr,
                    arr_field.as_ptr(),
                    leaf_name.as_ptr(),
                    3,
                    0,
                ),
                INT2DDS_RET_OK
            );
        }
        let ti = unsafe { &*ffi_ptr };
        let ffi_type_id = ti.build_type_identifier();

        let leaf_element =
            TypeIdentifier::MinimalTypeId(EquivalenceHash::compute("NestedLeaf".as_bytes()));
        let type_flags =
            TypeFlag::new(int2dds::xtypes::ExtensibilityKind::Appendable, false, false);
        let mut struct_type =
            CompleteStructType::new(type_flags, "NamedCollType".to_string(), None);
        struct_type.add_member(CompleteStructMember::new(
            0,
            // @key -> implicitly must-understand, matching the FFI builder and derive macro.
            MemberFlag::new(TryConstructKind::Discard, false, false, true, true, false),
            TypeIdentifier::Int32,
            "id".to_string(),
        ));
        struct_type.add_member(CompleteStructMember::new(
            1,
            MemberFlag::new(TryConstructKind::Discard, false, false, false, false, false),
            TypeIdentifier::PlainSequenceSmall {
                header: PlainCollectionHeader::default(),
                bound: 0,
                element_identifier: Box::new(leaf_element.clone()),
            },
            "leaves".to_string(),
        ));
        struct_type.add_member(CompleteStructMember::new(
            2,
            MemberFlag::new(TryConstructKind::Discard, false, false, false, false, false),
            TypeIdentifier::PlainArraySmall {
                header: PlainCollectionHeader::default(),
                array_bound_seq: vec![3],
                element_identifier: Box::new(leaf_element),
            },
            "fixed".to_string(),
        ));

        let derive_type_obj = TypeObject::Complete(CompleteTypeObject::Struct(struct_type));
        let derive_type_id = TypeIdentifier::CompleteTypeId(derive_type_obj.compute_hash());

        assert_eq!(
            ffi_type_id, derive_type_id,
            "TypeIdentifier hashes differ for named sequence/array element fields"
        );

        unsafe { int2dds_type_info_destroy(ffi_ptr) };
    }

    /// Production-path parity: build the `TypeObject` exactly as
    /// `create_topic_with_type_info` does (via `Int2DdsTypeInfo::build_type_object`),
    /// not from the derive macro, then confirm `compute_key` still equals the derive
    /// oracle. `type_info_handle` in raw_key_hash.rs feeds the *derive* TypeObject, so
    /// it cannot see a divergence in the FFI-built one: if member numbering or flag
    /// framing differed, `compute_key` would silently fall through to the non-canonical
    /// md5 path (production sets key_fields, all_fields is None). Covers multi-key
    /// (member_id ordering) and string keys.
    #[test]
    fn test_type_info_compute_key_matches_derive_via_production_builder() {
        use int2dds::common::instance_handle::InstanceHandle;
        use int2dds::topic::type_support::{DdsType, TypeSupport};
        use int2dds::xtypes::HasTypeObject;
        use std::any::Any;

        fn prod_handle(ti: &Int2DdsTypeInfo, payload: &[u8]) -> InstanceHandle {
            let support = crate::raw_type_support::RawTypeSupport::with_type_info(
                ti.type_name.clone(),
                ti.extensibility,
                ti.has_key_field(),
                ti.build_type_identifier(),
                ti.build_type_object(),
            );
            let data = support.deserialize(payload, None).unwrap();
            support.compute_key(data.as_ref())
        }

        // --- single long key (with FFI-vs-derive TypeObject byte-parity canary) ---
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct ProdKeyedLong {
            #[dds(key)]
            id: i32,
            value: i32,
        }
        let inst = ProdKeyedLong { id: 5, value: 99 };
        let oracle = ProdKeyedLong::get_type_support().compute_key(&inst as &dyn Any);
        let mut ti =
            Int2DdsTypeInfo::new("ProdKeyedLong".to_string(), ExtensibilityKind::Appendable);
        ti.push_field("id".to_string(), TypeIdentifier::Int32, INT2DDS_MEMBER_KEY);
        ti.push_field("value".to_string(), TypeIdentifier::Int32, 0);
        assert_eq!(
            match ti.build_type_object() {
                TypeObject::Complete(c) => c.serialize(),
                _ => panic!("Expected Complete"),
            },
            ProdKeyedLong::complete_type_object().serialize(),
            "FFI-built TypeObject bytes must match derive for compute_key parity to hold"
        );
        let handle = prod_handle(&ti, &inst.serialize().unwrap());
        assert_eq!(handle, oracle);
        assert_eq!(*handle.value(), [0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);

        // --- multi-key: two int keys exercise member_id ordering in serialize_key_cdr ---
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct ProdMultiKey {
            #[dds(key)]
            region: i32,
            #[dds(key)]
            id: i32,
            value: i32,
        }
        let inst = ProdMultiKey { region: 7, id: 5, value: 99 };
        let oracle = ProdMultiKey::get_type_support().compute_key(&inst as &dyn Any);
        let mut ti =
            Int2DdsTypeInfo::new("ProdMultiKey".to_string(), ExtensibilityKind::Appendable);
        ti.push_field("region".to_string(), TypeIdentifier::Int32, INT2DDS_MEMBER_KEY);
        ti.push_field("id".to_string(), TypeIdentifier::Int32, INT2DDS_MEMBER_KEY);
        ti.push_field("value".to_string(), TypeIdentifier::Int32, 0);
        let handle = prod_handle(&ti, &inst.serialize().unwrap());
        assert_ne!(handle, InstanceHandle::NIL, "multi-key must not fall to NIL");
        assert_eq!(handle, oracle);

        // --- string key ---
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct ProdStringKey {
            #[dds(key)]
            name: String,
            value: i32,
        }
        let inst = ProdStringKey { name: "BLUE".to_string(), value: 99 };
        let oracle = ProdStringKey::get_type_support().compute_key(&inst as &dyn Any);
        let mut ti =
            Int2DdsTypeInfo::new("ProdStringKey".to_string(), ExtensibilityKind::Appendable);
        ti.push_field("name".to_string(), TypeIdentifier::String8, INT2DDS_MEMBER_KEY);
        ti.push_field("value".to_string(), TypeIdentifier::Int32, 0);
        let handle = prod_handle(&ti, &inst.serialize().unwrap());
        assert_ne!(handle, InstanceHandle::NIL, "string key must not fall to NIL");
        assert_eq!(handle, oracle);
    }

    /// Composite (nested-struct) key parity through a registry-backed dynamic type.
    /// This settles the load-bearing reconciliation for the #336 composite residual.
    /// The derive macro references a nested struct member by its *content-hash*
    /// `CompleteTypeId` (`type_struct.rs` emits `<FieldType>::type_identifier()`), NOT
    /// the name-hash `MinimalTypeId` that `int2dds_type_info_add_named_type_field`
    /// produces — so the FFI builder must reference the nested member by
    /// `CompleteTypeId(nested_type_object.compute_hash())` to byte-match derive, and
    /// register the nested `TypeObject` under that same content hash. A `TypeRegistry`
    /// then resolves the child during `DynamicType` construction, after which
    /// `serialize_key_cdr` recurses into the nested key members. The byte-parity canary
    /// runs first: if the FFI outer TypeObject diverged from derive, discovery would
    /// break before keys ever do. Green here means the remaining work (FFI dependency
    /// API + generator recursion) is plumbing, not a design change.
    #[test]
    fn test_type_info_composite_key_resolves_via_registry() {
        use int2dds::topic::type_support::{DdsType, TypeSupport};
        use int2dds::xtypes::{
            deserialize_dynamic_data, DynamicTypeSupport, HasTypeObject, TypeRegistry,
        };
        use std::any::Any;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Final")]
        struct NestedKeyPart {
            a: i32,
            b: i32,
        }
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Final")]
        struct CompositeKeyed {
            #[dds(key)]
            loc: NestedKeyPart,
            value: i32,
        }

        let inst = CompositeKeyed { loc: NestedKeyPart { a: 7, b: 9 }, value: 1 };
        let oracle = CompositeKeyed::get_type_support().compute_key(&inst as &dyn Any);
        let bytes = inst.serialize().unwrap();

        // Nested member reference = content-hash CompleteTypeId of the nested TypeObject
        // (computed from the nested type_info, mirroring what the production builder will
        // do — here the derived NestedKeyPart stands in for a nested Int2DdsTypeInfo).
        let nested_to = TypeObject::Complete(NestedKeyPart::complete_type_object());
        let nested_id = TypeIdentifier::CompleteTypeId(nested_to.compute_hash());

        // Build the outer type through the FFI builder, referencing the nested struct.
        let mut ti = Int2DdsTypeInfo::new("CompositeKeyed".to_string(), ExtensibilityKind::Final);
        ti.push_field("loc".to_string(), nested_id, INT2DDS_MEMBER_KEY);
        ti.push_field("value".to_string(), TypeIdentifier::Int32, 0);

        // Canary: the FFI-built outer TypeObject must byte-match derive.
        let outer_to = ti.build_type_object();
        assert_eq!(
            match &outer_to {
                TypeObject::Complete(c) => c.serialize(),
                _ => panic!("Expected Complete"),
            },
            CompositeKeyed::complete_type_object().serialize(),
            "FFI composite TypeObject must byte-match derive (content-hash member ref)"
        );

        // Register the nested type under its content hash (matching the outer member's
        // CompleteTypeId ref) so the DynamicType build resolves it instead of leaving an
        // unresolved external ref.
        let mut registry = TypeRegistry::new();
        registry.register_type_object(nested_to);

        let dts = DynamicTypeSupport::from_type_object_with_registry(outer_to, &registry)
            .expect("outer dynamic type must build with nested resolved");
        let dyn_data = deserialize_dynamic_data(&bytes, dts.dynamic_type())
            .expect("sample must decode including nested struct");
        let handle = dts.compute_key(&dyn_data);

        assert_eq!(handle, oracle, "composite key must match derive oracle");
        assert_eq!(*handle.value(), [0, 0, 0, 7, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0]);
    }

    /// `@external` nested-struct parity: the derive treats `Box<T>` as a transparent
    /// wrapper and only raises the EXTERNAL member flag, so the FFI builder referencing
    /// the nested type by content hash with `INT2DDS_MEMBER_EXTERNAL` must byte-match it.
    /// This is the TypeObject the C#/Python/Java generators advertise for such members.
    #[test]
    fn test_type_info_external_nested_field_matches_derive() {
        use int2dds::xtypes::HasTypeObject;
        use int2dds_derive::DdsType;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct Inner {
            x: i32,
            y: f64,
        }
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct Outer {
            #[dds(key)]
            id: i32,
            #[dds(external)]
            ext: Box<Inner>,
        }

        let mut inner = Int2DdsTypeInfo::new("Inner".to_string(), ExtensibilityKind::Appendable);
        inner.push_field("x".to_string(), TypeIdentifier::Int32, 0);
        inner.push_field("y".to_string(), TypeIdentifier::Float64, 0);

        let mut outer = Int2DdsTypeInfo::new("Outer".to_string(), ExtensibilityKind::Appendable);
        outer.push_field("id".to_string(), TypeIdentifier::Int32, INT2DDS_MEMBER_KEY);
        outer.push_nested_field("ext".to_string(), &inner, INT2DDS_MEMBER_EXTERNAL);

        let ffi_bytes = match outer.build_type_object() {
            TypeObject::Complete(c) => c.serialize(),
            _ => panic!("Expected Complete"),
        };
        assert_eq!(
            ffi_bytes,
            Outer::complete_type_object().serialize(),
            "FFI external nested TypeObject must byte-match derive"
        );
    }

    /// Generator-representative drift guard: reproduces what the C#/Python bindings do when
    /// they walk generated `DdsTypeInfoFields`/`_dds_type_info_fields` — build each nested
    /// `Int2DdsTypeInfo` via the same `push_field`/`string_id`/`push_nested_field` calls the
    /// C ABI `add_field`/`add_string_field`/`add_nested_field` wrap — for a richer shape than
    /// the two-primitive proof above: a nested-in-nested key whose innermost member is a
    /// string. The outer TypeObject must byte-match derive (so the content-hash refs the
    /// bindings emit line up), and the whole closure must resolve so the composite key equals
    /// the native-Rust oracle. Divergence in nested extensibility, member order, string
    /// bound, or key flags would break byte-parity here before it ever reached a peer.
    #[test]
    fn test_type_info_nested_in_nested_string_key_matches_derive() {
        use int2dds::topic::type_support::{DdsType, TypeSupport};
        use int2dds::xtypes::{
            deserialize_dynamic_data, DynamicTypeSupport, HasTypeObject, TypeRegistry,
        };
        use std::any::Any;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Final")]
        struct Inner {
            x: i32,
            label: String,
        }
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Final")]
        struct Mid {
            inner: Inner,
            region: i32,
        }
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Final")]
        struct Outer {
            #[dds(key)]
            loc: Mid,
            value: i32,
        }

        let inst = Outer {
            loc: Mid { inner: Inner { x: 5, label: "hi".to_string() }, region: 3 },
            value: 1,
        };
        let oracle = Outer::get_type_support().compute_key(&inst as &dyn Any);
        let bytes = inst.serialize().unwrap();

        // Innermost: Inner { i32, string } — string via string_id (== add_string_field).
        let mut inner_ti = Int2DdsTypeInfo::new("Inner".to_string(), ExtensibilityKind::Final);
        inner_ti.push_field("x".to_string(), TypeIdentifier::Int32, 0);
        inner_ti.push_field("label".to_string(), string_id(0, false), 0);

        // Middle: Mid { Inner, i32 } — nested via push_nested_field (== add_nested_field).
        let mut mid_ti = Int2DdsTypeInfo::new("Mid".to_string(), ExtensibilityKind::Final);
        mid_ti.push_nested_field("inner".to_string(), &inner_ti, 0);
        mid_ti.push_field("region".to_string(), TypeIdentifier::Int32, 0);

        // Outer: Outer { @key Mid, i32 }.
        let mut outer_ti = Int2DdsTypeInfo::new("Outer".to_string(), ExtensibilityKind::Final);
        outer_ti.push_nested_field("loc".to_string(), &mid_ti, INT2DDS_MEMBER_KEY);
        outer_ti.push_field("value".to_string(), TypeIdentifier::Int32, 0);

        // Byte-parity at every level: transitively validates the content-hash refs.
        let ser = |to: &TypeObject| match to {
            TypeObject::Complete(c) => c.serialize(),
            _ => panic!("Expected Complete"),
        };
        assert_eq!(
            ser(&inner_ti.build_type_object()),
            Inner::complete_type_object().serialize(),
            "nested Inner TypeObject must byte-match derive"
        );
        assert_eq!(
            ser(&mid_ti.build_type_object()),
            Mid::complete_type_object().serialize(),
            "nested Mid TypeObject must byte-match derive"
        );
        let outer_to = outer_ti.build_type_object();
        assert_eq!(
            ser(&outer_to),
            Outer::complete_type_object().serialize(),
            "outer TypeObject must byte-match derive"
        );

        // Resolve exactly as RawTypeSupport::with_type_info_and_deps does: register the whole
        // dependency closure by content-hash id, then build the DynamicType against it.
        let mut registry = TypeRegistry::new();
        for (id, obj) in outer_ti.dependency_closure() {
            registry.register_type_object_with_id(&id, obj);
        }
        let dts = DynamicTypeSupport::from_type_object_with_registry(outer_to, &registry)
            .expect("outer dynamic type must build with the full nested closure resolved");
        let dyn_data = deserialize_dynamic_data(&bytes, dts.dynamic_type())
            .expect("sample must decode including nested-in-nested struct with a string");
        let handle = dts.compute_key(&dyn_data);

        assert_eq!(handle, oracle, "nested-in-nested composite key must match derive oracle");
    }

    /// Covers the shipped generator default: unspecified IDL extensibility resolves to
    /// Appendable, so the generated nested-key types are Appendable, not Final. The
    /// extensibility flag feeds the TypeObject content hash, so an all-Final golden alone
    /// would not prove the content-hash refs the bindings emit line up for the default
    /// case. (The key CDR itself is extensibility-agnostic below Mutable — serialize_key_cdr
    /// serializes nested Final/Appendable structs inline without a DHEADER — so the handle
    /// bytes match Final; what this guards is the byte-parity/resolution at Appendable.)
    #[test]
    fn test_type_info_composite_key_appendable_matches_derive() {
        use int2dds::topic::type_support::{DdsType, TypeSupport};
        use int2dds::xtypes::{
            deserialize_dynamic_data, DynamicTypeSupport, HasTypeObject, TypeRegistry,
        };
        use std::any::Any;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct Point {
            x: i32,
            y: i32,
        }
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct Track {
            #[dds(key)]
            origin: Point,
            id: i32,
        }

        let inst = Track { origin: Point { x: 5, y: -3 }, id: 1 };
        let oracle = Track::get_type_support().compute_key(&inst as &dyn Any);
        let bytes = inst.serialize().unwrap();

        let mut point_ti = Int2DdsTypeInfo::new("Point".to_string(), ExtensibilityKind::Appendable);
        point_ti.push_field("x".to_string(), TypeIdentifier::Int32, 0);
        point_ti.push_field("y".to_string(), TypeIdentifier::Int32, 0);

        let mut track_ti = Int2DdsTypeInfo::new("Track".to_string(), ExtensibilityKind::Appendable);
        track_ti.push_nested_field("origin".to_string(), &point_ti, INT2DDS_MEMBER_KEY);
        track_ti.push_field("id".to_string(), TypeIdentifier::Int32, 0);

        let ser = |to: &TypeObject| match to {
            TypeObject::Complete(c) => c.serialize(),
            _ => panic!("Expected Complete"),
        };
        assert_eq!(
            ser(&point_ti.build_type_object()),
            Point::complete_type_object().serialize(),
            "Appendable nested Point TypeObject must byte-match derive"
        );
        let track_to = track_ti.build_type_object();
        assert_eq!(
            ser(&track_to),
            Track::complete_type_object().serialize(),
            "Appendable outer Track TypeObject must byte-match derive"
        );

        let mut registry = TypeRegistry::new();
        for (id, obj) in track_ti.dependency_closure() {
            registry.register_type_object_with_id(&id, obj);
        }
        let dts = DynamicTypeSupport::from_type_object_with_registry(track_to, &registry)
            .expect("Appendable outer dynamic type must build with nested resolved");
        let dyn_data = deserialize_dynamic_data(&bytes, dts.dynamic_type())
            .expect("Appendable sample must decode including nested struct");
        let handle = dts.compute_key(&dyn_data);

        assert_eq!(handle, oracle, "Appendable composite key must match derive oracle");
    }

    /// enum-typed @key member. The enum builder (`new_enum` + `push_enum_literal`) must
    /// byte-match the derive enum TypeObject (bit_bound 32, literal values/flags), and the
    /// key resolves to the i32 discriminant — matching the native-Rust oracle.
    #[test]
    fn test_type_info_enum_key_matches_derive() {
        use int2dds::topic::type_support::{DdsType, TypeSupport};
        use int2dds::xtypes::{
            deserialize_dynamic_data, DynamicTypeSupport, HasTypeObject, TypeRegistry,
        };
        use std::any::Any;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds")]
        enum Color {
            Red = 0,
            Green = 5,
            Blue = 9,
        }
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct EnumKeyed {
            #[dds(key)]
            c: Color,
            v: i32,
        }

        let inst = EnumKeyed { c: Color::Green, v: 9 };
        let oracle = EnumKeyed::get_type_support().compute_key(&inst as &dyn Any);
        let bytes = inst.serialize().unwrap();

        // Enum builder: IDL enums are i32 -> bit_bound 32, no @default.
        let mut color_ti = Int2DdsTypeInfo::new_enum("Color".to_string(), 32);
        color_ti.push_enum_literal("Red".to_string(), 0, false);
        color_ti.push_enum_literal("Green".to_string(), 5, false);
        color_ti.push_enum_literal("Blue".to_string(), 9, false);

        assert_eq!(
            match color_ti.build_type_object() {
                TypeObject::Complete(c) => c.serialize(),
                _ => panic!("Expected Complete"),
            },
            Color::complete_type_object().serialize(),
            "FFI enum TypeObject must byte-match derive"
        );

        let mut outer =
            Int2DdsTypeInfo::new("EnumKeyed".to_string(), ExtensibilityKind::Appendable);
        outer.push_nested_field("c".to_string(), &color_ti, INT2DDS_MEMBER_KEY);
        outer.push_field("v".to_string(), TypeIdentifier::Int32, 0);

        let outer_to = outer.build_type_object();
        assert_eq!(
            match &outer_to {
                TypeObject::Complete(c) => c.serialize(),
                _ => panic!("Expected Complete"),
            },
            EnumKeyed::complete_type_object().serialize(),
            "outer TypeObject with enum key must byte-match derive"
        );

        let mut registry = TypeRegistry::new();
        for (id, obj) in outer.dependency_closure() {
            registry.register_type_object_with_id(&id, obj);
        }
        let dts = DynamicTypeSupport::from_type_object_with_registry(outer_to, &registry)
            .expect("outer dynamic type must build with enum resolved");
        let dyn_data = deserialize_dynamic_data(&bytes, dts.dynamic_type())
            .expect("sample must decode including enum member");
        let handle = dts.compute_key(&dyn_data);

        assert_eq!(handle, oracle, "enum key must match derive oracle");
        assert_eq!(*handle.value(), [0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
    }

    /// Fixed-array-of-struct @key (`Point[2]`). Element referenced by content-hash wrapped
    /// in a plain-array id; key resolves to the raw 16-byte inline serialization.
    #[test]
    fn test_type_info_array_of_struct_key_matches_derive() {
        use int2dds::topic::type_support::{DdsType, TypeSupport};
        use int2dds::xtypes::{
            deserialize_dynamic_data, DynamicTypeSupport, HasTypeObject, TypeRegistry,
        };
        use std::any::Any;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct Point {
            x: i32,
            y: i32,
        }
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct ArrKeyed {
            #[dds(key)]
            pts: [Point; 2],
            v: i32,
        }

        let inst = ArrKeyed { pts: [Point { x: 1, y: 2 }, Point { x: 3, y: 4 }], v: 9 };
        let oracle = ArrKeyed::get_type_support().compute_key(&inst as &dyn Any);
        let bytes = inst.serialize().unwrap();

        let mut point_ti = Int2DdsTypeInfo::new("Point".to_string(), ExtensibilityKind::Appendable);
        point_ti.push_field("x".to_string(), TypeIdentifier::Int32, 0);
        point_ti.push_field("y".to_string(), TypeIdentifier::Int32, 0);

        let mut outer = Int2DdsTypeInfo::new("ArrKeyed".to_string(), ExtensibilityKind::Appendable);
        outer.push_array_of_nested_field("pts".to_string(), &point_ti, 2, INT2DDS_MEMBER_KEY);
        outer.push_field("v".to_string(), TypeIdentifier::Int32, 0);

        let outer_to = outer.build_type_object();
        assert_eq!(
            match &outer_to {
                TypeObject::Complete(c) => c.serialize(),
                _ => panic!("Expected Complete"),
            },
            ArrKeyed::complete_type_object().serialize(),
            "outer TypeObject with array-of-struct key must byte-match derive"
        );

        let mut registry = TypeRegistry::new();
        for (id, obj) in outer.dependency_closure() {
            registry.register_type_object_with_id(&id, obj);
        }
        let dts = DynamicTypeSupport::from_type_object_with_registry(outer_to, &registry)
            .expect("outer dynamic type must build with array element resolved");
        let dyn_data = deserialize_dynamic_data(&bytes, dts.dynamic_type())
            .expect("sample must decode including array-of-struct member");
        let handle = dts.compute_key(&dyn_data);

        assert_eq!(handle, oracle, "array-of-struct key must match derive oracle");
        assert_eq!(*handle.value(), [0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4]);
    }

    /// Sequence-of-struct @key (`sequence<Point>`). Element referenced by content-hash
    /// wrapped in a plain-sequence id; the >16-byte key hashes (MD5) — must match derive.
    #[test]
    fn test_type_info_sequence_of_struct_key_matches_derive() {
        use int2dds::topic::type_support::{DdsType, TypeSupport};
        use int2dds::xtypes::{
            deserialize_dynamic_data, DynamicTypeSupport, HasTypeObject, TypeRegistry,
        };
        use std::any::Any;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct Point {
            x: i32,
            y: i32,
        }
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct SeqKeyed {
            #[dds(key)]
            pts: Vec<Point>,
            v: i32,
        }

        let inst = SeqKeyed { pts: vec![Point { x: 1, y: 2 }, Point { x: 3, y: 4 }], v: 9 };
        let oracle = SeqKeyed::get_type_support().compute_key(&inst as &dyn Any);
        let bytes = inst.serialize().unwrap();

        let mut point_ti = Int2DdsTypeInfo::new("Point".to_string(), ExtensibilityKind::Appendable);
        point_ti.push_field("x".to_string(), TypeIdentifier::Int32, 0);
        point_ti.push_field("y".to_string(), TypeIdentifier::Int32, 0);

        let mut outer = Int2DdsTypeInfo::new("SeqKeyed".to_string(), ExtensibilityKind::Appendable);
        outer.push_sequence_of_nested_field("pts".to_string(), &point_ti, 0, INT2DDS_MEMBER_KEY);
        outer.push_field("v".to_string(), TypeIdentifier::Int32, 0);

        let outer_to = outer.build_type_object();
        assert_eq!(
            match &outer_to {
                TypeObject::Complete(c) => c.serialize(),
                _ => panic!("Expected Complete"),
            },
            SeqKeyed::complete_type_object().serialize(),
            "outer TypeObject with sequence-of-struct key must byte-match derive"
        );

        let mut registry = TypeRegistry::new();
        for (id, obj) in outer.dependency_closure() {
            registry.register_type_object_with_id(&id, obj);
        }
        let dts = DynamicTypeSupport::from_type_object_with_registry(outer_to, &registry)
            .expect("outer dynamic type must build with sequence element resolved");
        let dyn_data = deserialize_dynamic_data(&bytes, dts.dynamic_type())
            .expect("sample must decode including sequence-of-struct member");
        let handle = dts.compute_key(&dyn_data);

        assert_eq!(handle, oracle, "sequence-of-struct key must match derive oracle (MD5)");
    }

    /// The bitmask builder (`new_bitmask` + `push_bitmask_flag`) must byte-match the derive
    /// bitmask TypeObject (bit_bound, flag positions/names). Proves the polymorphic builder's
    /// bitmask arm so bitmask-typed members resolve via the same content-hash machinery.
    #[test]
    #[allow(non_upper_case_globals)] // derive emits per-flag consts named after the variants
    fn test_type_info_bitmask_type_object_matches_derive() {
        use int2dds::xtypes::HasTypeObject;
        use int2dds_derive::DdsType;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", bitmask, bit_bound = 8)]
        enum Permissions {
            #[dds(position = 0)]
            Read,
            #[dds(position = 1)]
            Write,
            #[dds(position = 5)]
            Admin,
        }

        let mut bm = Int2DdsTypeInfo::new_bitmask("Permissions".to_string(), 8);
        bm.push_bitmask_flag("Read".to_string(), 0);
        bm.push_bitmask_flag("Write".to_string(), 1);
        bm.push_bitmask_flag("Admin".to_string(), 5);

        assert_eq!(
            match bm.build_type_object() {
                TypeObject::Complete(c) => c.serialize(),
                _ => panic!("Expected Complete"),
            },
            Permissions::complete_type_object().serialize(),
            "FFI bitmask TypeObject must byte-match derive"
        );
    }

    fn complete_bytes(ti: &Int2DdsTypeInfo) -> Vec<u8> {
        match ti.build_type_object() {
            TypeObject::Complete(c) => c.serialize(),
            _ => panic!("Expected Complete"),
        }
    }

    /// The bitset builder (`new_bitset` + `push_bitfield`) must byte-match the derive
    /// bitset TypeObject (cumulative positions, bitcounts, holder ids), and a struct
    /// carrying the bitset must decode a derive-serialized sample and compute the same key.
    #[test]
    fn test_type_info_bitset_key_matches_derive() {
        use int2dds::topic::type_support::{DdsType, TypeSupport};
        use int2dds::xtypes::{
            deserialize_dynamic_data, DynamicTypeSupport, HasTypeObject, TypeRegistry,
        };
        use std::any::Any;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", bitset)]
        struct Bits {
            #[dds(bitfield = 3)]
            a: u8,
            #[dds(bitfield = 10)]
            b: u16,
        }
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct BitsetKeyed {
            #[dds(key)]
            id: i32,
            bits: Bits,
        }

        let mut bits_ti = Int2DdsTypeInfo::new_bitset("Bits".to_string());
        bits_ti.push_bitfield("a".to_string(), 3, TypeIdentifier::Byte);
        bits_ti.push_bitfield("b".to_string(), 10, TypeIdentifier::Uint16);
        assert_eq!(
            complete_bytes(&bits_ti),
            Bits::complete_type_object().serialize(),
            "FFI bitset TypeObject must byte-match derive"
        );

        let mut outer =
            Int2DdsTypeInfo::new("BitsetKeyed".to_string(), ExtensibilityKind::Appendable);
        outer.push_field("id".to_string(), TypeIdentifier::Int32, INT2DDS_MEMBER_KEY);
        outer.push_nested_field("bits".to_string(), &bits_ti, 0);
        assert_eq!(
            complete_bytes(&outer),
            BitsetKeyed::complete_type_object().serialize(),
            "outer TypeObject with bitset member must byte-match derive"
        );

        let inst = BitsetKeyed { id: 3, bits: Bits { a: 5, b: 300 } };
        let oracle = BitsetKeyed::get_type_support().compute_key(&inst as &dyn Any);
        let bytes = inst.serialize().unwrap();

        let mut registry = TypeRegistry::new();
        for (id, obj) in outer.dependency_closure() {
            registry.register_type_object_with_id(&id, obj);
        }
        let dts = DynamicTypeSupport::from_type_object_with_registry(
            outer.build_type_object(),
            &registry,
        )
        .expect("outer dynamic type must build with bitset resolved");
        let dyn_data = deserialize_dynamic_data(&bytes, dts.dynamic_type())
            .expect("sample must decode including bitset member");
        assert_eq!(dts.compute_key(&dyn_data), oracle, "bitset-carrying key must match derive");
    }

    /// The union builder (`new_union` + `push_*_field` + `push_union_label`) must
    /// byte-match the derive union TypeObject when there is no `default:` case, and the
    /// `INT2DDS_MEMBER_DEFAULT` member must let the dynamic decoder accept a discriminator
    /// that matches no label (what a C publisher writes for its default case).
    #[test]
    fn test_type_info_union_key_matches_derive() {
        use int2dds::serialize::cdr::{PrimitiveSerialize, StringSerialize};
        use int2dds::topic::type_support::{DdsType, TypeSupport};
        use int2dds::xtypes::{
            deserialize_dynamic_data, DynamicTypeSupport, HasTypeObject, TypeRegistry,
        };
        use std::any::Any;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        #[repr(i32)]
        enum Shape {
            Circle(i32) = 0,
            Label(String) = 1,
        }
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        #[repr(i32)]
        enum Fallback {
            Value(i32) = 0,
            #[dds(default)]
            Other(u8) = -1,
        }
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct UnionKeyed {
            #[dds(key)]
            id: i32,
            shape: Shape,
            fallback: Fallback,
        }

        let mut shape_ti = Int2DdsTypeInfo::new_union(
            "Shape".to_string(),
            ExtensibilityKind::Appendable,
            TypeIdentifier::Int32,
        );
        shape_ti.push_field("Circle".to_string(), TypeIdentifier::Int32, 0);
        assert!(shape_ti.push_union_label("Circle", 0));
        shape_ti.push_field("Label".to_string(), TypeIdentifier::String8, 0);
        assert!(shape_ti.push_union_label("Label", 1));
        assert!(!shape_ti.push_union_label("Missing", 2), "unknown member must be rejected");
        assert_eq!(
            complete_bytes(&shape_ti),
            Shape::complete_type_object().serialize(),
            "FFI union TypeObject must byte-match derive"
        );

        let mut fallback_ti = Int2DdsTypeInfo::new_union(
            "Fallback".to_string(),
            ExtensibilityKind::Appendable,
            TypeIdentifier::Int32,
        );
        fallback_ti.push_field("Value".to_string(), TypeIdentifier::Int32, 0);
        assert!(fallback_ti.push_union_label("Value", 0));
        fallback_ti.push_field("Other".to_string(), TypeIdentifier::Byte, INT2DDS_MEMBER_DEFAULT);
        assert!(fallback_ti.push_union_label("Other", -1));
        match fallback_ti.build_type_object() {
            TypeObject::Complete(CompleteTypeObject::Union(u)) => {
                assert!(!u.member_seq[0].common.member_flags.is_default());
                assert!(u.member_seq[1].common.member_flags.is_default());
                assert_eq!(u.member_seq[1].common.label_seq, vec![-1]);
            }
            _ => panic!("Expected Complete union"),
        }

        let mut outer =
            Int2DdsTypeInfo::new("UnionKeyed".to_string(), ExtensibilityKind::Appendable);
        outer.push_field("id".to_string(), TypeIdentifier::Int32, INT2DDS_MEMBER_KEY);
        outer.push_nested_field("shape".to_string(), &shape_ti, 0);
        outer.push_nested_field("fallback".to_string(), &fallback_ti, 0);

        let inst = UnionKeyed {
            id: 4,
            shape: Shape::Label("x".to_string()),
            fallback: Fallback::Other(7),
        };
        let oracle = UnionKeyed::get_type_support().compute_key(&inst as &dyn Any);
        let mut bytes = inst.serialize().unwrap().to_vec();
        let disc_pos = bytes
            .windows(4)
            .position(|w| w == [0xff; 4])
            .expect("derive writes -1 for the default variant");
        bytes[disc_pos..disc_pos + 4].copy_from_slice(&99i32.to_le_bytes());

        let mut registry = TypeRegistry::new();
        for (id, obj) in outer.dependency_closure() {
            registry.register_type_object_with_id(&id, obj);
        }
        let dts = DynamicTypeSupport::from_type_object_with_registry(
            outer.build_type_object(),
            &registry,
        )
        .expect("outer dynamic type must build with unions resolved");
        let dyn_data = deserialize_dynamic_data(&bytes, dts.dynamic_type())
            .expect("sample with an unlisted default discriminator must decode");
        let handle = dts.compute_key(&dyn_data);
        assert_eq!(handle, oracle, "union-carrying key must match derive");
        assert_eq!(*handle.value(), [0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
    }

    /// Map members get the same plain-map id the derive advertises (scalar, nested-value
    /// and bounded forms), so the outer TypeObject byte-matches, and a struct with such
    /// maps decodes a derive-serialized sample and computes the same key.
    #[test]
    fn test_type_info_map_field_key_matches_derive() {
        use int2dds::topic::type_support::{DdsType, TypeSupport};
        use int2dds::xtypes::{
            deserialize_dynamic_data, DynamicTypeSupport, EquivalenceKind, HasTypeObject,
            TypeRegistry,
        };
        use std::any::Any;
        use std::collections::HashMap;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct Entry {
            code: i32,
            label: String,
        }
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct MapKeyed {
            #[dds(key)]
            id: i32,
            counts: HashMap<String, i32>,
            entries: HashMap<i32, Entry>,
            #[dds(bound = 4)]
            small: HashMap<String, f64>,
        }

        let mut entry_ti = Int2DdsTypeInfo::new("Entry".to_string(), ExtensibilityKind::Appendable);
        entry_ti.push_field("code".to_string(), TypeIdentifier::Int32, 0);
        entry_ti.push_field("label".to_string(), TypeIdentifier::String8, 0);

        let mut outer = Int2DdsTypeInfo::new("MapKeyed".to_string(), ExtensibilityKind::Appendable);
        outer.push_field("id".to_string(), TypeIdentifier::Int32, INT2DDS_MEMBER_KEY);
        outer.push_map_field(
            "counts".to_string(),
            TypeIdentifier::String8,
            TypeIdentifier::Int32,
            0,
            0,
        );
        outer.push_map_of_nested_field(
            "entries".to_string(),
            TypeIdentifier::Int32,
            &entry_ti,
            0,
            0,
        );
        outer.push_map_field(
            "small".to_string(),
            TypeIdentifier::String8,
            TypeIdentifier::Float64,
            4,
            0,
        );

        match outer.build_type_object() {
            TypeObject::Complete(CompleteTypeObject::Struct(s)) => {
                match &s.member_seq[1].common.member_type_id {
                    TypeIdentifier::PlainMapSmall { header, bound, .. } => {
                        assert_eq!(header.equiv_kind, EquivalenceKind::Both);
                        assert_eq!(*bound, 0);
                    }
                    other => panic!("scalar map must be PlainMapSmall, got {:?}", other),
                }
                match &s.member_seq[2].common.member_type_id {
                    TypeIdentifier::PlainMapSmall {
                        header,
                        key_identifier,
                        element_identifier,
                        ..
                    } => {
                        assert_eq!(header.equiv_kind, EquivalenceKind::Complete);
                        assert_eq!(**key_identifier, TypeIdentifier::Int32);
                        assert!(matches!(**element_identifier, TypeIdentifier::CompleteTypeId(_)));
                    }
                    other => panic!("nested-value map must be PlainMapSmall, got {:?}", other),
                }
                match &s.member_seq[3].common.member_type_id {
                    TypeIdentifier::PlainMapSmall { bound, .. } => assert_eq!(*bound, 4),
                    other => panic!("bounded map must keep its bound, got {:?}", other),
                }
            }
            _ => panic!("Expected Complete struct"),
        }
        assert_eq!(outer.dependency_closure().len(), 1, "map value type must be a dependency");
        assert_eq!(
            complete_bytes(&outer),
            MapKeyed::complete_type_object().serialize(),
            "outer TypeObject with map members must byte-match derive"
        );

        let inst = MapKeyed {
            id: 11,
            counts: HashMap::from([("a".to_string(), 1)]),
            entries: HashMap::from([(2, Entry { code: 3, label: "b".to_string() })]),
            small: HashMap::from([("c".to_string(), 1.5)]),
        };
        let oracle = MapKeyed::get_type_support().compute_key(&inst as &dyn Any);
        let bytes = inst.serialize().unwrap();

        let mut registry = TypeRegistry::new();
        for (id, obj) in outer.dependency_closure() {
            registry.register_type_object_with_id(&id, obj);
        }
        let dts = DynamicTypeSupport::from_type_object_with_registry(
            outer.build_type_object(),
            &registry,
        )
        .expect("outer dynamic type must build with map entries resolved");
        let dyn_data = deserialize_dynamic_data(&bytes, dts.dynamic_type())
            .expect("sample must decode including map members");
        let handle = dts.compute_key(&dyn_data);
        assert_eq!(handle, oracle, "map-carrying key must match derive");
        assert_eq!(*handle.value(), [0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
    }
}
