//! # Type Info Builder
//!
//! Provides `Int2DdsTypeInfo` for building DDS-XTypes TypeIdentifier and TypeObject
//! from field descriptions. This enables the FFI layer to send type information
//! during discovery (sent as PID_TYPE_INFORMATION 0x0075 + legacy 0x0069, and
//! PID_TYPE_OBJECTV1 0x0072).
//!
//! ## Usage from C
//!
//! ```c
//! Int2DdsTypeInfo *ti = PrimitivesType_type_info(); // auto-generated by IDL
//! int2dds_create_topic_with_type_info(participant, "TopicName", ti, NULL, &topic);
//! int2dds_type_info_destroy(ti);
//! ```

use std::ffi::CStr;

use int2dds::{
    serialize::cdr::ExtensibilityKind,
    xtypes::{
        plain_collection_equiv_kind, CollectionElementFlag, CommonStructMember,
        CompleteMemberDetail, CompleteStructMember, CompleteStructType, CompleteTypeObject,
        EquivalenceHash, MemberFlag, PlainCollectionHeader, TryConstructKind, TypeFlag,
        TypeIdentifier, TypeObject,
    },
};

use super::error::*;

/// Decode a C string argument to `&str`, returning `INT2DDS_RET_INVALID_ARGUMENT`
/// when it is not valid UTF-8. Caller must have already null-checked the pointer.
macro_rules! cstr_arg {
    ($ptr:expr) => {
        match CStr::from_ptr($ptr).to_str() {
            Ok(s) => s,
            Err(_) => return INT2DDS_RET_INVALID_ARGUMENT,
        }
    };
}

/// Field type constants for C FFI.
pub const INT2DDS_FIELD_BOOL: i32 = 0;
pub const INT2DDS_FIELD_BYTE: i32 = 1;
pub const INT2DDS_FIELD_CHAR8: i32 = 2;
pub const INT2DDS_FIELD_INT8: i32 = 3;
pub const INT2DDS_FIELD_INT16: i32 = 4;
pub const INT2DDS_FIELD_INT32: i32 = 5;
pub const INT2DDS_FIELD_INT64: i32 = 6;
pub const INT2DDS_FIELD_UINT8: i32 = 7;
pub const INT2DDS_FIELD_UINT16: i32 = 8;
pub const INT2DDS_FIELD_UINT32: i32 = 9;
pub const INT2DDS_FIELD_UINT64: i32 = 10;
pub const INT2DDS_FIELD_FLOAT32: i32 = 11;
pub const INT2DDS_FIELD_FLOAT64: i32 = 12;
pub const INT2DDS_FIELD_STRING: i32 = 13;
pub const INT2DDS_FIELD_CHAR16: i32 = 14;
pub const INT2DDS_FIELD_WSTRING: i32 = 15;
pub const INT2DDS_FIELD_NESTED: i32 = 16;
pub const INT2DDS_FIELD_SEQUENCE: i32 = 17;
pub const INT2DDS_FIELD_ARRAY: i32 = 18;
pub const INT2DDS_FIELD_MAP: i32 = 19;
pub const INT2DDS_MEMBER_KEY: i32 = 1 << 0;
pub const INT2DDS_MEMBER_OPTIONAL: i32 = 1 << 1;
pub const INT2DDS_MEMBER_MUST_UNDERSTAND: i32 = 1 << 2;
pub const INT2DDS_MEMBER_EXTERNAL: i32 = 1 << 3;

/// Internal field description.
struct FieldInfo {
    name: String,
    type_id: TypeIdentifier,
    flags: i32,
}

impl FieldInfo {
    fn is_key(&self) -> bool {
        self.flags & INT2DDS_MEMBER_KEY != 0
    }
    fn is_optional(&self) -> bool {
        self.flags & INT2DDS_MEMBER_OPTIONAL != 0
    }
    fn is_must_understand(&self) -> bool {
        self.flags & INT2DDS_MEMBER_MUST_UNDERSTAND != 0
    }
    fn is_external(&self) -> bool {
        self.flags & INT2DDS_MEMBER_EXTERNAL != 0
    }
}

/// Opaque type info builder for the FFI layer.
///
/// Collects field descriptions and builds TypeIdentifier/TypeObject
/// for DDS-XTypes discovery.
pub struct Int2DdsTypeInfo {
    pub(crate) type_name: String,
    pub(crate) extensibility: ExtensibilityKind,
    fields: Vec<FieldInfo>,
}

impl Int2DdsTypeInfo {
    /// Build a CompleteStructType from the collected fields.
    fn build_complete_struct_type(&self) -> CompleteStructType {
        let ext_kind = match self.extensibility {
            ExtensibilityKind::Final => int2dds::xtypes::ExtensibilityKind::Final,
            ExtensibilityKind::Appendable => int2dds::xtypes::ExtensibilityKind::Appendable,
            ExtensibilityKind::Mutable => int2dds::xtypes::ExtensibilityKind::Mutable,
        };
        let type_flags = TypeFlag::new(ext_kind, false, false);
        let mut complete = CompleteStructType::new(type_flags, self.type_name.clone(), None);

        for (index, field) in self.fields.iter().enumerate() {
            let member_flags = MemberFlag::new(
                TryConstructKind::Discard,
                field.is_external(),
                field.is_optional(),
                // @key members are implicitly must-understand (XTypes 7.2.2.4.4.4.7),
                // matching the derive macro so FFI-built and derived TypeObjects hash alike.
                field.is_must_understand() || field.is_key(),
                field.is_key(),
                false, // is_default
            );
            let common = CommonStructMember {
                member_id: index as u32,
                member_flags,
                member_type_id: field.type_id.clone(),
            };
            let detail = CompleteMemberDetail {
                name: field.name.clone(),
                ann_builtin: None,
                ann_custom: Vec::new(),
            };
            complete.add_member(CompleteStructMember { common, detail });
        }

        complete
    }

    /// Build TypeObject from the collected fields.
    pub(crate) fn build_type_object(&self) -> TypeObject {
        let complete = self.build_complete_struct_type();
        TypeObject::Complete(CompleteTypeObject::Struct(complete))
    }

    /// Check if any field is marked as a key field.
    pub(crate) fn has_key_field(&self) -> bool {
        self.fields.iter().any(|f| f.is_key())
    }

    /// Derive key-field descriptors (index + scalar type) for the keyed fields, so a topic
    /// created from this type_info still extracts instance keys (compute_key) like the
    /// field-descriptor path. Non-scalar keys are skipped (extraction supports scalars).
    pub(crate) fn key_field_infos(&self) -> Vec<crate::raw_type_support::KeyFieldInfo> {
        use crate::raw_type_support::{KeyFieldInfo, KeyFieldType};
        let mut out = Vec::new();
        for (index, field) in self.fields.iter().enumerate() {
            if !field.is_key() {
                continue;
            }
            let field_type = match &field.type_id {
                TypeIdentifier::String8
                | TypeIdentifier::String8Small { .. }
                | TypeIdentifier::String8Large { .. } => KeyFieldType::String,
                TypeIdentifier::Int32 => KeyFieldType::Int32,
                TypeIdentifier::Uint32 => KeyFieldType::UInt32,
                TypeIdentifier::Int16 => KeyFieldType::Int16,
                TypeIdentifier::Uint16 => KeyFieldType::UInt16,
                TypeIdentifier::Int64 => KeyFieldType::Int64,
                TypeIdentifier::Uint64 => KeyFieldType::UInt64,
                TypeIdentifier::Int8 => KeyFieldType::Int8,
                TypeIdentifier::Uint8 | TypeIdentifier::Byte => KeyFieldType::UInt8,
                TypeIdentifier::Boolean => KeyFieldType::Bool,
                _ => continue,
            };
            out.push(KeyFieldInfo { field_index: index, field_type });
        }
        out
    }

    /// Build TypeIdentifier (CompleteTypeId hash) from the collected fields.
    pub(crate) fn build_type_identifier(&self) -> TypeIdentifier {
        let type_obj = self.build_type_object();
        TypeIdentifier::CompleteTypeId(type_obj.compute_hash())
    }
}

/// Convert a field_type integer constant to a TypeIdentifier.
fn field_type_to_type_identifier(field_type: i32) -> Option<TypeIdentifier> {
    match field_type {
        INT2DDS_FIELD_BOOL => Some(TypeIdentifier::Boolean),
        INT2DDS_FIELD_BYTE => Some(TypeIdentifier::Byte),
        INT2DDS_FIELD_CHAR8 => Some(TypeIdentifier::Char8),
        INT2DDS_FIELD_CHAR16 => Some(TypeIdentifier::Char16),
        INT2DDS_FIELD_INT8 => Some(TypeIdentifier::Int8),
        INT2DDS_FIELD_INT16 => Some(TypeIdentifier::Int16),
        INT2DDS_FIELD_INT32 => Some(TypeIdentifier::Int32),
        INT2DDS_FIELD_INT64 => Some(TypeIdentifier::Int64),
        INT2DDS_FIELD_UINT8 => Some(TypeIdentifier::Uint8),
        INT2DDS_FIELD_UINT16 => Some(TypeIdentifier::Uint16),
        INT2DDS_FIELD_UINT32 => Some(TypeIdentifier::Uint32),
        INT2DDS_FIELD_UINT64 => Some(TypeIdentifier::Uint64),
        INT2DDS_FIELD_FLOAT32 => Some(TypeIdentifier::Float32),
        INT2DDS_FIELD_FLOAT64 => Some(TypeIdentifier::Float64),
        INT2DDS_FIELD_STRING => Some(TypeIdentifier::String8),
        INT2DDS_FIELD_WSTRING => Some(TypeIdentifier::String16),
        _ => None,
    }
}

fn named_type_identifier(hash_name: &str) -> TypeIdentifier {
    TypeIdentifier::MinimalTypeId(EquivalenceHash::compute(hash_name.as_bytes()))
}

/// Build the plain-collection header, deriving `equiv_kind` from the element exactly as
/// the derive macro does (primitives -> Both, hashed composites -> Minimal/Complete).
fn plain_collection_header(element: &TypeIdentifier) -> PlainCollectionHeader {
    PlainCollectionHeader {
        equiv_kind: plain_collection_equiv_kind(element),
        element_flags: CollectionElementFlag::default(),
    }
}

/// Sequence id: SMALL when `bound <= 255` (unbounded == 0 -> SMALL), else LARGE.
fn plain_sequence_id(element: TypeIdentifier, bound: u32) -> TypeIdentifier {
    let header = plain_collection_header(&element);
    if bound <= 255 {
        TypeIdentifier::PlainSequenceSmall {
            header,
            bound: bound as u8,
            element_identifier: Box::new(element),
        }
    } else {
        TypeIdentifier::PlainSequenceLarge { header, bound, element_identifier: Box::new(element) }
    }
}

/// Array id: SMALL when `array_size <= 255`, else LARGE.
fn plain_array_id(element: TypeIdentifier, array_size: u32) -> TypeIdentifier {
    let header = plain_collection_header(&element);
    if array_size <= 255 {
        TypeIdentifier::PlainArraySmall {
            header,
            array_bound_seq: vec![array_size as u8],
            element_identifier: Box::new(element),
        }
    } else {
        TypeIdentifier::PlainArrayLarge {
            header,
            array_bound_seq: vec![array_size],
            element_identifier: Box::new(element),
        }
    }
}

/// String id honoring an optional bound: `0` -> unbounded `String8`/`String16`;
/// `<= 255` -> `*Small`; else `*Large`. Mirrors the derive macro's `string_identifier`.
fn string_id(bound: u32, wide: bool) -> TypeIdentifier {
    match bound {
        0 => {
            if wide {
                TypeIdentifier::String16
            } else {
                TypeIdentifier::String8
            }
        }
        b if b <= 255 => {
            if wide {
                TypeIdentifier::String16Small { bound: b as u8 }
            } else {
                TypeIdentifier::String8Small { bound: b as u8 }
            }
        }
        b => {
            if wide {
                TypeIdentifier::String16Large { bound: b }
            } else {
                TypeIdentifier::String8Large { bound: b }
            }
        }
    }
}

#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_create(
    type_name: *const std::os::raw::c_char,
    extensibility: i32,
    out: *mut *mut Int2DdsTypeInfo,
) -> Int2DdsRet {
    check_null!(type_name);
    check_null!(out);

    let name_str = cstr_arg!(type_name);

    let ext_kind = match extensibility {
        0 => ExtensibilityKind::Final,
        1 => ExtensibilityKind::Appendable,
        2 => ExtensibilityKind::Mutable,
        _ => return INT2DDS_RET_INVALID_ARGUMENT,
    };

    let ti = Box::new(Int2DdsTypeInfo {
        type_name: name_str.to_string(),
        extensibility: ext_kind,
        fields: Vec::new(),
    });

    *out = Box::into_raw(ti);
    INT2DDS_RET_OK
}

/// Add a primitive-typed field to the type info builder.
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    field_type: i32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);

    let ti = &mut *type_info;

    let name_str = match CStr::from_ptr(field_name).to_str() {
        Ok(s) => s,
        Err(_) => return INT2DDS_RET_INVALID_ARGUMENT,
    };

    let type_id = match field_type_to_type_identifier(field_type) {
        Some(id) => id,
        None => return INT2DDS_RET_INVALID_ARGUMENT,
    };

    ti.fields.push(FieldInfo { name: name_str.to_string(), type_id, flags });

    INT2DDS_RET_OK
}

/// Add a (possibly bounded) narrow-string field. `bound == 0` means unbounded.
///
/// Prefer this over `int2dds_type_info_add_field(.., INT2DDS_FIELD_STRING, ..)` when the
/// IDL declares `string<N>`, so the emitted TypeIdentifier carries the bound and matches
/// strict XTypes peers byte-for-byte.
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_string_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    bound: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);

    let ti = &mut *type_info;
    let name_str = cstr_arg!(field_name);
    let type_id = string_id(bound, false);
    ti.fields.push(FieldInfo { name: name_str.to_string(), type_id, flags });

    INT2DDS_RET_OK
}

/// Add a (possibly bounded) wide-string (`wstring<N>`) field. `bound == 0` means unbounded.
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_wstring_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    bound: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);

    let ti = &mut *type_info;
    let name_str = cstr_arg!(field_name);
    let type_id = string_id(bound, true);
    ti.fields.push(FieldInfo { name: name_str.to_string(), type_id, flags });

    INT2DDS_RET_OK
}

/// Add a sequence field to the type info builder.
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_sequence_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    element_type: i32,
    bound: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);

    let ti = &mut *type_info;

    let name_str = cstr_arg!(field_name);

    let element_id = match field_type_to_type_identifier(element_type) {
        Some(id) => id,
        None => return INT2DDS_RET_INVALID_ARGUMENT,
    };

    let type_id = plain_sequence_id(element_id, bound);

    ti.fields.push(FieldInfo { name: name_str.to_string(), type_id, flags });

    INT2DDS_RET_OK
}

/// Add an array field to the type info builder.
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_array_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    element_type: i32,
    array_size: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);

    let ti = &mut *type_info;

    let name_str = cstr_arg!(field_name);

    let element_id = match field_type_to_type_identifier(element_type) {
        Some(id) => id,
        None => return INT2DDS_RET_INVALID_ARGUMENT,
    };

    let type_id = plain_array_id(element_id, array_size);

    ti.fields.push(FieldInfo { name: name_str.to_string(), type_id, flags });

    INT2DDS_RET_OK
}

/// Add a named (complex) type field to the type info builder.
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_named_type_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    type_hash_name: *const std::os::raw::c_char,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);
    check_null!(type_hash_name);

    let ti = &mut *type_info;

    let name_str = cstr_arg!(field_name);
    let hash_name = cstr_arg!(type_hash_name);

    let type_id = named_type_identifier(hash_name);

    ti.fields.push(FieldInfo { name: name_str.to_string(), type_id, flags });

    INT2DDS_RET_OK
}

#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_sequence_of_named_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    element_hash_name: *const std::os::raw::c_char,
    bound: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);
    check_null!(element_hash_name);

    let ti = &mut *type_info;

    let name_str = cstr_arg!(field_name);
    let hash_name = cstr_arg!(element_hash_name);

    let type_id = plain_sequence_id(named_type_identifier(hash_name), bound);

    ti.fields.push(FieldInfo { name: name_str.to_string(), type_id, flags });

    INT2DDS_RET_OK
}

#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_add_array_of_named_field(
    type_info: *mut Int2DdsTypeInfo,
    field_name: *const std::os::raw::c_char,
    element_hash_name: *const std::os::raw::c_char,
    array_size: u32,
    flags: i32,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(field_name);
    check_null!(element_hash_name);

    let ti = &mut *type_info;

    let name_str = cstr_arg!(field_name);
    let hash_name = cstr_arg!(element_hash_name);

    let type_id = plain_array_id(named_type_identifier(hash_name), array_size);

    ti.fields.push(FieldInfo { name: name_str.to_string(), type_id, flags });

    INT2DDS_RET_OK
}

#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_to_type_object(
    type_info: *const Int2DdsTypeInfo,
    out: *mut *mut crate::dynamic::Int2DdsTypeObject,
) -> Int2DdsRet {
    check_null!(type_info);
    check_null!(out);
    let to = (*type_info).build_type_object();
    *out = Box::into_raw(Box::new(crate::dynamic::Int2DdsTypeObject::from_type_object(to)));
    INT2DDS_RET_OK
}

/// Destroy a type info builder.
#[no_mangle]
pub unsafe extern "C" fn int2dds_type_info_destroy(type_info: *mut Int2DdsTypeInfo) {
    if !type_info.is_null() {
        drop(Box::from_raw(type_info));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use int2dds::xtypes::{
        CompleteStructMember, CompleteStructType, CompleteTypeObject, MemberFlag, TryConstructKind,
        TypeFlag, TypeIdentifier, TypeObject,
    };

    #[test]
    fn test_primitives_type_hash_matches_derive_macro() {
        use int2dds::xtypes::HasTypeObject;
        use int2dds_derive::DdsType;

        // The real derive-macro output is the source of truth. Comparing against an actual
        // `#[derive(DdsType)]` struct (not a hand-rolled CompleteStructType) is what makes
        // this test able to catch FFI-vs-derive divergence.
        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct PrimitivesType {
            #[dds(key)]
            id: i32,
            bool_val: bool,
            byte_val: u8,
            short_val: u16,
        }

        // FFI type_info builder path (mirrors what the generated C emits).
        let mut ti = Int2DdsTypeInfo {
            type_name: "PrimitivesType".to_string(),
            extensibility: ExtensibilityKind::Appendable,
            fields: Vec::new(),
        };
        ti.fields.push(FieldInfo {
            name: "id".to_string(),
            type_id: TypeIdentifier::Int32,
            flags: INT2DDS_MEMBER_KEY,
        });
        ti.fields.push(FieldInfo {
            name: "bool_val".to_string(),
            type_id: TypeIdentifier::Boolean,
            flags: 0,
        });
        ti.fields.push(FieldInfo {
            name: "byte_val".to_string(),
            type_id: TypeIdentifier::Byte,
            flags: 0,
        });
        ti.fields.push(FieldInfo {
            name: "short_val".to_string(),
            type_id: TypeIdentifier::Uint16,
            flags: 0,
        });

        let ffi_serialized = match ti.build_type_object() {
            TypeObject::Complete(c) => c.serialize(),
            _ => panic!("Expected Complete"),
        };
        let derive_serialized = PrimitivesType::complete_type_object().serialize();

        assert_eq!(
            ffi_serialized, derive_serialized,
            "Serialized CompleteTypeObject bytes differ between FFI and derive paths"
        );
        assert_eq!(
            ti.build_type_identifier(),
            PrimitivesType::type_identifier(),
            "TypeIdentifier hashes differ between FFI and derive paths"
        );
    }

    /// Sequence / array / bounded-sequence / uint8-element fields must produce the same
    /// TypeIdentifier as the real derive macro. Pinned to `T::type_identifier()` so it
    /// catches the SMALL/LARGE and equiv_kind divergences the old self-consistent test missed.
    #[test]
    fn test_sequence_type_hash_matches_derive_macro() {
        use int2dds::xtypes::HasTypeObject;
        use int2dds_derive::DdsType;

        #[derive(DdsType)]
        #[dds_type(crate_path = "int2dds", extensibility = "Appendable")]
        struct TestSeqType {
            #[dds(key)]
            id: i32,
            bool_seq: Vec<bool>,
            #[dds(bound = 10)]
            bounded_seq: Vec<i32>,
            #[dds(uint8)]
            payload: Vec<u8>,
            bool_array: [bool; 4],
        }

        let mut ti = Int2DdsTypeInfo {
            type_name: "TestSeqType".to_string(),
            extensibility: ExtensibilityKind::Appendable,
            fields: Vec::new(),
        };
        ti.fields.push(FieldInfo {
            name: "id".to_string(),
            type_id: TypeIdentifier::Int32,
            flags: INT2DDS_MEMBER_KEY,
        });
        ti.fields.push(FieldInfo {
            name: "bool_seq".to_string(),
            type_id: plain_sequence_id(TypeIdentifier::Boolean, 0),
            flags: 0,
        });
        ti.fields.push(FieldInfo {
            name: "bounded_seq".to_string(),
            type_id: plain_sequence_id(TypeIdentifier::Int32, 10),
            flags: 0,
        });
        ti.fields.push(FieldInfo {
            name: "payload".to_string(),
            type_id: plain_sequence_id(TypeIdentifier::Uint8, 0),
            flags: 0,
        });
        ti.fields.push(FieldInfo {
            name: "bool_array".to_string(),
            type_id: plain_array_id(TypeIdentifier::Boolean, 4),
            flags: 0,
        });

        assert_eq!(
            ti.build_type_identifier(),
            TestSeqType::type_identifier(),
            "TypeIdentifier hashes differ for sequence/array/bounded/uint8 fields"
        );
    }

    #[test]
    fn test_named_collection_type_hash_matches_derive_macro() {
        use std::ffi::CString;

        let name = CString::new("NamedCollType").unwrap();
        let mut ffi_ptr: *mut Int2DdsTypeInfo = std::ptr::null_mut();
        unsafe {
            assert_eq!(int2dds_type_info_create(name.as_ptr(), 1, &mut ffi_ptr), INT2DDS_RET_OK);
            let id_field = CString::new("id").unwrap();
            assert_eq!(
                int2dds_type_info_add_field(
                    ffi_ptr,
                    id_field.as_ptr(),
                    INT2DDS_FIELD_INT32,
                    INT2DDS_MEMBER_KEY,
                ),
                INT2DDS_RET_OK
            );
            let seq_field = CString::new("leaves").unwrap();
            let leaf_name = CString::new("NestedLeaf").unwrap();
            assert_eq!(
                int2dds_type_info_add_sequence_of_named_field(
                    ffi_ptr,
                    seq_field.as_ptr(),
                    leaf_name.as_ptr(),
                    0,
                    0,
                ),
                INT2DDS_RET_OK
            );
            let arr_field = CString::new("fixed").unwrap();
            assert_eq!(
                int2dds_type_info_add_array_of_named_field(
                    ffi_ptr,
                    arr_field.as_ptr(),
                    leaf_name.as_ptr(),
                    3,
                    0,
                ),
                INT2DDS_RET_OK
            );
        }
        let ti = unsafe { &*ffi_ptr };
        let ffi_type_id = ti.build_type_identifier();

        let leaf_element =
            TypeIdentifier::MinimalTypeId(EquivalenceHash::compute("NestedLeaf".as_bytes()));
        let type_flags =
            TypeFlag::new(int2dds::xtypes::ExtensibilityKind::Appendable, false, false);
        let mut struct_type =
            CompleteStructType::new(type_flags, "NamedCollType".to_string(), None);
        struct_type.add_member(CompleteStructMember::new(
            0,
            // @key -> implicitly must-understand, matching the FFI builder and derive macro.
            MemberFlag::new(TryConstructKind::Discard, false, false, true, true, false),
            TypeIdentifier::Int32,
            "id".to_string(),
        ));
        struct_type.add_member(CompleteStructMember::new(
            1,
            MemberFlag::new(TryConstructKind::Discard, false, false, false, false, false),
            TypeIdentifier::PlainSequenceSmall {
                header: PlainCollectionHeader::default(),
                bound: 0,
                element_identifier: Box::new(leaf_element.clone()),
            },
            "leaves".to_string(),
        ));
        struct_type.add_member(CompleteStructMember::new(
            2,
            MemberFlag::new(TryConstructKind::Discard, false, false, false, false, false),
            TypeIdentifier::PlainArraySmall {
                header: PlainCollectionHeader::default(),
                array_bound_seq: vec![3],
                element_identifier: Box::new(leaf_element),
            },
            "fixed".to_string(),
        ));

        let derive_type_obj = TypeObject::Complete(CompleteTypeObject::Struct(struct_type));
        let derive_type_id = TypeIdentifier::CompleteTypeId(derive_type_obj.compute_hash());

        assert_eq!(
            ffi_type_id, derive_type_id,
            "TypeIdentifier hashes differ for named sequence/array element fields"
        );

        unsafe { int2dds_type_info_destroy(ffi_ptr) };
    }
}
