// Auto-generated by int2dds-idl from HelloWorld.idl
// DO NOT EDIT

using System;
using Int2Dds.Cdr;
using Int2Dds.Types;

namespace HelloWorldPub
{
    [DdsType("HelloWorld", 1, false)]
    public class HelloWorld : IDdsType
    {
        public static string DdsTypeName => "HelloWorld";
        public static Extensibility TypeExtensibility => Extensibility.Appendable;
        public static bool HasKey => false;

        public static readonly DdsTypeInfoField[] DdsTypeInfoFields = new DdsTypeInfoField[]
        {
            new DdsTypeInfoField("field", "index", 9, 0u, 0),
            new DdsTypeInfoField("string", "message", 0, 0u, 0),
        };

        public uint Index { get; set; }
        public string Message { get; set; } = "";

        public HelloWorld() { }

        public byte[] SerializeCdr() => SerializeCdr(false);

        public byte[] SerializeCdr(bool xcdr2)
        {
            var w = new CdrWriter(TypeExtensibility, xcdr2: xcdr2);
            SerializeCdrInline(w);
            return w.ToBytes();
        }

        public void SerializeCdr(CdrWriter w) => SerializeCdrInline(w);

        public static HelloWorld DeserializeCdr(ReadOnlySpan<byte> data) => DeserializeCdrInline(new CdrReader(data));

        public static HelloWorld DeserializeCdr(byte[] data) => DeserializeCdrInline(new CdrReader(data));

        internal static HelloWorld DeserializeCdrInline(CdrReader r)
        {
            var obj = new HelloWorld();
            var (_dSize, _dStart) = r.ReadDheader();
            obj.Index = r.ReadU32();
            obj.Message = r.ReadString();
            r.ReadDheaderEnd(_dSize, _dStart);
            return obj;
        }

        internal void SerializeCdrInline(CdrWriter w)
        {
            var _dt = w.DheaderBegin();
            w.WriteU32(Index);
            w.WriteString(Message);
            w.DheaderFinalize(_dt);
        }

        private static readonly byte[] s_emptyKey = new byte[0];
        public byte[] SerializeKey() => s_emptyKey;
    }

}
