name: Library Integration Tests
run-name: Run integration tests on ${{ github.head_ref }}

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container:
      image: rust:1.89
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure socket buffer size
        run: |
          sysctl -w net.core.rmem_max=5242880
          sysctl -w net.core.wmem_max=5242880
          sysctl -w net.core.rmem_default=5242880
          sysctl -w net.core.wmem_default=5242880

      - name: Run integration tests
        run: cargo test --test "*" -- --test-threads=1