name: Cargo Tests
run-name: "Cargo test ${{ github.head_ref }}"

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  cargo-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: ubuntu-24.04-arm
          - os: windows-2022
          - os: [self-hosted, mac-local]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Disable Windows Defender realtime monitoring
        if: runner.os == 'Windows'
        run: Set-MpPreference -DisableRealtimeMonitoring $true
        shell: powershell

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.89.0
          rustflags: ""

      - name: Load cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargo-develop
          save-if: false

      - name: Run all tests
        shell: bash
        env:
          INT2DDS_UDP_SOCKET_BUFFER: 5242880
          RUSTFLAGS: ${{ runner.os == 'Windows' && '-C linker=lld-link' || '' }}
        run: cargo test -- --test-threads=1
